### ISSUE TITLE
New Tool: es-check

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1010]
See https://github.com/yowainwright/es-check

Usecases:

* to test whether `oxc_transformer` is correct
* to test whether your bundled app still has some higher ES features. For some apps or websites, they still require es5 for lower versions of ios safari or IE

Approach:

`oxc_parser` parses esnext, which means we are not going to add a `ecmaVersion` option to the parser. Instead we are just going to add a special linter. The the code setup can be copied from https://github.com/web-infra-dev/oxc/blob/main/crates/oxc_linter/examples/linter.rs

**Comment by magic-akari** [comment]
Something related: esbuild marks used features in the parser
https://github.com/evanw/esbuild/blob/427ee6054401042f509c2b3a2d31bc6eebca655c/internal/js_parser/js_parser_lower.go#L42

**Comment by byteHulk** [comment]
hi @Boshen  can I take on this issue?

**Comment by Boshen** [comment]
> hi @Boshen can I take on this issue?

Have fun! Please be aware of our rules https://oxc-project.github.io/docs/contribute/rules.html and sure that you submit smaller PRs!

**Comment by byteHulk** [comment]
hi @Boshen  Is it possible to do this just by checking(handwriting rules) the AST parsed by oxc_parser for new syntax for a particular version here?

And Do I still need to use the oxc_transformer package?

https://github.com/oxc-project/oxc/blob/774a257a66ca06b141a286c4e1336a81a6534be1/crates/oxc_linter/examples/linter.rs#L41

**Comment by Boshen** [comment]
> hi @Boshen Is it possible to do this just by checking(handwriting rules) the AST parsed by oxc_parser for new syntax for a particular version here?
> 
> And Do I still need to use the oxc_transformer package?
> 
> https://github.com/oxc-project/oxc/blob/774a257a66ca06b141a286c4e1336a81a6534be1/crates/oxc_linter/examples/linter.rs#L41

It should be similar to how the linter is written, see 

* https://github.com/oxc-project/oxc/blob/main/crates/oxc_linter/examples/linter.rs
* https://github.com/oxc-project/oxc/blob/main/crates/oxc_semantic/src/checker/javascript.rs

**Comment by byteHulk** [comment]
I see, but do I need to write the syntax matching rules by hand, or has someone else already done that part and I can just bring them in?

Like this?

```rust
AstKind::VariableDeclaration(stmt)
                if ecma_version < 6
                    && (stmt.kind == VariableDeclarationKind::Const
                        || stmt.kind == VariableDeclarationKind::Let) =>
            {
                The let declaration is not yet supported in the es5 environment.
                // errors...;
            }```

**Comment by Boshen** [comment]
> I see, but do I need to write the syntax matching rules by hand, or has someone else already done that part and I can just bring them in?
> 
> Like this?
> 
> ```rust
> AstKind::VariableDeclaration(stmt)
>                 if ecma_version < 6
>                     && (stmt.kind == VariableDeclarationKind::Const
>                         || stmt.kind == VariableDeclarationKind::Let) =>
>             {
>                 The let declaration is not yet supported in the es5 environment.
>                 // errors...;
>             }```
> ```

> do I need to write the syntax matching rules by hand

Yes, you need to write them by hand. All the tests from https://github.com/yowainwright/es-check/tree/main/tests has to be passed.

**Comment by byteHulk** [comment]
> 我将把它转移到另一个存储库，私下进行一些实验。

ok

**Comment by Boshen** [comment]
We need this for the transformer after finishing Milestone 1 @Dunqing

**Comment by Boshen** [comment]
Ok this isn't the right direction, closing again.

**Comment by Boshen** [comment]
Reopen again because I need this to validate the transformer.

**Comment by Boshen** [comment]
Will be developed in https://github.com/oxc-project/scan262
