### ISSUE TITLE
feat(playground): visualize symbols and scopes

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1048]
It would be nice to see symbol and scope information on the playground, ideally adding a new view for it https://oxc-project.github.io/oxc/playground

See https://github.com/oxc-project/oxc/tree/main/website for instructions

**Comment by Dunqing** [comment]
Wow, so looking forward to this, it will help me to write linter rules and understand OXC. I don't know the difference between symbols and scopes yet!

**Comment by IWANABETHATGUY** [comment]
1. The link is broken since the oxc has been transferred to `oxc-project`

**Comment by hyf0** [comment]
Could be related to https://github.com/oxc-project/oxc/issues/1227. Maybe they could share the same code.
