### ISSUE TITLE
A general way to test scope resolving logic

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#1227]
https://github.com/oxc-project/oxc/blob/9aa78f65fde86b802416169754010e4ac627fea2/crates/oxc_semantic/tests/util/mod.rs#L15-L19

The current `SemanticTester` is great to do many kinds of assertions. Such as

https://github.com/oxc-project/oxc/blob/9aa78f65fde86b802416169754010e4ac627fea2/crates/oxc_semantic/tests/symbols.rs#L8-L13.

But I kind of think the `SemanticTester` might not be that intuitive for testing general scope resolving logic, which means weather the symbol has correct scope and don't care about the flags or others.

Let's see we have test case

```js
log()

let a = 1
log(a)
let b = 1
log(b)
{
  let a = 2
  log(a)
  log(b)
}
```

we could transform it to

```js
log#0()

let a#1 = 1
log(a#1)
let b#1 = 1;
log(b#1);
{
  let a#2 = 2;
  log(a#2)
  log(b#1)
}
```

the `x` in `#x` is the `ScopeId` we get from the `Sematics`.

In this way, we could easily visualize the whether the scope is correct. And **with snapshot testing**, this could be a general way for testing without any other kinds of assertions.

---

I get this idea from contributing to swc. https://github.com/swc-project/swc/blob/main/crates/swc_ecma_transforms_base/tests/resolver/hoisting/output.js

**Comment by Boshen** [comment]
Intresting. I think it's hard to cover all cases by manually writing test cases, the general approach should be running Test262 over mangled files ... let me think about this.

**Comment by Boshen** [comment]
We should rely and take advantage of test262 instead of manual tests.
