### ISSUE TITLE
feat(cli): abort `--fix` when git has uncommited files

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#125]
`Cargo fix` does this, which is really nice.

See:
* https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/fix.rs#L136
* https://github.com/rust-lang/cargo/blob/master/tests/testsuite/fix.rs#L710-L816

**Comment by Boshen** [comment]
@shannonrothe I dug into `Cargo fix` and found all the expected behaviours, this should make us a bit easier.

**Comment by shannonrothe** [comment]
> @shannonrothe I dug into `Cargo fix` and found all the expected behaviours, this should make us a bit easier.

They use `git2` as well which should make this pretty easy 👀
