### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by milesj** [oxc-project/oxc#1326]
I believe oxc should look into supporting ast/parser/lexer/etc for other document types, starting with HTML.

Why HTML? It's useful for HTML based entry points (think vite), HTML based template plugins (webpack, rollup, etc), and especially critical for Vue/Svelte files.

I'd be willing to spike this, but unsure how you want to structure the repo (it's named heavily after JS/TS only).

In the future, we could then support CSS (probably piggy backing off of lightning css).

**Comment by Boshen** [comment]
HTML and CSS is out of scope for this project. 

From my point of view, `swc_html` and `lightningcss` should be used for such tasks because they are somewhat more stable technologies where we don't need to divert the community from, we should consolidate our man power to `swc` and `lightningcss` in these regards.

What do you think?

**Comment by milesj** [comment]
That's fair reasoning but I still think it should be considered. HTML (and indirectly CSS) are typically coupled to the JS ecosystem, especially when we need to support nested documents (JS `<script>` blocks within HTML documents). 

I'm curious how oxc plans to handle Vue/Svelte/Astro files if there's no plan for HTML support? Custom implementations for those 3? Or will oxc just focus on pure JS/TS files?

If maintenance is an issue, I could help champion it. Comparatively, HTML is far simpler than JS :P

**Comment by Boshen** [comment]
~The scope for oxc will stay within JavaScript / TypeScript.~

~We may still discuss the possibly of having supporting HTML and CSS in some other means, my DMS are open 😄~

Update in 2025: We may consider this.

**Comment by BryanHuntNV** [comment]
Can this be reopened?  We want to standardize on oxlint, but not supporting the template and css in .vue files is a bit of a blocker.

**Comment by LouisDeconinck** [comment]
What is the current state and stance on supporting other languages such as HTML and CSS by OXC?

**Comment by jackholden** [comment]
@Boshen is there any update on this? would be great to port over an eslint plugin which checks html accessibility for example. Thanks in advance.

**Comment by camc314** [comment]
Hi all, as an update here:

1. we have no plans to add this to oxlint core.
2. we are adding support for language plugins. please see https://github.com/oxc-project/oxc/discussions/21936, this will enable linting of arbitary languages (initial focus being vue), but linting of these files will all be via plugins, so it is flexible and extensible.

Thanks all!
