### ISSUE TITLE
Nested Code Fixes

### ISSUE THREAD

**Issue by YangchenYe323** [oxc-project/oxc#144]
I wonder if it's possible for us to implement nested code fixes. For example, the following expression:
`1 & 2 ^ 3 | 4`
should be changed to `((1 & 2) ^ 3) | 4`, which involves first changing the span `1 & 2` to be `(1 & 2)` and then changing `(1 & 2) ^ 3` to be `((1 & 2) ^ 3)`.

I noticed our current fixer seems to assume its fix spans are disjoint intervals. Could this be done with our current approach, i.e., manipulating source text directly rather than changing the AST?

**Comment by Boshen** [comment]
cc @jason89521 

Unfortunately we are not going to do AST manipulation, it's way too complicated and impedes our development.

But I have two ideas:
* constructor a small AST, print the snippet, and use the fixer to replace text.
* write some good utils to construct the snippet

**Comment by YangchenYe323** [comment]
> * write some good utils to construct the snippet

Thanks for your input. I was thinking about the same thing, probably keeping track of how span in the original source changed through all the fixes.

**Comment by jason89521** [comment]
For mixed operators, I wonder how should we fix this rule. For example, `a + b * c` can be fixed as `(a + b) * c` or `a + (b * c)`.

**Comment by YangchenYe323** [comment]
> For mixed operators, I wonder how should we fix this rule. For example, `a + b * c` can be fixed as `(a + b) * c` or `a + (b * c)`.

The latter is correct in this case because of the precedence. In the AST the multiple node is a parent of the add node, and the fix is parenthesizing the child node.
