### ISSUE TITLE
linter - support different output formats 

### ISSUE THREAD

**Issue by fbuchlak** [oxc-project/oxc#1462]
It would be nice to have different output from linter (at least json). This feature would allow developers to integrate this tool easily.

See https://eslint.org/docs/latest/use/formatters/

**Comment by lukasMega** [comment]
Hello, I would be very grateful for the `unix` format here. It's simple single-line output. https://eslint.org/docs/latest/use/formatters/#unix 
In IntelliJ Idea are these filepaths clickable for one-click opening:
<details><summary> see - Left side: ESLint output (format `unix`) - filepaths are clickable. Right side: oxlint output (default) and filepaths are not clickable :/ </summary>

<img width="1694" alt="Screen 2023-12-18 at 17 59 54" src="https://github.com/oxc-project/oxc/assets/2448004/04c57f8d-8c04-4751-815c-b624f3034a40">
</details>

**Comment by lukasMega** [comment]
Hello, I would be very grateful for the `unix` format here. It's simple single-line output. https://eslint.org/docs/latest/use/formatters/#unix 
In IntelliJ Idea are these filepaths clickable for one-click opening:
<details><summary> see - Left side: ESLint output (format `unix`) - filepaths are clickable. Right side: oxlint output (default) and filepaths are not clickable :/ </summary>

<img width="1694" alt="Screen 2023-12-18 at 17 59 54" src="https://github.com/oxc-project/oxc/assets/2448004/7ee29ee0-9231-4600-922c-44bb323d1b7d">

</details>

**Comment by lukasMega** [comment]
Hello, I would be very grateful for the `unix` format here. It's simple single-line output. https://eslint.org/docs/latest/use/formatters/#unix 
In IntelliJ Idea are these filepaths clickable for one-click opening:
<details><summary> see - Left side: ESLint output (format `unix`) - filepaths are clickable. Right side: oxlint output (default) and filepaths are not clickable :/ </summary>

<img width="1694" alt="Screen 2023-12-18 at 17 59 54" src="https://github.com/oxc-project/oxc/assets/2448004/cb693fb6-fa6d-4eea-8d7e-868bc23c2d0d">


</details>

**Comment by suxin2017** [comment]
Hi I am very interested in this, but I have a problem, there may be more than one "labels" in a "diagnostic" as shown below
```
   ╭─[./test.js:1:1]
 1 │ class C {
 2 │     async
   ·     ──┬──
   ·       ╰── "async" is previously declared here
 3 │     async
   ·     ──┬──
   ·       ╰── "async" is re-declared here
 4 │     foo() {}
   ╰────
```
it labels 
```
[crates/oxc_diagnostics/src/service.rs:185] line = 1
[crates/oxc_diagnostics/src/service.rs:185] column = 4
[crates/oxc_diagnostics/src/service.rs:185] offset = 14
[crates/oxc_diagnostics/src/service.rs:185] context = "async"
[crates/oxc_diagnostics/src/service.rs:185] span_contents.name() = Some(
    "./test.js",
)
[crates/oxc_diagnostics/src/service.rs:185] line = 2
[crates/oxc_diagnostics/src/service.rs:185] column = 4
[crates/oxc_diagnostics/src/service.rs:185] offset = 24
[crates/oxc_diagnostics/src/service.rs:185] context = "async"
[crates/oxc_diagnostics/src/service.rs:185] span_contents.name() = Some(
    "./test.js",
)
```
eslint output json 
```
   {
                "ruleId": "no-else-return",
                "severity": 1,
                "message": "Unnecessary 'else' after 'return'.",
                "line": 4,
                "column": 12,
                "nodeType": "BlockStatement",
                "messageId": "unexpected",
                "endLine": 6,
                "endColumn": 6,
                "fix": {
                    "range": [
                        0,
                        94
                    ],
                    "text": "function addOne(i) {\n    if (i != NaN) {\n        return i ++\n    } \n      return\n    \n}"
                }
            },
```
What is the best way to output json for multiple labels

**Comment by Boshen** [comment]
The infrastructure is ready to accept more reporters. See https://github.com/oxc-project/oxc/blob/main/crates/oxc_diagnostics/src/reporter.rs

The json reporter does not conform to the ESLint format yet.

PRs are welcomed for both changes.
