### ISSUE TITLE
Support `import-attributes` and deprecate `import-assertions`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [oxc-project/oxc#1513]
Recently, Typescript introduced a new syntax https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/#import-attributes, and deprecated the old `import-assertions`, maybe we should follow.
## Reference 
- proposal: https://github.com/tc39/proposal-import-attributes
- implementation: https://github.com/microsoft/TypeScript/pull/54242

**Comment by magic-akari** [comment]
- #1476

**Comment by IWANABETHATGUY** [comment]
> * [feat(ast): implement new proposal-import-attributes #1476](https://github.com/oxc-project/oxc/pull/1476)

Sorry, I didn't notice that, also maybe we should deprecate the `import-assertions` rather than replace them directly, just like Typescript did?

**Comment by magic-akari** [comment]
> > * [feat(ast): implement new proposal-import-attributes #1476](https://github.com/oxc-project/oxc/pull/1476)
> 
> Sorry, I didn't notice that, also maybe we should deprecate the `import-assertions` rather than replace them directly, just like Typescript did?

This PR adds support for `with` and `assert` in the parse and codegen stages, including Prettier. Both of them are supported without deprecation or replacing the support for the previous syntax. 
Perhaps we can consider adding `assert` checks during the linting stage.

**Comment by IWANABETHATGUY** [comment]
> > > * [feat(ast): implement new proposal-import-attributes #1476](https://github.com/oxc-project/oxc/pull/1476)
> > 
> > 
> > Sorry, I didn't notice that, also maybe we should deprecate the `import-assertions` rather than replace them directly, just like Typescript did?
> 
> This PR adds support for `with` and `assert` in the parse and codegen stages, including Formatter. Both of them are supported without deprecation or replacing the support for the previous syntax. Perhaps we can consider adding `assert` checks during the linting stage.

LGTM
