### ISSUE TITLE
vscode extension - check on file change (not on file save)

### ISSUE THREAD

**Issue by Newbie012** [oxc-project/oxc#1518]
Currently, the extensions run a check each time a file is saved. Instead, it would be useful if it will each on file change (like ESLint does)

**Comment by IWANABETHATGUY** [comment]
According to the code, it should run check when file change? 
https://github.com/oxc-project/oxc/blob/c934d93713b5b5fd577d704a9e5063518e546719/editors/vscode/server/src/main.rs#L83-L85

**Comment by IWANABETHATGUY** [comment]
Do you mean run a full check for each file update?

**Comment by IWANABETHATGUY** [comment]
[record.webm](https://github.com/oxc-project/oxc/assets/17974631/95b24e5b-4aad-4ece-ac34-c88242ef1148)
Currently oxc vscode extension already lint the file for each file update event

**Comment by Newbie012** [comment]
Seems like it behaves differently on my machine:

https://github.com/oxc-project/oxc/assets/10504365/9773a196-044d-4a61-925b-ddc292e1cd87

WSL2 (Windows 11)

**Comment by Boshen** [comment]
> Seems like it behaves differently on my machine:

This is actually a bug! 

The parser is producing an empty AST when there is a syntax error, which kicks in the empty file rule that is checking against an empty AST.

cc @camc314 This is an interesting bug, let me think about how to fix this. We'll probably need to skip linting when there is a syntax error from the parser.

**Comment by IWANABETHATGUY** [comment]
OK, I can reproduce it now.
