### ISSUE TITLE
feature request: Circular dependency linting.

### ISSUE THREAD

**Issue by JustFly1984** [oxc-project/oxc#1648]
As I remember a while ago I've encountered some plugin which finds circular import references. It was long time ago, but at some point it saved me from hours of searching it myself. It was a time of early eslint, and as I remember even before plugin-import. Even before typescript became eslint plugin. Does somebody remembers ts-lint?
It was very perf heavy rule, and for performance there was a depth limit.
As I understand the nature of this project, it should be doable.

Is there anything similar already exist?

**Comment by mysteryven** [comment]
Yes, we have already supported [no-cycle](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md).

https://twitter.com/boshen_c/status/1700826985340248345

```
```
