### ISSUE TITLE
VSCode: don't underline if there's already an error

### ISSUE THREAD

**Issue by KraXen72** [oxc-project/oxc#1653]
since oxc is so quick, i often get to look at overlapping underlines with the default typescript extension:
![image](https://github.com/oxc-project/oxc/assets/21956756/fc91764a-c28f-4622-9e8f-2adeadcfaa17)

it looks ugly.
obviously, i know that it's incorrect, i just haven't finished typing yet.
if it can't be detected that error underlines are overlapping with oxc blue ones, please add an option to the vscode extension to support a debounce time in ms.
Thanks!

**Comment by Boshen** [comment]
> @Boshen, here are my thoughts. I did some quick research, there are a few ways we can implement linting debounce:
> 
> 1. Use a [pull-based diagnostics implementation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics), but I think it is more suitable for the large project analysis scenario(e.g. typescript type checking, only specific file, and its dependency would be affected), also the implementation complexity is pretty high.
> 2. debounce on the server side, better code reuse, but not sure if it is easy to implement debounce in Rust.

How does ESLint, Biome and Ruff does it?

**Comment by IWANABETHATGUY** [comment]
https://github.com/microsoft/vscode-eslint/issues/1461, https://github.com/microsoft/vscode-eslint/issues/222, eslint has a default 200ms debounce on client side.Also user can choose lint timing `onSaved` or `onChanged`, maybe we can follow this?

**Comment by Boshen** [comment]
> [microsoft/vscode-eslint#1461](https://github.com/microsoft/vscode-eslint/issues/1461), [microsoft/vscode-eslint#222](https://github.com/microsoft/vscode-eslint/issues/222), eslint has a default 200ms debounce on client side.Also user can choose lint timing `onSaved` or `onChanged`, maybe we can follow this?

Let's follow! Take a look at how Biome / Rust does it since they are written in Rust.

**Comment by IWANABETHATGUY** [comment]
both biome and ruff don't have a debounce logic, so I think following the eslint would be just fine.
