### ISSUE TITLE
vscode: report problem more accurately

### ISSUE THREAD

**Issue by RiESAEX** [oxc-project/oxc#1674]
![image](https://github.com/oxc-project/oxc/assets/89718456/ff73eaba-09be-4647-a230-8db60d773941)
I'd like it to report only the problematic code, not lines between them.

**Comment by IWANABETHATGUY** [comment]
I Agree.

**Comment by Dunqing** [comment]
It looks like we need to modify the `no-const-assign` rule.

**Comment by IWANABETHATGUY** [comment]
Not only `no-const-assign` has this issues,  here is another case.
![image](https://github.com/oxc-project/oxc/assets/17974631/e933e3d3-a696-4b35-946f-7c8ab6850092)

**Comment by IWANABETHATGUY** [comment]
![image](https://github.com/oxc-project/oxc/assets/17974631/032e1d5c-47c5-4f02-80cc-9bb5e2ad746d)
Here is a case of how ra handle diagnostics with relatedInfomation, maybe we can follow this, @Boshen

**Comment by IWANABETHATGUY** [comment]
only the source is underlined with the error not the whole error span

**Comment by Boshen** [comment]
How does Biome do it? I think we just need to figure out the proper way to extract the diagnostic spans.

**Comment by IWANABETHATGUY** [comment]
This is how biome handle **no-const-assign**: 
![image](https://github.com/oxc-project/oxc/assets/17974631/1265f1e0-4159-499d-b632-37f738e965a9)

**Comment by IWANABETHATGUY** [comment]
https://github.com/oxc-project/oxc/pull/1681 made a draft here, use first span of  `ErrorWithPosition.labels_with_pos` , if it is not empty, or fallback to the default span: 
https://github.com/IWANABETHATGUY/oxc/blob/141be0e104723701345cbc4f3bb564fd82a6db87/editors/vscode/server/src/linter.rs#L88-L97
