### ISSUE TITLE
Support for eslint-plugin-i18next

### ISSUE THREAD

**Issue by rcanfield-tandem** [oxc-project/oxc#1678]
Hi, love the project :) just curious if [eslint-plugin-i18next](https://github.com/edvardchen/eslint-plugin-i18next) has support planned in oxc?

**Comment by Boshen** [comment]
Sorry for the super later reply, this issue somehow slipped through.

Our current effort is to port most of the rules listed in https://github.com/oxc-project/oxc/issues/481
