### ISSUE TITLE
prefer-string-starts-ends-with ignores /i case insensitive modifier

### ISSUE THREAD

**Issue by AndyA** [oxc-project/oxc#1687]
The (most welcome) `prefer-string-starts-ends-with` doesn't consider whether the RegExp it proposes replacing has an `i` modifier to make it case insensitive.

```
eslint-plugin-unicorn(prefer-string-starts-ends-with): Prefer String#startsWith over a regex with a caret.
     ╭─[lib/model/setup.ts:103:1]
 103 │               const uri = rec["target-uri"] || "";
 104 │               if (/^http/i.test(uri)) {
     ·                   ──────────────────
     ╰────
```

Arguably it could recommend str.toLowerCase().startsWith() but for long strings it's presumably more efficient to run a case insensitive RegExp on the first few characters rather than down casing the whole string.

Thanks for oxlint - it's awesome.

**Comment by camc314** [comment]
Thanks for the detailed issue!

I think it's reasonable in this case, to not report an error. 

Will fix shortly!

**Comment by AndyA** [comment]
Here's a PR: https://github.com/oxc-project/oxc/pull/1688 :)
