### ISSUE TITLE
Cannot execute oxlint

### ISSUE THREAD

**Issue by gpremer** [oxc-project/oxc#1690]
So, after the announcement of the general availability of oxlint I decided to give it a try. 

However, I immediately get an exception:

```
❯ npx oxlint@latest
/home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/oxlint/bin/oxlint:37
    throw result.error;
    ^

Error: spawnSync /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at Object.spawnSync (node:child_process:871:24)
    at Object.<anonymous> (/home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/oxlint/bin/oxlint:21:43)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint',
  path: '/home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint',
  spawnargs: []
}
```

Yet, the file does exist:

```
❯ ls -l /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint
.rwxr-xr-x 6,6M ME 15 dec 13:49 /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint
```

strace doesn't tell me much more:

```
❯ strace -f /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint
execve("/home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint", ["/home/ME/.npm/_npx/f4a33d9b"...], 0x7ffdc63603a8 /* 189 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
```

Everything is properly linked:

```
❯ ldd /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint
        linux-vdso.so.1 (0x00007ffd129c9000)
        libgcc_s.so.1 => /nix/store/jd99cyc0251p0i5y69w8mqjcai8mcq7h-xgcc-12.2.0-libgcc/lib/libgcc_s.so.1 (0x00007efe95108000)
        librt.so.1 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/librt.so.1 (0x00007efe95103000)
        libpthread.so.0 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libpthread.so.0 (0x00007efe950fe000)
        libm.so.6 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libm.so.6 (0x00007efe94520000)
        libdl.so.2 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libdl.so.2 (0x00007efe950f9000)
        libc.so.6 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 (0x00007efe9433a000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007efe9512b000)
```

Is there anything else I should try?

This is on a NixOs system. On another machine with just nix home-manager, but the same linked libraries, everything works as expected.

Impressed by the speed by the way.

**Comment by Boshen** [comment]
I have a gut feeling that the linux-x64 binary has a glibc problem.

What happens if execute the binary directly (by passing node altogether)? i.e. run `/home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint`.

By looking at the [build](https://github.com/oxc-project/oxc/actions/runs/7191214007/job/19585543349), it's using ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.5 under "build with cross".

Unfortunately I'm not familiar with system builds where I can figure out the rest of the puzzle pieces :-(

**Comment by gpremer** [comment]
As suspected, it appears to be a NixOS-specific problem. As seen in https://discourse.nixos.org/t/why-does-this-binary-executable-give-cannot-execute-required-file-not-found/33948/3, a fix is patching the binary by running:
`nix run nixpkgs#patchelf -- --set-interpreter "$(nix eval nixpkgs#stdenv.cc.bintools.dynamicLinker --raw)" /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint`.

After that, oxlint runs it is supposed to. I learned this is common with arbitrary executables on NixOS. Given the usefulness of this application, sooner rather than later someone will package oxlint for NixOS.

**Comment by Boshen** [comment]
There's an outdated version that is compiled from source 😅 https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/oxlint/default.nix

**Comment by Boshen** [comment]
> As suspected, it appears to be a NixOS-specific problem. As seen in https://discourse.nixos.org/t/why-does-this-binary-executable-give-cannot-execute-required-file-not-found/33948/3, a fix is patching the binary by running: `nix run nixpkgs#patchelf -- --set-interpreter "$(nix eval nixpkgs#stdenv.cc.bintools.dynamicLinker --raw)" /home/ME/.npm/_npx/f4a33d9b4519ccab/node_modules/@oxlint/linux-x64/oxlint`.
> 
> After that, oxlint runs it is supposed to. I learned this is common with arbitrary executables on NixOS. Given the usefulness of this application, sooner rather than later someone will package oxlint for NixOS.

Let me quickly search through github and see if there's similar installation script with nix specific instructions in it.

**Comment by sysarcher** [comment]
For those discovering this issue today, add support for dynamically linked executables:

```diff
diff --git a/configuration.nix b/configuration.nix
index 8f8d1bc..3e24cf3 100644
--- a/configuration.nix
+++ b/configuration.nix
@@ -165,6 +165,8 @@

+  programs.nix-ld.enable = true;
+  programs.nix-ld.libraries = [ pkgs.gcc ];
 
```
