### ISSUE TITLE
[Bug] Rule creator of unicorn: would not create cases with `outdent`

### ISSUE THREAD

**Issue by suyanhanx** [oxc-project/oxc#1694]
Take this rule `no-array-push-push` as an example:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-push-push.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/test/no-array-push-push.mjs

The original test cases:
![image](https://github.com/oxc-project/oxc/assets/24221472/f20bb749-02b9-492d-8152-2bf6fdaaec4f)
![image](https://github.com/oxc-project/oxc/assets/24221472/48e7fbbc-5363-4f58-9861-e929ad112833)

The cases generated by the rule creator:
![image](https://github.com/oxc-project/oxc/assets/24221472/a25bf804-3892-4aca-8b2b-a0516d7fa182)

It only generated the cases without `outdent`.

---
Outdent: https://www.npmjs.com/package/outdent

**Comment by suyanhanx** [comment]
Many rules that have been added need to be updated either. 😢

**Comment by mysteryven** [comment]
> Many rules that have been added need to be updated either. 😢

May continue to track this in #1699 😢

**Comment by camc314** [comment]
> Many rules that have been added need to be updated either. 😢

Most of the rules i added, if the rule gen did not copy it, i added the cases manually

for some rules such as https://github.com/sindresorhus/eslint-plugin-unicorn/blob/4cbcabe1b1cbaac0b03cf35196a141c14bf6c8ec/test/empty-brace-spaces.mjs#L44-L60 eslint plugin unicorn uses `map` which we also won't generate
