### ISSUE TITLE
Please consider adding From<Bump> for Allocator

### ISSUE THREAD

**Issue by Qix-** [oxc-project/oxc#1701]
As the title states, writing a transformer using a `VisitMut` where I need to change node types makes it really messy to do so when allocating new objects using the allocator that was used with the program. It requires that I have the consumer of the transformer pass down the `Allocator` they're using, which doesn't seem as nice.

It'd be great if I could do something like

```rust
Vec::from_iter_in(
    some_other_vec.iter().map(transform_element),
    some_other_vec.bump().into()
);
```

**Comment by Boshen** [comment]
It would be nice if you can show us some real usages, I'm happy to merge in utility functions.

We also have a `AstBuilder` you can utilize https://github.com/oxc-project/oxc/blob/main/crates/oxc_ast/src/ast_builder.rs
