### ISSUE TITLE
linter: shorthand for describing more detailed settings

### ISSUE THREAD

**Issue by tvolodimir** [oxc-project/oxc#1744]
Is there a more succinct way to describe more detailed settings? 

`oxlint --D perf -D correctness -D ..more... -A no-namespace -A jsx-no-useless-fragment -A react-in-jsx-scope -A no-new-array -A no-mixed-operators  -A ...and more`

as an example set in the file with parameters. `oxlint --some-config-prop ./my.config` ?

**Comment by Boshen** [comment]
Reading from `.eslintrc.json` is currently being worked on.

**Comment by Boshen** [comment]
Documented: https://oxc-project.github.io/docs/guide/usage/linter.html#usages
