### ISSUE TITLE
VSCode: don't lint files in .gitignore

### ISSUE THREAD

**Issue by KraXen72** [oxc-project/oxc#1752]
i do not need my auto-generated build files to be linted.
if somebody wants to lint files in git-ignored files, they can use the CLI.

**Comment by IWANABETHATGUY** [comment]
Do we need a `.oxlintignore`  @Boshen

**Comment by Boshen** [comment]
> Do we need a `.oxlintignore` @Boshen ?

No.

I think the problem is that vscode is not reading `.eslintignore` and `.gitignore` like how the CLI does it.

**Comment by IWANABETHATGUY** [comment]
> > Do we need a `.oxlintignore` @Boshen ?
> 
> No.
> 
> I think the problem is that vscode is not reading `.eslintignore` and `.gitignore` like how the CLI does it.

Got it

**Comment by KraXen72** [comment]
thanks!
