### ISSUE TITLE
How to enable all rules in Linter?

### ISSUE THREAD

**Issue by notramo** [oxc-project/oxc#1773]
I couldn't find documentation regarding rules in `oxlint`. When I run it, it says 70 rules are used, however the docs says it has 200+ rules.

**Comment by Boshen** [comment]
There is a `-D all` / `-A all` flag that I should document. Thank you for bringing this up.

**Comment by Boshen** [comment]
Documented: https://oxc-project.github.io/docs/guide/usage/linter.html#usages
