### ISSUE TITLE
How to run side by side with eslint?

### ISSUE THREAD

**Issue by jgeurts** [oxc-project/oxc#1774]
I'd like oxlint to run all of the rules it supports but use eslint for the remaining custom/unsupported rules. How are people accomplishing this now?

Do you have the primary/default eslint config with all oxlint rules explicitly turned off and then another eslint file for oxlint, with all 200 rules explicitly specified (see #1773)?

**Comment by Boshen** [comment]
It seems like we need to publish a `eslint-oxlint-plugin` that turns off all supported rules.

Since we are crossing the boundary with eslint, we will act diligently for these kind of things.

> How are people accomplishing this now?

The rules that we supply aren't too slow in ESLint right now so people haven't brought this topic up yet.

**Comment by Dunqing** [comment]
I created a [eslint plugin](https://github.com/Dunqing/eslint-plugin-oxlint) that supports turning off all rules that `oxc` already supports
