### ISSUE TITLE
Can oxlint support read eslintrc to use my configuration?

### ISSUE THREAD

**Issue by jjj-guo** [oxc-project/oxc#1799]
I want to use oxlint in my project,but oxlint default rule can not match my rule configuration.

**Comment by IWANABETHATGUY** [comment]
use 
```
npx oxlint@latest -c {{your config path}}
```

**Comment by IWANABETHATGUY** [comment]
e.g.: 
`npx oxlint@latest test.js -c ./.eslintrc.json`
Noticed the `--config` params is an experimental feature, so you can file an issue if you meet any problem.

**Comment by IWANABETHATGUY** [comment]
Closed, you could reopen this issue if you have any further question.
