### ISSUE TITLE
oxlint Failed to parse non-json eslint config

### ISSUE THREAD

**Issue by SymphonyIceAttack** [oxc-project/oxc#1804]
// .eslintrc.js
`
module.exports = {
  parser: "@typescript-eslint/parser",
  root: true,
  extends: "@react-native",
  rules: {
    "react-native/no-inline-styles": "off",
  },
};
`
when i run npx oxlint . -c .eslintrc.js  --fix 
Error: 
  × Failed to parse config ".eslintrc.js" with error "expected value at line 1 column 1"

**Comment by Boshen** [comment]
We won't be supporting `.js`, only `.json` will be supported in the foreseeable future.

We need to improve the error message when non-`.json` files passed.

**Comment by IWANABETHATGUY** [comment]
Maybe we can find a more static way to support this,  like a glob pattern, `!eslint-config-airbnb-base/react-*`. support configuration written with javascript requires a embed javascript engine,  even a javascript runtime, that would improve the binary and project complexity
