### ISSUE TITLE
ci: change benchmark files to capture more JavaScript features.

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1806]
The benchmarks are currently es5 javascript files, we need to add TypeScript files in the mix.

**Comment by Dunqing** [comment]
We can use https://esm.sh instead which supports pass `target`. This way we can test more javascript features. But I don't know which packages make heavy use of `PrivateIdentifier` 

https://esm.sh/v135/antd@5.12.5/es2022/antd.bundle.mjs
https://esm.sh/v135/typescript@5.3.3/es2022/typescript.bundle.mjs

**Comment by Boshen** [comment]
We can use raw github files instead of reading from cdn

https://raw.githubusercontent.com/microsoft/TypeScript/v5.3.3/src/compiler/checker.ts

I'll make a bigger change for this.
