### ISSUE TITLE
Considering rename `oxc_vscode` into `oxc_language_server`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [oxc-project/oxc#1821]
Currently, the **oxc language server** is named `oxc_vscode` https://github.com/oxc-project/oxc/blob/117d95f0aedcc3fe5d92030e1195ec05057b0741/editors/vscode/server/Cargo.toml#L2-L2,  but as a generic language server, it can be used in any editor that supports [language server protocol](https://microsoft.github.io/language-server-protocol/). So I think `oxc_ls` aka **oxc language server** should be a better name for our language server.

**Comment by IWANABETHATGUY** [comment]
cc @Boshen

**Comment by IWANABETHATGUY** [comment]
part of https://github.com/oxc-project/oxc/issues/1217#issuecomment-1811740007

**Comment by Boshen** [comment]
biome calls it biome_lsp I think? The naming doesn't really matter as long as it works for IDEs ...

**Comment by IWANABETHATGUY** [comment]
No, if we want to support more editor clients, it matters, `oxc_vscode` sounds like it is `vscode` only, but it is a generic language server, It may affect adoption.

**Comment by IWANABETHATGUY** [comment]
I think we should rename it ASAP since the language server is not widely used yet.

**Comment by Boshen** [comment]
> I think we should rename it ASAP since the language server is not widely used yet.

Sure, just do it. It's currently published to vscode market place as `oxc`, the underlying crate is not published.

**Comment by IWANABETHATGUY** [comment]
Alright, lsp technically means `language server protocal`, I don't think  `biome_lsp` is a good name for a language server, so I am sticked to use `oxc_ls` aka `oxc language server`

**Comment by Boshen** [comment]
I always try to avoid abbreviations when possible, to avoid confusion for new contributors, how about oxc_language_server?

**Comment by IWANABETHATGUY** [comment]
> I always try to avoid abbreviations when possible, to avoid confusion for new contributors, how about oxc_language_server?

That's alright, but `ls` is commonly used, 

**ls**
![image](https://github.com/oxc-project/oxc/assets/17974631/92b5315f-dc14-4d76-9047-6301463cd642)
**language_server**
![image](https://github.com/oxc-project/oxc/assets/17974631/d2ab8352-fd5f-4560-8e10-f1c5fbe45c8a)

**Comment by IWANABETHATGUY** [comment]
> I always try to avoid abbreviations when possible, to avoid confusion for new contributors, how about oxc_language_server?

I used name `oxc_language_server` in pull request.
