### ISSUE TITLE
EmptyParenthesizedExpression should generate non-recoverable error

### ISSUE THREAD

**Issue by u9g** [oxc-project/oxc#1870]
EmptyParenthesizedExpression should generate a non-recoverable error since when it happens, the ast is no longer valid.

**Comment by Boshen** [comment]
Context: 

https://github.com/oxc-project/oxc/blob/96b8f8f80c9ff0b5db8c39eee9cbffd7cdb1abfd/crates/oxc_parser/src/js/expression.rs#L209-L211

Return the error here.
