### ISSUE TITLE
Vscode doesn't show Problems/Lints upon installation

### ISSUE THREAD

**Issue by shunkakinoki** [oxc-project/oxc#1883]
Thank you for your contribution!

Trying the `oxlint`, installed both locally and globally, but fails to show the problems and lints inside the Vscode code editor - would love to get help on how to get it working

Again, thank you really for your tireless work on the project - really gonna save tireless dev hours

**Comment by shunkakinoki** [comment]
These are some screenshots in the `Output` of `oxc` and `oxc server`

<img width="1719" alt="Screenshot 2024-01-03 at 10 06 33" src="https://github.com/oxc-project/oxc/assets/39187513/2b3b6712-6f6c-4eca-a880-69c581593ab9">
<img width="632" alt="Screenshot 2024-01-03 at 10 06 44" src="https://github.com/oxc-project/oxc/assets/39187513/d81a95ea-8f25-43f5-a2db-934faa6bdeff">

**Comment by Boshen** [comment]
@IWANABETHATGUY It seems like we need to emit more debugging messages for triaging issues like this

**Comment by IWANABETHATGUY** [comment]
Can you check if the `oxlint`, (npm package) works?

**Comment by IWANABETHATGUY** [comment]
And can 

> @IWANABETHATGUY It seems like we need to emit more debugging messages for triaging issues like this

Sure

**Comment by Boshen** [comment]
Close as lacking context, feel free to reopen if you figured out why it's not working.

We'll add more debugging messages in the future.
