### ISSUE TITLE
creating rules for next.js (based on eslint-config-next)

### ISSUE THREAD

**Issue by MrOxMasTer** [oxc-project/oxc#1905]
I think we need to come up with something by the developers of next.js make joint rules based on those that already exist in next.js . I think they will appreciate such an alternative, especially on Rust, instead of

**Comment by MrOxMasTer** [comment]
https://github.com/vercel/next.js/discussions/60271

**Comment by Boshen** [comment]
@camc314 @mysteryven do you wanna take a look at their test suite and see whether we can write a rule gen?
