### ISSUE TITLE
feat(vscode): support vue / astro / svelte

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1915]
https://github.com/oxc-project/oxc/blob/bb6128bfa8141050b107e995960ff939d3155761/crates/oxc_language_server/src/linter.rs#L312-L316

Sorry I was in a rush 😅

**Comment by Stanzilla** [comment]
Will that also stop oxlint from throwing Unexpected token for <template> tags in .vue files?

**Comment by IWANABETHATGUY** [comment]
> Will that also stop oxlint from throwing Unexpected token for tags in .vue files?

Yeah, oxlint vue supportation has been done before, this pull request is about the vscode and language server.

**Comment by crystalfp** [comment]
Nice, but seems oxlint is ignoring *.vue files:
```
$ npx oxlint@latest --no-ignore  src/components/*.*
Finished in 0ms on 0 files with 87 rules using 12 threads.
Found 0 warnings and 0 errors.
$
```
Which is the magic to enable *.vue files check? Also there are rules related to react, but none about vue.
On Window 11 oxlint 0.2.13

**Comment by Boshen** [comment]
> Nice, but seems oxlint is ignoring *.vue files:
> 
> ```
> $ npx oxlint@latest --no-ignore  src/components/*.vue
> Finished in 0ms on 0 files with 87 rules using 12 threads.
> Found 0 warnings and 0 errors.
> $
> ```
> 
> Which is the magic to enable *.vue files check? Also there are rules related to react, but none about vue. On Window 11 oxlint 0.2.13

Can you try `npx oxlint@latest --no-ignore "src/components/*.vue"`, there's a shell expansion if it's unquoted I think.

**Comment by crystalfp** [comment]
No change
```
$ npx oxlint@latest --no-ignore "src/components/*.vue"
Finished in 0ms on 0 files with 87 rules using 12 threads.
Found 0 warnings and 0 errors.
```
And there are 7 vue files in the directory.

**Comment by crystalfp** [comment]
Well, found the problem. You have to specify the directory, not wildcards.
```
$ npx oxlint src/components
Finished in 8ms on 7 files with 87 rules using 12 threads.
Found 0 warnings and 0 errors.
```
Seems a problem specific to Windows that does not expand wildcards on the command line.
Maybe adding this to the documentation could help...
