### ISSUE TITLE
bug(parser): TSJSDocNonNullableType

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1920]
```
interface Cart {
	createdAt: string!
	updatedAt: string!
}
```

This `!` gets parsed into `TSJSDocNonNullableType` 

![image](https://github.com/oxc-project/oxc/assets/1430279/29b15e1f-e575-49c9-9afc-320c3f266deb)

Type definition is here:

https://github.com/oxc-project/oxc/blob/e550b4bd9721e3bb333109f6e2b70f1b9e92bff0/crates/oxc_ast/src/ast/jsdoc.rs#L11-L16

**Comment by Dunqing** [comment]
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJymZBvAUASASgjkgBMBBMALmQGcwpQBzAQgIFcAHM0iSmvUYt2AXyA

I'm curious why typescript can't parse this code

**Comment by Boshen** [comment]
TypeScript 🤷
