### ISSUE TITLE
Misinterprets closing tag when using Vue generic component

### ISSUE THREAD

**Issue by Tsuyoshi84** [oxc-project/oxc#1938]
When using [Vue generic component](https://vuejs.org/api/sfc-script-setup.html#generics), oxc misinterprets the closing tag if using another generic inside the `generic` attribute. 

Here is an example:

```vue
<script setup lang="ts" generic="T extends Record<string, string>">
defineProps<{ value: T }>()
</script>
```

In the above example, `generic` includes `Record<string, string>`. Since it has `>`, it looks like that oxc interprets that `>` as the closing tag of `script`.

Here is the result of oxlint:
```
❯ npx oxlint@latest

  × Unterminated string
   ╭─[src/components/Sample.vue:1:1]
 1 │ ">
   · ───
 2 │ defineProps<{ value: T }>()
   ╰────
```

**Comment by Dunqing** [comment]
It looks like the vue loader doesn't currently support the generic syntax.

**Comment by Boshen** [comment]
I didn't know this is a thing.

We'll have to parse the html attributes now :-)

**Comment by Stanzilla** [comment]
Is this what causes that error as well? 
![Code-2024-01-08-08 55 33](https://github.com/oxc-project/oxc/assets/75278/d24e2b9b-d972-4c1a-b94a-e77ad273584f)
