### ISSUE TITLE
support configuring the config file path from vscode settings.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [oxc-project/oxc#1944]

**Comment by Djiit** [comment]
Hey team, this is currently a show-stopper for us. Any guidance on where to start hacking to get this working?

**Comment by Boshen** [comment]
@IWANABETHATGUY is taking a break from a huge neck pain.

---

To start hacking:

* build instructions: https://oxc-project.github.io/docs/contribute/vscode.html
* js glue: https://github.com/oxc-project/oxc/blob/main/editors/vscode/client/extension.ts
* Rust part: make this configurable https://github.com/oxc-project/oxc/blob/2794064eef4c6b57cfc9f58d18ed7e2730a994a4/crates/oxc_language_server/src/main.rs#L336
* Vscode part: figure out how to add a UI for accepting a path configuration

**Comment by IWANABETHATGUY** [comment]
for how to add a config in vscode extension: you could refer to https://code.visualstudio.com/api/references/contribution-points#contributes.configuration,

**Comment by Djiit** [comment]
Thanks both of you - really good pointers. Will try my luck this weekend.

**Comment by Boshen** [comment]
Released in https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.2.6
