### ISSUE TITLE
Is it possible to disable a whole "plugin" ?

### ISSUE THREAD

**Issue by Djiit** [oxc-project/oxc#1970]
I'd like to be able to disable "eslint-unicorn-plugin" rules altogether. Is there any specific syntax for this? Thanks.

**Comment by Boshen** [comment]
Good call, this is a missing feature.

**Comment by Djiit** [comment]
Appreciate the quick answer. Thanks.

**Comment by Boshen** [comment]
Next version:

```
--disable-react-plugin** — Disable react plugin, which is turned on by default
--disable-unicorn-plugin** — Disable unicorn plugin, which is turned on by default
--disable-typescript-plugin** — Disable TypeScript plugin, which is turned on by default
```

**Comment by Mouvedia** [comment]
@Boshen do we also have `--disable-oxc-plugin` and `--disable-deepscan-plugin`?
i.e. I want only ESLint rules
