### ISSUE TITLE
Parser avoid hashing on writing/reading escaped strings

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2016]
#2010 uses a clever wheeze to avoid storing an ID in `Token` for escaped strings.

It just occurred to me that maybe there's a further optimization:

When `get_string()` or `get_template_string()` is called, isn't the relevant `&str` always the last one to have been inserted into `escaped_strings` / `escaped_templates`?

If so, `escaped_strings` and `escaped_templates` could be `Vec`s, and `get_string()` would just do:

```rs
fn get_string(&self, token: Token) -> &'a str {
  if token.escaped {
    return self.escaped_strings.last().unwrap();
  }
  // ...
}
```

That would avoid hashing `start` on insertion and lookup.

**Comment by Boshen** [comment]
We can give it a try. I doubt it's going to work because of `peek` though.

**Comment by Boshen** [comment]
I made a draft https://github.com/oxc-project/oxc/pull/2120

But my small brain still don't understand why would this work ... Let me sit on this for a bit.

**Comment by overlookmotel** [comment]
I was thinking about this. I'm guessing that the circumstances in which a token has to be "rewound" and re-lexed don't include the cases where strings/regexes/identifer tokens get built, so the order is preserved. But I'm not familiar with the parser yet, so can't say for sure.

`peek()` in the lexer shouldn't affect order, as it only peeks a char and doesn't cause a string/regex/identifier to be lexed in full.

If there's any circumstance where strings/regexes/identifers can get lexed twice, we should probably try to prevent that anyway, as those are some of the most expensive operations in the lexer.

**Comment by Boshen** [comment]
I'm going to close this for now because this is on a cold path, and it is easy to verify the current approach is correct.
