### ISSUE TITLE
Linter doesn't support VNode in the *.vue file

### ISSUE THREAD

**Issue by YFengFly** [oxc-project/oxc#2034]
oxc lint version: 0.2.0

An example:
[https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/Sidebar/Item.vue](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/Sidebar/Item.vue)

It will be reported as:
```bash
  × Unexpected token
    ╭─[src\layout\components\Sidebar\Item.vue:20:1]
 20 │       if (icon.includes('el-icon')) {
 21 │         vnodes.push(<i class={[icon, 'sub-el-icon']} />)
    ·                     ─
 22 │       } else {
    ╰────
```

For Vue, it supports VNode&JSX：
[https://cn.vuejs.org/guide/extras/render-function.html](https://cn.vuejs.org/guide/extras/render-function.html)
[https://v2.cn.vuejs.org/v2/guide/render-function.html](https://v2.cn.vuejs.org/v2/guide/render-function.html)

### Expect:
support for vnode syntax

**Comment by Boshen** [comment]
The app uses the babel plugin `babel-preset-app`, which uses `@vue/babel-preset-jsx`. Oxlint will never be able to figure this out.

The best approach to fix this is adding the `lang="jsx"` tag.

I'm going to to close this as won't fix because oxlint doesn't read other configuration files.
