### ISSUE TITLE
VSCode Extension: Crash on start

### ISSUE THREAD

**Issue by mubaidr** [oxc-project/oxc#2047]
Type: <b>Bug</b>

workbench.desktop.main.js:sourcemap:149 [Extension Host] stack trace: Error: Client is not running and can't be stopped. It's current state is: startFailed
	at Bl.shutdown (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8639)
	at Bl.stop (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8218)
	at Bl.stop (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:51862)
	at Bl.doInitialize (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8043)
	at async Bl.start (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:4623) (at console.<anonymous> (c:\Users\ubaid58653\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:168551))
p @ workbench.desktop.main.js:sourcemap:149
workbench.desktop.main.js:sourcemap:2006 [oxc.oxc-vscode]Client is not running and can't be stopped. It's current state is: startFailed
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2006
workbench.desktop.main.js:sourcemap:2006 Error: Client is not running and can't be stopped. It's current state is: startFailed
	at Bl.shutdown (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8639)
	at Bl.stop (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8218)
	at Bl.stop (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:51862)
	at Bl.doInitialize (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:8043)
	at async Bl.start (c:\Users\ubaid58653\.vscode-insiders\extensions\oxc.oxc-vscode-0.2.0-win32-x64\out\main.js:39:4623)

Extension version: 0.2.0
VS Code version: Code - Insiders 1.86.0-insider (81725794264e4c0fddbc1b3b728013744ae90840, 2024-01-15T05:36:06.405Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Boshen** [comment]
@IWANABETHATGUY I think we need more logs for triaging issues like this.

**Comment by IWANABETHATGUY** [comment]
Can you try this? https://github.com/microsoft/vscode/issues/170836#issuecomment-1378333714

**Comment by mubaidr** [comment]
I don't have that specific extension installed (one mentioned in the referenced comment),but sure I will try extension bisecting vscode feature to identify the issue.

**Comment by IWANABETHATGUY** [comment]
cay you try to reinstall https://marketplace.visualstudio.com/items?itemName=oxc.oxc-vscode?

**Comment by mubaidr** [comment]
Sure, I will do that too. Will report back

**Comment by mubaidr** [comment]
Update: 
- removed extension
- restart vscode
- reinstall [oxc.oxc-vscode](https://marketplace.visualstudio.com/items?itemName=oxc.oxc-vscode)

Extension runtime status shows following errors: 
```bash
Activation Event:onLanguage:vue
Activation Time:26ms
Uncaught Errors (7)
Pending response rejected since connection got disposed
Client is not running and can't be stopped. It's current state is: starting
Client is not running and can't be stopped. It's current state is: startFailed
Pending response rejected since connection got disposed
Client is not running and can't be stopped. It's current state is: startFailed
Client is not running and can't be stopped. It's current state is: startFailed
Client is not running and can't be stopped. It's current state is: startFailed
```

Let me know if you need any log or info, please

**Comment by mubaidr** [comment]
Found the issue, seems like oxc is unable to parse `.eslintrc` file. (For example trailing commas are fine in this syntax but oxc parser does not support it and fails).
More over, i tried converting eslint config to `json` file, but still get following error: 

Error: 
```bash
Error - 2:55:24 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:55:24 AM] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:55:24 AM] oxc client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:55:24 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
thread 'main' panicked at crates/oxc_language_server/src/main.rs:346:18:
should initialized linter with new options:   × Failed to parse eslint config

Error:   × Failed to parse config "/projects/fl-qrgallery360/.eslintrc.json" with
  │ error "trailing comma at line 5 column 3"

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 2:55:43 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:55:43 AM] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:55:43 AM] oxc client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

`.eslintrc.json`
```json
{
  "env": {
    "browser": true,
    "node": true
  },
  "extends": [
    "@nuxt/eslint-config",
    "plugin:security-node/recommended",
    "plugin:anti-trojan-source/recommended",
    "prettier"
  ],
  "root": true,
  "rules": {
    "@typescript-eslint/consistent-type-imports": ["error"],
    "@typescript-eslint/no-import-type-side-effects": "error",
    "@typescript-eslint/no-unused-vars": "warn",
    "curly": ["error", "all"],
    // "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "import/default": "off",
    "import/export": "off",
    "import/named": "off",
    "import/namespace": "off",
    "import/no-named-as-default": "off",
    "import/no-named-as-default-member": "off",
    "max-statements-per-line": [
      "error",
      {
        "max": 1
      }
    ],
    "no-console": "off",
    "no-unused-vars": "off",
    "require-await": "off",
    "security-node/detect-unhandled-async-errors": "off",
    "security-node/detect-crlf": "off",
    "vue/component-options-name-casing": ["error", "PascalCase"],
    "vue/max-attributes-per-line": [
      "error",
      {
        "multiline": {
          "max": 1
        },
        "singleline": {
          "max": 1
        }
      }
    ],
    "vue/multi-word-component-names": "off",
    "vue/no-multiple-template-root": "off"
  }
}

```

**Comment by mubaidr** [comment]
Closing this in favor of: https://github.com/oxc-project/oxc/issues/2080
