### ISSUE TITLE
Bug in lexer's `read_jsx_child` function

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2094]
Sorry not to be more specific in the issue description, but I don't really understand what I'm looking at, except to know it doesn't look right.

From `read_jsx_child`:

https://github.com/oxc-project/oxc/blob/a36813405b386815c1b4076885a0df07e605a6d9/crates/oxc_parser/src/lexer/mod.rs#L955-L971

I can see 3 problems here:

1. `push_matching()` is called with the 1st char twice.
2. `push_matching()` is a no-op as `force_allocation_without_current_ascii_char()` is never called.
3. `builder` is discarded without using it anyway.

I'm unclear whether the problem is that there's some code missing to handle escapes, or whether all it needs to do is consume the JSX Text, so `builder` serves no purpose and can be removed.

I'm further confused because the comment here doesn't match the code it accompanies. Are the characters in question `>` and `}` (as in the comment) or `<` and `{` (as in the code)?

https://github.com/oxc-project/oxc/blob/a36813405b386815c1b4076885a0df07e605a6d9/crates/oxc_parser/src/lexer/mod.rs#L959-L963

**Comment by Boshen** [comment]
I removed the string builder in https://github.com/oxc-project/oxc/pull/2096, it felt like I thought I had to store the escaped jsx string, but realized it's not needed but I forgot to remove the code.

**Comment by Boshen** [comment]
Here's the git history before open sourcing:

```dif
-                    if matches!(self.peek(), '{' | '<' | '>' | '}') {
+                    // `>` and `}` are errors in TypeScript but not Babel
+                    // let's make this less strict so we can parse more code
+                    if matches!(self.peek(), '{' | '<') {
```

Here's one of the test that shows up if you revert the change:

```
+  × Unexpected token
+    ╭─[conformance/jsx/jsxEsprimaFbTestSuite.tsx:40:1]
+ 40 │
+ 41 │ <LeftRight left=<a /> right=<b>monkeys /> gorillas</b> />;
+    ·                                         ─
+ 42 │
+    ╰────
+
```

This test passes in babel but fails in TypeScript.

---

I'll improve the comment.

**Comment by overlookmotel** [comment]
Thank you. All makes sense now!
