### ISSUE TITLE
Run `oxlint --deny=correctness --deny=perf --fix` on a vue project will remove file contents mistakenly

### ISSUE THREAD

**Issue by ModyQyW** [oxc-project/oxc#2122]
## Steps

1. `git clone git@github.com:ModyQyW/oxc-2122.git`
2. `npm install`
3. `npm run oxlint`

## Expections

Not remove file contents mistakenly.

## Actual Happened

Remove file contents mistakenly.

<img width="1512" alt="image" src="https://github.com/oxc-project/oxc/assets/31850793/7aa853ef-8167-4eb7-b901-5fdad243f41a">

<img width="1512" alt="image" src="https://github.com/oxc-project/oxc/assets/31850793/79497d97-37a7-47f9-864d-e3ecb4693084">

## Env

<img width="509" alt="image" src="https://github.com/oxc-project/oxc/assets/31850793/6c1fc69b-6c36-400c-94d4-141026d670d4">

**Comment by Dunqing** [comment]
It looks like the problem is caused by the fact that we're extracting the contents of the `script`.

**Comment by Boshen** [comment]
We should ban this usage for now, the spans are wrong :-(

**Comment by Hebilicious** [comment]
I've noticed the same thing with svelte files and --fix when I tried it. Can this issue track for both?
