### ISSUE TITLE
AST Type generation for wasm targets

### ISSUE THREAD

**Issue by H-Plus-Time** [oxc-project/oxc#2151]
Ref: #301 for motivation.

More or less this boils down to deriving Tsify::tsify on _**all**_ the AST nodes in oxc_ast, some in oxc_syntax, oxc_span, oxc_semantic (bitflags, which semantic seems to have more of than the others, seem to be unreachable by the macro). Minimal changes to oxc_wasm itself.

I'm thinking the `cfg_attr(target_arch="wasm32", ...)` gate is probably evenly matched with a feature flag (`wasm`, naturally, as seen in zstd-rs, reqwest, chrono, etc), but I'm happy to go with the maintainers' preference.

Given the number of nodes (several hundred), the close association with serde and the low variation in the `cfg_attr(feature = "serde", ...)` macros (e.g. 80 identical ones in oxc_ast/src/js.rs), a macro_rules shorthand would be worthwhile, along the lines of:
```rust
#[ast_serde_macro(tag = "type")]
// expanding to:
#[cfg_attr(feature = "serde", derive(Serialize), serde(tag = "type"))]
#[cfg_attr(all(feature = "serde", feature = "wasm"), derive(Tsify)]
```
(as far as I can tell, it'll never be the intention to conditionally derive `serde::Deserialize`, so the only non-static part is the serde macro).

Let me know what you think is a reasonable compromise, I should have a PR up in a day or two.

As for the AST walker, I gather that'd be based on oxc_semantic's AstNodes impl, and wouldn't need to deal with closures crossing the JS-RS boundary (this is a particularly hairy part of wasm-bindgen :disappointed_relieved: ). Provided that's the case, these types should be sufficient.

**Comment by Boshen** [comment]
This is awesome! I think a prototype on a few ast nodes will point us to the right direction. Happy to move this forward!
