### ISSUE TITLE
☂️ eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2174]
> [!WARNING]
> This comment is maintained by CI. Do not edit this comment directly.
> To update comment template, see https://github.com/oxc-project/oxc/tree/main/tasks/lint_rules

This is tracking issue for `eslint-plugin-react-hooks`.

There are 2(+ 0 deprecated) rules.

- 2/2 recommended rules are remaining as TODO
- 0/0 not recommended rules are remaining as TODO
  - All done! 🎉

To get started, run the following command:

```sh
just new-react-hooks-rule <RULE_NAME>
```

Then register the rule in `crates/oxc_linter/src/rules.rs` and also `declare_all_lint_rules` at the bottom.

## Recommended rules

<details open>
<summary>
  ✨: 0, 🚫: 0 / total: 2
</summary>

| Status | Name | Docs |
| :----: | :--- | :--- |
|  | react-hooks/rules-of-hooks | https://reactjs.org/docs/hooks-rules.html |
|  | react-hooks/exhaustive-deps | https://github.com/facebook/react/issues/14920 |

✨ = Implemented, 🚫 = Not supported

</details>

**Comment by rzvxa** [comment]
@Boshen I wanted to implement these, I've noticed that the command `just new-react-hooks-rule <RULE_NAME>` doesn't work; I can create the rule manually I just need to know what should I change in order to keep this comment in sync in CI.

**Comment by rzvxa** [comment]
I just noticed that #2637 is a thing, I'm going to only work on the hook rules.

**Comment by Boshen** [comment]
> I just noticed that #2637 is a thing, I'm going to only work on the hook rules.

https://github.com/oxc-project/oxc/pull/2637 is stale, maybe you can help out and merge the code first, then improve upon it.

**Comment by Boshen** [comment]
> @Boshen I wanted to implement these, I've noticed that the command `just new-react-hooks-rule <RULE_NAME>` doesn't work; I can create the rule manually I just need to know what should I change in order to keep this comment in sync in CI.

There are only 2 rules, and the tests cannot be parsed automatically :-/

**Comment by rzvxa** [comment]
> > @Boshen I wanted to implement these, I've noticed that the command `just new-react-hooks-rule <RULE_NAME>` doesn't work; I can create the rule manually I just need to know what should I change in order to keep this comment in sync in CI.
> 
> There are only 2 rules, and the tests cannot be parsed automatically :-/

Should I put them under `react` or create a new category? It won't be such a bad thing to unify such categories and not base them strictly on the origin plugin.

**Comment by Boshen** [comment]
> > > @Boshen I wanted to implement these, I've noticed that the command `just new-react-hooks-rule <RULE_NAME>` doesn't work; I can create the rule manually I just need to know what should I change in order to keep this comment in sync in CI.
> > 
> > 
> > There are only 2 rules, and the tests cannot be parsed automatically :-/
> 
> Should I put them under `react` or create a new category? It won't be such a bad thing to unify such categories and not base them strictly on the origin plugin.

Yeah, under the react plugin should be fine.

**Comment by rzvxa** [comment]
> ✨: 0, 🚫: 0 / total: 2
> Status 	Name 	Docs
> 	react-hooks/rules-of-hooks 	https://reactjs.org/docs/hooks-rules.html
> 	react-hooks/exhaustive-deps 	[facebook/react#14920](https://github.com/facebook/react/issues/14920)

This didn't update, Have I missed something with the tasks?

**Comment by leaysgur** [comment]
That's because `react-hooks/*` rules are defined under `react::` mod, it should be `react_hooks::` to be tracked by lint_rules task.

https://github.com/oxc-project/oxc/blob/7ed673d2a5d53e5d9c69a60d21c4cd8ccaa0e817/crates/oxc_linter/src/rules.rs#L643

If this is intended, we need to update lint_rules task to mange these conversion.

**Comment by rzvxa** [comment]
> That's because `react-hooks/*` rules are defined under `react::` mod, it should be `react_hooks::` to be tracked by lint_rules task.
> 
> https://github.com/oxc-project/oxc/blob/7ed673d2a5d53e5d9c69a60d21c4cd8ccaa0e817/crates/oxc_linter/src/rules.rs#L643
> 
> If this is intended, we need to update lint_rules task to mange these conversion.
> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/6259812/329966019-4d8de237-2846-4604-9123-b700d114f667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODY2OTAsIm5iZiI6MTcxNTU4NjM5MCwicGF0aCI6Ii82MjU5ODEyLzMyOTk2NjAxOS00ZDhkZTIzNy0yODQ2LTQ2MDQtOTEyMy1iNzAwZDExNGY2NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMDc0NjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ4NjVjNTliYWIwNGQxODc0MzFhZWFkNzczNGU3NWJjYWI2Yzg3NzYwZGZjMjIzZDA2YWQwODkzNzgzNjlhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MsGhq40DdVhajJrUdUte5NNDk6hU_eairY_TfVLCZog">

Thanks, Yes it was intentional there are only 2 rules for hooks and I've spoken with @Boshen about merging them into react; And he gave the green light for it.

**Comment by Boshen** [comment]
I'm in favor of modifying the task script.

**Comment by rzvxa** [comment]
Can you help me with the change?

Should I do it in such a way that this issue gets closed in favor of adding these entries to #1022, Or keep this issue and just resolve the implementation from the `react` module?

**Comment by leaysgur** [comment]
FYI: If

> keep this issue and just resolve the implementation from the react module?

```diff
diff --git a/tasks/lint_rules/src/oxlint-rules.cjs b/tasks/lint_rules/src/oxlint-rules.cjs
index 65302b62..e8ee28c5 100644
--- a/tasks/lint_rules/src/oxlint-rules.cjs
+++ b/tasks/lint_rules/src/oxlint-rules.cjs
@@ -90,7 +90,12 @@ exports.createRuleEntries = (loadedAllRules) => {
 exports.updateImplementedStatus = async (ruleEntries) => {
   const implementedRuleNames = await readAllImplementedRuleNames();

-  for (const name of implementedRuleNames) {
+  for (let name of implementedRuleNames) {
+    // These rules are implemented under `react::` mod, but issue is separated
+    if (name === "react/rules-of-hooks" || name === "react/exhaustive-deps") {
+      name = name.replace("react/", "react-hooks/");
+    }
+
     const rule = ruleEntries.get(name);
     if (rule) rule.isImplemented = true;
     else console.log(`👀 ${name} is implemented but not found in their rules`);
```

If not, there is a little more work to do. 😅

**Comment by rzvxa** [comment]
Well, I haven't tested it, You seem to have a much clearer knowledge of linters. Do you think it is possible to resolve this by changing the prefix here?
https://github.com/oxc-project/oxc/blob/34dd53cc9842161b20d78682596e5367a7119cfa/tasks/lint_rules/src/eslint-rules.cjs#L186-L194

**Comment by rzvxa** [comment]
> If not, there is a little more work to do. 😅

You seem to have a much clearer idea of this, Do you think it is possible to add `react-hook` plugins as `react` here so we can add it to the `react` issue(in case even want to)?

https://github.com/oxc-project/oxc/blob/34dd53cc9842161b20d78682596e5367a7119cfa/tasks/lint_rules/src/oxlint-rules.cjs#L64-L87

**Comment by leaysgur** [comment]
(Actually, I am the original author of this task. 🤫 )

I was thinking that there are a few possible ways to handle this.
If it's okay to address it (maybe) this weekend, I can take care of it.

**Comment by rzvxa** [comment]
> (Actually, I am the original author of this task. 🤫 )

Makes sense😅

Let me know if there is anything that I can help with, especially if you didn't have the time to do it.

**Comment by smorimoto** [comment]
@Boshen I think some rules for React Compiler have been added. Are there any plans to add support for them? Now that the Vite React plugin supports React Compiler, I think the Vite ecosystem could be considered to fully support it once Oxlint does as well.
https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks#flat-config-eslintconfigjsts-1

**Comment by camc314** [comment]
>  I think some rules for React Compiler have been added. Are there any plans to add support for them? Now that the Vite React plugin supports React Compiler, I think the Vite ecosystem could be considered to fully support it once Oxlint does as well.

Hi, thanks for the suggestion, we have no plans to add suport for the react compiler rules due to the large maintence burden associated with it. You can run the react compiler rules via a JS plugin. [Here](https://github.com/camc314/oxlint-repros/tree/main/issue-react-compiler-rules) is a demo of running the react compiler rules inside oxlint - thanks!

**Comment by smorimoto** [comment]
There was certainly JS Plugin! Thank you!
