### ISSUE TITLE
Throw error with pnpx oxlint@latest

### ISSUE THREAD

**Issue by s3xysteak** [oxc-project/oxc#2186]
2024-1-27 00:19:39
I use `pnpx oxlint@latest` in windows powershell with `Node.js v20.9.0`
It throw : 
```
PS D:\Code\co-de> pnpx oxlint@latest
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '@oxlint/win32-x64/oxlint.exe'
Require stack:
- D:\.pnpm-store\v3\tmp\dlx-126484\node_modules\.pnpm\oxlint@0.2.6\node_modules\oxlint\bin\oxlint
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at Object.<anonymous> (D:\.pnpm-store\v3\tmp\dlx-126484\node_modules\.pnpm\oxlint@0.2.6\node_modules\oxlint\bin\oxlint:114:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\.pnpm-store\\v3\\tmp\\dlx-126484\\node_modules\\.pnpm\\oxlint@0.2.6\\node_modules\\oxlint\\bin\\oxlint'
  ]
}
```

**Comment by mysteryven** [comment]
Didn't reproduce it in windows with pnpm 8.15.0.

Could you please try if npm works for you?

```bash
npx oxlint@latest
```

**Comment by s3xysteak** [comment]
It both works well with `pnpx` & `npx` now. I think it was just a temporary network issues, so I close the issue. If it happened again, I will reopen it and try to figure out what happened.

**Comment by lvjiaxuan** [comment]
> It both works well with `pnpx` & `npx` now. I think it was just a temporary network issues, so I close the issue. If it happened again, I will reopen it and try to figure out what happened.

It happens again for now. I have reproduced it on GitHub CodeSpaces to make sure it isn't network problem.

**Comment by Boshen** [comment]
> > It both works well with `pnpx` & `npx` now. I think it was just a temporary network issues, so I close the issue. If it happened again, I will reopen it and try to figure out what happened.
> 
> It happens again for now(oxlint@0.2.13). I have reproduced it on GitHub CodeSpaces to make sure that isn't network problem.

Can you help me and find the cause of the problem?

**Comment by lvjiaxuan** [comment]
> > > It both works well with `pnpx` & `npx` now. I think it was just a temporary network issues, so I close the issue. If it happened again, I will reopen it and try to figure out what happened.
> > 
> > 
> > It happens again for now(oxlint@0.2.13). I have reproduced it on GitHub CodeSpaces to make sure that isn't network problem.
> 
> Can you help me and find the cause of the problem?

It seems like dependencies trouble, it isn't a common issue. I will figure it out.
