### ISSUE TITLE
[bug][scope analysis] A symbol has two owner scopes in the same time

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#2205]
```js
(() => {
	function a() {
		b()
	}
	{
		var b = () => {}
	}
	a()
})()
```

I notice that symbol `b` belong to two owner scopes after the sematic analysis in `oxc@0.5.0`.

**Comment by hyf0** [comment]
> The logic here is that these scopes have the variable `b`. There is no owning logic.

So, is this logic expected? A binding could belong to many scopes in the same time.

If this is expected, what's right way to get a binding's owner scope(the scope that store it in the first place)?

**Comment by hyf0** [comment]
> I put the code in the [playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIDEgICAgICAgICU4CDAwYNr8hGcuCDxYi6%2FNT2Pq2agjPh5gSkw0MoSG2qHiQh%2BxtptaByIxzZ5Zk8U1P7pxA9KeOB%2FdyhOgA%3D%3D)

Wow I didn't thought the playgound is already support visulize the scopes. This is very useful.

If the playgound could aslo print out the symbol id for symbols, it will be very useful to distinguash symbols that has the same name.

**Comment by hyf0** [comment]
The scope output for input

```js
(() => {
        var b;
	function a() {
		b()
	}
	{
		var b = () => {}
	}
	a()
})()
```

is 

```
Scope1 (ScopeFlags(StrictMode | Top)) {
  Scope2 (ScopeFlags(StrictMode | Function | Arrow)) {
    Bindings: {
      b (SymbolFlags(FunctionScopedVariable))
      a (SymbolFlags(FunctionScopedVariable))
    }
    Scope3 (ScopeFlags(StrictMode | Function)) {
    }
    Scope4 (ScopeFlags(StrictMode)) {
      Scope5 (ScopeFlags(StrictMode | Function | Arrow)) {
      }
    }
  }
}

```

I'm not sure if this is right or wrong, but it does feel weird to me.

**Comment by Dunqing** [comment]
> If the playgound could aslo print out the symbol id for symbols, it will be very useful to distinguash symbols that has the same name.

Maybe the symbol view is useful for you, the b symbol has been highlighted<img width="1153" alt="image" src="https://github.com/oxc-project/oxc/assets/29533304/1bdb1ecf-3089-4c5f-a8dd-a59dd78bdf9a">

**Comment by hyf0** [comment]
> > If this is expected, what's the right way to get a binding's owner scope(the scope that store it in the first place)?
> 
> 
> 
> I think we can't get the binding's owner scope now. 
> 
> 
> 
> Although the `b` symbol contains the symbol in both its scope and its parent scope, that symbol id and node id both point to the same one, I don't know if this will help you

Yeah, I know that. I just want to know if the current behavior is correct. If it's expected, I will try to solve my problems in user land. If it's not, it becomes a bug that oxc needs to fix.

**Comment by Dunqing** [comment]
I think that is expected. But need @Boshen to confirm this.

**Comment by Boshen** [comment]
@hyf0 Let me investigate and get back to you. var hoisting logic is complicated :-)

**Comment by Dunqing** [comment]
After the communication, we think the result is expected.
