### ISSUE TITLE
refactor(linter): use the same miette graphical reporter for tests

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2217]
> I'm a bit worried that none of the tests failed though - would that be expected?

This is the forked graphical reporter, the testers are using the one from miette. Let me clean this up a little bit.

**Comment by maurice** [comment]
If it's not urgent, can I have a go at that?

**Comment by Boshen** [comment]
> If it's not urgent, can I have a go at that?

Yes of course!
