### ISSUE TITLE
Symbol missing redeclare variable information

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#2219]
Symbol missing redeclare variable information
              The scope output for input

```js
(() => {
        var b;
	function a() {
		b()
	}
	{
		var b = () => {}
	}
	a()
})()
```

is 

```
Scope1 (ScopeFlags(StrictMode | Top)) {
  Scope2 (ScopeFlags(StrictMode | Function | Arrow)) {
    Bindings: {
      b (SymbolFlags(FunctionScopedVariable))
      a (SymbolFlags(FunctionScopedVariable))
    }
    Scope3 (ScopeFlags(StrictMode | Function)) {
    }
    Scope4 (ScopeFlags(StrictMode)) {
      Scope5 (ScopeFlags(StrictMode | Function | Arrow)) {
      }
    }
  }
}

```

I'm not sure if this is right or wrong, but it does feel weird to me.

_Originally posted by @hyf0 in https://github.com/oxc-project/oxc/issues/2205#issuecomment-1914823750_

**Comment by Boshen** [comment]
Can be used to simplify https://github.com/oxc-project/oxc/blob/main/crates/oxc_linter/src/rules/eslint/no_shadow_restricted_names.rs
