### ISSUE TITLE
Irregular whitespace in Lexer

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2236]
Is it intentional that `self.consume_char()` is *after* `self.trivia_builder.add_irregular_whitespace()` here:

https://github.com/oxc-project/oxc/blob/a79988d5e2cd0cf616b56ae1236e5c29d3d950bd/crates/oxc_parser/src/lexer/unicode.rs#L30-L35

As it is at present, `self.current.token.start` and `self.offset()` are the same, so the "trivia"'s span is just a pointer to the start of the irregular whitespace. If `self.consume_char()` was moved to before, span would cover the characters in question (start to end).

I'm not clear what the purpose of recording irregular whitespace is, so not sure if this is intentional or not.

**Comment by Boshen** [comment]
It's for the linter rule "no irregular whitespaces".

I'll take a look soon.

**Comment by overlookmotel** [comment]
Ah I see. Should irregular line breaks also be recorded as trivia and caught by the linter too? (I don't believe they are at present)

**Comment by Boshen** [comment]
I need to check when I get home.

Speaking of irregular whitespaces and line breaks, if we can do a pre parsing using simd or memchr to get rid of these irregulars (allocation will be rare because they aren't present 99.99% of the time), then we can remove these irregular checks from the tokenizers and truely simd them!

**Comment by overlookmotel** [comment]
> Speaking of irregular whitespaces and line breaks, if we can do a pre parsing using simd or memchr to get rid of these irregulars (allocation will be rare because they aren't present 99.99% of the time), then we can remove these irregular checks from the tokenizers and truely simd them!

My [work in progress](https://codspeed.io/overlookmotel/oxc/branches/lexer-string4) takes a similar approach to what you've suggested, except it doesn't do a pre-pass. It just assumes there won't be Unicode characters or escapes in identifiers, and has a fast path for that case. Only when a Unicode character is found, it de-opts and deals with it. I've not used SIMD instructions, but have designed the implementation so it's processing batches of 32 bytes, so could be SIMD-ized quite easily later on.

A pre-pass might be even faster, but I'm not sure. That'd have the disadvantage of reading the whole file from memory twice, whereas doing it chunk-by-chunk avoids that. Not sure how the balance of those 2 would play out. Might well be worth trying.
