### ISSUE TITLE
Implement eslint/no-dupe-args

### ISSUE THREAD

**Issue by TzviPM** [oxc-project/oxc#2257]
Part of #479

Docs at https://eslint.org/docs/latest/rules/no-dupe-args

Note this comment:

> It does not apply to arrow functions or class methods, because the parser reports the error.

I imagine the test262 parser tests already exercise this code path, but let's confirm that the parser should behave this way, and if it should, that it does.

**Comment by Boshen** [comment]
This rule is only useful in non-strict nowadays. I think we can safely whitelist this from our automated reporter.

https://github.com/oxc-project/oxc/blob/de6d2f5dc5efb4986dbfb88486e2fc8ad715ee3c/tasks/lint_rules/src/oxlint-rules.cjs#L45
