### ISSUE TITLE
The col of the file position output by oxlint's error log is always 1

### ISSUE THREAD

**Issue by higuaifan** [oxc-project/oxc#2270]
Hi, 
I've looked through the documentation but couldn't find any explanation about this. 
Also, I'm not very familiar with Rust. I've spent some time trying to understand the source code, but it's still a bit challenging for me. Therefore, I can't determine from the source code whether this is a feature or a bug, and I can only create an issue to seek help. 

 However, from the results, it seems that the positioning is not very accurate, and even the row can have problems.
<img width="1399" alt="image" src="https://github.com/oxc-project/oxc/assets/9988024/c9911072-7c9c-4a74-b40d-a0224d9f3c40">
 I think, according to conventional cognition, a clear positioning like eslint seems to be more correct? 
<img width="575" alt="image" src="https://github.com/oxc-project/oxc/assets/9988024/b362bfbe-ed1f-48c5-9df6-203c9212ef6e">

Clear positioning means that I can use some means to directly jump to the location of the error in bash. 

This is a minimally implemented demo project：[link](https://codesandbox.io/p/devbox/gh45r2?file=%2Fpackage.json%3A10%2C16-10%2C37&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls4e1fee00063b6hnpq9tsdk%2522%252C%2522sizes%2522%253A%255B44.20289855072464%252C55.79710144927536%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls4e1fee00023b6hpim7i1sv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls4e1fee00033b6h1k0v1929%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls4e1fee00053b6hlh4a16bo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls4e1fee00023b6hpim7i1sv%2522%253A%257B%2522id%2522%253A%2522cls4e1fee00023b6hpim7i1sv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls4e1fee00013b6heb494n5u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls4e1fee00013b6heb494n5u%2522%257D%252C%2522cls4e1fee00053b6hlh4a16bo%2522%253A%257B%2522id%2522%253A%2522cls4e1fee00053b6hlh4a16bo%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls4e1fee00033b6h1k0v1929%2522%253A%257B%2522id%2522%253A%2522cls4e1fee00033b6h1k0v1929%2522%252C%2522activeTabId%2522%253A%2522cls4e4hlz009q3b6hb5qdop0w%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cls4e2ksf003w3b6h87nehxo6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cls4e4hlz009q3b6hb5qdop0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls4e4hsk000xddeec9soheu8%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Boshen** [comment]
Fixed by https://github.com/oxc-project/oxc/pull/2242, will make a new release soon.
