### ISSUE TITLE
Shard benchmarks into multiple CI jobs

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2345]
Now that #2343 has bust out of using Codspeed's `cargo codspeed build` for building benchmarks, could next step be to repeat the trick for the Github action which runs the benchmarks, and shard the benchmarks across multiple jobs?

I'm thinking:
* Separate jobs for each group of benchmarks.
* Final job that pulls all the results together and uploads them to CodSpeed as if it was one.

Have also opened an issue on CodSpeed's Github action repo: https://github.com/CodSpeedHQ/action/issues/92

**Comment by Boshen** [comment]
We already raise several similar issues in their discord. They are only 2 engineers who are busy with lots of stuff 😅

**Comment by overlookmotel** [comment]
Fair enough. Do you think it'd be a lot of work to hack something together ourselves?

From looking at their [runner](https://github.com/CodSpeedHQ/runner/blob/main/src/uploader/upload.rs) it looks like what it uploads is just a GZIP of the `profile` folder and some metadata from Github. I have no experience of writing Github Actions, but it seems *maybe* feasible...

**Comment by Boshen** [comment]
Let's wait for their feedback.

**Comment by adriencaccia** [comment]
Hey guys, just responded in https://github.com/CodSpeedHQ/action/issues/92#issuecomment-1935729924

It could be done without any changes in our app, only changing the https://github.com/CodSpeedHQ/runner and https://github.com/CodSpeedHQ/action repos

**Comment by Boshen** [comment]
Closing this one for house keeping. This issue is subscribed at https://github.com/CodSpeedHQ/action/issues/92
