### ISSUE TITLE
Export checkstyle or SARIF format

### ISSUE THREAD

**Issue by Maeda-Naoki** [oxc-project/oxc#2355]
Can oxc export Lint results in checkstyle format or SARIF format?   
I would like to display oxc's Lint results on the PR using [reviewdog](https://github.com/reviewdog/reviewdog).

**Comment by Boshen** [comment]
The infrastructure is ready to accept more reporters. See https://github.com/oxc-project/oxc/blob/main/crates/oxc_diagnostics/src/reporter.rs

**Comment by Boshen** [comment]
`checkstyle` is preferred https://eslint.org/docs/latest/use/formatters/#checkstyle
