### ISSUE TITLE
Support import attributes in TS import type

### ISSUE THREAD

**Issue by ArnaudBarre** [oxc-project/oxc#2394]
It was probably missed in https://github.com/oxc-project/oxc/pull/1476 cc @magic-akari

[playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAICugICAgICAgIC6nsrEgteLFrCnWxZJ6UoiXAWr%2BrfTnfm4guFpz5olWBypnRuwJFTQb9mCgzqMsX9%2FPEoAgA%3D%3D)

I don't know if this is actually used, found it when exploring the difference between Oxc and TSESTree.

**Comment by magic-akari** [comment]
If TypeScript supports this syntax, I believe we should adopt it as well.

**Comment by Dunqing** [comment]
Do you have time to do this? If not, I'm interested in taking over @Boshen
