### ISSUE TITLE
oxlint: jest-plugin: no-export: false positives for exports in __mocks__ files

### ISSUE THREAD

**Issue by jokeyrhyme** [oxc-project/oxc#2397]
Thanks so much for sharing this exciting project!

I have a project that uses the manual mocks feature for jest: https://jestjs.io/docs/manual-mocks

e.g.

- other.js (contains `export do() => { /* ... */ }`)
- \_\_mocks\_\_/other.js (contains `export do() -> jest.fn().mockImplementation(() => { /* ... */ })`)
- thing.js (contains `import './other.js'`)
- thing.test.js (contains `jest.mock('./other.js')`)

It's expected that these jest manual mock files `export` just like the production files that they mirror

`oxlint --jest-plugin` (version 0.2.8) results in "⚠ eslint-plugin-jest(no-export): Do not export from a test file." when scanning \_\_mocks\_\_/other.js , so it seems to consider these manual mock files to be test files, but I _think_ it should not classify them as test files

**Comment by mysteryven** [comment]
Thanks for your using! we treated it as a test file if it imports global variables like `jest`, `beforeEach`, `test`, etc… we should distinguish it by [file path](https://jestjs.io/docs/configuration#testmatch-arraystring).

**Comment by jokeyrhyme** [comment]
By default, jest uses these lists of globs to find test files:

- https://jestjs.io/docs/configuration#testmatch-arraystring: `[ "**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)" ]`
- https://jestjs.io/docs/configuration#testregex-string--arraystring: `(/__tests__/.*|(\\.|/)(test|spec))\\.[jt]sx?$`

But, by default, it will also search for a `jest.config.js|ts|mjs|cjs|json` file ( https://jestjs.io/docs/configuration ) that can override these globs

I'm not sure how much complexity is desirable in this area, but perhaps we could start with the equivalent of those hard-coded globs? Would you accept a PR that also checks for the jest.config.* file?

**Comment by mysteryven** [comment]
We can start with a hard-coded glob first, PR is always welcome!

Do we need to check static jest config? @Boshen

**Comment by Boshen** [comment]
> Do we need to check static jest config? 

Let's try and not to read another config file. Are there any workarounds? For example ignore the rule by using https://eslint.org/docs/latest/use/configure/ignore#ignorepatterns-in-config-files?
