### ISSUE TITLE
[Feature request]: `ignorePatterns` in `.eslintrc.json`

### ISSUE THREAD

**Issue by matthew-dean** [oxc-project/oxc#2398]
Sometimes it's just nicer to have fewer files. It would be nice if `ignorePatterns` was supported in oxlint. https://eslint.org/docs/latest/use/configure/ignore#ignorepatterns-in-config-files

**Comment by andymac4182** [comment]
I had to use ignore patterns due to eslintignore not being looked for in parent folders. This would be great to have 😀

**Comment by mysteryven** [comment]
> due to eslintignore not being looked for in parent folders

Could you please explain more about this? @andymac4182

**Comment by andymac4182** [comment]
From the eslint docs (https://eslint.org/docs/latest/use/configure/ignore)
> When ESLint is run, it looks in the current working directory to find an .eslintignore file before determining which files to lint.

vs the config file (https://eslint.org/docs/latest/use/configure/configuration-files)
> ESLint automatically looks for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem (/), the home directory of the current user (~/), or when root: true is specified. 

If you include the `ignorePatterns` in the config file then you can load them when running eslint lower in the tree.

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/pull/7092
