### ISSUE TITLE
oxlint: how to share linting config?

### ISSUE THREAD

**Issue by LeOndaz** [oxc-project/oxc#2406]
I can see no .oxlint file mentioned, this means that no one can contribute with the same linting rules as the author, any plans?

**Comment by fimgzking** [comment]
I've just started using oxlint. How can I use eslint config?

**Comment by leaysgur** [comment]
You can use `-c`(or `--config`) CLI option. 

```sh
npx oxlint -c ./path/to/your/config/file
```

Currently JSON(or JSONC) format is only supported.

> See also https://oxc-project.github.io/docs/guide/usage/linter.html#useful-options
> Or `oxlint --help`
