### ISSUE TITLE
 Error: Cannot find module '@oxlint/linux-x64-gnu/oxlint'

### ISSUE THREAD

**Issue by PollionChang** [oxc-project/oxc#2421]
<img width="808" alt="image" src="https://github.com/oxc-project/oxc/assets/27656729/89544e31-f4f2-4918-9f9a-144ac3b23c6a">

**Comment by PollionChang** [comment]
problem version is 0.2.8
change version to @0.2.7  can work

**Comment by Boshen** [comment]
Can you help me debug what could possibility gone wrong? For example which binary is download into `node_modules/@oxlint`? You can `console.log` information from the `node_modules/oxlint/bin/oxlint` script to help you with the process.

I'm seeing 10k downloads of `@oxlint/linux-x64-gnu` from the npm.

**Comment by PollionChang** [comment]
I know what caused it now; it was an issue on my end. I'm sorry for taking up your time
