### ISSUE TITLE
the problem hint position is not correct in VS Code extension

### ISSUE THREAD

**Issue by luhc228** [oxc-project/oxc#2456]
I am using the oxc vscode extension now. When my file have non-ASCII character(for example in the below screenshot is `数`), the problem hint position is not correct.

<img width="453" alt="image" src="https://github.com/oxc-project/oxc/assets/44047106/4948a507-7b8f-40b2-82d8-56fc258f0923">

I have debugged but I can't figure out. Maybe read the content with `bytes` but not `char`? 

Hoping for your reply and guide. If possible, I can send you PR. Thanks.

**Comment by Dunqing** [comment]
Thank you for the feedback! It is caused by the fact that we need to convert offset(byte) to position(line, column). Both line and column are char. I figured out how to fix this problem, I will send a PR later.
