### ISSUE TITLE
Generate Typescript Definitions of AST

### ISSUE THREAD

**Issue by andymac4182** [oxc-project/oxc#2466]
To make it easier to work with the output of the AST it would be great to create the types for AST after the JSON string has been parsed then can be cast as these Types and get completion in the IDE.

**Comment by andymac4182** [comment]
If I am using the oxc parser in TS I get back a string then you run `JSON.parse()` over it. That returns an `any`. I would love to be able to cast it to the types that are the real AST so I get type safety in TS.

**Comment by leaysgur** [comment]
FYI: Currently there are 2 parser implementation available in JS/TS land.

- `oxc-parser`: https://github.com/oxc-project/oxc/tree/main/npm/oxc-parser
- `@oxc-parser/wasm`: https://github.com/oxc-project/oxc/tree/main/wasm/parser

I guess you are using `oxc-parser` and it is not typed as you say.

By using `@oxc-parser/wasm`, you will get some type safety.

![image](https://github.com/oxc-project/oxc/assets/6259812/d89d822f-286b-4b04-a38f-e83ccac0eb23)

**Comment by andymac4182** [comment]
Ahh thanks :)
