### ISSUE TITLE
bug/feature request with jsx-no-useless-fragment

### ISSUE THREAD

**Issue by evanbernstein** [oxc-project/oxc#2484]
Hi, thanks for making oxlint. I'm using it for the first time in my personal coding project. I think I've discovered something that might be a bug. (Forgive me if I'm reporting this in the wrong way. Happy to adjust anything I'm doing here.)

Using oxlint 0.2.10

I'm getting a warning from the rule `eslint-plugin-react(jsx-no-useless-fragment)` which don't think I should be getting. The code in question is:

`{num && <>{num}</>}`

When I run eslint, I don't get a warning on that line. I don't have any specific configuration for that line in my eslintrc other than `"plugin:react/recommended", "plugin:react/jsx-runtime"`. I've checked out the documentation on this rule and it seems there is an additional rule option [allowExpressions](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md#allowexpressions) that could help here.

I've added this rule specifically to my eslintrc file:
* `"react/jsx-no-useless-fragment": ["warn", {"allowExpressions": false}]` eslint produces the warning
* `"react/jsx-no-useless-fragment": ["warn", {"allowExpressions": true}]` eslint does not produce the warning

Two issues:
* I get these eslint warnings even though I also have [eslint-plugin-oxlint](https://github.com/oxc-project/eslint-plugin-oxlint) configured
* I'm calling oxlint `oxlint -c .eslintrc.json` and oxlint produces the warning with either of those configurations in my eslintrc file so I don't know how to make that warning go away.

Is this intended behavior or something that should/could be adjusted in oxlint?

Thanks for your great work!

**Comment by Boshen** [comment]
Thank you for the detailed report. We need to read the `{"allowExpressions": true}` configuration.

**Comment by keita-hino** [comment]
May I try to solve this issue?

**Comment by evanbernstein** [comment]
Thanks for responding to this and solving it so quickly!

I'm curious where this rule was turned on from. It doesn't seem to be turned on in. I don't see it in `"plugin:react/recommended"`. Is this something oxlint decided to turn on? If so, should `allowExpressions` be considered the default?

**Comment by Boshen** [comment]
> Thanks for responding to this and solving it so quickly!
> 
> I'm curious where this rule was turned on from. It doesn't seem to be turned on in. I don't see it in `"plugin:react/recommended"`. Is this something oxlint decided to turn on? If so, should `allowExpressions` be considered the default?

Unfortunately the default is false in eslint-plugin-react :-( https://github.com/jsx-eslint/eslint-plugin-react/blob/e880213f3958f44ccca4642d7593e26de72864cf/lib/rules/jsx-no-useless-fragment.js#L109

**Comment by Boshen** [comment]
It's turned on from the `correctness` category, where we think useless fragments are useless code.
