### ISSUE TITLE
Doc: Which rules are enabled by default?

### ISSUE THREAD

**Issue by TTtuntuntutu** [oxc-project/oxc#2495]
Hi, thanks for making OXLint. 

I am researching migrating from ESLint to OXLint for our company's projects. I want to compare the ESLint rules configured in the company project with those enabled by default in OXLint. But I can't find which rules are enabled by default.

In the README's Quick Start section, only "The linter is ready to catch mistakes for you. It comes with over 60 default rules and no configuration is required."

And in https://github.com/oxc-project/bench-javascript-linter/blob/main/.eslintrc.json, only 48 rules.

Thanks for your great work!

**Comment by leaysgur** [comment]
`oxlint` cli has `--rules` option to show which rules are implemented.

You can grep it by `oxlint --rules | grep eslint:` to see them.

Or you may check this file.
https://github.com/oxc-project/oxc/blob/70295a55521a2372597980076566272d1a1f54bb/crates/oxc_linter/src/rules.rs#L38-L106

**Comment by Boshen** [comment]
The `correctness` rules from `--rules` are enabled by default.
