### ISSUE TITLE
Parse uninitialize const declaration in namespace in `.d.ts` file

### ISSUE THREAD

**Issue by ArnaudBarre** [oxc-project/oxc#2502]
I just discover this and I hate it. Personally I would love to see tools that don't support legacy things like enum and namespaces, but given that OXC already added support for `TSModuleBlock` in the AST it's propbably better to follow allow this.

Maybe there are other differences, but in .d.ts, this is valid for TS
```
export namespace builders {
  const breakParent: string;
}
``` 
See in TS playground with [.ts](https://www.typescriptlang.org/play?&filetype=ts#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgIwFcBLAGwBNgp04BvAKDjmwgXXnymCQGsAFJFwQwAXHHZRiCAOYBuegF969StlKC8LNhy68BQ0eJiSZsoA) and [.d.ts](https://www.typescriptlang.org/play?ssl=4&ssc=1&pln=1&pc=1&filetype=d.ts#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgIwFcBLAGwBNgp04BvAKDjmwgXXnymCQGsAFJFwQwAXHHZRiCAOYBuegF969StlKC8LNhy68BQ0eJiSZsoA)

**Comment by Boshen** [comment]
I can't reproduce this, the snippet parses correctly:

* in `.ts` it produces an correct AST with the error "Missing initializer in const declaration"
* in `.d.ts` it produces a correct AST

**Comment by ArnaudBarre** [comment]
Oh yeah I completely mess up in my local setup and didn't correctly pass the file name to the parser. So I suppose what is missing  `.d.ts` support in the playground: https://github.com/oxc-project/oxc/pull/2520
