### ISSUE TITLE
vscode extension Oxc_language_server: Config Path loading issue

### ISSUE THREAD

**Issue by alexandre-combemorel** [oxc-project/oxc#2563]
In the settings of vscode extension, when providing a path to a json config file, the server return 
```bash
[2024-03-01T11:00:49Z ERROR oxc_language_server] Can't fetch `oxc_language_server` configuration
``` 

See following screenshot:
<img width="979" alt="Screenshot 2024-03-01 at 12 10 06" src="https://github.com/oxc-project/oxc/assets/24472130/52021ec5-97b3-4bf0-8124-92ed0716e390">

Not exactly sure why, but it seems that the relative path is not correctly resolved?
Any idea?

**Comment by IWANABETHATGUY** [comment]
I will fix this ASAP, as a workaround, you could change the config **global** scope rather than **workspace** scope
