### ISSUE TITLE
AST: remove ParenthesizedExpression?

### ISSUE THREAD

**Issue by ArnaudBarre** [oxc-project/oxc#2576]
Re #2463 

It seems that this is something that exist only in [the TS parser](https://astexplorer.net/#/gist/9f43cf0fe91760e11f1572934681c92f/788f1fd3bbf8bcda183fe2f1a5c63498b436beca), it seems to be skipped for all other parsers, even with type cast ([acorn](https://astexplorer.net/#/gist/9f43cf0fe91760e11f1572934681c92f/e10608846e66c33713ec1cf72f5b4c9183d7c432), [babel](https://astexplorer.net/#/gist/9f43cf0fe91760e11f1572934681c92f/3444f9239273e4d4b94b03e5c0f7a209c5e7bfab), [babel-estree-ts](https://astexplorer.net/#/gist/9f43cf0fe91760e11f1572934681c92f/70826c8040fa10de8c1cb0f262da577f98fee434), [ts-eslint](https://astexplorer.net/#/gist/626dd346956a02c221d4e128450652af/7fdf6f557ada77dde09d8ac7797d4450d63b1c9a))

This is [always removed/flatten](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/convert.ts#L2653) in the TS->ESTree conversion from TSESLint.

[oxc-playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIChgICAgICAgICUmQl4qZeUj%2BRYoXXd%2FFj11Bh%2FsDm6RVMnocOPf3pYAIA%3D)

**Comment by Boshen** [comment]
There's a configuration for this, but when removed, the parser raises a few false positive syntax errors which need to be fixed :-(

I'll expose this option first.
