### ISSUE TITLE
eslint-plugin-tree-shaking

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2609]
https://github.com/lukastaegert/eslint-plugin-tree-shaking

**Comment by Boshen** [comment]
It seems like we are 99% done?

**Comment by mysteryven** [comment]
Yeah, the remain parts are recorded in #3155, support options and clean TODO is easy, and I am working on it, I'll find a time to complete it soon! Add more support for operator computation will cost some time, it's just work now, (e.g., [for `+`](https://github.com/oxc-project/oxc/blob/c0abbbd204b759acd0915c07db2d773da2bf148b/crates/oxc_linter/src/utils/tree_shaking.rs#L260-L270), we only support number plus number and string plus string).

We may report a side effect even if it's a dead code. 

```js
if ('1' - 1) {
	foo() // it's a dead code, we treat `'1'-1` as a unkonwn value, so we need check its consequent
}
```

I don't plan to add every edge case for it now, and in my personal view, maybe dead code also needs check?
