### ISSUE TITLE
Rules activation error

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [oxc-project/oxc#2613]
If I use `oxlint --jsx-a11y-plugin --react-perf-plugin --deny-warnings` I see 
![image](https://github.com/oxc-project/oxc/assets/107539652/79d2da88-9449-49cf-8ec2-a7c7af94ec14)

But if I disable 1 rule `oxlint --jsx-a11y-plugin --react-perf-plugin --deny-warnings -A jsx-no-new-object-as-prop` I can see that all rules are disabled.
![image](https://github.com/oxc-project/oxc/assets/107539652/498fbb2c-8af4-4913-aed1-81191ddcbdbe)

I think that is an error.

**Comment by Boshen** [comment]
You need `-D all -A jsx-no-new-object-as-prop`, I'll add an example of this to the website.

**Comment by Boshen** [comment]
Oh, to turn on a single rule, you need `-A all -D jsx-no-new-object-as-prop`

**Comment by Boshen** [comment]
These flags are accumulated from left to right.

**Comment by Boshen** [comment]
Try `-D correctness -A jsx-no-new-object-as-prop`. `correctness` is the default category.

**Comment by JoseBuendiaDigio** [comment]
Alright, this is what I was looking for. Thanks and sorry for the inconvenience
