### ISSUE TITLE
Memory leak in `Atom<'a>`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2621]
Partial reprise of the previous memory leak.

`Atom<'a>` is implemented as:

```rs
pub enum Atom<'a> {
    Arena(&'a str),
    Compact(CompactString),
}
```

`From<&'a str> for Atom<'a>` does not leak because it creates the `Arena` variant which doesn't allocate. But `From<String> for Atom<'a>` and `From<Cow<'_, str>> for Atom<'a>` will leak if the `Atom` is inserted into the AST. For example:

```rs
fn rename_id(id: &mut IdentifierName) {
  let mut s = String::from(&id.name);
  s.push_str("_stuff");
  let atom = Atom::from(s);
  // `atom` is the `Compact` variant
  id.name = atom;
}
```

AST now contains an `Atom<'a>` containing a `CompactString`. The `CompactString` owns an allocation on the general heap. It will not get freed when the arena is dropped.

Here are a couple of examples in practice:

https://github.com/oxc-project/oxc/blob/1f14d946aa3a5bdae6c0d694cff10bf4c5873227/crates/oxc_ast/src/ast/js.rs#L468-L476

https://github.com/oxc-project/oxc/blob/1f14d946aa3a5bdae6c0d694cff10bf4c5873227/crates/oxc_minifier/src/compressor/fold.rs#L260-L269

**Comment by overlookmotel** [comment]
The bad news is: This is going to be hard to fix. It's widespread, and will require a lot of refactoring in the transformer and minifier.

The good news is: The changes required will likely make it easier to migrate transformer and minifier away from `CompactString` and to using `Atom<'a>` directly, and everything will get faster!

**Comment by Boshen** [comment]
I'm in favor of banning `From<String> for Atom<'a>` and `From<Cow<'_, str>> for Atom<'a>` and eventually rename this to `ArenaStr`.

**Comment by overlookmotel** [comment]
Yes, we'd need to remove those 2 impls to fix the leak.

On naming: Instead of `Atom<'a>` + `CompactStr`, how about `StrRef<'a>` + `Str`?

`ArenaStr` isn't quite descriptive of what it is, as most of the references will point to the source text, which isn't strictly in the arena. And the name `CompactStr` is making a thing of the inline optimization, which is mostly an implementation detail.

The main difference between these 2 types is that one owns its string data, and the other doesn't, so I guess the naming should make that primary distinction as obvious as possible.

But I'm not at all adamant on this. Please feel free to disagree with me!

(I wish I'd bikeshedded first before I renamed about 1000 `CompactString`s to `CompactStr`s!)

**Comment by Boshen** [comment]
Let me try and ban the two `From` methods first. Renaming can be done at any time.

**Comment by overlookmotel** [comment]
I had a quick try last night.

As far as I can see, to replace those impls requires adding a method `Atom<'a>::new_in(s: &'str, alloc: &Allocator)` which converts `s` to a bump String (i.e. copies the string data into the arena), so then you can safely store a ref to it in the `Atom`.

The problem is that some of the methods currently using `From<String> for Atom<'a>` don't have access to an `Allocator`. I don't know minifier or transformer well enough to know how easy it is to give them access to one.

**Comment by Boshen** [comment]
These two removals means we can remove the `Atom::Compact` enum variant lol

**Comment by overlookmotel** [comment]
Holy crap! You did it already. I thought it would be much harder.

**Comment by overlookmotel** [comment]
> These two removals means we can remove the `Atom::Compact` enum variant lol

Yes. That'll reduce size of `Atom` from 32 bytes to 16 too. Great!

**Comment by overlookmotel** [comment]
A magnificent voyage! It's a hard problem - SWC also changed theirs multiple times, from what I know.

Can I suggest not removing `Atom<'a>` at this point? If we implement it as just a wrapper around `&str` for now, that leaves the door open to adding an inline optimization without changing external API.
