### ISSUE TITLE
RestElement.argument has wrong span end in ESTree

### ISSUE THREAD

**Issue by ArnaudBarre** [oxc-project/oxc#2653]
Copilot suggested something like that in the serializer, but I'm unsure of the implications:

```rs
        // Update argument.end to typeAnnotation.start
        if let Some(rest) = self.rest.as_ref() {
            if let Some(type_annotation) = &rest.argument.type_annotation {
                rest.argument.span().end = type_annotation.span.start;
            }
        }
```

**Comment by overlookmotel** [comment]
Hmm. Is the span as we have it now how we want it on Rust side?

i.e. do we change this just in JSON AST, or in the Rust AST?

**Comment by Boshen** [comment]
Seems like a Rust AST update is needed, I did a similar change before, assigning to me.
