### ISSUE TITLE
Change shape of `Language`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2677]
Could we change the shape of `oxc_span::source_type::Language`?

Currently it's:

https://github.com/oxc-project/oxc/blob/d47f0e247db24319995fbe4f26255379a931db6d/crates/oxc_span/src/source_type.rs#L29-L35

Could we change this to either:

```rs
pub enum Language {
    JavaScript,
    TypeScript,
    TypeScriptDefinition,
}
```

or:

```rs
pub enum Language {
    JavaScript,
    TypeScript(TypescriptVariant),
}
pub struct TypescriptVariant {
    is_definition_file: bool,
}
```

Reason I'm asking is that it's tricky the way it is now for #2409, because [memoffset::offset_of](https://docs.rs/memoffset/0.9.0/memoffset/macro.offset_of.html) does not allow getting the offset of a nested enum variant field, due to some weird compiler quirk. This is the only type in the AST which has this problem.

The first option seems cleaner to me, but is there a reason the JSON AST needs to be as it is now? Currently it's one of:

* `"language": "javaScript"`
* `"language": { "typeScript": { "isDefinitionFile": false } }`
* `"language": { "typeScript": { "isDefinitionFile": true } }`

**Comment by Boshen** [comment]
`Language` isn't in the public API. I'd go for 

```
pub enum Language {
    JavaScript,
    TypeScript,
    TypeScriptDefinition,
}
```

**Comment by ArnaudBarre** [comment]
Maybe merge with variant into a 5 entries enum? This avoid incoherent `TypeScriptDefinition` and `JSX` at the same time?

**Comment by overlookmotel** [comment]
Let's open a separate issue for further changes. Personally I find it odd that `.js` is interpreted as being JSX.

**Comment by Boshen** [comment]
Yeah they can't be merged 😅

**Comment by overlookmotel** [comment]
> Yeah they can't be merged 😅

How do you mean?

**Comment by Boshen** [comment]
language and variant are separated

https://github.com/oxc-project/oxc/blob/8a73d18fcf4ac135ec906174bc4de6bca6abbd58/crates/oxc_span/src/source_type.rs#L184-L198

These values are internal and are parsed from file extensions, I'm not sure what improvements can be made 😅
