### ISSUE TITLE
Support for modify transformer configurations in playground

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#2709]
We can write the configuration like this

```json
{
  "plugins": ["transform-typescript", "transform-parameters"],
  "sourceType": "module"
}
```

We need to support the json syntax and then deserialize the configuration when running the transformer

**Comment by Dunqing** [comment]
Can we refactor this using a modern front-end framework before doing this? As more features are added I think a vanilla.js-based implementation would become more cumbersome and difficult to maintain.

Additionally, we should use [monaco](https://github.com/microsoft/monaco-editor) to replace it with `codemirror`. `monaco` has better API and is easy to support multiple languages. (this configuration needs `json` syntax)

We can refer to https://ast.sxzz.moe to complete the refactoring. Thank you for your amazing ast explorer for inspiring me! @sxzz

**Comment by Boshen** [comment]
Let's dog food ourself, you know what to do ;-)

**Comment by Boshen** [comment]
Should we also build the playground in the website repo? I see biome do this https://github.com/biomejs/website/blob/dfed531a1bea6f2bef648e7014f84e530c436627/package.json#L32

**Comment by Dunqing** [comment]
> Should we also build the playground in the website repo? I see biome do this https://github.com/biomejs/website/blob/dfed531a1bea6f2bef648e7014f84e530c436627/package.json#L32

I don't think it's needed, I checked `vue` playground and `swc` playground neither of them is on the website. Let's keep the website purely static

**Comment by Boshen** [comment]
Close as duplicate.
