### ISSUE TITLE
[QUESTION]How to ignore rule with .eslintrc.js

### ISSUE THREAD

**Issue by xmsz-stu** [oxc-project/oxc#2714]
I want to turn off some rules like `react/jsx-no-useless-fragment`.

```
module.exports = {
  extends: ['plugin:oxlint/recommended'],
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        'react/jsx-no-useless-fragment': 'off',
      },
    },
  ],
};

```
```
npx oxlint
```
it doesn't working

**Comment by Boshen** [comment]
https://oxc-project.github.io/docs/guide/usage/linter.html#useful-options-and-examples

-c ./eslintrc.json use the rules field to configure the rules, as documented in [ESLint](https://eslint.org/docs/latest/use/configure/rules#using-configuration-files). Only json format is supported.

**Comment by xmsz-stu** [comment]
ok

**Comment by bigopon** [comment]
The link above no longer point to any example, may I have a new link? I can't find any example how to use `overrides`, and the way I use `overrides` in eslint doesn't seem to apply.
