### ISSUE TITLE
[Feature Request] Codegn sourcemap `name` filed need to be orignal name.

### ISSUE THREAD

**Issue by underfin** [oxc-project/oxc#2753]
The transformer maybe mutate identfier name to different name, eg renamed `a` -> `a$1`, we need to add `a` to sourcemap, but here hasn't original name info, we need to find a way to resolve it.

**Comment by Boshen** [comment]
When we rename, don't we just keep the original span positions of the name?

I may need an example of how it breaks right now.

**Comment by underfin** [comment]
- [rolldown example](https://evanw.github.io/source-map-visualization/#MTI5AAovLyBzaGFyZWQuanMKY29uc3QgYSA9ICdzaGFyZWQuanMnOwoKLy8gaW5kZXguanMKY29uc3QgYSQxID0gJ2luZGV4LmpzJzsKY29uc29sZS5sb2coYSQxLCBhKTsKCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWJhc2ljLmpzLm1hcDMwMgB7InZlcnNpb24iOjMsImZpbGUiOiJiYXNpYy5qcyIsInNvdXJjZXMiOlsic2hhcmVkLmpzIiwiaW5kZXguanMiXSwic291cmNlc0NvbnRlbnQiOlsiY29uc3QgYSA9ICdzaGFyZWQuanMnXG5cbmV4cG9ydCB7IGEgfSIsImltcG9ydCB7IGEgYXMgYTIgfSBmcm9tICcuL3NoYXJlZCdcbmNvbnN0IGEgPSAnaW5kZXguanMnXG5jb25zb2xlLmxvZyhhLCBhMilcbiJdLCJuYW1lcyI6WyJhIiwiYSQxIl0sIm1hcHBpbmdzIjoiOztBQUFBLE1BQU1BLElBQUk7OztBQ0NWLE1BQU1DLE1BQUk7QUFDVixRQUFRLElBQUlBLEtBQUdELEVBQUcifQ==), you can see here sourcemap name show `a$1`
<img width="1096" alt="image" src="https://github.com/oxc-project/oxc/assets/14008915/fe994e71-883f-4514-81c6-0d9cb4d310dd">

- [esbuild example](https://evanw.github.io/source-map-visualization/#MTEzACgoKSA9PiB7CiAgLy8gc2hhcmVkLmpzCiAgdmFyIGEgPSAic2hhcmVkLmpzIjsKCiAgLy8gaW5kZXguanMKICB2YXIgYTIgPSAiaW5kZXguanMiOwogIGNvbnNvbGUubG9nKGEyLCBhKTsKfSkoKTsKMzA3AHsKICAidmVyc2lvbiI6IDMsCiAgInNvdXJjZXMiOiBbIi4uL3NoYXJlZC5qcyIsICIuLi9pbmRleC5qcyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiY29uc3QgYSA9ICdzaGFyZWQuanMnXG5cbmV4cG9ydCB7IGEgfSIsICJpbXBvcnQgeyBhIGFzIGEyIH0gZnJvbSAnLi9zaGFyZWQnXG5jb25zdCBhID0gJ2luZGV4LmpzJ1xuY29uc29sZS5sb2coYSwgYTIpXG4iXSwKICAibWFwcGluZ3MiOiAiOztBQUFBLE1BQU0sSUFBSTs7O0FDQ1YsTUFBTUEsS0FBSTtBQUNWLFVBQVEsSUFBSUEsSUFBRyxDQUFFOyIsCiAgIm5hbWVzIjogWyJhIl0KfQo=), you can see here sourcemap name show `a`
<img width="1155" alt="image" src="https://github.com/oxc-project/oxc/assets/14008915/bc74ae6d-2538-4094-b27f-96dcd4f49c84">
