### ISSUE TITLE
oxlint: max-lines should not display offending code

### ISSUE THREAD

**Issue by aparajita** [oxc-project/oxc#2775]
When `max-lines` fails, it displays the entire file — which could be several hundred lines — as offending code. This is clearly unnecessary and undesirable.

**Comment by aparajita** [comment]
Thank you, what will it display now?

**Comment by Dunqing** [comment]
> Thank you, what will it display now?

will now only report lines that exceed the maximum allowed

<img width="1086" alt="image" src="https://github.com/oxc-project/oxc/assets/29533304/2d22a01a-1c82-4bc5-b65c-b2387663ae46">

**Comment by aparajita** [comment]
Honestly it isn't necessary to display any lines. Because if the file is too long, we can easily end up moving entire functions, and it would be sheer luck if they happened to be at the end of the file. So I would submit that showing excess lines is not at all helpful in most cases to the process of shortening the file.

**Comment by mysteryven** [comment]
> Because if the file is too long, we can easily end up moving entire functions, and it would be sheer luck if they happened to be at the end of the file.

I agree with this, so initially I think it is OK to report all lines and let the user choose which part needs to be deleted. after all, people open this rule, they need to fix it, although it does get a little annoying.


> I would submit that showing excess lines is not at all helpful in most cases to the process of shortening the file.

Look through ESLint's issue about max-line, don't find folk's report about this(perhaps I missed it), I think we can follow the [ESLint behavior](https://eslint.org/play/#eyJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsic291cmNlVHlwZSI6Im1vZHVsZSJ9fSwidGV4dCI6Ii8qZXNsaW50IG1heC1saW5lczogW1wiZXJyb3JcIiwgMl0qL1xuXG52YXIgYSxcbiAgICBiLGM7In0=) for now.
