### ISSUE TITLE
Add `ast_node_id` field to all ast nodes

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#2818]
We should have a field similar to `IdentifierReference`'s `reference_id` that would keep the `AstNodeId` of each AST node.

Can be written manually, using a declarative `ast_node` macro for definition or a procedural derive macro.
I guess we can also remove `AstNode` as it can be changed into SOA in the `AstNodes` structure.
If we remove the `AstNode` struct we can add a trait with the same name which would implement a function called `ast_node_id` that would give us the information for getting things that `AstNode` would've provided before. With this trait, we can use any ast node with the help of generics since with the ast_node_id alone we can infer the node's kind, parents, scope, control flow, and anything that gets added down the road.

**Comment by rzvxa** [comment]
cc @Boshen

**Comment by Boshen** [comment]
It's a 👍 for adding a node id because rustc has them as well https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/node_id/struct.NodeId.html, so the following arguments are not theoretical but practical.

Since this requires a lot of effort, I think we need a few real world scenarios that can motivate this change, to decide whether we want to do this right now, or later when it's absolutely necessary.

**Comment by rzvxa** [comment]
Well, let me try my best to explain a real-world situation in which this change can help make things easier.

Let's say we want to transform a given node based on its parent, Right now this is achieved by monitoring all nodes and keeping a stack of them. I'm going to take the `ArrowFunctions` transformer as an example but after studying the babel transformers I find it a common thing.

```rust
impl<'a> VisitMut<'a> for ArrowFunctions<'a> {
    fn enter_node(&mut self, kind: AstType) {
        self.nodes.push(kind);
    }

    fn leave_node(&mut self, _kind: AstType) {
        self.nodes.pop();
    }

    fn visit_jsx_identifier(&mut self, ident: &mut JSXIdentifier<'a>) {
        let parent_kind = self.nodes.last().unwrap();
        let parent_parent_kind = self.nodes[self.nodes.len() - 2];
        // ...
        walk_jsx_identifier_mut(self, ident);
    }
}
```

Well if we go for this change it can be simplified into something more akin to this:

```rust
impl<'a> VisitMut<'a> for ArrowFunctions<'a> {
    fn visit_jsx_identifier(&mut self, ident: &mut JSXIdentifier<'a>) {
        let parent = self.ctx.semantics().nodes().parent(ident.ast_node_id());
        let parent_kind = parent.kind();
        let parent_parent_kind = self.ctx.semantics().nodes().parent_kind(parent.ast_node_id());
        // ...
        walk_jsx_identifier_mut(self, ident);
    }
}
```

Keep in mind that the example above is only using its parent's kind, If we want the actual parent node in `VisitMut` we have to do crazy things like having a reverse lookup table, searching through the nodes, or trying to achieve the same thing with only scope information. While having the `ast_node_id` would make it a simple array indexing.

**Comment by rzvxa** [comment]
Even in `Visit` which has the node reference passed through `enter/leave_node`, the need to keep a stack of parents while there is already such representation in semantics is counterproductive. It may also have minimal impact on performance and memory footprint while scaling but I don't find this part problematic. Not to mention the loss of extra information because of lack of access to the ast_node_id, basically if we want to add any complex analysis in which its result is needed further down the road would make for a good mind-boggler.

I guess it makes sense that Rust does it; since it needs complex analysis. `Roc` and `Elm` get away with this because of their language design.

If you are worried about having extra fields in the AST, We may be able to make it optional via features if we make the `AstNodeId` non-clonable I guess it would result in the cell needing a mutable reference to get the node_id without swapping it and it would limit its scope to the `VisitMut` trait which would result in it not being necessary for basic semantic analysis and tree traversal. I'm not really into having this field as a feature but it shouldn't be a problem implementing either.

**Comment by rzvxa** [comment]
In some cases we can intercept the parent using a visit on a higher node, for example instead of detecting a function parameter and then getting its parent function node, We can detect functions and search for a viable function parameter. I strongly believe that these cases should be written/ported from Babel in a manner that keeps the data flow local, We should go for using semantics information if it is absolutely necessary however it doesn't mean that we won't need it to implement some of these cases.

**Comment by rzvxa** [comment]
> Well if we go for this change it can be simplified into something more akin to this:
> 
> ```rust
> impl<'a> VisitMut<'a> for ArrowFunctions<'a> {
>     fn visit_jsx_identifier(&mut self, ident: &mut JSXIdentifier<'a>) {
>         let parent = self.ctx.semantics().nodes().parent(ident.ast_node_id());
>         let parent_kind = parent.kind();
>         let parent_parent_kind = self.ctx.semantics().nodes().parent_kind(parent.ast_node_id());
>         // ...
>         walk_jsx_identifier_mut(self, ident);
>     }
> }
> ```

Just want to point out an interesting approach, If we implement the ast_node_id method via the `AstNode` trait we can have methods and functions like parent take advantage of generics which makes a nicer interface.

```rust
impl<'a> VisitMut<'a> for ArrowFunctions<'a> {
    fn visit_jsx_identifier(&mut self, ident: &mut JSXIdentifier<'a>) {
        let parent = self.ctx.semantics().nodes().parent(ident);
        let parent_kind = parent.kind();
        let parent_parent_kind = self.ctx.semantics().nodes().parent_kind(parent);
        // ...
        walk_jsx_identifier_mut(self, ident);
    }
}
```

**Comment by rzvxa** [comment]
>  We can detect functions and search for a viable function parameter.

Just to make it clear, This approach is necessary if we want to replace the node instead of mutating it in place. So I believe that it makes sense to default to this when appropriate.

**Comment by Boshen** [comment]
How do we deal with enum types? The current approach has enum types in the parent pointing tree, it's going to be a impractical to migrate it (I think).

**Comment by rzvxa** [comment]
@Boshen 

```rust
/// Array Expression Element
#[derive(Debug, Hash)]
#[cfg_attr(feature = "serialize", derive(Serialize))]
#[cfg_attr(feature = "serialize", serde(untagged))]
pub enum ArrayExpressionElement<'a> {
    SpreadElement(Box<'a, SpreadElement<'a>>),
    Expression(Expression<'a>),
    /// Array hole for sparse arrays
    /// <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#arrays>
    // Serialize as `null`. `serialize_elision` in serialize.rs.
    #[cfg_attr(
        feature = "serialize",
        serde(serialize_with = "ArrayExpressionElement::serialize_elision")
    )]
    Elision(Span),
}
```

The `Elision` variant here is the only example that I could find that needs refactoring, Since `Span` can't be an AstNode we should add an `ElisionElement` similar to `SpreadElement` and `RestElement`.

**Comment by Boshen** [comment]
> The Elision variant here is the only example I found which needs refactoring;

Feel free to create another issue for this change.

---

You may have missed the thread on discord https://discord.com/channels/1079625926024900739/1222938985224081528

I'll create an umbrella issue for progress report and a milestone to officially kick off new transformer implementation.

**Comment by rzvxa** [comment]
> Feel free to create another issue for this change.

I think it is a part of this issue and just something we have to do in order to get this working. It won't have any concerning effect on the other parts, We almost always ignore elision elements. It is just there to fill a space in the array.

> You may have missed the thread on discord https://discord.com/channels/1079625926024900739/1222938985224081528

Yes, I saw this after commenting here, I don't have a habit of checking my discord servers(I still have notifications for directs).

-----------

I guess It's decided then, I'll start by creating a PR for this change. As soon as it gets to a working state I'll mention you guys for feedback.

**Comment by Boshen** [comment]
FYI I created the AST builder back in the day envisioning that we are going to add node ids ... I think this is the day. Good luck!

**Comment by rzvxa** [comment]
@overlookmotel @Boshen I still think there is a use for this ID, If we have the scope ID along with our nodes we can traverse through things like scopes with no issue(both in linters and transformers). It makes rules like #2637 simpler(since we can rely on scope data without having to do a lot of iterations).

Let me know what you think, Since we are doing a lot of changes on AST maybe it is a good time to also sneak this in.

**Comment by overlookmotel** [comment]
I do not have a clear idea at present of best way to implement scope binding lookups in transformers. You may be right that an AST node ID is the best way. On the other hand, we may be able to find a more efficient way using the kind of "pointer tricks" that `Traverse` is using.

So... er... don't know!

But I've made a comment on #2861 to not delete the branch in case we want to come back to this. Could you also please make sure you keep a local copy of the branch too, just in case?

**Comment by rzvxa** [comment]
I'll fork the branch; Graphite might cause me to delete the local branch by accident.
