### ISSUE TITLE
When the submodule is updated, tester should help us update the cloned repository to match what is defined in the justfile

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#2819]
There is also another issue, when we update the commit hash of the submodule, we also need to manually execute `just submodule` to update our cloned repo to be consistent with the configuration in justfile. Otherwise, the snapshot will never be the same. Maybe we check if the commit hash is the same when testing execution

_Originally posted by @Dunqing in https://github.com/oxc-project/oxc/issues/2817#issuecomment-2019329493_

**Comment by Boshen** [comment]
Idea: save the commit id in the snapshot, and trigger a warning when commit is different.

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/pull/3267
