### ISSUE TITLE
Svelte parser fails with generic components

### ISSUE THREAD

**Issue by notramo** [oxc-project/oxc#2875]
The Svelte parser fails when the component has TypeScript generics.
This is valid Svelte syntax:
```svelte
<script lang=ts generics="T extends Record<string, unknown>">
```
The TS generic type syntax in `Record<string, unknown>` is considered as closing `>` by the parser, disregarding that it's inside an attribute.

**Comment by Boshen** [comment]
Similar to https://github.com/oxc-project/oxc/issues/2017, we need to improve the parser to balance out the angle brackets.

The parsing code is here https://github.com/oxc-project/oxc/tree/main/crates/oxc_linter/src/partial_loader

PRs are welcome.

**Comment by kalvenschraut** [comment]
@Boshen  this issue can be closed, not sure why it didn't auto close on my PR being merged
