### ISSUE TITLE
[tasks/lint_rules] Use flat ESLint for list generation

### ISSUE THREAD

**Issue by leaysgur** [oxc-project/oxc#2932]
- For now, https://github.com/oxc-project/oxc/tree/main/tasks/lint_rules is using the ESLint Node.js API to track implementation progress
- The latest ESLint, now at v9 (which defaults to flat config), does not support APIs such as `Linter#getRules()` and `defineRule()` that we've been using 😢
- Unfortunately, there is no direct Node.js API replacement for these functions
  - https://github.com/eslint/eslint/issues/18103
  - We need to fetch https://github.com/eslint/eslint/blob/main/docs/src/_data/rules_meta.json directly
- However, it's still possible to access the legacy APIs by using `Linter({ configType: "eslintrc" })`
- Major plugins have yet to support flat config and appear to be in a transitional phase

There's no need to rush, but we should address this in the near future, before the release of v10.

See also:

> 📈 Tracking: Flat Config support · Issue #18093 · eslint/eslint
> https://github.com/eslint/eslint/issues/18093

**Comment by Boshen** [comment]
Action: fetch rule list from https://github.com/eslint/eslint/blob/main/docs/src/_data/rules_meta.json

**Comment by Boshen** [comment]
According to https://github.com/eslint/eslint/issues/18103, there'll be something else by the next major version. Let's close this as not planned for now and wait until things break since there's no actionable items to do.
