### ISSUE TITLE
ast: revisit `Modifiers`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2958]
The `Modifiers` data is used for error recoverable, but it causes a lot of confusion while working on the AST. Consider removing it.

**Comment by Boshen** [comment]
I want a data structure to clearly indicate the allowed modifiers, with other disallowed modifiers attached to it.

**Comment by overlookmotel** [comment]
Would it be OK to:

Only allow valid modifiers to be encoded in the AST.

When parser finds a modifier in an invalid location, it raises an error and then ignores it (i.e. doesn't put it in AST) and can then continue parsing the rest of the file.

Then we get a simpler AST which we can rely on being valid, but don't cause the parser to grind to a halt when it hits something illegal.

Does that count as recoverable?

**Comment by Boshen** [comment]
AST no longer uses `Modifiers` but parser still uses it for maximum control.
