### ISSUE TITLE
Reduce indirection in AST types

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3048]
AST types in a few places have what seems like unnecessary indirection via `Vec<Box<T>>`. I believe `Vec<T>` should suffice.

The downsides of `Vec<Box<T>>` are:

1. An extra level of indirection.
2. The `T`s are scattered in memory rather than in a contiguous block.

Only advantage I can see is that if the `Vec` grows repeatedly, reallocation is cheaper when entries of the `Vec` are `Box<T>` (8 bytes) rather than `T` (generally larger). But if this is a genuine advantage, we could probably be using that optimization elsewhere e.g. `Vec<'a, TemplateElement<'a>>` in `TemplateLiteral`.

@Boshen Is there a rationale for `Vec<Box<T>>`? Or just an accidental "how it ended up" as the AST evolved?

Current uses of `Vec<Box<T>>` are:

```rs
pub struct Class<'a> {
    pub implements: Option<Vec<'a, Box<'a, TSClassImplements<'a>>>>,
}
```

```rs
pub struct TSTypeParameterDeclaration<'a> {
    pub params: Vec<'a, Box<'a, TSTypeParameter<'a>>>,
}
```

```rs
pub struct TSInterfaceDeclaration<'a> {
    pub extends: Option<Vec<'a, Box<'a, TSInterfaceHeritage<'a>>>>,
}
```

```rs
pub struct TSIndexSignature<'a> {
    pub parameters: Vec<'a, Box<'a, TSIndexSignatureName<'a>>>,
}
```

**Comment by Boshen** [comment]
We can remove these. I didn't actually implement these ts types ;-)

**Comment by Boshen** [comment]
We can remove these. I didn't actually implement these ts types ;-)

**Comment by overlookmotel** [comment]
OK great. Will get to it.
