### ISSUE TITLE
oxlint ignores symbolic links

### ISSUE THREAD

**Issue by sergi** [oxc-project/oxc#3080]
I'm using the following command:
```
oxlint -c .eslintrc.json --tsconfig ./tsconfig.json .
```
but it's ignoring a `./shared/` folder inside the folder where its run, while eslint doesn't. Is there any option or parameter that can be set up to explicitly parse symlinks?

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/88ded0cef5304e471758c504e8e26915b0f0407a/crates/oxc_cli/src/walk.rs#L104-L107

Let me think about this.

**Comment by Boshen** [comment]
`--symlinks` added in https://github.com/oxc-project/oxc/pull/3244 and released in v0.3.3.
