### ISSUE TITLE
Implement `no-mixed-enums` lint rule

### ISSUE THREAD

**Issue by todor-a** [oxc-project/oxc#3094]
https://typescript-eslint.io/rules/no-mixed-enums/

**Comment by Boshen** [comment]
> This rule requires [type information](https://typescript-eslint.io/getting-started/typed-linting) to run.

:thiking:

**Comment by todor-a** [comment]
Interesting, I must've missed that. I thought it's a simple check but turns out it isn't.

Should we close this issue then?

**Comment by magic-akari** [comment]
We can handle simple situations. 
But in practice, enums can be merged across different distributions. 
In extreme cases, they might even be merged across namespaces, leaving us with no viable solution.

**Comment by todor-a** [comment]
Yep, I missed those "small" caveats :)
