### ISSUE TITLE
[Parser] support top level return statement

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#3168]
```js
return require('fs')
```

Above code is valid in Node.js. We might need to deal with such code using oxc.

**Comment by Dunqing** [comment]
[Babel](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=E4UwLgrsB2AEoEcIEtQAoDkAzAzhglAFBA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.24.5&externalPlugins=%40babel%2Fplugin-transform-react-jsx-self%407.24.1&assumptions=%7B%7D) also doesn't support it. This code is not compliant with the specification and does not make sense. Is there a reason we must support it?

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/be87ca8419333b84918f250be38479e3812549ec/crates/oxc_parser/src/lib.rs#L158-L166
