### ISSUE TITLE
Speed up builds on CI with more caching

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3200]
Follow on from #2981.

The largest component of the time it takes to run benchmarks on CI is *building* the benchmarks.

Obviously the benchmarks for whichever crates a PR touches do need to be rebuilt, but all the rest could be cached.

The [docs for Swatinem/rust-cache](https://github.com/Swatinem/rust-cache?tab=readme-ov-file#cache-details) say:

> In particular, the workspace crates themselves are not cached since doing so is generally not effective.

That would indeed make sense for a single crate, but in a workspace project where the majority of PRs will only touch a single crate, I don't think this is a good strategy.

Not sure how to solve it, but I imagine if we can improve the caching strategy, it could improve CI times significantly.

**Comment by Boshen** [comment]
If the goal is to speed up the benchmark build, 2 things:

1. lto = "thin", it should cut the build time by a huge amount with about 10% perf regression
2. figure out why it's building the entire workspace?

```
Run cargo build --release -p oxc_benchmark --bench lexer --features codspeed
    Updating crates.io index
   Compiling oxc_span v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_span)
   Compiling oxc_index v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_index)
   Compiling oxc_allocator v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_allocator)
   Compiling oxc_ast_macros v0.0.0 (/home/runner/work/oxc/oxc/crates/oxc_ast_macros)
   Compiling oxc_diagnostics v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_diagnostics)
   Compiling oxc_sourcemap v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_sourcemap)
   Compiling oxc_macros v0.0.0 (/home/runner/work/oxc/oxc/crates/oxc_macros)
   Compiling oxc_syntax v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_syntax)
   Compiling oxc_ast v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_ast)
   Compiling oxc_tasks_common v0.0.0 (/home/runner/work/oxc/oxc/tasks/common)
   Compiling oxc_semantic v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_semantic)
   Compiling oxc_parser v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_parser)
   Compiling oxc_codegen v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_codegen)
   Compiling oxc_minifier v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_minifier)
   Compiling oxc_linter v0.0.0 (/home/runner/work/oxc/oxc/crates/oxc_linter)
   Compiling oxc_prettier v0.0.0 (/home/runner/work/oxc/oxc/crates/oxc_prettier)
   Compiling oxc_transformer v0.12.5 (/home/runner/work/oxc/oxc/crates/oxc_transformer)
   Compiling oxc_benchmark v0.0.0 (/home/runner/work/oxc/oxc/tasks/benchmark)
```

**Comment by Boshen** [comment]
> How about using sccache with Github Actions backend?

https://github.com/mozilla/sccache/blob/main/docs/GHA.md

Already tried a year go https://github.com/oxc-project/oxc/pull/268

**Comment by Boshen** [comment]
> And what do you think about my "wacky idea" above?

I don't not a fan of constructing our infra against a third party tool ...

**Comment by overlookmotel** [comment]
> Already tried a year go https://github.com/oxc-project/oxc/pull/268

Damn!

> cargo caches at the crate level

Would you mind explaining that a bit more? This is what I was trying to say originally, but I'm not great on infrastructure stuff, so probably don't know the right words/concepts.

**Comment by Boshen** [comment]
Split `oxc_benchmark` into more crates, i.e. `oxc_bench_lexer` etc etc

**Comment by overlookmotel** [comment]
Ah I see. I didn't try that exactly, but I did try putting all `oxc_benchmark`'s dependencies (`oxc_linter`, `oxc_prettier` etc) behind different features and then only enabling the feature required for each benchmark. It helped a bit, but not much.

But maybe problem is I didn't get them to use different cache keys, so they all destroyed each others' caches?

**Comment by Boshen** [comment]
> The other thing we could try is having 1 job build oxc_benchmark, and then all the other jobs to actually run the benchmarks wait for that to complete.

Oh yeah, this is simpler.

**Comment by overlookmotel** [comment]
Just to go back to 2 things you said earlier:

> I already tried.
> 
> You need something like https://github.com/holmgr/cargo-sweep to tidy up things, but I got into dead ends. I read all the issues around this topic and even tried building my own tools, but there's some problem with cargo not keeping some meta if I remember correctly.

I've just read a bunch of the issues linked to from https://github.com/Swatinem/rust-cache/issues/37

Can't say I understand most of it, but it seems like maybe "some problem with cargo not keeping some meta" was that cargo judges if a file is changed or not by its `mtime`, but restoring the cache on Github Actions does not preserve the timestamps. If so, this looks like a promising solution for that:

https://github.com/rust-lang/cargo/issues/6529#issuecomment-1558438048

(this "retimer" tool was never made public, but it doesn't sound complicated to build something similar)

It may well be that I'm being hopelessly naive, and there's a whole rabbit hole of further complications. But given that CI speed is a priority for Oxc, maybe it's worthwhile giving it another shot?

> > And what do you think about my "wacky idea" above?
>
> I don't not a fan of constructing our infra against a third party tool ...

I didn't see it like that. I saw it as hacking an external tool to make it do what we want - make the infra fit *us* (and we are already hacking CodSpeed's API to do sharded benchmarks).

**Comment by overlookmotel** [comment]
And just to drop the link as a sort of "bookmark", I found this comment interesting on the subject:
https://github.com/yewstack/yew/pull/2340#issuecomment-1007878941

**Comment by milesj** [comment]
IMO I'd suggest sccache + S3 again. I use it in moon just fine.

**Comment by overlookmotel** [comment]
@milesj Does S3 not run up the bills quite a bit?

**Comment by Boshen** [comment]
@overlookmotel That's why are living in a refugee camp. Too poor.

**Comment by Boshen** [comment]
We don't need more caches, we just need to fix our code https://github.com/oxc-project/oxc/issues/3213

closing as non-actionable.

**Comment by overlookmotel** [comment]
@Boshen Concerning sccache: How much data storage do we need?

sccache supports Cloudflare R2 which is cheaper than S3 - $1.50 a month for 100 GB storage, and data transfer is free.

Surely even us refugees can afford $1.50 a month?!

**Comment by overlookmotel** [comment]
Tell you what... I'll split it with you. 75 cents a month each. 😆

**Comment by milesj** [comment]
FWIW, moon's S3 CI costs are only like $8 a month.
