### ISSUE TITLE
Parse `cls.fn<C> = x` error

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#3206]
Please see [oxc playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIAOgYCAgICAgICyHorESipoTWsAyIDOIR7Txpd%2BY3p%2FxeTv%2Ba%2FzqsuMoU3Ft8ctOnCBcPMjXEGiYolFnhzGEquYYv7M3ocdF74Z4dk8Gs29MeEQmToPgZvp2dHHBSEppY09JoxjCYCnjTsQ%2BOuai6OyMwbfMwhfh%2B%2F2IvAeeFdt0OLqfxRMHnQ%2B7mgY4XuSxlHHT8%2BaQWAvI6rSywK5XOKTpgpfA%2B3z29eAv5JJvGiNS0tTRk5sIPr8U2vIHlkDP6CANlOTAnAlSnQiuUybsOCSnmdt5Ga94H9%2F7ax%2BgA%3D%3D). Babel has already fixed in https://github.com/babel/babel/pull/16476

**Comment by magic-akari** [comment]
It is clear that adding a `TSInstantiationExpression` enum case in `SimpleAssignmentTarget` is the first step to solving this issue.
When I tried to do so, I found that the current macro is quite challenging to understand.

**Comment by overlookmotel** [comment]
@magic-akari Hi. I am the author of the dreadful monstrosity which is the `inherit_variants!` macro. In my defence, it's a temporary implementation. It's going to be a replaced with a proc macro + codegen combo which will make it much better in various ways.

In the meantime...

If you want to add a variant to `SimpleAssignmentTarget`, you need to:

1. Add it to `SimpleAssignmentTarget` enum in `js.rs`, in usual way.
2. Add it to the `macro_rules! match_simple_assignment_target` macro definition below that (line 1149).
3. Add it to the `macro_rules! inherit_variants` macro definition in `macros.rs` in the part below the comment `// Inherit SimpleAssignmentTarget variants` (line 347).
4. Add it to the `shared_enum_variants!` macro invocation just below that (line 372).

NB: Assign the variant a discriminant value of `5` (1 more than the current largest discriminant) and make sure that same discriminant value is used consistently everywhere in the above 4 steps. If you get that wrong, it won't let you commit runtime UB, but it will produce a compile time error.

Sorry this is such a hassle. I was hoping I'd be able to replace the present implementation with an improved version which will make all the above unnecessary before anyone needed to make changes to these enums, so no-one would notice. But you are too quick!

If you want to understand what all this "inherited enums" business is about, I also added lengthy doc comments yesterday: https://github.com/oxc-project/oxc/blob/main/crates/oxc_ast/src/ast/mod.rs

If you can't figure it out, or it won't work, just ping me and I'll be happy to help.

**Comment by Dunqing** [comment]
> It is clear that adding a `TSInstantiationExpression` enum case in `SimpleAssignmentTarget` is the first step to solving this issue. When I tried to do so, I found that the current macro is quite challenging to understand.

Thank you for your try! I figure it out in #3208.
