### ISSUE TITLE
Allow repo members with write access to add their own PRs to merge queue

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3232]
I just merged my own PR #3231. It was fairly small changes, and only touched code which I'm the person best-placed to understand (`oxc_traverse` build script), so it didn't seem worthwhile wasting someone else's time to review it.

To merge it, I ticked the "Merge without waiting for requirements to be met" button and then hit "Squash and merge".

However, I see we're now using the Graphite merge queue, which I assume is a better way to merge PRs. But that requires one approving review. Github does not allow PR authors to review their own work, so it's not possible to merge your own PR using the merge queue at present.

Is there any way we can enable this?

2 ways I can think of:

1. Is there some way to disable the "1 approving review" requirement on a specific PR, in order to clear that blocker?
2. A bot which those with write access can command `@oxcbot merge`. Bot would make an approving review, and add the `merge` tag.

**Comment by Boshen** [comment]
I disabled the approving review, it's pretty useless so far. Let me check if I can change it to allow only a few people to merge PRs.

**Comment by overlookmotel** [comment]
OK great. I think the "approving review" requirement was not ideal, as I think a review from any old random Joe could satisfy the requirement. Locking down who has permission to merge is probably a better way.

I assume Graphite doesn't obey the `merge` label unless the person who adds it has write access? Otherwise any random passer-by could merge anything they like.

**Comment by Boshen** [comment]
> I assume Graphite doesn't obey the merge label unless the person who adds it has write access? Otherwise any random passer-by could merge anything they like.

yes.
