### ISSUE TITLE
eslint-plugin-regexp

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3263]
https://github.com/ota-meshi/eslint-plugin-regexp

**Comment by Boshen** [comment]
After going through the rules list of https://github.com/ota-meshi/eslint-plugin-regexp, my recommendation is that we only port / implement rules that will trigger performance problem or ReDos. Everything else should be declared as out of scope due to our lack of resources.

e.g.

* https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-super-linear-backtracking.html 
* https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-super-linear-move.html

What do you think about this decision, @leaysgur?

**Comment by leaysgur** [comment]
LGTM. 👍🏻 

I think it's a matter of priority? So if other rules become necessary, we can just implement them.

**Comment by Boshen** [comment]
> LGTM. 👍🏻
> 
> I think it's a matter of priority? So if other rules become necessary, we can just implement them.
> 
> After a little peeking these rules, it seems that they depend on yet another library, which may take some time. 😅
> 
> * https://github.com/RunDevelopment/scslre
> * https://github.com/RunDevelopment/regexp-ast-analysis
> * https://github.com/RunDevelopment/refa

TIL. So given these requirements, I'm just going to close this as not planned.
