### ISSUE TITLE
CI: add oxlint-ecosystem-ci action to the main repo.

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#3313]
I've been using https://github.com/oxc-project/oxlint-ecosystem-ci recently, And it is quite useful especially if we add more big projects to it.

It would be a treat if we could have it with a manual trigger to run it when we need to test linter rules on a handful of real projects.

**Comment by Boshen** [comment]
I added a bunch of scripts to get it running locally https://github.com/oxc-project/oxlint-ecosystem-ci?tab=readme-ov-file#local

I'll look into cross repo trigger when the requirement arises.
