### ISSUE TITLE
linter: option to disable oxc and deepscan rules

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3316]
@Boshen do we also have `--disable-oxc-plugin` and `--disable-deepscan-plugin`?
i.e. I only want ESLint rules

e.g.

```
    "deepscan/bad-array-method-on-arguments": 0,
    "deepscan/bad-char-at-comparison": 0,
    "deepscan/bad-comparison-sequence": 0,
    "deepscan/bad-object-literal-comparison": 0,
    "deepscan/bad-min-max-func": 0,
    "deepscan/bad-replace-all-arg": 0,
    "deepscan/missing-throw": 0,
    "deepscan/number-arg-out-of-range": 0,
    "deepscan/uninvoked-array-callback": 0,
    "oxc/const-comparisons": 0,
    "oxc/double-comparisons": 0,
    "oxc/erasing-op": 0,
    "oxc/only-used-in-recursion": 0,
```

_Originally posted by @Mouvedia in https://github.com/oxc-project/oxc/issues/1970#issuecomment-2115345592_

**Comment by Boshen** [comment]
I think it's time to drop the `deepscan` prefix and move them all to `oxc`

**Comment by Mouvedia** [comment]
> I think it's time to drop the `deepscan` prefix and move them all to `oxc`

https://github.com/oxc-project/oxc/pull/3327/files#diff-5b9a9978f5684197a572f7f7c1966147673c49bc90c6162849107b8ffd2a3fad
