### ISSUE TITLE
linter: map rules of hooks to react-hooks

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3317]
BTW, will linter configurations be also supported?

```json
{
  "rules": {
    // ...
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  }
}
```

> https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks#custom-configuration

If we need to change like this, might there be compatibility issues...?

```json
{
  "rules": {
    // ...
    "react/rules-of-hooks": "error",
    "react/exhaustive-deps": "warn"
  }
}
```

_Originally posted by @leaysgur in https://github.com/oxc-project/oxc/issues/3315#issuecomment-2115376471_

**Comment by rzvxa** [comment]
Can we have it in such a way that both the `react` and `react-hooks` alias work? this way we can ease the migration while providing easy-to-understand names for newcomers with no eslint experience.
