### ISSUE TITLE
linter: panic in `jest/expect-expect`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3323]
Found in https://github.com/oxc-project/oxlint-ecosystem-ci/actions/runs/9123766396/job/25086817261?pr=6

Reduced case:

```javascript
test("event emitters bound to CLS context", function(t) {
    t.test("emitter with newListener that removes handler", function(t) {
        ee.on("newListener", function handler(event: any) {
            this.removeListener("newListener", handler);
        });
    });
});
```

Infinite recursion in

https://github.com/oxc-project/oxc/blob/27030b9eb4d7b19ff2db55cfd0e9b04bdff69ec6/crates/oxc_linter/src/rules/jest/expect_expect.rs#L179-L188

because it went back inside `handler`

**Comment by Boshen** [comment]
Why does it need to check for the arguments when `matches_assert_function_name` is false?

https://github.com/oxc-project/oxc/blob/27030b9eb4d7b19ff2db55cfd0e9b04bdff69ec6/crates/oxc_linter/src/rules/jest/expect_expect.rs#L170-L174

**Comment by Boshen** [comment]
Can we do a temporary fix first, and then figure out how to best write this?

**Comment by mysteryven** [comment]
Panic is resolved, and the below belongs to another issue.

> I found the current implementation was not correct. It finds assert function from `test funtion` to bottom, There will be so many cases I would forget(e.g. `if (condition){ expect()}`), I plan to follow the [jest implementation](https://github.com/jest-community/eslint-plugin-jest/blob/2f21f3301181185f5e9aaa72e8ad4b7e884d029a/src/rules/expect-expect.ts#L115-L139), it needs to loop all nodes... any better ideas?
> 
> ```rust
> fn run_once(&self, ctx: &LintContext) {
>         let test_functions = HashSet::new();
> 
>         for node in ctx.nodes() {
>             if is_test_function(node) {
>                 test_functions.insert(node.span());
>             } else if is_expect_call(node) {
>                 // try get nearest test function, if got, remove it from test_functions
>             }
>         }
>     }
> ```
