### ISSUE TITLE
new-rule for eslint doesn't handle `languageOptions`

### ISSUE THREAD

**Issue by jelly** [oxc-project/oxc#3366]
I was a bit confused after having run `new-rule` and valid test cases error'ing out as languageOptions are not respected when generating a new rule.

For example:
```
{ code: "globalThis.Math.pow(a, b)", languageOptions: { ecmaVersion: 2019 } },
```

https://github.com/eslint/eslint/blob/main/tests/lib/rules/prefer-exponentiation-operator.js#L73

**Comment by jelly** [comment]
I'm not sure if oxlint wants to support `languageOptions`, so maybe this can just be dropped when generating a rule.

**Comment by Boshen** [comment]
Rule gen will now pick up `languageOptions` and attach it as a inline comment, for the implementor to decide how to deal with it.
