### ISSUE TITLE
Align visitation order in `Traverse` with `Visit` and `VisitMut`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3392]
`Traverse` is codegen-ed from the AST node type definitions. The codegen generates a walker which visits children of a node in the order which they're defined in the AST types. e.g. for:

https://github.com/oxc-project/oxc/blob/8a1db6738c761b87a2581275e728445c1bb63e5a/crates/oxc_ast/src/ast/js.rs#L52-L60

Visitors are called in order matching the above:

* `enter_program`
* `enter_directive` + `exit_directive` (for each directive)
* `enter_hashbang` + `exit_hashbang`
* `enter_statements` + `exit_statements`
* `exit_program`

On the other hand, `Visit` and `VisitMut` were written by hand. It's likely that for some types the visitation order is different from the types' field order. So it will be different from `Traverse`'s visitation order.

This mismatch is going to cause problems at some point as contributors who are used to `Visit`/`VisitMut` will assume that `Traverse` behaves the same, and be confused when it doesn't, or unwittingly introduce bugs due to incorrect assumptions.

I think best way to tackle this is:

* Write a codegen for `Visit` and `VisitMut` which does visitation in AST node field order (like `Traverse` does).
* Diff current `Visit` vs codegen-ed `Visit`.
* Where they don't match, change the field order in AST types, and run codegen again.
* Keep doing that until the codegen-ed `Visit` and current hand-written `Visit` match exactly.
* Throw away the old hand-written `Visit` and `VisitMut` and use the codegen from here on.

Once we switch to codegen, any changes to AST types will automatically update `Visit` + `VisitMut` to match.

In addition: We know there are also some discrepancies with `Visit`/`VisitMut` not visiting some child nodes. Likely in some cases this is a mistake (inevitable when writing this much code by hand), but in other cases it's intentional (like not visiting some TS nodes where it's pointless to do so).

The process above will reveal all such discrepancies, and then we can decide which are mistakes and which are intentional, and we can then adapt `Visit`, `VisitMut` and `Traverse` to make them all consistent and all reflecting what we decide is the "correct" visitation policy.

**Comment by Boshen** [comment]
@rzvxa FYI

**Comment by rzvxa** [comment]
@overlookmotel I think this can be closed after merging #4001 and #4007

**Comment by rrandom** [comment]
Can anybody tell me what is the difference between these two traits?

I noticed that the `Visit` trait is utilized in crates such as `semantic`, while the `Traverse` trait is employed in `transformer` and `minifier` crates. Could anyone clarify the rationale behind having these two different traits?

Additionally, when I am implementing my own traversal, how should I decide which trait to use?

**Comment by overlookmotel** [comment]
`Visit` is for if you want an immutable visitor (i.e. you do not need to alter the AST), `VisitMut` and `Traverse` are mutable visitors (for when you want to mutate the AST). The difference between `VisitMut` and `Traverse` is more subtle. Read the doc comments in `oxc_traverse` crate for more details.

Just for future reference, for questions please open a Discussion here on Github or reach out on our [Discord](https://discord.gg/9uXCAwqQZW), rather than commenting on old issues.
