### ISSUE TITLE
Invalid Unicode escape sequence after 0.4.0

### ISSUE THREAD

**Issue by eMerzh** [oxc-project/oxc#3399]
hello, is seems that 0.4 is somewhat breaking here

It detect an invalid escape in our node_modules (https://github.com/PrismJS/prism/blob/master/prism.js#L1862C5-L1862C61) 

the extract is 
```js
var extension = (/\.(\w+)$/.exec(src) || [, 'none'])[1]
```

if i put that in a single file i still have the issue

```
  × Invalid Unicode escape sequence
   ╭─[brol.js:3:20]
 2 │ // in this case, we want to use the extension as the language
 3 │ var extension = (/\.(\w+)$/.exec(src) || [, 'none'])[1]
   ·                    ─
   ╰────
   ```

**Comment by Boshen** [comment]
Looking at this right now, seems related to a bunch of parser work I did earlier.

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.4.1

**Comment by eMerzh** [comment]
thanks for the quick fix!
❤️
