### ISSUE TITLE
Avoid Antivirus Message every install/update

### ISSUE THREAD

**Issue by passariello** [oxc-project/oxc#3401]
Hello, oclint is great. I love it!

Just a smaller notice / advice. Every installation or update Avast start to check the EXE. It's fine, security first but... if someone contact Avast and major antivirus can sign it as community secure and this message will be unecessary. Please, take this a priority to avoid some stop from companies with elevate security check.

Have a great day guys!
Dario Passariello

![image](https://github.com/oxc-project/oxc/assets/17809213/937c0aa9-1e58-4f84-af84-3c02c6e20ada)

**Comment by rzvxa** [comment]
Hi there,

Thanks for informing us about this issue, I've reached out to Avast about the problem; We'll let you know the outcome of this and hopefully, then you can confirm whether it is fixed or not.

I wish you a wonderful day!

**Comment by Boshen** [comment]
Close as stale and no action can be taken to address this.
