### ISSUE TITLE
Make fields of `SourceType` public

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#3485]
I would like use `SourceType` in a way that prevent potential breaking changes.

Currently, you could only use `SourceType` with builder pattern

```rust
SourceType::default().with_xxx()
```

The problem is that the behavior of `SourceType::default()` could be changed in the future. I want the changes in `SourceType` could be a compile error for users if there is any change.

Expected usages

```rust
let ty = Self {
            language: Language::JavaScript,
            module_kind: ModuleKind::Script,
            variant: LanguageVariant::Standard,
            always_strict: false,
  }
```

**Comment by Boshen** [comment]
Can you add a unit test to Rolldown for the defaults? I'm not sure about exposing the internals :-(

**Comment by hyf0** [comment]
> I'm not sure about exposing the internals :-(

I'm more considering these as options to users. So there aren't special compared to other options passing to parser or semantic.

I mean if every field there is `with_xxx` to set it, adding `pub ` to each field doesn't seem to meaning exposing internals, since it's already be exposed.
