### ISSUE TITLE
Test the Transformer

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3517]
We have https://github.com/oxc-project/transform-ci up and running.

Need ideas to check whether the transformed code is correct in all aspects.

Current tests:

* idempotency test
* run `tsc` over the transformed file

**Comment by overlookmotel** [comment]
To test that transformer correctly keeps scopes tree updated, we could:

* Parse code.
* Transform it.
* Save the scopes tree after transform (tree A).
* Clone AST.
* Run semantic on clone to generate a fresh new scopes tree (tree B).
* Compare tree A and tree B. They should match.

Unfortunately it'd be more complicated than a simple `PartialEq` between the 2 trees. It's OK for `scope_id`s to be different between the 2 scope trees, as long as the pattern of *usage* of those `scope_id`s is consistent. i.e. in tree A the `scope_id` for a certain node might be 100, but in tree B it might be 200, and that's fine as long as every identifier which is bound in scope 100 in tree A is bound to 200 in tree B. Same thing for `SymbolId`s and `ReferenceId`s.

We'd probably need to sort IDs in both trees to a consistent order somehow to be able to compare them.

So quite a bit of work, but it would be a really good test and I expect would catch almost all scope-related bugs.

**Comment by Boshen** [comment]
It seems like we can run vitest over the transformed file if we configure a new vitest config.

**Comment by Boshen** [comment]
Will track more ideas in the transform-ci repo.
