### ISSUE TITLE
Add `raw` field to `StringLiteral`

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#3518]
This field stores the original text and contains quotes.  I saw  both `babel` and `swc` have this field

For example
```ts
let a = '\ud834\udf06'
```

The `a` should be
```text
StringLiteral {
  span: SPAN,
  value: "𝌆"
  raw: "'\\ud834\\udf06'"
}
```

There are two problems we need to figure out via `raw` in `codegen`

1. Printing a single quote or double quote depends on the original text used and what kind of quote it is.
2. Printing escape unicode instead of unescape unicode 

Also, I see a lot of tests for unicode being ignored, and I think we might be able to fix them as well

**Comment by Boshen** [comment]
I think we need to port this https://github.com/evanw/esbuild/blob/67cbf87a4909d87a902ca8c3b69ab5330defab0a/internal/js_printer/js_printer.go#L64

**Comment by Dunqing** [comment]
> I think we need to port this https://github.com/evanw/esbuild/blob/67cbf87a4909d87a902ca8c3b69ab5330defab0a/internal/js_printer/js_printer.go#L64

I have a look at this, I found some our [tests](https://github.com/oxc-project/oxc/blob/06-04-refactor_codegen_reduce_allocation_for_print_unquoted_str/crates/oxc_codegen/tests/mod.rs#L75-L79) are wrong. The source text and expected text for these tests should be the same. This seems to be a problem with `rust`, which can't treat an invalid unicode as a unicode

**Comment by Boshen** [comment]
> > I think we need to port this https://github.com/evanw/esbuild/blob/67cbf87a4909d87a902ca8c3b69ab5330defab0a/internal/js_printer/js_printer.go#L64
> 
> I have a look at this, I found some of our [tests](https://github.com/oxc-project/oxc/blob/06-04-refactor_codegen_reduce_allocation_for_print_unquoted_str/crates/oxc_codegen/tests/mod.rs#L75-L79) are wrong. The source text and expected text for these tests should be the same. This seems to be a problem with `rust`, which can't treat an invalid unicode as a unicode

It feels like the test cases should be in raw utf16, are you able to fix these tests?

**Comment by Dunqing** [comment]
> It feels like the test cases should be in raw utf16, are you able to fix these tests?

I've spent all day researching this, but I haven't found a way to fix it yet. The result of `'\\uD808'.chars()` is `["\", "u", "D", "8", "0", "8"]`。Obviously rust cannot treat an invalid unicode as a `char`

**Comment by Dunqing** [comment]
> > It feels like the test cases should be in raw utf16, are you able to fix these tests?
> 
> I've spent all day researching this, but I haven't found a way to fix it yet. The result of `'\\uD808'.chars()` is `["\", "u", "D", "8", "0", "8"]`。Obviously rust cannot treat an invalid unicode as a `char`. I also tried `encode_utf16` but the result is the same.

**Comment by Boshen** [comment]
You can always get raw from `span.source_text(source_text)`.
