### ISSUE TITLE
`JSXIdentifierReference` type

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3528]
`Foo` in `<Foo />` is equivalent to an `IdentifierReference`. It should have a `reference_id`, and semantic should resolve its binding.

`JSXIdentifier` is also used in other positions e.g. as a `JSXAttributeName`, so would probably need a separate type `JSXIdentifierReference` for this specific use.

Could also differentiate between `<div />` and `<Div />` in parser, with `JSXIdentifierReference` only used for the latter.

**Comment by Boshen** [comment]
I confirmed with tsc, which uses a plain `Identifier`:

```typescript
export type JsxTagNameExpression =
    | Identifier
    | ThisExpression
    | JsxTagNamePropertyAccess
    | JsxNamespacedName
    ;
```

which means we can remove `JsxIdentifier` and use `IdentifierReference` and `IdentifierName` directly.

```rust
pub enum JSXElementName<'a> {
    /// `<Apple />`
    IdentifierReference(Box<'a, IdentifierReference<'a>>),
    /// `<div />
    IdentifierName(Box<'a, IdentifierName<'a>>),
    /// `<Apple:Orange />`
    NamespacedName(Box<'a, JSXNamespacedName<'a>>),
    /// `<Apple.Orange />`
    MemberExpression(Box<'a, JSXMemberExpression<'a>>),
}
```

but, in order to make it compatible with estree, we need to add at least one new AST node `JSXIdentifierReference `
```

:-/

**Comment by overlookmotel** [comment]
Ditto for:

```rs
pub enum JSXMemberExpressionObject<'a> {
    /// `<Foo.bar />`
    IdentifierReference(Box<'a, IdentifierReference<'a>>),
    /// `<foo.bar />`
    IdentifierName(Box<'a, IdentifierName<'a>>),
    MemberExpression(Box<'a, JSXMemberExpression<'a>>),
}
```

I think we can use `IdentifierReference` and `IdentifierName` directly and get ESTree compatibility with a custom `Serialize` impl.

**Comment by overlookmotel** [comment]
Looks like `JSXElementName` also needs a `ThisExpression` variant. `<this />` is valid syntax.

**Comment by overlookmotel** [comment]
Dunqing did bulk of this work in #5223.

Remaining bits to cover: #5352, #5353, #5354.

Closing in favour of those individual issues.
