### ISSUE TITLE
parser: unmatched jsx element error `<Foo></Bar>`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3548]
The parser happily parses this invalid JSX syntax: `<Foo></Bar>`.

[Oxc playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAICMgICAgICAgICekQl4vp6EPSzPb%2BqmUbsGf3%2B0%2FICA)

**Comment by Boshen** [comment]
This should be implemented in the parser for convenience.

**Comment by overlookmotel** [comment]
What do we do if they don't match? Do we conform the `JSXElementName` in `JSXClosingElement` to match `JSXOpeningElement` if they don't match? Or leave it as is in an invalid state?

If we enforce them matching in parser, we could remove the `JSXElementName` from `JSXClosingElement` type entirely, as it'll always be a duplicate of the one from `JSXOpeningElement`. This would be much more efficient. Linter wouldn't be able to see the problem, but parser will have already raised the error, so I guess that's OK?

**Comment by xyloflake** [comment]
I think throwing an error would be the bestthig to do when something like this s encountered @overlookmotel @Boshen ?
