### ISSUE TITLE
Handle `@jsx` pragmas for TypeScript

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3560]
We recently added more support for `@jsx` pragmas in conformance suite (#3553).

I believe some of these should be handled in parser/semantic/transformer (not sure which) instead for TS/TSX files. According to TS docs, they're valid:

https://www.typescriptlang.org/docs/handbook/jsx.html#configuring-jsx

**Comment by Boshen** [comment]
It should be analyzed in the transformer.

**Comment by overlookmotel** [comment]
Would it not be useful to add a `pragmas` field to `Program` and populate it in the parser, like with `Hashbang`? I imagine other tools might find this info useful as its meaningful information for interpreting the AST (broadly equivalent to an `import React from "whatever";` statement).

**Comment by Boshen** [comment]
Nope, it's not part of the spec so it can't go into the AST.

**Comment by overlookmotel** [comment]
But it is part of the TS spec, no? https://www.typescriptlang.org/docs/handbook/jsx.html#configuring-jsx

**Comment by Boshen** [comment]
That's not an AST spec, it's just documentation 😅

**Comment by overlookmotel** [comment]
OK, true! But what's the difference? Spec and config are both things which are present in the source text, and alter the meaning of the code.

Therefore I feel it's better to store the info in AST. But I don't feel strongly about it. Say no one more time, and I'll shut up!

**Comment by overlookmotel** [comment]
PS It'd also be faster to find these comments in parser while parsing comments anyway, rather than searching through all comments again later.

**Comment by Boshen** [comment]
You can save them into `Trivias` if you really want to parse them from the parser.

**Comment by Boshen** [comment]
In https://github.com/oxc-project/oxc/pull/3553

The lines in https://github.com/microsoft/TypeScript/blob/main/tests/cases/compiler/jsxComplexSignatureHasApplicabilityError.tsx
```
// @strict: true
// @jsx: react
// @skipLibCheck: true
```

are compiler settings for the test file, they aren't pragmas.

---

In tsx files, the prgrama

```
/** @jsxImportSource preact */

<Foo />
```

Produces

```
import {jsx as _jsx} from 'preact/jsx-runtime';
_jsx(Foo, {});
```

This is working as intended.
