### ISSUE TITLE
Add `directives` field to `TSModuleDeclaration`?

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3564]
From #3532, it seems like this is legal syntax and `'use strict';` should be interpreted as a `Directive`:

```ts
namespace Foo {
    'use strict';
    export const bar = 123;
}
```

Should we add a `directives: Vec<'a, Directive<'a>>` field to `TSModuleDeclaration` and fill it in the parser, using same logic as for functions?

**Comment by Boshen** [comment]
Babel parser hands out `Directive` nodes. We can do this.

**Comment by overlookmotel** [comment]
Babel doesn't use `Directive`s, as far as I can see, and nor does typescript-eslint or SWC:

[AST explorer - Babel](https://ast.sxzz.moe/#eNotjkEKwzAMBL9idM4L0ntf0FvVg+OK4uJIwrILJeTvkUluq9lB7AYFZvjGX7RUszaYQB0scaHiOXnmuJJpTBTuImFDDgGhGwVrNaeGcEPekd0Wt6/epNdEj78Swuz3Ku9ePE9nraV/MtvonoMM1lw+RyAM9vK3sB9WfjQI)
[AST explorer - typescript-eslint](https://ast.sxzz.moe/#eNotjEEOwjAMBL8S+Vw+UO68AHHKxQoWCkqcyHaQUNW/Y5re7Jnd3aDACm/8oCbJ3WCB7sC+nSa4kJbMf56cM1bSjonCrbWwRQ4hwlAKapKTRbhG3iN7unn69NqGJLr7ZITV/9qeo/i9TE2p4oNEc+PpCxqpb51ekF9H02SQz8P+A2+zPCI=)
[AST explorer - SWC](https://ast.sxzz.moe/#eNotjEsOg1AIRbdCGLsCO+8qmBBKExsLLw/6Mca9i9HZyb0nZ8UZR3zxl0P61BIHbDXET4qkyPit0VgU7u6wkgEQfkIhsk+ShDeyjaxsL/v6Y7HkP+FYnEvTs004nPdDxTun9ziUJ8+hFcFtB5gpLoQ=)

They all produce a `StringLiteral`. But I think they're all doing it wrong!

NB: If we do this, we'd need to add a custom `Serialize` impl to get ESTree-compatible JSON AST output.

We could just ignore this, and leave it as is. It's not at all a common case. But it will cause semantic to be incorrect. This should be an error (even if `alwaysStrict: false` in TS config), but it won't be:

```ts
namespace Foo {
    'use strict';
    let arguments;
}
```

Typescript gets this right: [TS playground](https://www.typescriptlang.org/play/?alwaysStrict=false#code/HYQwtgpgzgDiDGEAEBBJBvAUEnSA2EALkiAE4DmArpMIVANyYC+mmoksCyAQhtrgHJKUZFEKkAlvEIDGufERIVqEWg2aYgA)
