### ISSUE TITLE
Make `NumericLiteral` `raw` field an `Option`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3609]
`NumericLiteral` has a `raw` field for the "raw" source code that was parsed:

https://github.com/oxc-project/oxc/blob/d65202d7885f816deb9764fc5d0d7d42375f2c98/crates/oxc_ast/src/ast/literal.rs#L72-L79

However, when a `NumericLiteral` is generated in transformer, I don't think it should be required to generate a `raw` value. Therefore, `raw` should be `Option<&str>`.

Babel's treatment of the `raw` field is that it can be `null`. Babel's codegen in non-compact mode uses `raw` field if it's defined, but otherwise converts `value` back to a string in the most compact form. i.e. `10000000000` will be output as `1e10`. `raw` field is only there as an optimization for codegen in non-compact mode, to avoid having to convert the `value` field back to a string.

Babel's approach makes sense to me - centralize the logic for converting numbers back to strings in the codegen, and avoid having to repeat that logic everywhere in transformer.

Same thing for `StringLiteral`, if we add a `raw` field to it (#3518).

@Boshen @Dunqing Do you agree?

**Comment by Dunqing** [comment]
Sounds good to me. I dislike generating a `raw` value in the `transformer`.

**Comment by Boshen** [comment]
It seems like test setup is incorrect for `noStrict`, e.g.

* language/expressions/object/__proto__-permitted-dup-shorthand.js
* language/eval-code
* annexB/language/eval-code

Need to format computed class / object exactly written

* **-computed-property-name-**

The last case is how astral strings should be generated

* language/statements/for-of/string-astral-truncated.js

**Comment by Boshen** [comment]
I tried this in branch 06-23-refactor_ast_remove_raw_field_from_numbericliteral_ for 2 hours, we have way too many places where we use `raw` over `value`.

`Option<&'a str>` is too confusing for consumers.

Close as not planned until we fix our usages of raw first.

**Comment by overlookmotel** [comment]
As mentioned in https://github.com/oxc-project/oxc/issues/3518#issuecomment-2184408938, could get raw text from the span. So we could remove the `raw` field entirely.

**Comment by Boshen** [comment]
Need to fix call sites one by one first instead doing it in one go. There are really annoying call sites right now, e.g. codegen.
