### ISSUE TITLE
docs: Document control flow graph.

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#3649]
Write documentation along with some basic and intermediate examples; We already have a relatively advanced example of doing a custom serialization on the graph and some rules like `no_unreachable`, `require_render_return`, and `getter_return` inferring information from CFG but if anyone has time we can also use a clean, straight forward and well-documented graph walk example.

**Comment by Boshen** [comment]
I don't think anyone is going to pick this as a good first issue. Either you do this or close the issue 😅

**Comment by rzvxa** [comment]
My thought process for creating this issue was that; If someone else does the documentation they would accumulate all of the things that went through in it and then we would have at least 2 people who understand this area of oxc.

But I see your point, It isn't a "good first issue", Please don't close it.
I'll start writing docs and guides for its usage when we hit relative maturity.

**Comment by rzvxa** [comment]
Note to anyone reading this issue, If you want to study the code and write docs for it go ahead I would be more than happy to get another pair of eyes on the source as a way to find issues and mistakes of mine. Feel free to ask any questions you may have.

**Comment by Boshen** [comment]
Close as stale.
