### ISSUE TITLE
Improve codegen

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3692]
- [x] https://github.com/oxc-project/oxc/blob/main/tasks/coverage/codegen_typescript.snap
- [x] Figure out precedence of ts types so `X | Y` don't print as `((X) | (Y))`
- [x] copy `printNextIndentAsSpace` logic https://github.com/evanw/esbuild/blob/fc37c2fa9de2ad77476a6d4a8f1516196b90187e/internal/js_printer/js_printer.go#L290
- [x] `for (;;) ;`
- [x] `--x;` `x++;` `{ foo: !xx }`
- [x] `const {d:e = ''} = {}`
- [x] Improve API separate out sourcemap construction
Some really difficult cases :-/

**Comment by Dunqing** [comment]
The `class` needs to print `superTypeParameters` and `implements` fields.

```ts
class A extend B<superTypeParameters>
                ^^^^^^^^^^^^^^^^^^^^^

class A implements F
                  ^^^

**Comment by Boshen** [comment]
It seems like test setup is incorrect for `noStrict`, e.g.

* language/expressions/object/__proto__-permitted-dup-shorthand.js
* language/eval-code
* annexB/language/eval-code

Need to format computed class / object exactly written

* **-computed-property-name-**

The last case is how astral strings should be generated

* language/statements/for-of/string-astral-truncated.js

And the famous one where `(fn) = function() {};` is different from `fn = function() {};` for `fn.name`.

* language/expressions/assignment/fn-name-lhs-cover.js
