### ISSUE TITLE
isolated-declarations: reporting errors for codes that do not support Isolated Declarations

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#3703]
Here's a list of all the errors with the Isolated Declaration that we need to report in full.
https://github.com/microsoft/TypeScript/blob/d8086f14b6b97c0df34a0cc2f56d4b5926a0c299/src/compiler/diagnosticMessages.json#L6905-L7032

**Comment by Dunqing** [comment]
`Declaration emit for this file requires preserving this import for augmentations. This is not supported with --isolatedDeclarations.`

https://github.com/microsoft/TypeScript/blob/d8086f14b6b97c0df34a0cc2f56d4b5926a0c299/tests/baselines/reference/isolatedDeclarationErrorsAugmentation.errors.txt#L24-L25

This error requires cross-file checking, which we cannot support.

**Comment by Dunqing** [comment]
We have only one error left to report. If anyone is interested please feel free to send a PR.
https://github.com/oxc-project/oxc/blob/f3c3970131e64d46aaff41f03a0738674cf68431/crates/oxc_isolated_declarations/src/diagnostics.rs#L115-L121

**Comment by Boshen** [comment]
This isn't a good first issue, we'll have to fix this our self ;-)

**Comment by Dunqing** [comment]
Done
