### ISSUE TITLE
Please warn about javascript es6 modules "export let x = 1"

### ISSUE THREAD

**Issue by lborgman** [oxc-project/oxc#3733]
I just did

``` JavaScript
export let x = 1;
```
and then 
``` JavaScript
const myModule = await import("my-module");
myModule.x = 2;
const myX = myModule.x; // myX will be 1...
```

The value of `myX` was a bit unexpected.
Could you please warn about this? (I am using your Visual Studio Code extension. The extension is very nice! <3)

The accepted answer here explains the problem:
https://stackoverflow.com/questions/32558514/javascript-es6-export-const-vs-export-let

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/bf9b38a197b66503259700a1ccef5a908492c1aa/crates/oxc_linter/src/rules/eslint/no_import_assign.rs#L44

Let me test this and turn it on by default, given it's a eslint recommend rule.
