### ISSUE TITLE
transformer: differentiate `import {} from "a";` and `import from "a";`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3736]
Our AST differentiates `import {} from "a";` and `import from "a";`

Failing babel test cases like `imports/elide-no-import-specifiers/input.ts`

Added failing test cases: https://github.com/oxc-project/oxc/pull/3735/files#diff-0a1b8e143f74590ed69ad0ad7abfcf2add6d7e6a9c3daff2bbb132b71e0f3f14

**Comment by Boshen** [comment]
I tried this for 30 minutes but couldn't figure out 🙃

**Comment by overlookmotel** [comment]
Do we want to distinguish them? Is there any semantic difference?

TypeScript seems to treat them differently: [TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwL5wGZQiOByAHtgbgChRJYcBPQooA)

**Comment by Boshen** [comment]
> Do we want to distinguish them?

yes

> Is there any semantic difference?

no
