### ISSUE TITLE
semantic: referenced in `export type {}` but `ReferenceFlag` is a value

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#3826]
Please see: https://oxc-project.github.io/oxc/playground/?code=3YCAAICjgICAgICAgIC6nsrEgtebpnCnOkfmyvXpODDg8TpqyEqtH7oZDFcLulh6zbV%2Fe74ogA%3D%3D

Expect `ReferenceFlag` to be the type

**Comment by Boshen** [comment]
Seems like working as intended?
 
<img width="681" alt="image" src="https://github.com/oxc-project/oxc/assets/1430279/6927a6f0-204a-48f7-851d-645122b81af0">

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/445603444f98402fb66a4a956b1023611bc66133/crates/oxc_semantic/src/builder.rs#L1690-L1695

Seems to be correct.

**Comment by Dunqing** [comment]
Yes, I checked now. It is correct. It may be due browser's cache  😕
