### ISSUE TITLE
missing source map when swapping (re-ordering) ast nodes

### ISSUE THREAD

**Issue by hi-ogawa** [oxc-project/oxc#3843]
I'm experimenting with writing transforms on oxc https://github.com/hi-ogawa/experiments/pull/47 and I found that source map is not generated when swapping around ast nodes.
For example, simple repro I found is to swap two statements by `program.body.swap(0, 1)`. I created a repro in https://github.com/hi-ogawa/oxc/commit/4ffa0982c7e9f1c448f47ed2aef56f64a373ff29 and current output looks like this [evanw.github.io/source-map-visualization](https://evanw.github.io/source-map-visualization/#MTI2AGV4cG9ydCBmdW5jdGlvbiBnKCkgewoJbGV0IGEgPSAzOwoJbGV0IGIgPSA0OwoJcmV0dXJuIGEgKyBiOwp9CmV4cG9ydCBmdW5jdGlvbiBmKCkgewoJbGV0IHggPSAxOwoJbGV0IHkgPSAyOwoJcmV0dXJuIHggKyB5Owp9CjMwOAB7InZlcnNpb24iOjMsIm5hbWVzIjpbXSwic291cmNlcyI6WyJ0ZXN0LmpzIl0sInNvdXJjZXNDb250ZW50IjpbIlxuZXhwb3J0IGZ1bmN0aW9uIGYoKSB7XG4gICAgbGV0IHggPSAxO1xuICAgIGxldCB5ID0gMjtcbiAgICByZXR1cm4geCArIHk7XG59XG5leHBvcnQgZnVuY3Rpb24gZygpIHtcbiAgICBsZXQgYSA9IDM7XG4gICAgbGV0IGIgPSA0O1xuICAgIHJldHVybiBhICsgYjtcbn1cbiJdLCJtYXBwaW5ncyI6IkFBTUEsT0FBTyxTQUFTLElBQUk7Q0FDaEIsSUFBSSxJQUFJO0NBQ1IsSUFBSSxJQUFJO0FBQ1IsUUFBTyxJQUFJO0FBQ2QifQ==)

![image](https://github.com/oxc-project/oxc/assets/4232207/1308ee50-5a52-48d6-9a27-b06c8a0e7a48)

I'm not entirely sure but it looks like source map of "previously previous" node is not generated due to the following `last_position` check. I commented this out locally and the source map seems correct [evanw.github.io/source-map-visualization](https://evanw.github.io/source-map-visualization/#MTI2AGV4cG9ydCBmdW5jdGlvbiBnKCkgewoJbGV0IGEgPSAzOwoJbGV0IGIgPSA0OwoJcmV0dXJuIGEgKyBiOwp9CmV4cG9ydCBmdW5jdGlvbiBmKCkgewoJbGV0IHggPSAxOwoJbGV0IHkgPSAyOwoJcmV0dXJuIHggKyB5Owp9CjM3OQB7InZlcnNpb24iOjMsIm5hbWVzIjpbXSwic291cmNlcyI6WyJ0ZXN0LmpzIl0sInNvdXJjZXNDb250ZW50IjpbIlxuZXhwb3J0IGZ1bmN0aW9uIGYoKSB7XG4gICAgbGV0IHggPSAxO1xuICAgIGxldCB5ID0gMjtcbiAgICByZXR1cm4geCArIHk7XG59XG5leHBvcnQgZnVuY3Rpb24gZygpIHtcbiAgICBsZXQgYSA9IDM7XG4gICAgbGV0IGIgPSA0O1xuICAgIHJldHVybiBhICsgYjtcbn1cbiJdLCJtYXBwaW5ncyI6IkFBTUEsT0FBTyxTQUFTLElBQUk7Q0FDaEIsSUFBSSxJQUFJO0NBQ1IsSUFBSSxJQUFJO0FBQ1IsUUFBTyxJQUFJO0FBQ2Q7QUFURCxPQUFPLFNBQVMsSUFBSTtDQUNoQixJQUFJLElBQUk7Q0FDUixJQUFJLElBQUk7QUFDUixRQUFPLElBQUk7QUFDZCJ9)

https://github.com/oxc-project/oxc/blob/4ffa0982c7e9f1c448f47ed2aef56f64a373ff29/crates/oxc_codegen/src/sourcemap_builder.rs#L78-L81

I also compared with babel's codegen and they seem to also support such "swapping" pattern. I made a quick example here for babel https://github.com/hi-ogawa/reproductions/blob/main/babel-swap-source-map/src/repro.js

---

My actual use case in https://github.com/hi-ogawa/experiments/pull/47 is for the transform of inline server action and it needs to move closure to a top level function. For example, missing source map of `$$hoist_0` function looks like this [source-map-visualization](https://evanw.github.io/source-map-visualization/#MzYwAGxldCBjb3VudCA9IDA7CmV4cG9ydCBmdW5jdGlvbiBDb3VudGVyKCkgewoJY29uc3Qgb3V0ZXIxID0gMDsKCWNvbnN0IG91dGVyMiA9IDA7CglyZXR1cm4gewoJCXR5cGU6ICdmb3JtJywKCQlhY3Rpb246ICQkcmVnaXN0ZXIoJCRob2lzdF8wLCAnPGlkPicsICckJGhvaXN0XzAnKS5iaW5kKG51bGwsIG91dGVyMSwgb3V0ZXIyKQoJfTsKfQpleHBvcnQgZnVuY3Rpb24gJCRob2lzdF8wKG91dGVyMSwgb3V0ZXIyLCBmb3JtRGF0YSkgewoJY29uc3QgaW5uZXIgPSAwOwoJY291bnQgKz0gTnVtYmVyKGZvcm1EYXRhLmdldCgnbmFtZScpKTsKCWNvdW50ICs9IGlubmVyOwoJY291bnQgKz0gb3V0ZXIxOwoJY291bnQgKz0gb3V0ZXIyOwp9CjUxNgB7InZlcnNpb24iOjMsIm5hbWVzIjpbXSwic291cmNlcyI6WyJ0ZXN0LmpzIl0sInNvdXJjZXNDb250ZW50IjpbImxldCBjb3VudCA9IDA7XG5cbmV4cG9ydCBmdW5jdGlvbiBDb3VudGVyKCkge1xuICBjb25zdCBvdXRlcjEgPSAwO1xuICBjb25zdCBvdXRlcjIgPSAwO1xuXG4gIHJldHVybiB7XG4gICAgdHlwZTogXCJmb3JtXCIsXG4gICAgYWN0aW9uOiAoZm9ybURhdGEpID0+IHtcbiAgICAgIFwidXNlIHNlcnZlclwiO1xuICAgICAgY29uc3QgaW5uZXIgPSAwO1xuICAgICAgY291bnQgKz0gTnVtYmVyKGZvcm1EYXRhLmdldChcIm5hbWVcIikpO1xuICAgICAgY291bnQgKz0gaW5uZXI7XG4gICAgICBjb3VudCArPSBvdXRlcjE7XG4gICAgICBjb3VudCArPSBvdXRlcjI7XG4gICAgfVxuICB9XG59XG4iXSwibWFwcGluZ3MiOiJBQUFBLElBQUksUUFBUTtBQUVaLE9BQU8sU0FBUyxVQUFVO0NBQ3hCLE1BQU0sU0FBUztDQUNmLE1BQU0sU0FBUztBQUVmLFFBQU87RUFDTCxNQUFNO0VBQ047Q0FRRDtBQUNGIn0=)

**Comment by Boshen** [comment]
@underfin can you help me on this one.

**Comment by hi-ogawa** [comment]
Awesome, thanks for the fix!
I verified it's working as expected on v0.16.0 https://github.com/hi-ogawa/experiments/pull/52. Here is an updated version [sourcemap viz](https://evanw.github.io/source-map-visualization/#MzYwAGxldCBjb3VudCA9IDA7CmV4cG9ydCBmdW5jdGlvbiBDb3VudGVyKCkgewoJY29uc3Qgb3V0ZXIxID0gMDsKCWNvbnN0IG91dGVyMiA9IDA7CglyZXR1cm4gewoJCXR5cGU6ICdmb3JtJywKCQlhY3Rpb246ICQkcmVnaXN0ZXIoJCRob2lzdF8wLCAnPGlkPicsICckJGhvaXN0XzAnKS5iaW5kKG51bGwsIG91dGVyMSwgb3V0ZXIyKQoJfTsKfQpleHBvcnQgZnVuY3Rpb24gJCRob2lzdF8wKG91dGVyMSwgb3V0ZXIyLCBmb3JtRGF0YSkgewoJY29uc3QgaW5uZXIgPSAwOwoJY291bnQgKz0gTnVtYmVyKGZvcm1EYXRhLmdldCgnbmFtZScpKTsKCWNvdW50ICs9IGlubmVyOwoJY291bnQgKz0gb3V0ZXIxOwoJY291bnQgKz0gb3V0ZXIyOwp9CjYzNgB7InZlcnNpb24iOjMsIm5hbWVzIjpbIiJdLCJzb3VyY2VzIjpbInRlc3QuanMiXSwic291cmNlc0NvbnRlbnQiOlsibGV0IGNvdW50ID0gMDtcblxuZXhwb3J0IGZ1bmN0aW9uIENvdW50ZXIoKSB7XG5cdGNvbnN0IG91dGVyMSA9IDA7XG5cdGNvbnN0IG91dGVyMiA9IDA7XG5cblx0cmV0dXJuIHtcblx0XHR0eXBlOiBcImZvcm1cIixcblx0XHRhY3Rpb246IChmb3JtRGF0YSkgPT4ge1xuXHRcdFx0XCJ1c2Ugc2VydmVyXCI7XG5cdFx0XHRjb25zdCBpbm5lciA9IDA7XG5cdFx0XHRjb3VudCArPSBOdW1iZXIoZm9ybURhdGEuZ2V0KFwibmFtZVwiKSk7XG5cdFx0XHRjb3VudCArPSBpbm5lcjtcblx0XHRcdGNvdW50ICs9IG91dGVyMTtcblx0XHRcdGNvdW50ICs9IG91dGVyMjtcblx0XHR9LFxuXHR9O1xufVxuIl0sIm1hcHBpbmdzIjoiQUFBQSxJQUFJLFFBQVE7QUFFWixPQUFPLFNBQVMsVUFBVTtDQUN6QixNQUFNLFNBQVM7Q0FDZixNQUFNLFNBQVM7QUFFZixRQUFPO0VBQ04sTUFBTTtFQUNOLFFBUkY7Q0FnQkU7QUFDRDtBQVRTLGdCQVJWQSwwQkFRVyxVQUFhO0NBRXJCLE1BQU0sUUFBUTtBQUNkLFVBQVMsT0FBTyxTQUFTLElBQUksT0FBTyxDQUFDO0FBQ3JDLFVBQVM7QUFDVCxVQUFTO0FBQ1QsVUFBUztBQUNUIn0=)
