### ISSUE TITLE
feat(linter): eslint-plugin-unicorn/no-useless-undefined

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#3870]
To get started, run

```sh
just new-unicorn-rule no-useless-undefined
```

- [Rule docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v54.0.0/docs/rules/no-useless-undefined.md)
- [Rule source](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v54.0.0/rules/no-useless-undefined.js)

**Comment by jordan-boyer** [comment]
I'm trying to implement this rule but I have one problem. 

the eslint version strip some whitespace and I'm not sure if I should do it exactly the same or not. <

Example: 

```
function test() { return       undefined; } // --> eslint fix  function test() { return; }
```

It's seem to me that you don't plan to add rules like https://eslint.org/docs/latest/rules/no-irregular-whitespace should i just stip the undefined keyworld nothing else or should i do it like eslint ?

**Comment by Boshen** [comment]
Let's not worry about the whitespace.

But if you really want to give it a try, you can follow the implementation in its implementation, and you'll end up in https://github.com/sindresorhus/eslint-plugin-unicorn/blob/1deb9bb5edf27fdb2f656add11c924dfa59fdac9/rules/fix/replace-node-or-token-and-spaces-before.js
