### ISSUE TITLE
parser: finish parsing of `Modifiers`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3929]
https://github.com/oxc-project/oxc/blob/main/crates/oxc_parser/src/modifiers.rs

**Comment by DonIsaac** [comment]
Mind if I take this?

**Comment by Boshen** [comment]
@DonIsaac if you don't mind porting typescript code line by line ... I ended up porting because it was really hard to debug TypeScript parsing.

**Comment by DonIsaac** [comment]
@Boshen would mind if I add modifiers back to (at least some) AST nodes for checking purposes?

**Comment by Boshen** [comment]
> @Boshen would mind if I add modifiers back to (at least some) AST nodes for checking purposes?

We aren't that recoverable, so just emit them in the parser.

**Comment by Boshen** [comment]
> Ive spent two hours staring at this code, parse_modifers and typescript's implementation. When I try to use parse_modifiers where this function is consumed, I get an infinite loop over Kind::Const. I can't figure it out. Any insights?
