### ISSUE TITLE
transformer: React fast refresh transform

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3943]
Reference: 

* https://www.npmjs.com/package/@vitejs/plugin-react-swc
* https://github.com/facebook/react/blob/5b89d353e27a7ef07b40929f7343ebcc43bdaa58/packages/react-refresh/src/ReactFreshBabelPlugin.js
* https://github.com/pmmmwh/react-refresh-webpack-plugin
* https://mariosfakiolas.com/blog/what-the-heck-is-react-fast-refresh/

**Comment by Dunqing** [comment]
Based on internally discussed priorities for milestone2, I plan to start development of this plugin

**Comment by Boshen** [comment]
There are a few remaining issues but we'll close this issue for house keeping.
