### ISSUE TITLE
Oxlint -D all doesn't seem to trigger all rules - unclear documentation

### ISSUE THREAD

**Issue by bartekleon** [oxc-project/oxc#3944]
Did:
`npx oxlint -D all`
got: `Finished in 1.4s on 29 files with 243 rules using 16 threads.`
Apparently there should be 376 rules (according to https://oxc.rs/docs/guide/usage/linter/rules.html), so a lot seems to be is missing.

There is mismatch between https://oxc.rs/docs/guide/usage/linter/rules.html and https://github.com/oxc-project/oxc/issues/479

For example these are in rules, but in issues it doesn't say they are implemented
![image](https://github.com/oxc-project/oxc/assets/28489774/e56a6308-ea2c-4a8f-8f68-df257cf3ae73)

You write "The progress of all rule implementations is tracked https://github.com/oxc-project/oxc/issues/481."
So I assume rules on site is what You plan to implement, but this is just very misleading/confusing.

Maybe add another collumn on website with progress on the rules and add a counter on how many rules are implemented? Otherwise one need to look into ~10 issues to check which are implemented and which are not.

**Comment by dalisoft** [comment]
@bartekleon Try `npx oxlint -D all --import-plugin --jest-plugin --jsdoc-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin`
