### ISSUE TITLE
bug(parser): parse interface heritage clause as a `TSQualifiedName`

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#3963]
[playground link](https://oxc-project.github.io/oxc/playground/?code=3YCAAIAJgYCAgICAgIC3mMl9fWP2DOEtSy2TfSPTeIKYMRhuxke7z%2BZepTY%2FkK9iIuzvKjtn9KrXSlzo2QhSIKGAIirkHm7SO9BgfV6L8w7Dd%2B6DX00JZ%2FKz5dXwzTVFpo7o7Kr34w2%2FO1WQbZj6D7qNZe6drv0KuJ7GXvlGK5DinLpGmT4bm5XhThbnnBXP4Kyi9yiDpvRvwMN0Kj%2F%2Fx%2FcXyxG%2BA2rCTkQil1FlDDUv0POhX8tad6vvIrafdaq5gryWDz9%2FbYEUwA%3D%3D)
```ts
namespace A {
  interface B {
    
  }
}

class Foo extends A.B {}
//                ^^^
//                Parsed as StaticMemberExpression
interface Bar extends A.B {}
//                    ^^^
//                    Also parsed as StaticMemberExpression,
//                    but should be TSQualifiedName
type Baz = A.B
//         ^^^
//         Parsed as TSTypeReference -> TSQualifiedName
```

**Comment by Boshen** [comment]
https://astexplorer.net/ with @typescript/eslint shows `type Baz = A.B` is the only one parsed wrong here.

**Comment by Dunqing** [comment]
This may cause some trouble for resolve references
