### ISSUE TITLE
isolatedDeclaration The method following an abstract method gets dropped

### ISSUE THREAD

**Issue by MichaelMitchell-at** [oxc-project/oxc#4019]
Tested version: 0.16.3

```
require('oxc-transform').isolatedDeclaration('hello.ts', `
    export abstract class Foo {
        abstract foo(): void;
        bar(): void {}
        baz(): void {}
    }
`);
{
  sourceText: 'export declare abstract class Foo {\n' +
    '\tabstract foo(): void;\n' +
    '\tbaz(): void;\n' +
    '}\n',
  errors: []
}
```

Expected:
```ts
export declare abstract class Foo {
    abstract foo(): void;
    bar(): void {}
    baz(): void {}
}
```

Actual:
```ts
export declare abstract class Foo {
    abstract foo(): void;
    baz(): void {}
}
```

**Comment by Dunqing** [comment]
Thank you for reporting a series of bugs regarding `isolatedDeclarations`, are these bugs found in the public repo?

**Comment by MichaelMitchell-at** [comment]
> Thank you for reporting a series of bugs regarding `isolatedDeclarations`, are these bugs found in the public repo?

My company's codebase is private, but I've tried to reduce the bugs down to reproducible examples.

**Comment by Dunqing** [comment]
That’s fine. We're planning to include repos with `IsolatedDeclarations` enabled in the [monitor-oxc](https://github.com/oxc-project/monitor-oxc) to avoid any regression issues
