### ISSUE TITLE
[napi] Give access to ast

### ISSUE THREAD

**Issue by escaton** [oxc-project/oxc#4046]
Hello,

I'm newby in Rust and Napi, so the question might be incorrect (very).
How hard would it be to return the parsed ast of the program as an object instead of a JSON string?
I assume since the `Box` and `Vec` are serializable, they could be also transformed into napi-compatible objects?

I understand, that it is much better to walk the ast in Rust, but I'm thinking of replacing the parser in the existing JS tool.
So far I got these timings comparing `oxc.parseSync` with `JSON.parse(oxc.parseSync)` on 170loc TS file:
```
┌───────────────────────┬──────────┬────────────────────┬──────────┬─────────┐
│ Task Name             │ ops/sec  │ Average Time (ns)  │ Margin   │ Samples │
├───────────────────────┼──────────┼────────────────────┼──────────┼─────────┤
│ oxc                   │ 11,317   │ 88361.82420494797  │ ±0.65%   │ 1132    │
│ oxc with JSON.parse   │ 2,917    │ 342781.79109589255 │ ±0.85%   │ 292     │
└───────────────────────┴──────────┴────────────────────┴──────────┴─────────┘
```

And can't see how to use the speed of oxc parser in my case.

**Comment by Boshen** [comment]
Thank you for getting interested in this rabbit hole 😛. You may read about this topic in 
* https://dev.to/herrington_darkholme/benchmark-typescript-parsers-demystify-rust-tooling-performance-2go8
* https://github.com/oxc-project/oxc/issues/2409

**Comment by escaton** [comment]
Wow, it's really deep!
