### ISSUE TITLE
eslint-plugin-promise 

### ISSUE THREAD

**Issue by jelly** [oxc-project/oxc#4083]
This plugin is part of the `eslint-config-standard` so would be nice to have implemented.

https://github.com/eslint-community/eslint-plugin-promise

**Comment by jelly** [comment]
I've been working on this today, already implemeneted `valid-params`, `avoid-new` and `no-new-statics`

**Comment by Boshen** [comment]
Tracking in `https://github.com/oxc-project/oxc/issues/4655`
