### ISSUE TITLE
Incorrect binding types for `oxc-transform`

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4131]
Both `transform` and `isolatedDeclarations` functions should be exported
https://github.com/oxc-project/oxc/blob/cb1af043b8bd69fd34ccf2bf380ea09175ad5c53/napi/transform/index.d.ts#L56-L62

**Comment by Dunqing** [comment]
I had encountered the same issue before. Seems caused by upgrade `napi-derive` to `3.0.0-alpha.2`

**Comment by Boshen** [comment]
I had to run `pnpm run build` and commit the types https://github.com/oxc-project/oxc/pull/4133

**Comment by Dunqing** [comment]
> I had to run `pnpm run build` and commit the types https://github.com/oxc-project/oxc/pull/4133

Still incorrect😅
