### ISSUE TITLE
RFC: codegen AST related codes

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#4134]
## Requirements

* no build.rs published to the user
* all generated code are checked into git
* no nightly
* Rust code is source of truth, need to read parse `#[visited_node]`

## Workflow

* a user changes the oxc_crate
* a watch change picks it up
* parse all `#[visited_node]`
* saves them into a model, e.g. `struct ASTModel { name: String, attributes: Vec<Attributes> }`
* generate code and save file

## Code to generate

* `ASTKind` (Milestone 1)
* `GetSpan` (Milestone 2)
* `Hash`, `PartialEq` implementations (Milestone 3)
* `ASTBuilder` (Milestone 4)
* `Visit` (Milestone 5)
* `VisitMut` (Milestone 5)
* `Traverse`, remove current js code (Milestone 6)
* ~typescript definition for napi and wasm~ moving the scope to AST transfer.

Every milestone should be a stack of PRs, since they will involve changing other files as well.

---

## Things we need to discuss:

* Rust or JavaScript based code generation? `traverse` currently uses JavaScript, I think it's fine, but does it scale to supporting these many code patterns?

update: The consensus is stay with our current approach and parse `#[visited_node]` as the source of truth.  

## Topic not part of this RFC:

* Change or reduce AST visit patterns

**Comment by overlookmotel** [comment]
I've moved this issue to main oxc repo as we're currently working on this.

**Comment by Dunqing** [comment]
> > These visit functions are outdated
> 
> Outdated as in field visitation order is wrong?

or missing visits to some fields

**Comment by Boshen** [comment]
> These visit functions are outdated, do we have a better way to reimplement them here? It is now difficult to manually update
> 
> https://github.com/oxc-project/oxc/blob/2fd55b0da22c6c8af9ec23dca976c2b47e5957bb/crates/oxc_semantic/src/builder.rs#L454-L1650

Consensus was manually patch them, we eat our own 💩

**Comment by rzvxa** [comment]
It can be fine to have a slightly different visitation order for some implementations of our visits if it is necessary for them. The good thing about the generated code is that we have the correct walk order by default but it shouldn't prevent anyone from doing custom walks.
For example, a specific implementation might require visiting a statement and then visiting the decorators for it.

It is fine as long as we acknowledge the difference and know it has a reason to be that way.

**Comment by rzvxa** [comment]
or implement scope visit as a trait for our types so we can write `stmt.enter_scope(visitor)`.

**Comment by Dunqing** [comment]
We need a `visit_scope_id` method. This way we can easily set the `current_scope_id` for different ast `scope_id` in the semantic builder

**Comment by overlookmotel** [comment]
Could we pass the AST node (`&mut T`) into `enter_scope`? That would avoid need for adding `visit_scope_id` method.

**Comment by rzvxa** [comment]
> Could we pass the AST node (`&mut T`) into `enter_scope`? That would avoid need for adding `visit_scope_id` method.

I was thinking about this when I saw the @Dunqing's comment. But the type erasure will prevent us from doing anything useful to the `T`. Maybe we can implement a trait so this can be bound to something like `Scoped<T>`?

If we don't want to pass in T we can pass `AstType` + &mut node.scope_id

**Comment by overlookmotel** [comment]
> we can pass `AstType` + `&mut node.scope_id`

Maybe that's better. I think just `&node.scope_id` would do it. That removes need for generics (and only `&` is required, not `&mut`, since it's a `Cell`).

**Comment by rzvxa** [comment]
> That removes need for generics

I used `AstType` instead of `AstKind` for the same reason, but if we don't need it, then we shouldn't pass it in. I thought we may want to do some checking depending on the type we are entering but with scopeFlags, it should be enough information already.

> and only & is required, not &mut, since it's a Cell

This one I just forgot, You are absolutely right.

**Comment by Dunqing** [comment]
pass `scope_id` to `enter_scope` just enough for now

**Comment by rzvxa** [comment]
> pass `scope_id` to `enter_scope` just enough for now

It seems we all agree on this so I'll go ahead and implement it

**Comment by overlookmotel** [comment]
He done it! #4168
