### ISSUE TITLE
CI infrastructre for the `ast_codegen`

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#4138]
As mentioned in #3819 we need a CI workflow that would pick up on changes made in the `crates/oxc_ast/src/ast` and `tasks/ast_codegen/`, Build and run the `oxc_ast_codegen` binary and produce an error on any change after the fact.

For now, we can only check the `oxc_ast` crate for side effects but later on, we might want to generate code in different crates as well. At that point, we can use `git status` for fast comparison.

**Comment by Boshen** [comment]
What I ended up doing is - run the command and git diff 

https://github.com/oxc-project/oxc/blob/714bf1dd7f39eca7eef500039a617b093cfa591f/.github/workflows/ci.yml#L305

**Comment by rzvxa** [comment]
> What I ended up doing is - run the command and git diff
> 
> https://github.com/oxc-project/oxc/blob/714bf1dd7f39eca7eef500039a617b093cfa591f/.github/workflows/ci.yml#L305

Nice! So for this one, we should do something similar.
