### ISSUE TITLE
Rename and unpublish the `oxc_ast_macros`

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#4148]
It is currently a published crate but it should be an internal one instead. And right now we are calling these `oxc_ast_macros` which might make people think it does something.

In the process of unpublishing this crate, we can hit 2 birds with one stone by renaming it to something like `oxc_ast_codegen_markers`. This will show the actual purpose of the attribute while also distancing it from the [published crate](https://crates.io/crates/oxc_ast_macros) so we can call that one deprecated(maybe by releasing a README to the crates.io before deleting it from GitHub for good).

This renaming can also be handy if we would want to call our `ast` macro(#4112) something like `oxc_ast_macro`.

@oxc-project/core

**Comment by rzvxa** [comment]
I can't find the PR related to [this commit](https://github.com/oxc-project/oxc/commit/23b39169a67e38a811c129c6b1f22678984df23d), What where the reason for publishing it in the first place? possible future use cases?

**Comment by rzvxa** [comment]
I just had an idea, Maybe we can move the current content of this crate to `oxc_ast_codegen_markers` and use this crate for our actual "ast macros".

**Comment by Boshen** [comment]
It's in the dependency of the oxc_ast crate https://github.com/oxc-project/oxc/blob/e6c407d1c362e3bb9f010b9c840d0c65d2ee2cdf/crates/oxc_ast/Cargo.toml#L21-L23

**Comment by Boshen** [comment]
This is an unfortunate Cargo problem where proc macros has to go into a crate, and the crate has to be published to be used.

I'll close this as not planned for now, don't really wanna touch these until things are stable 😅

**Comment by rzvxa** [comment]
@Boshen Oh sorry I wasn't aware of this limitation of cargo.

With all that said, Shall we move the markers to their own crate and reuse this one for our AST template macros?
Last night I did a simple benchmark on our cold build and our markers only add %0.14 to the build time. If we add anything but markers to this crate it would unnecessarily slow down the pure `oxc_ast` build time. We have to either move the markers to their own crate or feature-gate them to only run when the `oxc_ast_codegen` is parsing them.

With the latter, we might be able to avoid publishing the markers but It is just too hacky for my liking.

**Comment by Boshen** [comment]
Let's wait until all ast codegen features are complete before moving things around.

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/backlog/issues/53 will require macros which do actually do something (not just markers). As discussed, we intend to make those macros as cheap on compile time as we can, but they won't be a cheap as the current no-op markers are. I'm not sure if that changes things re crate organisation.

I also wasn't aware that proc macro crates have to be published.
