### ISSUE TITLE
Optimize unresolved references in semantic

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4169]
#4162 boosted perf of semantic by turning `unresolved_references` into a stack.

I think we can potentially do even better. From https://github.com/oxc-project/oxc/pull/4162#issuecomment-2220267268:

What I had in mind is that you never call `unresolved_references.pop()`. Instead, hold on to the hash map and re-use it. That way we avoid generating (and allocating) new hash map when entering a scope most of the time.

`unresolved_references` is `Vec<UnresolvedReferences>`, indexed by *scope depth*.

e.g. with this input:

```js
function foo() {}
function bar() {}
```

* Enter top level scope:
  * Depth is 0.
  * Push a `UnresolvedReferences` hash map to `unresolved_references`.
  * Current hashmap is `unresolved_references[0]`.
* Enter scope for `foo`:
  * Increment depth to 1.
  * Push another `UnresolvedReferences` hash map to `unresolved_references`.
  * Current hashmap is `unresolved_references[1]`.
* Exit scope for `foo`:
  * Clear current hashmap (`unresolved_references[1]`).
  * Decrement depth to 0.
  * Do NOT pop from `unresolved_references`.
  * Current hashmap is now `unresolved_references[0]`.
* Enter scope for `bar`:
  * Increment depth to 1.
  * Do NOT push to `unresolved_references`.
  * Current hashmap is `unresolved_references[1]` (i.e. reuse same hash map that was used for `foo`)
 * Exit scope for `bar`: same as for `foo`
 * Exit top level scope: same
 
I *think* this would be a further perf boost due to reducing allocations, and reusing allocations which are already warm in the cache.

cc @lucab (though no obligation on you to do this)

**Comment by Boshen** [comment]
Hashing into `UnresolvedReferences` remains the slower part of the pipeline. Are there any other improvements can be made before storing the hash value inline?

<img width="1511" alt="image" src="https://github.com/oxc-project/oxc/assets/1430279/699306a9-603c-4cbd-bfaa-e549611d09c7">
<img width="1518" alt="image" src="https://github.com/oxc-project/oxc/assets/1430279/88caabf9-4ae6-420e-a409-c3a5b8f77ba0">


(I'm currently working on the mangler, which involves rebuilding the symbol and scope tree again.)

**Comment by overlookmotel** [comment]
> Are there any other improvements can be made before storing the hash value inline?

Very likely yes. See point 7 on https://github.com/oxc-project/backlog/issues/32 (I only added it earlier this week).

We should certainly be able to reduce hashing, but I don't know the internals of the hashmap we're using well enough to say best way to do it. We may not even need to store the whole hash, maybe just the top 7 bits of it (if it's a SwissTable-style hashmap).

**Comment by overlookmotel** [comment]
Fixed in #4213.
