### ISSUE TITLE
ast-codegen: visit `it.body.body` or`it.body` in CatchClause?

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4186]
### CatchClause 
https://github.com/oxc-project/oxc/blob/07506ece83e7101f618093afa74be23babfc58c3/crates/oxc_ast/src/ast/js.rs#L1307-L1313

### In semantic builder:
https://github.com/oxc-project/oxc/blob/07506ece83e7101f618093afa74be23babfc58c3/crates/oxc_semantic/src/builder.rs#L1351-L1363

### In `Visit`
https://github.com/oxc-project/oxc/blob/07506ece83e7101f618093afa74be23babfc58c3/crates/oxc_ast/src/generated/visit.rs#L3691-L3707

The difference between them is that one calls `visit_statements(it.body.body)` and the other `visit_block_statements(it.body)`

Because we will create a scope within the `CatchClause`, we do not need to create a scope again in the `BlockStatement`.

Is there a better way to resolve this problem? Such as changing the `body` to `Vec<'a, Statements<'a>> `

**Comment by Dunqing** [comment]
@rzvxa @Boshen cc

**Comment by rzvxa** [comment]
I think the bigger question here is that do we want the block in a catch clause to be processed as its own thing or a dedicated block. I went with this because it makes more sense to visit the catch block on `visit_block_statement`. If it isn't the desired outcome we can change it to `Vec<'a, Statements<'a>>` as @Dunqing has suggested.

**Comment by rzvxa** [comment]
Oh sorry I just saw your edit, Let me reconsider my answer and reach back to you.

**Comment by Boshen** [comment]
I'm not sure about this one either, spec wants two scopes here 🤔 

https://tc39.es/ecma262/#sec-runtime-semantics-catchclauseevaluation

**Comment by Dunqing** [comment]
> I'm not sure about this one either, spec wants two scopes here 🤔
> 
> https://tc39.es/ecma262/#sec-runtime-semantics-catchclauseevaluation

I took a look at [boa](https://github.com/boa-dev/boa/blob/5b1621abd2b702b99bd6b4491973095f9b27c362/core/engine/src/bytecompiler/statement/try.rs#L111-L143). Yes, you are right. I think I know what to do.

**Comment by Dunqing** [comment]
Leave this issue to me. I'll fix this according to the spec.
