### ISSUE TITLE
CI: Run tests regardless of lint, formatting and cargo check.

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#4233]
Originally suggested by @Sysix in the [Discord](https://discord.com/channels/1079625926024900739/1117322804291964931/1261059283525832825)

> 2: When question one is valid, why are my Test Pipeline failing because of the lint? It has its own pipeline 🙂 

It also has prevented me - and I'm sure other contributors - from running tests when the code is dirty and in the early stages. It is not a blocking issue but just an annoying one.

**Comment by Boshen** [comment]
On CI or local development?

**Comment by rzvxa** [comment]
On CI, We already check lint and fmt on separate required steps. We can just add cargo check as its own step and let the tests run on PRs regardless of those.

We already allow conformance tests to run either way so why not also allow the unit tests to run? After all, those take way less time and would be done in a shorter time than the conformance.

Does cargo check rely on the target OS for valid results? Because as it is right now, we run cargo checks 3 times(once per target OS). Maybe we can run it once with the lint to prevent yet another rust setup while reducing 2 extra runs.

`cargo ck --all --all-targets`

I know you did a lot of try and error with CI to speed it up, Have you ever considered doing this before? I won't be surprised if it were this way before and you had to change it for a good reason which I'm missing here.

**Comment by Boshen** [comment]
The steps are together so we can create a warm cache on the main branch.

I also want to keep the total number of jobs down so we don't wait for queued jobs - splitting out the check step would create another 3 jobs.

I suggest everyone run `just r` before commit to save some bandwidth.
