### ISSUE TITLE
ast-codegen: support `#[visit(enter_before)]` attribute

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4240]
We have discussed this at https://github.com/oxc-project/oxc/pull/4147#issuecomment-2220216905. But we do need this at the moment.

In semantic builder, We need `enter_scope` before `enter_node` in `visit_function` and `visit_class`.

https://github.com/oxc-project/oxc/blob/2eb37d52f1250dfc1348379cbf9d3fb3c70b7961/crates/oxc_semantic/src/builder.rs#L1423-L1450

We want to treat `FunctionExpression` and `FunctionDeclaration` differently and the class is the same too.

**FunctionExpression**: create a binding for function `id` to the current scope
**FunctionDeclaration**: create a binding for function `id` to the parent scope

To add the binding to the parent scope, we must need `enter_scope` before `enter_node`.

I tried another way to get around it (Same as `TypeScript`). But I find it a bit confusing. See: https://github.com/oxc-project/oxc/pull/4195#pullrequestreview-2175953763

**Comment by Dunqing** [comment]
Ah. Haha, this is also a bit confusing for visit orders.  I thought about it again. We can defer binding `FunctionExpression` and `ClassExpression` and bind them when we visit `BindingIdentifier`.

**Comment by overlookmotel** [comment]
@Dunqing Just to throw in my 2 cents, I wonder if `FunctionExpression` and `FunctionDeclaration` should be separate types (and each type would have `Function` as a field within it). The 2 have various significant differences:

1. One is a `Statement`, the other an `Expression`.
2. `FunctionExpression`'s `name` field should be an `Option`, whereas it's compulsory in `FunctionDeclaration`.
3. Scope should be entered before `name` for `FunctionExpression` and after name for `FunctionDeclaration`.

We could also have a separate type for `ObjectMethod` (whose `name` isn't a binding at all).

At present, it's possible to create non-sensical AST nodes (e.g. a `FunctionDeclaration` with no name) - it'd be good to make this impossible through the type system.

**Comment by Dunqing** [comment]
> @Dunqing Just to throw in my 2 cents, I wonder if `FunctionExpression` and `FunctionDeclaration` should be separate types (and each type would have `Function` as a field within it). The 2 have various significant differences:
> 
> 1. One is a `Statement`, the other an `Expression`.
> 2. `FunctionExpression`'s `name` field should be an `Option`, whereas it's compulsory in `FunctionDeclaration`.
> 3. Scope should be entered before `name` for `FunctionExpression` and after name for `FunctionDeclaration`.
> 
> We could also have a separate type for `ObjectMethod` (whose `name` isn't a binding at all).
> 
> At present, it's possible to create non-sensical AST nodes (e.g. a `FunctionDeclaration` with no name) - it'd be good to make this impossible through the type system.

Yes, I talked with @Boshen about the above. Since they are not very different, they have been combined into one type. I agree we should have different types for `FunctionExpression` and `FunctionDeclaration`, and also class should be `ClassExpression` and `ClassDeclaration`

> 3. Scope should be entered before `name` for `FunctionExpression` and after name for `FunctionDeclaration`.

We bind in `enter_node`. So we have to switch the order of `enter_node` and `enter_scope` to bind it to the corresponding scope. Or do something like https://github.com/oxc-project/oxc/pull/4195#discussion_r1676863076.
