### ISSUE TITLE
Enter node before scope for all types in semantic

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4276]
We recently changed `Visit` to call `enter_node` before `enter_scope` (#4203).

This change is mostly also reflected in `SemanticBuilder`'s `Visit` method overrides, but a few still have `enter_scope` before `enter_node`. These are:

* `visit_for_statement`
* `visit_for_in_statement`
* `visit_for_of_statement`

We should alter them to align with `Visit`'s default behavior, to avoid surprise.

**Comment by overlookmotel** [comment]
@Dunqing Do you think this would break anything?

**Comment by Dunqing** [comment]
> @Dunqing Do you think this would break anything?

I don't think this will break anything, I just forgot about them. Could you leave it to me? I will finish this after #4253 is merged.

**Comment by overlookmotel** [comment]
Fixed in #4347.
