### ISSUE TITLE
consider remove `import_kind` for TSImportEqualsDeclaration

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4291]
AST is:
https://github.com/oxc-project/oxc/blob/c66e025df966c966c99a8dac31cce0a961364453/crates/oxc_ast/src/ast/ts.rs#L1082-L1088

Will throw an error for `import type A = B` in [TypeScript](https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBDAnmApnAgnAvHAQgbiA)

**Comment by overlookmotel** [comment]
@Dunqing Is the rationale for this along the lines of https://github.com/oxc-project/backlog/issues/28?

**Comment by Dunqing** [comment]
> @Dunqing Is the rationale for this along the lines of [oxc-project/backlog#28](https://github.com/oxc-project/backlog/issues/28)?

Yes, but this also needs to throw the same error as `TypeScript`

**Comment by armano2** [comment]
`TSImportEqualsDeclaration` is used for special syntax that typescript offers

https://www.typescriptlang.org/docs/handbook/2/modules.html#es-module-syntax-with-commonjs-behavior

```
import type A = require('B')
import A = require('B')
```

**Comment by Dunqing** [comment]
Thanks for your pointing out that `import require`!
