### ISSUE TITLE
refactor: store error codes in `OxcDiagnostic`

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4333]
Instead of inlining error codes into messages (e.g. `eslint(eqeqeq): use '===' instead of '=='`), they should be stored separately.
This will let us
- configure codes automatically for lint rules
- support hyperlinks in the future

## Tasks
First, change `OxcDiagnosticInner` from
```rust
pub struct OxcDiagnosticInner {
    pub message: Cow<'static, str>,
    pub labels: Option<Vec<LabeledSpan>>,
    pub help: Option<Cow<'static, str>>,
    pub severity: Severity,
}
```

To:
```rust
pub struct OxcDiagnosticInner {
    pub message: Cow<'static, str>,
    pub labels: Option<Vec<LabeledSpan>>,
    pub help: Option<Cow<'static, str>>,
    pub severity: Severity,
    pub code_scope: Option<Cow<'static, str>>, // eg `eslint`
    pub code_num: Option<Cow<'static, str>>,   // eg `eqeqeq`
}
```

Next, update `LintContext` to set `code_scope` and `code_num` before running a rule.

Finally, update all lint rule diagnostics to remove their inlined error codes.

**Comment by mysteryven** [comment]
> - configure codes automatically for lint rules

Could you explain more about this? 🤔
