### ISSUE TITLE
Parser accepts function declaration as the sole statement of in strict mode

### ISSUE THREAD

**Issue by aapoalas** [oxc-project/oxc#4359]
This code ([Playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIAQgICAgICAgICRncrm5BJ12ajhv4guQbbA5tHj8LFfzUn14pS0WHVixkSaDgKUrkRydT4YHU4S4vi%2ByKeqHoGsJakBVLfKl2LH63%2FsEU5rL4Uhop6zpwN%2Fn38PPmCA)) has 4 syntax errors:
```js
for (var x of []) function a() {}
for (var x of []) foo: function b() {}
if (true) function c() {}
if (true) foo: function d() {}
```
Labeled function statement as the sole statement in if / for is always a syntax error (except maybe with [B.3.1](https://tc39.es/ecma262/#sec-labelled-function-declarations)?).

The third line is a syntax error in strict mode.

None of these produce a syntax error in oxc, regardless of any `"use strict";` directives.

**Comment by Boshen** [comment]
Same answer as https://github.com/oxc-project/oxc/issues/4360#issuecomment-2238869728

https://github.com/oxc-project/oxc/blob/729b288c5d461318ce7a7bcecf1691934c782b1b/crates/oxc_semantic/src/checker/javascript.rs#L489-L502

**Comment by aapoalas** [comment]
Hmm, I guess we have to do these checks on our own. Maybe. On one hand we do need full semantic analysis, but on the other hand we probably don't want front-load it but would rather do it while we build the bytecode... Oh well, problems problems.

**Comment by Boshen** [comment]
> Hmm, I guess we have to do these checks on our own. Maybe. On one hand we do need full semantic analysis, but on the other hand we probably don't want front-load it but would rather do it while we build the bytecode... Oh well, problems problems.

I agree this is a dilemma of where the checks should go, in the name of performance :-(
