### ISSUE TITLE
transformer: non-type-only import is only referenced by the type, but is not eliminated.

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4423]
`esbuild` handles this case correctly. [esbuild repl](https://esbuild.github.io/try/#dAAwLjIzLjAALS1sb2FkZXI9InRzIgBpbXBvcnQgeyBUIH0gZnJvbSAnbW9kJwoKbGV0IFQ6IFQgPSAwOwoKZXhwb3J0IHsgVCB9)

[OXC Playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIC0gICAgICAgIC0G8rnONK89IyoDqjbUICdKXoMpBISB7xGkDo%2BNmF8NIvulUd%2BRBA8LzlwlZxs4l9%2FO3IAgA%3D%3D)

### In 
```ts
import { T } from 'mod'
let T: T = 0;
export { T }
```
### Out

```js
import { T } from "mod";
let T = 0;
export { T };
```

### Expected

```js
let T = 0;
export { T };
```

**Comment by 7086cmd** [comment]
By the way, when the `type` keyword is used in an import statement, the value `T` is not exported as expected.

#### Input Code

```javascript
import type { T } from 'mod';

let T: T = 0;

export { T };
```

#### Output Code

```javascript
let T = 0;
export {};
```

#### Expected Output

```javascript
let T = 0;
export { T };
```

---

I am investigating this issue to enhance the understanding and functionality of `oxc`. Nevermind for better solutions :)

**Comment by Dunqing** [comment]
> May I try it? I am going to investigate this issue to enhance the understanding and functionality of `oxc`. Nevermind for better solutions :)

Go for it!

**Comment by Dunqing** [comment]
I came up with a solution to this problem. We need to check if the next value binding definition has a value reference before defining it. If it doesn't, we can safely remove the import.

To make it possible, we need to add `SymbolFlags` in
 
https://github.com/oxc-project/oxc/blob/2c431cb89b5e20a44977c622a4b55b9394fa800d/crates/oxc_semantic/src/symbol.rs#L43-L45 

This could help us to find if it is a value symbol or a type symbol from `redeclarations` 

Also, Since the transformer doesn't have a whole `Semantic`, so we can't get the reference's span by `Semantic`. So I'm going to revert https://github.com/oxc-project/oxc/pull/4464.

@overlookmotel Can you confirm this for me?

**Comment by overlookmotel** [comment]
I'm not familiar with the changes you've made over past few weeks to resolve TS type references. But I'd have assumed could figure out that can remove `import { T } from 'mod';` without needing to figure out `Span`.

But, given that I don't understand how it's working now, I could well be wrong.

I don't object if you want to revert #4464. Really I didn't want to be making changes to `Semantic` until I've finished my "review". Mainly I made that PR just to *inform* that review - to research how much perf boost we can get by reducing the size of `Semantic`'s structures.

**Comment by magic-akari** [comment]
It's hard to verify; consider this situation.

```TypeScript
export class T {}
```

In this situation, the value of T and its type have been exported. 
I believe that only a comprehensive type analyzer like TSC can solve this problem. 
Or a bundle tool like esbuild, which can analyze across files, thereby eliminating intermediate values.

**Comment by magic-akari** [comment]
Oh, I misunderstood, this is about the issue of name resolution.

**Comment by Dunqing** [comment]
After digging deeper into how `TypeScript` handles this, I realized that we don't need to make any changes to what I said above! Sorry to bother you @overlookmotel

**Comment by DonIsaac** [comment]
@Dunqing can we close this?
