### ISSUE TITLE
bug(semantic): incorrect parents for `ArrayAssignmentTarget`

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4435]
Consider the following JS snippet:
```js
let _a, b;
foo.forEach(item => {
	[_a, b] = item;
	doSomething(b);
});
```

When the AST is viewed on the [playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIDGgICAgICAgIC2mcpqpbutXC+Uf72ne1SDCJK4Tn++NlLltohMrXmjZqTqJg1QwG6pQhU2rkclTIa8/2PwyR/FKLiP+NUxD23V6F5UHPN/ezQkgA%3D%3D), `_a` is in the (seemingly) expected node:

https://oxc-project.github.io/oxc/playground/?code=3YCAAIDGgICAgICAgIC2mcpqpbutXC+Uf72ne1SDCJK4Tn++NlLltohMrXmjZqTqJg1QwG6pQhU2rkclTIa8/2PwyR/FKLiP+NUxD23V6F5UHPN/ezQkgA%3D%3D

However, when I get a reference to `_a` and iterate through its parents like so:
```rust
// here, `reference` is the restructured write on _a (the only reference _a has)
for parent in self.nodes().iter_parents(reference.node_id()) {
    println!("{:#?}", parent.kind().debug_name());
}
```

I get this output:
```
"IdentifierReference(_a)"
"SimpleAssignmentTarget"
"AssignmentTarget"
"AssignmentTarget"
"AssignmentExpression"
"ExpressionStatement"
"FunctionBody"
"ArrowFunctionExpression"
"Argument"
"CallExpression"
"ExpressionStatement"
"Program"
```

**Comment by Dunqing** [comment]
I cannot reproduce it in your provided playground.
<img width="734" alt="image" src="https://github.com/user-attachments/assets/e5479802-76a9-4cc1-9759-b5f76643060b">

**Comment by Dunqing** [comment]
> I get this output:
> 
> ```
> "IdentifierReference(_a)"
> "SimpleAssignmentTarget"
> "AssignmentTarget"
> "AssignmentTarget"
> "AssignmentExpression"
> "ExpressionStatement"
> "FunctionBody"
> "ArrowFunctionExpression"
> "Argument"
> "CallExpression"
> "ExpressionStatement"
> "Program"
> ```

Which AST is unexpected?

**Comment by DonIsaac** [comment]
_a's parent shouldn't be a simple assignment target, it should be an array pattern target.

**Comment by Dunqing** [comment]
> _a's parent shouldn't be a simple assignment target, it should be an array pattern target.

I get it. That's because we don't have `AstKind::ArrayAssigmentTarget`

**Comment by Boshen** [comment]
We can try adding these back https://github.com/oxc-project/oxc/blob/e3b0c4066af6fb81ab66497ccce57c793390e65a/tasks/ast_codegen/src/generators/ast_kind.rs#L22
