### ISSUE TITLE
bug(semantic): non-last expression in sequence counted as a read

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4437]
```js
let x = 0; foo = (x++, 0)
//                ^
```
This `Reference` has `Read | Write` flags, but it should only have `Write`.

**Comment by overlookmotel** [comment]
Related to #3326.

**Comment by Dunqing** [comment]
I agree with what @overlookmotel said

**Comment by Dunqing** [comment]
If you can provide more examples, we will be happy to think more about it!

**Comment by DonIsaac** [comment]
I can make no-unused-vars work around it, we can treat this as expected behavior
