### ISSUE TITLE
bug(semantic): references on `MemberExpression` not recorded

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4446]
```ts
enum Foo { // <- foo creates a scope, just like a namespace
  A        // <- has a symbol (SymbolFlags::EnumMember)
}

// Foo has a reference, but A does not
console.log(Foo.A) 
```

> (edit: it appears playground links are broken. When I go to copy a playground URL for this snippet, it takes me to the playground with the default react component snippet)

**Comment by armano2** [comment]
enums are special

```ts
const imOutside = 2;
const b = 2;
enum Foo {
  outer = imOutside, // 2
  a = 1, // 1
  b = a, // 1 - it shadows b from outside of enum
  c = b, // c == Foo.b == Foo.c == 1
}
```

**Comment by overlookmotel** [comment]
I agree with @armano2 that the property of a `MemberExpression` should not be a reference (i.e. the `A` in `Foo.A`).

But the issue of what is a symbol is trickier.

In one sense `A` inside the `enum` is a symbol. But it doesn't quite map cleanly onto the usual scopes concept. e.g.:

```ts
const A = 123;
enum X {
    A = 1,
    B = A, // refers to `A = 1`
}
enum X {
    C = A, // refers to `A = 1`
}
```

[TS playground](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAgjAvDAjAJgMwG4BQBTMAVwFsYANGAbxxlviVQBoa6AhBuRmAem5gCc8AMzz8IMKCBgADBMhTScAX3xFSFanRgBhDl14Dho8ZJlzUilUA)

If we're treating `A` in `enum X` as a symbol, then that symbol should also be bound inside the body of the *second* `enum X`.

@armano2 How does `typescript-eslint` handle this case?

I think we probably *do* need it to be a symbol to make this kind of thing tractable:

 ```ts
const A = 123;
enum X {
    A = 1,
    B = A, // refers to `A = 1`
}
enum X {
    C = A, // refers to `A = 1`
    D = (() => {
      enum Y {
        Q = A, // refers to `A = 1`
      }
      return Y.Q;
    })(),
}
```

We don't seem to be getting this quite right at present: [Oxc playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIBYgICAgICAgICxG0qZRraXmvwwyjjIOyK%2FSdJ88UgUlv5LwN5U97gda1UYCca%2FeyoKZHGdrCkxAdkIe6V3AP3yqGvaPbSEoohsBUQvcu6KD1ogYqFlUCdt9ni9h%2BOBzo38K8PE%2B0A7HwAGqwgPhyvvRIG9RzXaLB9%2F7EbAgA%3D%3D)


[TS playground](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAgjAvDAjAJgMwG4BQBTMAVwFsYANGAbxxlviVQBoa6AhBuRmAem5gCc8AMzz8IMKCBgADBMhTScAX3xFSFanRgBhDl14Dho8ZJlzUirQBEGAClsBKJAD4qLLQRIwAmm61aART0ePkERMQkpWQYFdzoVf0MoQn4wHwA6ANwtJQdHZhUgA)

**Comment by armano2** [comment]
we are ignorign this case, and we are "marking" all references in enum's as already in use

https://github.com/typescript-eslint/typescript-eslint/blob/e239e0cca073e93873d146e5e7a74aef91a00f31/packages/eslint-plugin/src/rules/no-unused-vars.ts#L519-L529

**Comment by DonIsaac** [comment]
I agree that `no-unused-vars` should ignore this case. I'm hoping to add class/object/interface/etc members to the symbol table later, but that can be for a later time. I'll close this issue.
