### ISSUE TITLE
bug(semantic): Incorrect `ScopeId` for IIFEs

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4452]
See [this test case](https://github.com/oxc-project/oxc/blob/4dc0a4499dc4e36423c793b309fb19f230a8bf87/crates/oxc_semantic/tests/integration/scopes.rs#L161) for a reproduction

```ts
function foo()
```
In this following scope ids are equal:
- the root scope id
- `AstNode::scope_id()`, when called on foo's declaration node
- `SymbolTable::get_scope_id()`, when called with foo's `SymbolId`

Now, consider this snippet:
```ts
(function foo() {})()
```
Here, the following scope ids are equal
- the root scope id
- `AstNode::scope_id()`, when called on foo's declaration node
However, the symbol id obtained from `SymbolTable::get_scope_id()` is not the same as the other two.

I'm not certain what expected behavior here is, whether foo should be considered in the root scope or not, but the scope id for its AstNode and for the Symbol should definitely be the same.

**Comment by Dunqing** [comment]
This is expected behavior. The main difference here is between `FunctionDeclaration` and `FunctionExpression`. I explained in https://github.com/oxc-project/oxc/issues/4240#issue-2406562859

**Comment by DonIsaac** [comment]
Oh boy that's confusing haha

Any chance we could write that down somewhere?

**Comment by Dunqing** [comment]
> Oh boy that's confusing haha
> 
> Any chance we could write that down somewhere?

Maybe we should write down what the `ScopeFlags` are for each of the different `SymbolFlags`?

**Comment by overlookmotel** [comment]
As mentioned in https://github.com/oxc-project/oxc/issues/4240#issuecomment-2227051744, I feel we should have separate types `FunctionDeclaration` and `FunctionExpression`. I think this would make it less confusing.
