### ISSUE TITLE
bug(semantic): Export equals declaration not counted as a `Read` reference

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4488]
> Found by #4445
Correct, counts as a `Reference::Read`
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/8aa1103a-88c4-4fab-9442-bdf74667fa69">

Incorrect, does not count as a `Reference::Read`
```ts
type Foo = number
export = Foo
```
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/9d7f9361-2402-4770-a414-532ff1b55407">

**Comment by Dunqing** [comment]
```ts
type Foo = number
export { Foo }
```

In this example. The `foo` flagged as `ReferenceFlags::Read` and `ReferenceFlags::Type`. Do you think we should just flag `foo` as `ReferenceFlags::Type`?

**Comment by Dunqing** [comment]
> ```ts
> type Foo = number
> export { Foo }
> ```
> 
> In this example. The `foo` flagged as `ReferenceFlags::Read` and `ReferenceFlags::Type`. Do you think we should just flag `foo` as `ReferenceFlags::Type`?

It would be better if we only flagged it as `ReferenceFlags::Read`, We can determine `Foo` is not a type symbol by `ReferebceFlags`. That would be useful for fixing #4504

**Comment by DonIsaac** [comment]
What if it's not a type? Shouldn't `export =` compile to `module.exports =`? Or is it only used in type declarations?

**Comment by Dunqing** [comment]
> What if it's not a type? Shouldn't `export =` compile to `module.exports =`? Or is it only used in type declarations?


Both value and type declarations can be referenced.
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/bce6fede-f125-4317-9525-2d0070eeaccf">

**Comment by DonIsaac** [comment]
Closing this as it seems resolved.
