### ISSUE TITLE
bug(semantic): `typeof` operator on type imports not counted as a reference

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4494]
> Part of #4445. Found by @camc314.

```ts
import type { mySchema } from './my-schema';
function test(arg: ReturnType<typeof mySchema>) {
  //                          ^^^^^^^^^^^^^^^ should be a `Type` reference
    arg;
}
test('');
```

Note that non-type imports work as expected:
```ts
import { mySchema } from './my-schema';
function test(arg: ReturnType<typeof mySchema>) {
    arg;
}
test('');
```
## Screenshots

Incorrect:
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/6fd6d212-078b-44d7-8b4e-5aed48baa95a">
Correct:
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/b805cffd-af1d-4e3c-a3b5-e41cbc501682">

**Comment by Dunqing** [comment]
This usage looks weird, but typescript supports it, and so must we.
