### ISSUE TITLE
ast: IdentifierReference's reference_flag is always empty

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4512]
SemanticBuilder's already resolved reference usage but never doesn't set `reference_flag` for IdentifierReference.

Although we can get `reference_flag` by `reference_id`, would be great if we could directly `reference_flag`.

**Comment by Dunqing** [comment]
> SemanticBuilder's already resolved reference usage but never doesn't set `reference_flag` for IdentifierReference.

I know the reason now. We can only get the immutable `IdentifierReference` from `AstKind`, so we can't change the `reference_flag`. In this way, we need to change `reference_flag: ReferenceFlag` to `reference_flag: Cell<ReferenceFlag>`

**Comment by overlookmotel** [comment]
Agreed, it should be `Cell<ReferenceFlag>`. Or do we remove it entirely from `IdentifierReference`? Or remove it from `Reference`? It doesn't really need to be in 2 places does it?

**Comment by Dunqing** [comment]
> make transformer/minifier more complex to have to update in 2 places when flags get changed.

Yes! It is better to remove `reference_flag` from `IdentifierReference`

**Comment by overlookmotel** [comment]
> Yes! It is better to remove `reference_flag` from `IdentifierReference`

I agree that's the better one to remove. It makes more sense for that info to be stored in `Reference`.

Annoyingly, removing `reference_flag` from `IdentifierReference` doesn't save any bytes in AST, as that type has excess padding anyway. Whereas removing it from `Reference` would reduce size of `Reference` by 4 bytes.

But still, in my view it's more important that our data structures make logical sense, than that we've optimized every last drop out of them.

**Comment by overlookmotel** [comment]
Closed in #5077.
