### ISSUE TITLE
crates/oxc_traverse/tests/compile_fail.rs takes too long to test

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#4537]
https://github.com/oxc-project/oxc/actions/runs/9161427480/job/25186250402

test compile_fail ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 17.59s

It went through a build process 🤔 

Finished `dev` profile [unoptimized + debuginfo] target(s) in 17.14s

So this test takes 17 seconds in total on windows CI.

**Comment by overlookmotel** [comment]
Fixed in #4538.
