### ISSUE TITLE
Introduce `span_mut` for `GetSpan`

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#4606]
There's situiation that we need turn a identifier `a` into various form depend on the conditions. And we want to apply the `span` of  `a` to the final form. The current solution make it complex to do it.

```rust
let span_of_a = a.span;
let expr = if rewrite_to_member_expr {
  member_expr!(a, SPAN)
} else {
  a
 }
let expr = if is_callee {
  member_expr_again!(expr, SPAN)
} else {
  expr
};

expr.span = span_of_a;
```

You will see we have to apply the `span` of `a` in the end, otherwise the sourcemap might be wrong, which is caused by nested ast nodes have the same span. I guess this is allowed maybe? But it's doesn't generate accurate sourcemap.

**Comment by overlookmotel** [comment]
I don't see any reason why we couldn't add this, and it wouldn't be too hard to do.
