### ISSUE TITLE
`npx oxlint@latest` returns npm error

### ISSUE THREAD

**Issue by steadily-worked** [oxc-project/oxc#4661]
for me, current version was not `@0.7.0`. So i tried to run `npx oxlint@latest` and tried to update by pressing `y`. But it returned npm error like below.
So, I solved the problem by accessing the `.npm` and deleting the `_npx` file.
However, I don't think this was intended, so I'm opening an issue.

```sh
Need to install the following packages:
oxlint@0.7.0
Ok to proceed? (y) y

npm error code ENOTEMPTY
npm error syscall rename
npm error path /Users/steadily-worked/.npm/_npx/f4a33d9b4519ccab/node_modules/oxlint
npm error dest /Users/steadily-worked/.npm/_npx/f4a33d9b4519ccab/node_modules/.oxlint-ACwWByF5
npm error errno -66
npm error ENOTEMPTY: directory not empty, rename '/Users/steadily-worked/.npm/_npx/f4a33d9b4519ccab/node_modules/oxlint' -> '/Users/steadily-worked/.npm/_npx/f4a33d9b4519ccab/node_modules/.oxlint-ACwWByF5'
npm error A complete log of this run can be found in: /Users/steadily-worked/.npm/_logs/2024-08-05T08_31_44_293Z-debug-0.log
```

**Comment by rzvxa** [comment]
Were there any errors before it went through? Perhaps a failed attempt at updating before this?
It doesn't seem to be an oxlint-related issue, Maybe dumping the log here(or uploading it if it contains lots of entries) can help.

I just tried reproducing it, But it was successful on both Linux and Windows targets. I can't confirm it on Mac though.

**Comment by Boshen** [comment]
Seems like a generic problem with `npm`: `https://github.com/npm/cli/issues/5825`.

Closing as won't fix :-/

**Comment by steadily-worked** [comment]
ah, got it. Thanks!
