### ISSUE TITLE
bug(linter): missing arm64-gnu oxlint build?

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4669]
This happened when I ran `npx oxlint@latest` in one of my GH actions CI pipelines.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/5d66d810-3a3a-48e3-adc8-9c1de3ea6623">

**Comment by Boshen** [comment]
Your company has a `arm64-gnu` CI machine 👀 ?

**Comment by DonIsaac** [comment]
That was run on a hosted github actions runner

**Comment by Boshen** [comment]
Weird, the binary is here https://www.npmjs.com/package/@oxlint/linux-arm64-gnu

**Comment by DonIsaac** [comment]
If it happens again I'll re open this.
