### ISSUE TITLE
Run AST codegen automatically when files in crates read by codegen are modified?

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4705]
Instead of requiring user to run `just ast` when they update e.g. AST type definitions, could we do it automatically?

The core team are aware of the codegen and what it's doing, but others may not be, and it may be confusing for them.

Could we add build scripts to `oxc_ast`, `oxc_syntax` and `oxc_span` crates which run the AST codegen when changes are made to `.rs` files in their crates?

We don't want codegen to run on CI. Build scripts could recognise that they're on CI from `CI` env var, and in that case exit without doing anything. To avoid the build scripts blowing up compile time on CI, I suggest that they don't have `ast_codegen` as a dependency, but just execute `cargo run -p ast_codegen` as a command.

This *seems* a good idea to me, but is there any downside I'm missing?

**Comment by Boshen** [comment]
I'm not a fan of build scripts, they add a lot of extra complexity to the codebase.

I'm going to close this for house keeping. Given it's guarded by CI, and code will definitely not be able to compile when the ast files are changed.

A quick improvement we can do right now is add documentation to a few places: the website contribution guide and the `just command`.

I'll do these right now.
