### ISSUE TITLE
Incorrect `Span` on `BindingIdentifier` 

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4739]
Spans for binding identifiers cover the identifier itself and the type annotation on `BindingPattern`. This was introduced in #2624, and is blocking https://github.com/oxc-project/backlog/issues/84.

## Expected Behavior
```ts
//    ___________ BindingPattern
const foo: number = 1
//    ^^^-------- TSTypeAnnotation
//    ^^^BindingIdentifier
```

## Actual Behavior
```ts
//    ___________ BindingPattern and BindingIdentifier
const foo: number = 1
//       -------- TSTypeAnnotation
```

**Comment by Boshen** [comment]
This is a weird one ...

<img width="778" alt="image" src="https://github.com/user-attachments/assets/d893e5ce-0d28-4891-adf1-5068c12d093b">

**Comment by Dunqing** [comment]
This is also weird in `TypeScript`, Why not `{ pos: 6, end: 7 }`?
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/090bbe46-e6e5-4c32-9e42-7def62e38b76">

**Comment by Boshen** [comment]
Shall we go for the more intuitive version? i.e. 

//    ___________ BindingPattern
const foo: number = 1
//       ^^^^^^^^ TSTypeAnnotation
//    ^^^BindingIdentifier

**Comment by DonIsaac** [comment]
The cause is BindingPattern gets its span from `kind`, which covers the whole BindingPattern. I see two possible solutions:

1) give BindingPattern its own `span` field, which would increase its size to 40 bytes in total
2) derive span as `kind.span().merge(type_annotation.span)`, which would save size at the cost of a) GetSpan performance, b) we could not implement GetSpanMut, and c) we'd need to create a custom GetSpan impl for BindingPattern.

**Comment by Boshen** [comment]
Ahh, I don't like either of these options. What if we accept that it's the way it is and hack it in `no-unused-vars` alone?

**Comment by DonIsaac** [comment]
That's also acceptable assuming nobody else needs this.

**Comment by magic-akari** [comment]
This is weird in SWC.

<img width="856" alt="image" src="https://github.com/user-attachments/assets/6ed09305-2bfa-4a28-9a22-18a6e663f527">
<img width="856" alt="image" src="https://github.com/user-attachments/assets/e01fb106-ef81-44e3-9d62-ceaaac3c48ed">


https://github.com/swc-project/swc/issues/8856

**Comment by overlookmotel** [comment]
In my opinion, we should add a `span` field to `BindingPattern`.

Yes, that costs 8 bytes. But having a weird oddity like this is a footgun, and is bound to lead to trouble. I ran into it on #4473 and couldn't understand what was going on, and Don's also run into it here. That's 2 people tripped up by this in 2 weeks!

If we wanted to, later on we could potentially optimize that field out again by making span access via a `span()` method only. But we could also do the same thing to various other structs (e.g. `BinaryExpression`), so I don't think it makes a great deal of sense to only do it on `BindingPattern`.

**Comment by Boshen** [comment]
Close as won't fix. Let's try keep this as is and hack `no-unused-vars`.
