### ISSUE TITLE
semantic: check symbols and scopes after transformation

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#4790]
cc @overlookmotel how exactly do we want to check symbols and scopes?

**Comment by overlookmotel** [comment]
I would be happy to take this is on if you'd like, Boshen.

**Comment by Dunqing** [comment]
Just a note, we may need to check duplicate AstNodeId, ScopeId, and SymbolId in `AST`. related to https://github.com/oxc-project/oxc/issues/4809

**Comment by Boshen** [comment]
Borrowing the idea of the mangler, we can check whether symbols are the same in scope visitation order.

**Comment by rzvxa** [comment]
> Just a note, we may need to check duplicate AstNodeId, ScopeId, and SymbolId in `AST`. related to #4809

This feels more related to #4804
