### ISSUE TITLE
Should we add windows shell support for `just`?

### ISSUE THREAD

**Issue by shulaoda** [oxc-project/oxc#4794]
When I use my own `Windows` computer for work, I find that it doesn't seem to work.
![wecom-temp-27415-49d2fbc0124d193cce822732f0411ecb](https://github.com/user-attachments/assets/7cf4b890-65ec-48ff-a8b7-970214594614)

**Comment by shulaoda** [comment]
If you agree, I will bring up the relevant PR.

**Comment by Boshen** [comment]
Sure, seems easy https://github.com/casey/just?tab=readme-ov-file#windows-shell
