### ISSUE TITLE
GitHub action check annotation

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#480]
Biome has implemented this: https://biomejs.dev/blog/biome-v1-5/#the-command-biome-ci-now-prints-diagnostics-in-github-prs

**Comment by jbergstroem** [comment]
@Boshen another approach could be to check in the environment for [`GITHUB_ACTION`](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) and output the [`::error` string(s)](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) as part of stdout. That way you'd just run the binary in CI and it'd Just Work.

**Comment by re-taro** [comment]
@Boshen Hello! I would like to address this issue!

**Comment by Boshen** [comment]
> @Boshen Hello! I would like to address this issue!

Assigned 😁

**Comment by re-taro** [comment]
> > @Boshen Hello! I would like to address this issue!
>
> Assigned 😁

Thanks! By the way, where should I create a repository?
- First, I'll create it privately, and if @Boshen decides it's a good idea, I'll import it into oxc-project.
- Create it in oxc-project from the beginning

**Comment by Boshen** [comment]
@re-taro Do you wanna take a look at how biome does it? It seems like all we need to do is detect for github CI and dump things differently 

> @Boshen another approach could be to check in the environment for [`GITHUB_ACTION`](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) and output the [`::error` string(s)](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) as part of stdout. That way you' run the binary in CI and it'd Just Work.

**Comment by Boshen** [comment]
The text should be wrapper here I think 

https://github.com/oxc-project/oxc/blob/4cd5f1a05ecf11d34cc881d0181bd29a220131b4/crates/oxc_diagnostics/src/service.rs#L127

**Comment by re-taro** [comment]
>> @re-taro Do you wanna take a look at how biome does it? It seems like all we need to do is detect for github CI and dump things differently
>
> @Boshen another approach could be to check in the environment for [GITHUB_ACTION](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) and output the [::error string(s)](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) as part of stdout. That way you' run the binary in CI and it'd Just Work.

Ah, I see, my apologies, you mean to respond with a Biome-like approach. Yes, sir.

**Comment by re-taro** [comment]
hmm... If you can escape `&err_str` and get file name, line number and column number in `output.push_str(&err_str);` inside `crates/oxc_diagnostics/src/service.rs` It would be nice, but it is not simple because line number and column number are obtained in `crates/oxc_diagnostics/src/graphic_reporter.rs` and are nicely hidden.

**Comment by Boshen** [comment]
> hmm... If you can escape `&err_str` and get file name, line number and column number in `output.push_str(&err_str);` inside `crates/oxc_diagnostics/src/service.rs` It would be nice, but it is not simple because line number and column number are obtained in `crates/oxc_diagnostics/src/graphic_reporter.rs` and are nicely hidden.

Can you help me with what's needed to be printed / outputted on the screen?

**Comment by jbergstroem** [comment]
> Can you help me with what's needed to be printed / outputted on the screen?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message

**Comment by re-taro** [comment]
Sorry for the hassle. As @jbergstroem posted the link, you need to get the file name, column number and line number inside `crates/oxc_diagnostics/src/service.rs` (if you wrap `output.push_ str(&err_str);` if you wrap it...). For workflow-command, you can get it from `diagnostic.severity()`.
