### ISSUE TITLE
incorrect symbol when a function is assigned to a variable

### ISSUE THREAD

**Issue by camc314** [oxc-project/oxc#4817]
apologies if this is a duplicate

given the following input:
```
const test = function hello(arg0) {
}

hello()
```

the second `hello` should be an unresolved reference.

currently it's resolved to the function above

playground

https://oxc-project.github.io/oxc/playground/?code=3YCAAICugICAgICAgICxG0qZRraXVswnifU1q2%2Fm%2BJLccV2rnStJM1nSHXd7kNzN6i4LIHQr9wC%2BGhx%2FfzfAgIA%3D

the symbol highlighted on the RHS should not be there

<img width="1463" alt="Screenshot 2024-08-10 at 22 04 04" src="https://github.com/user-attachments/assets/588675ed-465d-4dbf-8238-9679770260e4">

**Comment by Dunqing** [comment]
From the screenshot, This is correct. As you see the `hello` symbol hasn't any references. So `hello()` is indeed an unresolved reference.

When `hello()` is resolved, the `hello` symbol will look like this
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/1eebabae-78a5-4597-9db7-1f19a2349571">

> the symbol highlighted on the RHS should not be there

We will create a symbol for `FunctionExpression` which helps us resolve the self-reference function

```js
const test = function hello() {
  hello()
}
```

Feel free to reopen this issue If I have misunderstood

**Comment by camc314** [comment]
ah got it, thank you for explaining.

i didn't realize:
```
const test = function hello() {
  hello()
}
```
was valid 🙂
