### ISSUE TITLE
Change order of fields in `CallExpression`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4821]
`CallExpression` currently has `arguments` before `callee`:

https://github.com/oxc-project/oxc/blob/4e818a434ccc9100c4b28591e56166304fa590bc/crates/oxc_ast/src/ast/js.rs#L601-L608

Is there a reason for this? It seems like this field order would make more sense:

```rs
pub struct CallExpression<'a> { 
     #[serde(flatten)] 
     pub span: Span, 
     pub callee: Expression<'a>, 
     pub type_parameters: Option<Box<'a, TSTypeParameterInstantiation<'a>>>, 
     pub arguments: Vec<'a, Argument<'a>>, 
     pub optional: bool, // for optional chaining 
 } 
```

**Comment by rzvxa** [comment]
Arguments are evaluated first then callee is evaluated. It is in the execution order.

**Comment by overlookmotel** [comment]
Ah ha. That makes sense. But... in what sense are arguments evaluated first?

```js
(console.log('callee'), () => {})(console.log('arg'));
// Logs:
// callee
// arg
```

```js
Object.defineProperties(global, {
    $callee: {
        get() {
            console.log('callee');
            return () => {};
        }
    },
    $arg: {
        get() {
            console.log('arg');
        }
    },
});

$callee($arg);
// Logs:
// callee
// arg
```

**Comment by rzvxa** [comment]
Oh, you are right, Maybe "evaluated" first wasn't the best phrase to characterize it. By evaluation of `callee` I've meant the call itself; Evaluating the callee happens first(for example member expression needs to be evaluated beforehand).

Here's what I meant by the execution order:

```js
function callee() {
  console.log("callee");
}

function a() {
  console.log("a");
}
function b() {
  console.log("b");
}

console.log("main", callee(a(), b()))
// Logs:
// a
// b
// callee
// main
```

So TL;DR you are right, And I was wrong. It used to get visited in this order and I used the test above to check the execution order(which is testing the wrong thing) As a result I assumed this as the execution order and swapped the field positions.

I know revering this change and reordering visits breaks some tests, But I think we should fix those instead of keeping these fields like this.

I'll relabel it as a bug. Because it seems like one, If I'm wrong feel free to change it back.

cc @Boshen

**Comment by Dunqing** [comment]
According to our resolve algorithm, the order of the fields should depend on the order in which the code's syntax is written.

Looks like this:
```ts
callee        <T>                 ?.          (arguments)
^^^^^^ callee ^^^ type_parameters ^^ optional ^^^^^^^^^^^ arguments
```

The order of `span` and `optional` doesn't matter, so it's fine wherever the.

So the expected field order is as @overlookmotel says. This makes sense and is more intuitive. 

Additionally, this change should not affect any tests or snapshots.

**Comment by cblh** [comment]
reordering visits breaks some tests 
```
error[E0080]: evaluation of constant value failed
   --> crates/oxc_ast/src/generated/assert_layouts.rs:181:5
    |
181 |     assert!(offset_of!(CallExpression, arguments) == 8usize);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: offset_of!(CallExpression, arguments) == 8usize', crates/oxc_ast/src/generated/assert_layouts.rs:181:5
    |
    = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Dunqing** [comment]
Have you run `just ast`?

**Comment by rzvxa** [comment]
> reordering visits breaks some tests
> 
> ```
> error[E0080]: evaluation of constant value failed
>    --> crates/oxc_ast/src/generated/assert_layouts.rs:181:5
>     |
> 181 |     assert!(offset_of!(CallExpression, arguments) == 8usize);
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: offset_of!(CallExpression, arguments) == 8usize', crates/oxc_ast/src/generated/assert_layouts.rs:181:5
>     |
>     = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

We generate some code based on our AST types, For example, these assertions are based on AST type layouts which change after reordering the fields; Running the `just ast` command would regenerate these modules.

If you are considering submitting a PR for it, It should be done like this:

1. Reorder fields
2. run `just ast`
3. fix `AstBuilder` calls(those methods would get their parameters reordered to reflect the new AST field orders)
4. fix broken tests(some need updating their snapshots, IIRC some need minor logic tweaks)

Feel free to submit the work-in-progress PR and request an early review so I can help you with it.
It isn't the best first issue but you are already somewhat familiar with the linter so I feel you'll be OK.
