### ISSUE TITLE
oxlint -v return 'dev' instead of '0.7.1' 

### ISSUE THREAD

**Issue by GiladShoham** [oxc-project/oxc#4891]
When running `oxlint -V` it returns `dev` instead of `0.7.1`

**Comment by rzvxa** [comment]
It was caused by a mistake in our CI, @Boshen fixed it in a direct push(no PR so I can't link)
https://github.com/oxc-project/oxc/commit/0813af9d3053118d4b2d0985dda014df4c063896

It should report the correct version in our upcoming release.
