### ISSUE TITLE
`AstBuilder` methods which take an `Option` accept `None` without type annotation

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4901]
Came across this in #4884:

https://github.com/oxc-project/oxc/blob/c0d4397a75956f61c32701bd128ad62ca2f7fb48/crates/oxc_transformer/src/es2020/nullish_coalescing_operator.rs#L78

And also:

https://github.com/oxc-project/oxc/blob/1e6d0fe7dddb9fa40a1d7b27df83de96b48fbc6e/crates/oxc_minifier/src/keep_var.rs#L60-L61

Is there any way to avoid need for type annotations when the param is `None`?

I tried changing `binding_pattern` to:

```rs
pub fn binding_pattern<T1>(
    self,
    kind: BindingPatternKind<'a>,
    type_annotation: Option<T1>,
    optional: bool,
) -> BindingPattern<'a>
where
    T1: IntoIn<'a, Box<'a, TSTypeAnnotation<'a>>>,
{
    BindingPattern {
        kind,
        type_annotation: type_annotation.map(|it| it.into_in(self.allocator)),
        optional
    }
}
```

But that doesn't help.

Is there anything we can do to avoid the need for type annotation on `None`?

**Comment by overlookmotel** [comment]
@rzvxa Any bright ideas? I'm a bit stumped.

**Comment by IWANABETHATGUY** [comment]
https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/struct.Application.html#associatedconstant.NONE

**Comment by IWANABETHATGUY** [comment]
A simple test: 
```diff
diff --git a/crates/oxc_minifier/src/keep_var.rs b/crates/oxc_minifier/src/keep_var.rs
index 40297b7c8..454d58bc8 100644
--- a/crates/oxc_minifier/src/keep_var.rs
+++ b/crates/oxc_minifier/src/keep_var.rs
@@ -1,3 +1,4 @@
+use oxc_allocator::Box;
 use oxc_ast::{ast::*, syntax_directed_operations::BoundNames, AstBuilder, Visit};
 use oxc_span::{Atom, Span, SPAN};
 
@@ -43,7 +44,7 @@ impl<'a> Visit<'a> for KeepVar<'a> {
         }
     }
 }
-
+pub const NONE: Option<Box<TSTypeAnnotation<'_>>> = None;
 impl<'a> KeepVar<'a> {
     pub fn new(ast: AstBuilder<'a>) -> Self {
         Self { ast, vars: std::vec![] }
@@ -57,8 +58,8 @@ impl<'a> KeepVar<'a> {
         let kind = VariableDeclarationKind::Var;
         let decls = self.ast.vec_from_iter(self.vars.into_iter().map(|(name, span)| {
             let binding_kind = self.ast.binding_pattern_kind_binding_identifier(span, name);
-            let id =
-                self.ast.binding_pattern::<Option<TSTypeAnnotation>>(binding_kind, None, false);
+
+            let id = self.ast.binding_pattern(binding_kind, NONE, false);
             self.ast.variable_declarator(span, kind, id, None, false)
         }));
 
```

**Comment by rzvxa** [comment]
> @rzvxa Any bright ideas? I'm a bit stumped. It's not so important, but would be nice if there's a simple way to solve this.

Since default function generic arguments are phased out there is no standard way to avoid it.
I have some idea of how we can avoid this via a custom trait that can provide a concrete None based on the type T. However, I haven't spent much time on it.

I'll mull this over and come back with some comments.

**Comment by overlookmotel** [comment]
> Since default function generic arguments are phased out there is no standard way to avoid it.

Drat!

Maybe a generalized version of what @IWANABETHATGUY suggested?

```rs
struct AnyNone;

impl<'a, T> FromIn<'a, AnyNone> for Option<Box<'a, T>> {
    fn from_in(_: AnyNone, _: &'a Allocator) -> Self {
        None
    }
}

const NONE: AnyNone = AnyNone;
```

I'm actually not sure how good an idea this is, though. It's weird to have to use `NONE` instead of `None`. Maybe the cure is worse than the disease!

@rzvxa Does your idea remove the need for this "magic" `NONE`? Or much the same?

**Comment by Boshen** [comment]
Close as stale. There are no better alternatives right now.

**Comment by overlookmotel** [comment]
On reflection, I think providing `NONE` is better than having to use annotations. Re-opening and moving to backlog.
