### ISSUE TITLE
traverse: port the `generateUidIdentifierBasedOnNode` method of the Babel scope.

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#4906]
reference: https://github.com/babel/babel/blob/419644f27c5c59deb19e71aaabd417a3bc5483ca/packages/babel-traverse/src/scope/index.ts#L543-L545 

#4890 needs to use `maybeGenerateMemoised` function, and it depends on  `generateUidIdentifierBasedOnNode`

**Comment by Boshen** [comment]
Consensus: just port the thing 😢
