### ISSUE TITLE
NodeJS: Pnpm can not install oxc-parser on Linux images

### ISSUE THREAD

**Issue by EmilNordling** [oxc-project/oxc#4952]
While the root cause users may encounter already has an open PR: https://github.com/pnpm/pnpm/pull/8431 

It might be good to know that the distributed oxc-parser node binding may cause issues for machines using Linux and pnpm together. The optional package [@oxc-parser/binding-win32-arm64-msvc](https://www.npmjs.com/package/@oxc-parser/binding-win32-arm64-msvc/v/0.24.2?activeTab=code) has its libc property set to null, and that causes installation through pnpm to fail.

This is `@oxc-parser/binding-win32-arm64-msvc` package.json:
```json
{
  "name": "@oxc-parser/binding-win32-arm64-msvc",
  "version": "0.24.2",
  "main": "parser.win32-arm64-msvc.node",
  "license": "MIT",
  "author": "Boshen and oxc contributors",
  "bugs": "https://github.com/oxc-project/oxc/issues",
  "homepage": "https://oxc.rs",
  "repository": {
    "type": "git",
    "url": "https://github.com/oxc-project/oxc.git",
    "directory": "npm/oxc-parser"
  },
  "files": [
    "parser.win32-arm64-msvc.node"
  ],
  "cpu": [
    "arm64"
  ],
  "os": [
    "win32"
  ],
  "libc": [
    null
  ]
}
```

I don't think you guys need to update anything, potentially not including platform properties if they're set to null. I'm hopeful my pnpm PR will be merge and fix the code that causing the expiation. More can be read in the PR: https://github.com/pnpm/pnpm/pull/8431 

But FYI that setting the libc property to null causes issues, apparently.

**Comment by Boshen** [comment]
This like a bug on our end setting libc to `null`.

**Comment by Boshen** [comment]
The latest version no longer has `null` in the libc field https://www.npmjs.com/package/@oxc-parser/binding-win32-arm64-msvc/v/0.25.0?activeTab=code
