### ISSUE TITLE
Rename `ReferenceFlag` to `ReferenceFlags` (plural)

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4991]
All the other semantic flags have plural names - `ScopeFlags`, `SymbolFlags`, `NodeFlags`. `ReferenceFlag` is the outlier.

Rename:

* `ReferenceFlag` to `ReferenceFlags`.
* `Reference::flag` field to `flags`.
* `Reference::flag` method to `flags`.
* `Reference::flag_mut` method to `flags_mut`.
* All vars called `flag` to `flags`.

Only reason I'm opening an issue for this rather than just submitting a PR is it'd cause merge conflicts with PR stack #4973, so will wait for that to get merged first.

**Comment by overlookmotel** [comment]
Good idea. How do I mark the export as deprecated? (not done that before)

Ditto for the `Reference::flag` + `Reference::flag_mut` methods?

**Comment by overlookmotel** [comment]
Actually, on 2nd thoughts, I'm not sure we should get into deprecation for such a simple change. Oxc is not at v1.0.0 yet, and we're making breaking changes all the time. This change is extremely minor compared to most of them, and if we leave an extra `flag_mut` method doubling the new `flags_mut` then we'll just have to remember to go and remove it later on (and discuss when!).

What do you think?

**Comment by DonIsaac** [comment]
If it's not too much effort, deprecating for a single release could be worth it. It is definitely appreciated when upgrades do not break your code without warning :) 

If you think we won't remember to clean it up, then adding a deprecation is not worth it. After all, like you said, it is a very small change.

**Comment by overlookmotel** [comment]
Personally, my view is that it's not worth it. I do understand that breaking changes are always painful, but we are nowhere near a stable API for `Semantic`, and this change is small beer. If we try to keep deprecated methods etc around for every change to `Semantic` over next few months I imagine it'll add up to a sizeable workload for us, and for fairly little benefit - people are still going to have to change their code *at some point* soon.

But also: If we also exported `ReferenceFlags` and `ReferenceFlag`, I'm not clear how do you mark `ReferenceFlag` as deprecated (in a way where people *know* it's deprecated). If there's no good way of doing that, the deprecation process would seem a bit pointless as no-one will notice the deprecation, and then they'll just experience it as a breaking change later on when we finally do remove the old name.
