### ISSUE TITLE
`Reference::flag` method should return `ReferenceFlag`, not `&ReferenceFlag`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4992]
`ReferenceFlag` is `Copy`. `Reference::flag` method should return `ReferenceFlag` (1 byte), not `&ReferenceFlag` (8 bytes).

See also #4991 - I also propose renaming this method.

**Comment by DonIsaac** [comment]
When you make this change, could you add a re-export of `ReferenceFlags` as `ReferenceFlag` and mark it as deprecated? This will give downstream consumers time to update their code.

**Comment by overlookmotel** [comment]
Fixed in #5019.
