### ISSUE TITLE
Make all scopes unconditional

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5008]
Almost all nodes which can hold a scope *always* hold a scope. But a small handful only create a scope if required:

* `ForStatement`
* `ForInStatement`
* `ForOfStatement`
* `CatchClause`

I propose that we make all scopes unconditional i.e. all these nodes *always* have a scope.

My rationale is:

* Simplicity - especially in transformer where scope-related logic is already complicated.
* In most JS code, these nodes will create a scope anyway (`for (let item of arr)` is more common than `for (item of arr)`, and `catch (err) {` is much more common than `catch {`).
* Resolving references against a scope which has no bindings is very cheap.
* These are not the most common constructs (vs `if` or `function`), so even if it wasn't so cheap, a few extra unnecessary scopes would not hurt perf much anyway.

If I remember right, Dunqing was in favour of this a while back, but I resisted. At that point I didn't realise how few nodes had conditional scopes, so I thought the perf upside of eliding them was much bigger than it is.

**Comment by Dunqing** [comment]
> * Simplicity - especially in transformer where scope-related logic is already complicated.

Yes, I agreed

**Comment by Dunqing** [comment]
We need to remove these conditional in `SemanticBuilder`
https://github.com/oxc-project/oxc/blob/4e1f4abf8979fa2bb81543481904908309ab684c/crates/oxc_semantic/src/builder.rs#L946-L950

**Comment by overlookmotel** [comment]
Glad you agree!

We would also need to remove the `#[scope(if(...))]` attrs from AST (and remove support for that attr from `ast_tools` and from `Traverse` codegen).

**Comment by overlookmotel** [comment]
@Boshen Would you be happy with this change?

**Comment by Dunqing** [comment]
> @Boshen Would you be happy with this change?

I bet @Boshen totally agree this, he likes the standard way to handle scopes 😀

**Comment by Boshen** [comment]
:shipit:

**Comment by overlookmotel** [comment]
> :shipit:

What does a mouse dressed as a detective mean??!

**Comment by Boshen** [comment]
> > :shipit:
> 
> What does a mouse dressed as a detective mean??!

`:shipit:` https://www.quora.com/On-GitHub-what-is-the-significance-of-the-Ship-It-squirrel

Sorry I'm old.

**Comment by overlookmotel** [comment]
Not as old as me! But thanks for explaining.

**Comment by overlookmotel** [comment]
Implemented in #5114 and preceding PRs.
