### ISSUE TITLE
Problem in oxlint with exit code

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [oxc-project/oxc#5073]
If I run the command `oxlint -c oxlint.json -A all --max-warnings=23`  I only have 22 errors and 0 warnings but it return an exit code 1

Always that threre is a diagnostic seems that it returns an exit code 1. If I'm using --max-warnings it should exit with 1 only when it surpasses de count

**Comment by florianwittmann** [comment]
Isn't that working as intended?

>  --max-warnings=INT — Specify a **warning threshold**, which can be used to force exit with an error status if there are too many warning-level rule violations in your project

It sets a warning treshold, but not an error treshold. If you change all rules to be warnings instead of errors, it would also respect that 23 warnings limit that you set.

 But if you have them classified as error, even one single error leads to an exit code 1.

**Comment by DonIsaac** [comment]
Ah I read that as warnings, not errors. Yes, this is intended.
