### ISSUE TITLE
linter: false postivies and panics in `no-unused-vars`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5129]
https://github.com/oxc-project/oxlint-ecosystem-ci/actions/runs/10526918402/job/29168997426

**Comment by DonIsaac** [comment]
https://github.com/napi-rs/napi-rs/pull/2233

**Comment by camc314** [comment]
related: https://github.com/oxc-project/oxc/issues/5202

**Comment by camc314** [comment]
@DonIsaac are there any outstanding panics that need fixing?

**Comment by DonIsaac** [comment]
@camc314 not that I'm aware of, but they could exist...
