### ISSUE TITLE
bug(semantic): implicit return in arrow function does not count as a read

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#5156]
Given a variable `i`:

Expected behavior
![image](https://github.com/user-attachments/assets/b5bc9daf-53a4-4747-9909-ac10eeb0db79)

Actual behavior
![image](https://github.com/user-attachments/assets/7675ee10-7b15-4a41-a2b1-0594748139b1)

This causes `no-unused-vars` to incorrectly report `i` as unused.

**Comment by Boshen** [comment]
I recall @Dunqing made some changes to update expression before.
