### ISSUE TITLE
linter: use `simdutf8` for validating files

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5191]
See https://github.com/rolldown/rolldown/pull/2040

Our code to change is:

https://github.com/oxc-project/oxc/blob/666282a13b172de849e251eb3b8417bfb19a79cb/crates/oxc_linter/src/service.rs#L179-L183

**Comment by shulaoda** [comment]
Is it just changing this one place? I see that many places have used `read_to_string`.

**Comment by Boshen** [comment]
> Is it just changing this one place? I see that many places have used `read_to_string`.

Feel free to change it if it's in a hotspot for the linter.
