### ISSUE TITLE
bug(linter) incorrect fixer in `no_null`

### ISSUE THREAD

**Issue by camc314** [oxc-project/oxc#5194]
see https://github.com/oxc-project/oxlint-ecosystem-ci/actions/runs/10518058484/job/29218160739?pr=25

```ts
return null!
```
is being fixed to 
```ts
return !;
```
which is invalid TS

**Comment by camc314** [comment]
another one:

```
  x Expected a semicolon or an implicit semicolon after a statement, but found none
    ,-[packages/backend/server/src/core/quota/service.ts:73:19]
 72 |         } catch {}
 73 |         return  as unknown as typeof quota & {
    :                   ^
 74 |           feature: QuotaConfig;
    `----
  help: Try insert a semicolon here
  
  ```

**Comment by DonIsaac** [comment]
Re-opening this because @Dunqing's PR only handled the first mentioned problem, not the second.

**Comment by camc314** [comment]
I'll look at this - i think i will make the fixer **a lot** more concervative as to whether it fixes or doesn't.

**Comment by Dunqing** [comment]
> Re-opening this because @Dunqing's PR only handled the first mentioned problem, not the second.

https://github.com/oxc-project/oxc/blob/05d25e2aa371013443615441a0bc79d5e17ee67e/crates/oxc_linter/src/rules/unicorn/no_null.rs#L383

It's also resolved

**Comment by camc314** [comment]
still broken 😞 
although maybe this is a different issue.

```ts
const newDecorations = enabled ?
	this._debugService.getModel().getBreakpoints().map(breakpoint => {
		const parsed = CellUri.parse(breakpoint.uri);
		if (!parsed || parsed.notebook.toString() !== this._notebookEditor.textModel!.uri.toString()) {
			return null;
		}

		const options: INotebookCellDecorationOptions = {
			overviewRuler: {
				color: debugIconBreakpointForeground,
				includeOutput: false,
				modelRanges: [new Range(breakpoint.lineNumber, 0, breakpoint.lineNumber, 0)],
				position: NotebookOverviewRulerLane.Left
			}
		};
		return { handle: parsed.handle, options };
	}).filter(x => !!x) as INotebookDeltaDecoration[]
	: [];
```

is being fixed to:
```ts
const newDecorations = enabled ?
	
	: [];
```

**Comment by camc314** [comment]
@mysteryven do you want to fix this?

**Comment by DonIsaac** [comment]
I'm wondering if we should make this a suggestion 🤔

**Comment by camc314** [comment]
actually i'm not sure why our fixer works this way

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/204d31c9c2a92496a59635d9f42a532e1dc46f90/rules/no-null.js#L87-L122

unicorn:
1. if its the arg of a loose equals, suggests replacing with `undefined`
2. suggests deleteing the  `null` literal if it's the argument of a return stmt
3. suggests deleting it if it's not a `const` var decl
4. suggests replacing with undefined

**Comment by mysteryven** [comment]
> mysteryven do you want to fix this?

Oh, please excuse the delay of two days, I am always AFK these days due to something in my life. I'll take a look today!

**Comment by camc314** [comment]
no worries,

i think this one is fixed now https://github.com/oxc-project/oxc/commit/d6b84ec44e874fb5084b510cb9c0dbbc0334c5df
