### ISSUE TITLE
bug(linter) panic in fixer for `no-unused-vars` when fixing a `using` declaration

### ISSUE THREAD

**Issue by camc314** [oxc-project/oxc#5202]
the following code panics:

https://github.com/oxc-project/oxc/blob/841174f73cd9508742def46fddd3a941589a0b12/crates/oxc_linter/src/rules/eslint/no_unused_vars/fixers/fix_vars.rs#L40

given the following input
```ts
using foo = 2
```

as `VariableDeclarator` can be direct children of `UsingDeclaration` nodes.

**Comment by DonIsaac** [comment]
So _THATS_ what's causing it!
