### ISSUE TITLE
bug(linter) bug in fixer for `func-names`

### ISSUE THREAD

**Issue by camc314** [oxc-project/oxc#5229]
```ts
const setState = Component.prototype.setState;
Component.prototype.setState = function (update, callback) {
	return setState.call(this, update, callback);
};
```

is being fixed to
```
const setState = Component.prototype.setState;
Component.prototype.setState = function  setState(update, callback) {
	return setState.call(this, update, callback);
};
```

which is incorrect as now the `return setState.call` will now call itself rather than the `setState` from the outer scope

**Comment by Arian94** [comment]
I'm just checking this issue out of curiosity and I'm not getting this incorrect output in the playground.
Could you elaborate more on this?

**Comment by camc314** [comment]
so the playground doens't show this because (i believe) it only enables correctness rules.

if you try running oxlint locally with:
```ts
bunx oxlint@0.9.0 -D func-names <path to file>
```

you should see a report of the following:
```ts

  × eslint(func-names): Unexpected unnamed function.
   ╭─[<path>]
 1 │ const setState = Component.prototype.setState;
 2 │ Component.prototype.setState = function (update, callback) {
   ·                                ─────────
 3 │     return setState.call(this, update, callback);
   ╰────
  help: Consider giving this function expression a name.

Finished in 7ms on 1 file with 1 rules using 12 threads.
Found 0 warnings and 1 error.
```

when we run this with the fixer
```
bunx oxlint@0.9.0 -D func-names --fix <path to file>
```

it's fixed to 
```
const setState = Component.prototype.setState;
Component.prototype.setState = function  setState(update, callback) {
	return setState.call(this, update, callback);
};
```

this causes the `function setState` to shadow the outer `const setState`.
hence, after the fix, `return setState.call` no longer calls the outer `setState` (`const setState = ...`) but now calls the inner `setState`) `function setState`
