### ISSUE TITLE
Cal.com transformer benchmark showing lots of variance

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5267]
Appears to be due to a `hashbrown::HashSet` resizing unpredictably.

See flamegraph for: https://codspeed.io/oxc-project/oxc/branches/08-27-feat_wasm_output_symbol_ids_in_scope_tree

Maybe can fix by reserving additional capacity in hash maps upfront.

Wonder why it's only showing up on the Cal.com benchmark, and why it's non-deterministic.

**Comment by Boshen** [comment]
I traced the code and I suspect this:

https://github.com/oxc-project/oxc/blob/10279f55d92df80d9d5ce6b034a230e2a8a89e19/crates/oxc_transformer/src/env/data/babel.rs#L10-L13

I'll move this constructor out of the benchmark and see what happens.

**Comment by Boshen** [comment]
I have unignored the benchmark.

**Comment by overlookmotel** [comment]
Unclear if the variance is still there or not. Possible it is, but is masked by the massive increase in time that benchmark is now taking to run - #5457.

What was particularly confusing me wasn't so much what was causing the `HashSet` to resize, but why it was displaying *indeterminism* in doing so. I can't see the reason for that. Figuring that out might give us a clue how to reduce variance in the benchmarks overall.

We can see if the problem returns or not once #5457 is resolved.
