### ISSUE TITLE
Remove `JSXMemberExpressionObject::Identifier` variant

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5353]
Currently we parse all JSX member expressions as an `IdentifierReference` followed by one or more `JSXIdentifier`s.

This is the case regardless of whether the first identifier is upper case or not. i.e. `foo` in `<foo.bar>` is interpreted as an `IdentifierReference`, even though in `<foo>` it'd be a plain `IdentifierName`.

This behavior aligns with Babel: [Babel REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DwMQ9mB0BGCGBOACA9APgNwChQRgyAjgK4AeKG2AZrnEmlsNVLYaeVkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.25.6&externalPlugins=&assumptions=%7B%7D)

Therefore we can remove the `JSXMemberExpressionObject::Identifier` variant - it's not possible to create one - it's always an `IdentifierReference`, another nested `JSXMemberExpression`, or `this` (#5352).

It'll be easier to do this once we've closed #5352.

**Comment by Dunqing** [comment]
I've considered it, but it doesn't work. In this case: `<A.B.C />`, the `A` is an IdentifierReference, but `B` isn't. Therefore, we should keep it for nested `JSXMemberExpression`.

**Comment by overlookmotel** [comment]
I *think* it still works for `<A.B.C />`. The nesting is in the `object` field of `JSXMemberExpression`.

So in `<A.B.C />`, `B` and `C` are the `property` field and are `JSXIdentifier`s. It looks like this:

```rs
JSXMemberExpression {
    object: JSXMemberExpressionObject::MemberExpression(JSXMemberExpression {
        object: JSXMemberExpressionObject::IdentifierReference( IdentifierReference(A) ),
        property: JSXIdentifier(B),
    }),
    property: JSXIdentifier(C),
}
```

So, unless I'm mistaken, there are no circumstances in which `JSXMemberExpressionObject::Identifier` variant is ever generated by parser.

**Comment by Dunqing** [comment]
Ahh, My brain is broken. You are right.

I've made a mistake here
https://github.com/oxc-project/oxc/blob/fe62687bf12fceeffcff53c02e5c826031780013/crates/oxc_ast/src/ast_impl/jsx.rs#L63-L65

Doesn't have any tests failed 🥲
