### ISSUE TITLE
parser: `JSXMemberExpression` where property contains hyphens

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5355]
According to JSX spec, this is legal syntax: `<Foo.bar-qux>` (because `bar-qux` is a valid JSXIdentifier).

Currently Oxc transforms this to `_jsx(Foo.bar-qux, {})`:

https://oxc-project.github.io/oxc/playground/?code=3YCAAICRgICAgICAgICekQl4rrIkZg9c51vDD8rqZZS485A%2Ff3EUAIA%3D

We should transform it to `_jsx(Foo["bar-qux"], {})` instead.

NB: Babel just errors out on this input, and SWC gets it wrong the same way we do, so this is not a high priority. But it's probably easier to do it now while we're already making loads of changes to how we handle JSX.

**Comment by Boshen** [comment]
TODO: React transform should throw the same babel error.

**Comment by overlookmotel** [comment]
Babel throws that error in parser. [Babel REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DwMQ9mB0BGCGBOBaAjgVwB4AID0A-IA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.25.6&externalPlugins=&assumptions=%7B%7D)

I don't think Babel's behavior is correct because (as you pointed out yesterday) it's valid JSX. But it's undefined whether it's valid or not as *React* JSX.

So yes, we could raise an error in React transform, or we could accept it and transform it to `_jsx(Foo["bar-qux"], {})`.

**Comment by Boshen** [comment]
This is now a syntax error in oxc:

```
  × Unexpected token
   ╭─[misc/fail/oxc-5355.jsx:1:6]
 1 │ <Foo.bar-baz />
   ·      ───────
   ╰────
```
