### ISSUE TITLE
Quick access to span of expression

### ISSUE THREAD

**Issue by MrWaip** [oxc-project/oxc#5404]
Hello everyone,

I am developing a parser for a custom markup language based on HTML.

It includes interpolation, where curly braces can contain a JavaScript expression. I've encountered an issue where there's no API to access the span without iterating through all possible values of the `enum Expression`, which has many values. This is necessary to determine where the expression ends so that parsing can continue from that point.

Therefore, I'm submitting a feature request to add a method to the `enum Expression` that would return the span.

Example of function:

```rust
    fn read_interpolation(&mut self) -> Token {
        let source = &self.source[self.position..];
        let allocator = Allocator::default();
        let source_type = SourceType::default();
        let parser = Parser::new(&allocator, source, source_type);
        let expr = parser.parse_expression().unwrap();

        match expr {
            Expression::Identifier(e) => self.position = ident.span.end as usize,
            // too many variants
            _ => panic!(),
        }

        return Token::Interpolation(Interpolation {});
    }

```

Thank you!

**Comment by overlookmotel** [comment]
I believe the `oxc_span::GetSpan` trait is what you're looking for. If you bring that into scope with `use oxc_span::GetSpan`, then you can call `expr.span()` on an `Expression`.

**Comment by overlookmotel** [comment]
I'm going to close this as I think this answers your need, but feel free to re-open if I've misunderstood what you're asking for.

**Comment by MrWaip** [comment]
Thank you
