### ISSUE TITLE
Migrate regex linter rules to use parsed patterns

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#5416]
Merging #5256 provides support for optional parsed regex literals, We can enhance our regex-related linter rules to use this parsed pattern whenever available.

Here is the list of the rules operating on regex patterns which are written before the introduction of regex parser.

- [x] no_div_regex(#5417)
- [x] no_control_regex
- [x] no_empty_character_class
- [x] no_regex_spaces
- [x] no_hex_escape
- [x] no_useless_escape
- [x] prefer_string_replace_all
- [x] prefer_string_starts_ends_with

**Comment by Boshen** [comment]
I'll add "good first issue" when the required PRs are merged.
