### ISSUE TITLE
semantic: imported type is used but a warning message appears

### ISSUE THREAD

**Issue by btea** [oxc-project/oxc#5435]
When you import a type and then use this type as the key of an interface, a warning message will appear saying that this type is not used and it is recommended to remove it.

The sample code is as follows:
```ts
import type a from 'b'

export interface A {
  [a]: 'test' | '10'
}
```
I created a repro [link](https://playground.oxc.rs/#eNo9jb0OwjAMhF/F8pKlA6zZeA7KEIKDIjU/clypVcm7k4DSyXe+8+cDLWr0IScWkD0TGHCcAqinmuMcafslPgqxM5bgBsccAe7moUEJFVHwAXW9tHbtBzhhQn0gr7GPskcxG2rhlSZcGmfoYlOm0+zhmZbhhE0sLnFA7cxSqE6YDRfiRmy6U4Y+q2Nh04ve1H83E3z0zv+jWr/8NVGr) with the above code, and you can see the warning message when you open it.

**Comment by Dunqing** [comment]
Thank you for the feedback!

**Comment by btea** [comment]
So efficient! 👍

**Comment by btea** [comment]
@Dunqing I found that there are still problems in some scenarios, such as when a property of the imported type is used as a key, for [example](https://playground.oxc.rs/#eNo9jb0OwjAMhF/F8pKlQrBm4zkoQ1ocFKn5keNKrUrenQSUTr7znT8fOKNG51NkAdkTgQHL0YOa1BjGQNsvcUGIrZkJ7nCMAeBhLtNTgxLKouAD6nat/dJOcMCI+kBeQxt5D2I21MIrDbhUUtd5jolOs/spLt0Jm5BtZI/amiVTGTAZzsSVWHWjdH1W+2KOL3pT+12Nd8FZ949K+QKI9lI7).

**Comment by Dunqing** [comment]
> @Dunqing I found that there are still problems in some scenarios, such as when a property of the imported type is used as a key, for [example](https://playground.oxc.rs/#eNo9jb0OwjAMhF/F8pKlQrBm4zkoQ1ocFKn5keNKrUrenQSUTr7znT8fOKNG51NkAdkTgQHL0YOa1BjGQNsvcUGIrZkJ7nCMAeBhLtNTgxLKouAD6nat/dJOcMCI+kBeQxt5D2I21MIrDbhUUtd5jolOs/spLt0Jm5BtZI/amiVTGTAZzsSVWHWjdH1W+2KOL3pT+12Nd8FZ949K+QKI9lI7).

Thanks for the report! same problem.
