### ISSUE TITLE
minifier: handle parens in dce

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5436]
See https://github.com/rolldown/rolldown/pull/2153

**Comment by Boshen** [comment]
Note: need to revert this change in crates/rolldown/src/utils/pre_process_ecma_ast.rs

```
let options = CompressOptions {
      fold_constants: true,
      remove_dead_code: true,
      remove_syntax: true,
```

**Comment by DonIsaac** [comment]
@Boshen did #5439 resolve this ticket?
