### ISSUE TITLE
`ExportSpecifier::local` should be an `IdentifierReference`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5437]
https://github.com/oxc-project/oxc/blob/caf800700d583fac04eadb5b178c661f40c8009f/crates/oxc_ast/src/ast/js.rs#L2522-L2528

Is there a reason why the `local` field is a `ModuleExportName`? Can't it just be `IdentifierReference`?

This would correspond to the way `ImportSpecifier::local` is a `BindingIdentifier`:

https://github.com/oxc-project/oxc/blob/caf800700d583fac04eadb5b178c661f40c8009f/crates/oxc_ast/src/ast/js.rs#L2343-L2360

Then `ModuleExportName` can have its `IdentifierReference` variant removed.

Example:

```js
export { foo as bar };
export { foo as "bar qux" };
```

Here `local` (`foo`) is always an `IdentifierReference`, and `exported` can be either an `IdentifierName` (`bar`) or a `StringLiteral` (`"bar qux"`), but can't be an `IdentifierReference`.

**Comment by Dunqing** [comment]
Totally! I mentioned this in https://github.com/oxc-project/oxc/pull/3820#discussion_r1649698063

**Comment by Boshen** [comment]
You know how it goes ... I'll take a look at the spec and TypeScript.

**Comment by Boshen** [comment]
Valid: `export { "foo" as bar } from "source";`
Invalid: `export { "foo" as bar }`

https://tc39.es/ecma262/#sec-exports-static-semantics-early-errors

```
16.2.3.1 Static Semantics: Early Errors

ExportDeclaration : export NamedExports ;
  It is a Syntax Error if the ReferencedBindings of NamedExports contains any StringLiterals.
```

This is not applied to 

```
ExportDeclaration :
  export ExportFromClause FromClause ;
```

Confirmed by babel, tsc, esbuild ans swc.

**Comment by overlookmotel** [comment]
Ah sorry. I had totally neglected `export { foo as bar } from "source";` - in that case `foo` is not a reference to a local variable, so yes it needs to be an `IdentifierName`.

**Comment by overlookmotel** [comment]
Still it's not possible for `exported` to be an `IdentifierReference`. We could make `exported` a separate type to prevent constructing a non-sensical AST.
