### ISSUE TITLE
Sort errors to bottom after warnings always

### ISSUE THREAD

**Issue by Raynos** [oxc-project/oxc#5453]
What I expect

<img width="1496" alt="Screenshot 2024-09-04 at 12 54 00 PM" src="https://github.com/user-attachments/assets/11a5c898-6930-4211-b210-bbecdeda787f">

What I get sometimes.

<img width="1496" alt="Screenshot 2024-09-04 at 12 54 22 PM" src="https://github.com/user-attachments/assets/be9a9122-40f9-411e-8407-001119ba92ec">

Version 0.9.2

**Comment by DonIsaac** [comment]
@Boshen do we have a planned diagnostic order, or is it just by rule id?

**Comment by camc314** [comment]
i'm pretty sure it's unordered at the moment 

https://github.com/oxc-project/oxc/blob/ff7fa987db9c145cd74b762b69e6b377d2674307/crates/oxc_diagnostics/src/service.rs#L126-L170

it feels like it'd be pretty expensive to order, we'd have to collect every diagnostic first, and the output them, currently we output them as the arrive

**Comment by Raynos** [comment]
> it feels like it'd be pretty expensive to order, we'd have to collect every diagnostic first, and the output them, currently we output them as the arrive

Your cli takes 200ms, instead of 120,000ms like eslint, adding a --sort flag where i get no output until the end of the cli would be great for devex.

**Comment by DonIsaac** [comment]
For a single file, I agree. For multiple files, we'd need to allocate all diagnostics into a Vec, sort it, then log it. This is really expensive. We'd like to keep it at 200ms 😄

**Comment by camc314** [comment]
i guess it wouldn't be as bad actually, we could continue logging warnings as the come in, only collecting errs to report at the end

**Comment by rzvxa** [comment]
I have no opinion on whether we should support this or not, If all we want from this feature is having errors at the end we can avoid sorting by having 2 buffers for warnings and errors and flush them to the stdout at the end in the desired order(without sorting the elements). It increases the memory footprint but has its performance upsides - having fewer syscalls - that might balance our performance tradeoffs.

It has one UX downside which is we lose the instant feedback as it has to wait until the end of program lifetime to display the reports. But if we keep it optional we should be all good.

**Comment by camc314** [comment]
> Your cli takes 200ms, instead of 120,000ms like eslint, adding a --sort flag where i get no output until the end of the cli would be great for devex.

@Raynos did your eslint genuinly take 120,000ms? how many files was it running on?

**Comment by rzvxa** [comment]
> i guess it wouldn't be as bad actually, we could continue logging warnings as the come in, only collecting errs to report at the end

This is actually a better approach if we always want to keep errors at the end if this feature is on.

**Comment by Raynos** [comment]
@camc314 no it took 15 minutes on github actions and it timed out, about 3,000 files in a monorepo.

It also takes about 10GB of ram to run.

on my m3 macbook it takes 10gb and 2-4 minutes to run.

**Comment by Raynos** [comment]
An alternative and valid feature request would be for the read the cli help and use the cli flag to not log warnings at all. aka use --quiet as documented.

**Comment by Raynos** [comment]
Github actions

> Finished in 1.6s on 2832 files with 107 rules using 2 threads.

> Run npm run lint:eslint:slow
> socket.dev@1.0.0 lint:eslint:slow
> NODE_OPTIONS=--max-old-space-size=10240 time eslint ./workspaces/

> 125.69user 7.79system 1:19.17elapsed 168%CPU (0avgtext+0avgdata 6910988maxresident)k
> 7656inputs+0outputs (79major+2022427minor)pagefaults 0swaps

1.2minutes of time in github actions to run eslint with about 5 rules that are not backported to oxlint, running on a subset of the monorepo, with an upgrade from eslint 8 to eslint 9 

still needs 10GB of ram lol

**Comment by DonIsaac** [comment]
There's already a `--quiet` (and alternatively a `--silent`) CLI flag

**Comment by camc314** [comment]
@Raynos thanks for sharing

**Comment by Boshen** [comment]
The current architecture dumps all diagnostics to the screen as soon as possible. The only workaround is to use `--quiet` to see the errors.

Changing the current architecture is not feasible so close as not planned.
