### ISSUE TITLE
Transformer performing extremely badly on cal.com benchmark

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5457]
#5324 enabled all > es6 transforms in our transformer benchmarks.

As expected, measured performance dropped a lot, because the transformer doing much more work in our benchmarks.

However, something is badly wrong with the transformer on the cal.com benchmark. It went from 12.2 ms to over 6 seconds!

<img width="777" alt="bench" src="https://github.com/user-attachments/assets/fee214e7-9ed1-4ddf-a080-f35180806ba6">

I doubt this is a problem with the benchmarks. Likely one of the transforms is behaving extremely badly in some circumstances, and the cal.com fixture is triggering that behavior.

But which transform is the culprit?

**Comment by Boshen** [comment]
It's this:

```
                    // Enable React related plugins
                    transform_options.react.development = true;
```

What's so special about this?

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/64db1b4c406b367289794786b2d83d195a704819/crates/oxc_transformer/src/react/jsx_source.rs#L87-L90

**Comment by Boshen** [comment]
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/b7b83617-535d-4655-9286-31305dce6331">

**Comment by Boshen** [comment]
Continue in https://github.com/oxc-project/oxc/issues/5500
