### ISSUE TITLE
transformer: performance regression from `generated_uid`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5488]
<img width="1749" alt="image" src="https://github.com/user-attachments/assets/7f7b4fca-8350-4920-9338-862e890d638c">

It's inside `OptionalCatchBinding` -> `enter_catch_clause`.

**Comment by overlookmotel** [comment]
Do you suspect this is the root cause of #5457?

**Comment by Boshen** [comment]
Nope, I just checked `cal.com.tsx` doesn't have optional catch clause 🤔 

Giving it a spin anyway: https://github.com/oxc-project/oxc/pull/5489

**Comment by Boshen** [comment]
> Nope, I just checked `cal.com.tsx` doesn't have optional catch clause 🤔
> 
> Giving it a spin anyway: #5489

⚡ | transformer[pdf.mjs] | 10.6 ms | 7.4 ms | +43.59%
