### ISSUE TITLE
Wish to introduce  ast node location

### ISSUE THREAD

**Issue by ityuany** [oxc-project/oxc#5493]
I really like the range of crates provided by oxc and have been using them a lot in my projects, but I'm experiencing some problems with them.

I can't use ast node's span information to accurately restore the source location via oxc_sourcemap

So I hope

As below, there are LOC fields, which are more friendly to using sourcemap to directly reflect the source code

```json
{
          "type": "ImportDefaultSpecifier",
          "start": 7,
          "end": 12,
          "loc": {
            "start": {
              "line": 1,
              "column": 7
            },
            "end": {
              "line": 1,
              "column": 12
            }
          },
          "range": [
            7,
            12
          ],
          "local": {
            "type": "Identifier",
            "start": 7,
            "end": 12,
            "loc": {
              "start": {
                "line": 1,
                "column": 7
              },
              "end": {
                "line": 1,
                "column": 12
              }
            },
            "range": [
              7,
              12
            ],
            "name": "React"
          }
        }
```

Looking forward to your reply

**Comment by IWANABETHATGUY** [comment]
I assume you mean adding `location` information in the playground?

**Comment by IWANABETHATGUY** [comment]
Each `Location` will increase `span` size by 16 bytes, which could greatly impact performance.

**Comment by ityuany** [comment]
Great, thank you for providing the code snippet. I will come to learn your code later.

**Comment by IWANABETHATGUY** [comment]
Closed since oxc is not gonna adding this info in the core

**Comment by overlookmotel** [comment]
Actually we *may* add other forms of span (e.g. UTF-16 spans, line/column spans) in future, but it's likely a way off. #959

**Comment by IWANABETHATGUY** [comment]
> Actually we _may_ add other forms of span (e.g. UTF-16 spans, line/column spans) in future. But it's likely a way off. #959

Yeah, but the issue owner want `Location`, so he needs to convert anyway.
