### ISSUE TITLE
perf: memoize `Rope::from_str(source_text)`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5500]
https://github.com/oxc-project/oxc/blob/a96866d951ee6ce77d68af8d198ea663eaa9f92d/crates/oxc_transformer/src/react/utils.rs#L3-L19

https://github.com/oxc-project/oxc/blob/2514cc92e5a13b895ee12bc40c1404215c9c0da7/crates/oxc_language_server/src/linter.rs#L373-L381

`Rope::from_str(source_text)` is too expensive.

![image](https://github.com/user-attachments/assets/8e728866-6675-4b0d-b2ba-48ac053180bd)

**Comment by IWANABETHATGUY** [comment]
You could just use lineIndex, if you don't need incremental remove and add to a string.

**Comment by IWANABETHATGUY** [comment]
This remind me a blog long time ago, https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation
