### ISSUE TITLE
codegen: no need to print trailing_comma for `ArrayExpression`

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#5532]
https://playground.oxc.rs/#eNo9jUEOwyAMBL8S7ZlLe+QrVQ+UmgoJcGQTqVHE3wOKyMkztrV7wMPi9TDL0yxvGDDsAdnKGLqX6v6wVTYySLHUyep5pVv2/OE0rYorGlgybHBJqRmsTpSkJ3YeKZPv17nw/KUfje4uOZYY4nVq7QRM5zno

**Comment by camc314** [comment]
Fixed by #5551
