### ISSUE TITLE
perf(linter): replace string operations with `cow_utils::CowUtils`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5586]
I noticed we have many allocation methods which can be replaced by 

https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html

* [cow_replace](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_replace)
* [cow_replacen](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_replacen)
* [cow_to_ascii_lowercase](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_to_ascii_lowercase)
* [cow_to_ascii_uppercase](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_to_ascii_uppercase)
* [cow_to_lowercase](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_to_lowercase)
* [cow_to_uppercase](https://docs.rs/cow-utils/0.1.3/cow_utils/trait.CowUtils.html#tymethod.cow_to_uppercase)

Feel free to grep them in the `oxc_linter` crate and make improvements. You may find inefficient routines in the process, feel free to make separate PRs.

**Comment by Boshen** [comment]
The remaining cases in https://github.com/oxc-project/oxc/pull/5662 should be fixed.

**Comment by tisonkun** [comment]
I noticed https://github.com/RReverser/cow-utils-rs/issues/7. Not sure if oxc has some results that moving to cow-utils does help in perf.

**Comment by heygsc** [comment]
> I noticed [RReverser/cow-utils-rs#7](https://github.com/RReverser/cow-utils-rs/issues/7). Not sure if oxc has some results that moving to cow-utils does help in perf.

Oxc might have some relevant changes, you can take a look at these two issues: #8496 #8659

**Comment by tisonkun** [comment]
@heygsc thanks for your information!

@Boshen I'm considering leveraging both beef and cow-utils since oxc has most short cow strings that need not to change upon method calls.

A vendored cow version can fit oxc's requirement best. If it sounds like a good direction to try out, I may find some time to provide a prototype.
