### ISSUE TITLE
semantic: symbol id is `None` in `if (true) function id() {}`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5627]
https://github.com/oxc-project/oxc/blob/54e2e76d173d77d57ac1611d4df3b31ae769ef14/crates/oxc_semantic/src/post_transform_checker.rs#L652-L659

This is causing trouble in the linter.

**Comment by overlookmotel** [comment]
### Expression

In the expression form `if (function foo() {}) {}`, the function (and its name) is completely unobservable at runtime, but I guess we should create a symbol for `foo` and bind it in the function's scope (same as any other function expression).

Presumably no-one will write such pointless code, so it should only matter in tests.

### Declaration

It seems like the function declaration form *does* create a binding:

```js
// Sloppy mode code
if (true) function foo() {}
console.log(typeof foo); // Logs 'function'
```

So I guess we should just create a symbol for the function ID, and bind it in the scope above. Same as a `var` statement, except no error in this case:

```js
let foo;
if (true) function foo() {}
```

I believe this is a specific case of a more general complication over what scope functions declarations' are bound to in sloppy mode.

https://github.com/babel/babel/pull/14203#issuecomment-1038187168

I don't know what spec says (I think it's Annex B), but in NodeJS and Firefox, the observed behavior is that a function declaration in sloppy mode creates *two* independent bindings:

```js
function outer() {
    let getInnerF;
    {
        function f() { return 123; }
        getInnerF = () => f;
    }
    console.log(f()); // Logs 123
    console.log(getInnerF()()); // Logs 123
    f = undefined;
    console.log(typeof f); // Logs undefined
    // `f` binding in this scope is now undefined,
    // but in the inner block, `f` is still the function.
    // Therefore there are 2 `f` bindings.
    console.log(getInnerF()()); // Logs 123
}
outer();
```

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/pull/5673
