### ISSUE TITLE
Use `auto.fix` fix to untested snapshots

### ISSUE THREAD

**Issue by 7086cmd** [oxc-project/oxc#5636]
Related: https://github.com/rolldown/rolldown/issues/2190#issuecomment-2336778348.

It can be useful when we don't have enough bandwith / performance to run the tests when we temporarily modify some code, or sometimes we simply forgot to update shapshots.

**Comment by Boshen** [comment]
The whole idea of snapshot testing is to not accidentally commit incorrect snapshots. I'm going to close this one as not planned.
