### ISSUE TITLE
perf(formatter): can `cow_to_ascii_lowercase` be used here?

### ISSUE THREAD

**Issue by heygsc** [oxc-project/oxc#5639]
[https://github.com/oxc-project/oxc/blob/main/crates/oxc_prettier/src/format/mod.rs#L1406-L1409](https://github.com/oxc-project/oxc/blob/main/crates/oxc_prettier/src/format/mod.rs#L1406-L1409)

related examples: #5637 

I tried it and it seems to work. Should this be done?

**Comment by Boshen** [comment]
yes, we should somehow ban these methods.

Can you try https://rust-lang.github.io/rust-clippy/master/#/disallowed_method
