### ISSUE TITLE
isolatedDeclarations: should preserve jsdoc comments

### ISSUE THREAD

**Issue by yyx990803** [oxc-project/oxc#5687]
Currently, all comments are stripped during isolatedDeclaration transform. JSDoc comments are necessary for in-IDE documentation on hover, so JSDoc comments attached to types should be preserved in dts files.

**Comment by Boshen** [comment]
Duplicate of #1046 and #3906

**Comment by Boshen** [comment]
Released in https://www.npmjs.com/package/oxc-transform/v/0.30.0, along with the `stripInternal` option.
