### ISSUE TITLE
regular_expression: `to_string()` missmatch for LegacyOctalEscape

### ISSUE THREAD

**Issue by leaysgur** [oxc-project/oxc#5690]
Found in https://github.com/oxc-project/oxc/pull/5676#discussion_r1751905218

- - -

Failed regexp is `/\0003/`.

This is parsed as:

- Character(Octal): `\000`
- Character(Symbol): `3`

But once `to_string`ed, this will be `/\03/`.

This is parsed as:

- Character(Octal): `\03`

Because we remove leading `0`s for now.

This also happens:

- `/\0111/` => `/\111/`
- `/\0022/` => `/\22/`

Is it possible to restore these without having extra `raw` field in the AST?

But both `\000` and `\00` are the same Character(Octal)...

**Comment by Boshen** [comment]
This grammar is in the horror of Annex B https://tc39.es/ecma262/#sec-regular-expressions-patterns

I wonder whether it should be another ast node 🤔

**Comment by leaysgur** [comment]
Yes, always bothered by Annex B...! 

Now I'm considering to introduce `Octal1`, `Octal2` and `Octal3` here. 🙃

https://github.com/oxc-project/oxc/blob/9e9435f03bacd329a4958a85a0889e6002beb4e4/crates/oxc_regular_expression/src/ast.rs#L172-L181
