### ISSUE TITLE
Add ability to iterate over `IndexVec` with indexes in parallel

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5734]
Requested in: https://github.com/rolldown/rolldown/pull/2016#pullrequestreview-2244371518

I guess what's required is a parallel version of `ivec.iter_enumerated()` and `ivec.into_iter_enumerated()`, something like:

```rs
ivec.iter_enumerated().into_par_iter()
ivec.into_iter_enumerated().into_par_iter()
```

or

```rs
ivec.par_iter_enumerated()
ivec.into_par_iter_enumerated()
```

I'm not that great with `rayon` so I'm not sure what is best way. I'm surpised that `ivec.iter_enumerated().into_par_iter()` doesn't work "out of the box" already.

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/pull/5421

**Comment by overlookmotel** [comment]
Oh dear, I'm rather behind the curve, it seems...
