### ISSUE TITLE
transformer: react refresh panics when transforming `typescript.js`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5766]
I happened to run into this. When transforming `typescript.js` (one of fixtures used for minifier) with all transform options enabled, it panics:

```
thread 'main' panicked at crates/oxc_transformer/src/react/refresh.rs:933:52:
called `Option::unwrap()` on a `None` value
```

**Comment by Boshen** [comment]
`name.chars().nth(3).unwrap()` looks very dangerous 😄
