### ISSUE TITLE
VSCode extension: default `oxc_language_server.configPath` seems wrong

### ISSUE THREAD

**Issue by greeeg** [oxc-project/oxc#5802]
Hi 👋

While trying to move part of my linting config from eslint to oxlint, I did not understand why removing the `no-console` rule from `.eslintrc` & adding it to `.oxlintrc.json` did not trigger an error in my VSCode editor while it was triggering it properly running the oxlint CLI.

After a short investigating, I discovered that the default config path used by the OXC VSCode language server was [`.eslintrc`](https://github.com/oxc-project/oxc/blob/bb95306efda4af7f49fb9c393e834c299c6142da/crates/oxc_language_server/src/main.rs#L54).

It means that the oxlint language server was using my legacy eslint config instead of the new appropriate one. Should we change the default config path to be the filename documented [here](https://oxc.rs/docs/guide/usage/linter/config.html) or at least explain that the configuration file used can be changed using VSCode `settings.json` file? Many thanks!

**Comment by pumano** [comment]
@DonIsaac I can change default value to `.oxlintrc.json`, because documentation tells about `.oxlintrc.json` not about `.eslintrc`. 

Looks like good first issue for me)

**Comment by DonIsaac** [comment]
No-work-required eslint migration is a large goal for us. I'm down with checking for an `.oxlintrc.json` file and falling back to `.eslintrc`.

As a note: a lot of our users use `oxlint.json` as their config file name.

**Comment by pumano** [comment]
@DonIsaac OK would be good to have checking for .oxlintrc.json too. So I close my pull request

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/pull/7442
