### ISSUE TITLE
linter: Broken link display in CI

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#5819]
`! ]8;;[https://oxc.rs/docs/guide/usage/linter/rules/react/no-danger-with-children.html\eslint-plugin-react(no-danger-with-children)]8;;\:](https://oxc.rs/docs/guide/usage/linter/rules/react/no-danger-with-children.html%1B/eslint-plugin-react(no-danger-with-children)%1B]8;;%1B/:)`

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/28ae7e5f-7191-4575-bd07-dde24cbf826b">

It was introduced in https://github.com/oxc-project/oxc/pull/5318

**Comment by DonIsaac** [comment]
I assume github actions does not support hyperlink terminal control characters?

**Comment by camc314** [comment]
fixed by https://github.com/oxc-project/oxc/pull/6018 ?
