### ISSUE TITLE
oxc-transform npm package: allow options argument to `isolatedDeclaration` to be optional?

### ISSUE THREAD

**Issue by MichaelMitchell-at** [oxc-project/oxc#5871]
https://github.com/oxc-project/oxc/pull/5170 added support for sourcemaps and a third "options" argument to `isolatedDeclaration`, but starting in v0.26.0 the third argument became required. If you omit the third argument you get:
>`Uncaught TypeError: Cannot convert undefined or null to object`

and if you pass in `{}` as the third argument you get
> Uncaught [Error: Missing field `sourcemap`] { code: 'InvalidArg' }

This differs from the `transform` function, where the third argument is optional and the default behavior is equivalent to passing in `{sourcemap: false}`.

**Comment by Boshen** [comment]
@MichaelMitchell-at I assume you are using oxc at Airtable, feel free to dm me on Discord or twitter if you wish for a direct line of communication for higher level support.

**Comment by MichaelMitchell-at** [comment]
> @MichaelMitchell-at I assume you are using oxc at Airtable

Almost! Hoping to by the end of the week.

FWIW we're planning to be using the Rust crates directly now instead of the npm package, so this issue isn't blocking us :)
