### ISSUE TITLE
isolated-declarations: Keep code comments

### ISSUE THREAD

**Issue by long-woo** [oxc-project/oxc#5928]
Declare the following code:

```ts
export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
  /**
   * Order Status
   */
  status?: OrderStatus;
  complete?: boolean; 
}
```

The result is:

```diff
export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
- /**
-  * Order Status
-  */
  status?: OrderStatus;
  complete?: boolean;
}
```

I want to keep the original comments in the declaration code obtained using `oxc.isolatedDeclaration`. Are there plans to add a `removeComments` option in `IsolatedDeclarationsOptions` similar to the `tsconfig`?

**Comment by Dunqing** [comment]
Thanks for you give it a try on `oxc-isolated-declaration`! We have supported print `jsdoc` comments lately but haven't released a new version yet. We'll probably release it this week.

**Comment by Boshen** [comment]
We finished the implementation, will release next week after we fix a few minor issues.

**Comment by long-woo** [comment]
That's really cool 👍.

**Comment by Boshen** [comment]
Released in https://www.npmjs.com/package/oxc-transform/v/0.30.0
