### ISSUE TITLE
IsolatedDeclaration: incorrect emit for `node is Comment` in vue

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#5935]

**Comment by Dunqing** [comment]
Need to check in `TypeScript` if `lib.dom.d.ts` needs to be handled in IsolatedDeclaration.

**Comment by Dunqing** [comment]
I have tested the API `transpileDeclaration` of `TypeScript`, and its output is the same as we generated. I think support for this may need multi-file checking, it is out of our scope, so close as not planned.

**Comment by Boshen** [comment]
It feels like a bug to me. Let's clean up the issue description with a reproduction to the vue repo.

**Comment by Dunqing** [comment]
I created a [issue](https://github.com/microsoft/TypeScript/issues/60031) in TypeScript

**Comment by Boshen** [comment]
Follow ups: 

* https://github.com/microsoft/TypeScript/issues/60031
* https://github.com/vuejs/core/pull/12009
