### ISSUE TITLE
parser: `TSTypeAssertion` panics in `tsx`  context 

### ISSUE THREAD

**Issue by Sysix** [oxc-project/oxc#5954]
Test with following string:

`arr.push(<string>a);`

https://oxc-project.github.io/oxc/playground/

**Comment by DonIsaac** [comment]
I believe this is expected behavior. Both `oxc` and `tsc` treat `<string>` as a `JSXOpeningElement` that has no corresponding closing tag.
https://www.typescriptlang.org/play/?#code/DYUwLgBAhgTjBc0B2BPA2gXQgXgpg3AFCwwB0ADgK4DOAFgBQA81YMAlkgOYB8UAlESA
