### ISSUE TITLE
codegen: should escape reversed words as method name

### ISSUE THREAD

**Issue by KermanX** [oxc-project/oxc#6026]
Currently, Oxc's codegen generates `class A { static() {} }` ([playground](https://playground.oxc.rs/#eNpFUEFqxDAM/IrwxQmEsi2lh4SeFvqJugcndYqLI6eSsrsh5O9VCNkFg2ZG0mjwYjpTmziMmQQ8c9DSUx7AYv4O9a5Yhw67pATOsDgEYHFuOp3eniV2RQkLUJCJEF5fGlgd6nN48QS5/YV3wHCFc1E2m7o7PoW/yadC25+WxauL/SrKSvcrsCPlUWdmCLfIwrZsTGWyqRdDE26FZxR/M7XQFCqTIsqBudPVO5mHNqeDCXnkPtNg6t4nDmtlRk8aRh0Vby4Hvo8eQqd/8RO220qGiLGPjxYK5fSR8nWLdgnUZtYI+411/QdkaHqf)), which is invalid in ecma262 standard, as reversed words should be scaped in method names. (However, this code is somehow valid in Node?)

Test262: https://github.com/tc39/test262/blob/main/test/language/statements/class/ident-name-method-def-static-escaped.js

**Comment by Boshen** [comment]
Where does it say 

```
class C {
	static() {
		return 42;
	}
}```

is invalid syntax?

**Comment by KermanX** [comment]
Possibly [here in ecma262](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#sec-keywords-and-reserved-words) it says: "Those that are contextually disallowed as identifiers, in [strict mode code](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#sec-strict-mode-code): let, static, implements, interface, package, private, protected, and public;"

And the test262 test case above fails🤔

**Comment by Boshen** [comment]
```
Welcome to Node.js v22.7.0.
Type ".help" for more information.
> class C { static() { return 42; } }
undefined
> var obj = new C();
undefined
> console.log(obj['static']())
42
undefined
>
```


[MethodDefinition](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-MethodDefinition)[Yield, Await] :
[ClassElementName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-ClassElementName)[

[ClassElementName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-ClassElementName)[Yield, Await] :
[PropertyName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-PropertyName)


[PropertyName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-PropertyName)[Yield, Await] :
[LiteralPropertyName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-LiteralPropertyName)

[LiteralPropertyName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-LiteralPropertyName) :
[IdentifierName](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#prod-IdentifierName)

If you follow the grammar, `static` is `IdentifierName` here.

**Comment by KermanX** [comment]
Engine262 throws SyntaxError:
![image](https://github.com/user-attachments/assets/667d0386-d688-4f36-8beb-8dfcf4a1fc40)



> If you follow the grammar, `static` is `IdentifierName` here.

Yes, and the spec says "A reserved word is an IdentifierName that cannot be used as an identifier." [here](https://262.ecma-international.org/15.0/index.html?_gl=1*17utee4*_ga*MTQ5MTQzMjYxLjE3MjEwMDUwNzI.*_ga_TDCK4DWEPP*MTcyNzE4MDcyMC40LjAuMTcyNzE4MDcyMC4wLjAuMA..#sec-keywords-and-reserved-words)
