### ISSUE TITLE
Typo'd disable comments disable linting for the entire file

### ISSUE THREAD

**Issue by tylerlaprade** [oxc-project/oxc#6041]
`// oxlint-disable-lext-nine prefer-spread`
Since the `L` and `N` are swapped, rather than doing nothing, this comment is being partially matched as `// oxlint-disable` and disabling the entire file, which is not the intention. This should instead be ignored.

**Comment by camchenry** [comment]
Thanks for the bug report! This should be fixed now by https://github.com/oxc-project/oxc/pull/6045
