### ISSUE TITLE
Change the permissions of the oxc_language_server node file in the bin folder of the oxlint package to make it executable.

### ISSUE THREAD

**Issue by suxiaoshao** [oxc-project/oxc#6064]
I am developing the oxc plugin for zed and have found that the oxc_language_server in the .bin directory of the oxlint package stored under node_modules does not have executable permissions by default. 

I know there are two solutions: 

1. Use a postinstall script 

 ```json 
"scripts": {   
  "postinstall": "chmod +x ./bin/oxc_language_server" 
} 
``` 

2. Add oxc_language_server to the bin field in package.json 
```json 
"bin": {   
  "oxlint": "bin/oxlint",   
  "oxc_language_server":"bin/oxc_language_server" 
} 
``` 

Can you resolve this issue, or should I submit a PR to you?

**Comment by Boshen** [comment]
Thank you, I didn't know we need to add it to the `bin` field.

Btw I still don't have admin permission to zed-oxc so I can't move the repo to this org.

**Comment by suxiaoshao** [comment]
> Thank you, I didn't know we need to add it to the `bin` field.
> 
> Btw I still don't have admin permission to zed-oxc so I can't move the repo to this org.

I have re-invited you.

**Comment by Boshen** [comment]
Will release tomorrow when I wake up.

**Comment by suxiaoshao** [comment]
> Thank you, I didn't know we need to add it to the `bin` field.
> 
> Btw I still don't have admin permission to zed-oxc so I can't move the repo to this org.

You can check this link [Permission Levels for a Personal Account Repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository); it seems that personal repo cannot set admin permissions.

**Comment by Boshen** [comment]
The latest version now has `./node_modules/.bin/oxc_language_server`.

> it seems that personal repo cannot set admin permissions.

interesting, we may need to transfer it to me first, and then I transfer it to the org.

**Comment by suxiaoshao** [comment]
Okay, I updated oxlint in a certain project, and it seems that oxc_language_server already has default running permissions. 

I’ll transfer the repository to you in the next couple of days; please remind me when you transfer it to the org, as I need to submit a PR to <https://github.com/zed-industries/extensions> to modify the basic information of the oxc extension.
