### ISSUE TITLE
Semantic checker store conformance pass/fail info in a separate file

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6069]
#5976 added a structured test suite for `Semantic`.

As discussed in https://github.com/oxc-project/oxc/pull/5976#issuecomment-2368477213, currently it records whether the tests pass or fail in the `.snap` files. e.g. [nested-assignment.snap](https://github.com/oxc-project/oxc/blob/93575cd09e626a783c780d244996a447099e5782/crates/oxc_semantic/tests/fixtures/oxc/assignment/nested-assignment.snap)

I think this is not ideal because I am worried that if details of test fails are hidden away there, they may never get fixed.

I can imagine a scenario like this: Someone makes a PR that breaks a test. They say "I'll fix that test in a follow-up". But they forget to do it, and because it's hidden away in one `.snap` file out of 290, no-one notices, and the bug lives on unfixed forever.

@DonIsaac [said](https://github.com/oxc-project/oxc/pull/5976#issuecomment-2368793766) he'd make that change in a follow-up PR.

**Comment by overlookmotel** [comment]
@DonIsaac I've assigned you as you said you'd do this. But if you're too busy, feel free to unassign yourself.

**Comment by DonIsaac** [comment]
Yup, I'll handle it
