### ISSUE TITLE
isolated declarations: performance regression due to cloning too much

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6074]
https://github.com/oxc-project/oxc/blob/c2616f7fa1e2fb36f5ce1d76d63870cf6f5e9e2e/crates/oxc_isolated_declarations/src/lib.rs#L154

https://github.com/oxc-project/oxc/blob/c2616f7fa1e2fb36f5ce1d76d63870cf6f5e9e2e/crates/oxc_isolated_declarations/src/lib.rs#L192

**Comment by overlookmotel** [comment]
Fixed in #6078.
