### ISSUE TITLE
More documentation and API changes

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6079]
I'm clicking around and listing all the missing documentation and confusing APIs for me to work on:

- [x] crate README https://crates.io/crates/oxc
- [x] crate level https://docs.rs/oxc/0.30.1/oxc
- [ ] import `SourceType` from `oxc_span`?
- [ ] So many options in https://docs.rs/oxc_transformer/0.30.1/oxc_transformer/index.html, where's the entry point?
- [ ] Tranformer: super confusing entry point `targets` vs Options
- [x] Many unintended `pub` in all of the crates
- [x] https://www.npmjs.com/package/oxc-transform Usage example is outdated.
- [ ] npm packages should list binary files with their rough binary size for connivence.
- [ ] If an API has performance impact, it should be documented with % change.
- [ ] https://www.npmjs.com/package/oxc-parser should mention we don't have d.ts yet (or figure out how to get it from the wasm version).
- [ ] Align the shape of all APIs for npm packages (parser and transformer)
- [x] consolidate benchmark results on oxc.rs https://oxc.rs/docs/guide/benchmarks.html
- [x] update https://oxc.rs/docs/guide/usage/transformer.html
- [ ] Eliminate confusing terms by building a glossary?
- [ ] document https://crates.io/crates/oxc_module_lexer

> EDIT (@DonIsaac): related: #5870

**Comment by DonIsaac** [comment]
> I'm clicking around and listing all the missing documentation and confusing APIs for me to work on:
> 
> * [ ]  crate README https://crates.io/crates/oxc
> * [ ]  crate level https://docs.rs/oxc/0.30.1/oxc

Added in #6035

**Comment by DonIsaac** [comment]
> * [ ]  Eliminate confusing terms by building a glossary?

[We have one](https://oxc.rs/docs/learn/terminology.html) , though it's not very detailed and out of date.

**Comment by Boshen** [comment]
I updated most of the outdated ones.
