### ISSUE TITLE
Error message using npx oxlint --format=json

### ISSUE THREAD

**Issue by lifengsbotlp** [oxc-project/oxc#6099]
oxlint v0.9.7

<img width="911" alt="image" src="https://github.com/user-attachments/assets/e4bfa742-d3a9-49c3-9ba8-460341c53376">

System

<img width="592" alt="image" src="https://github.com/user-attachments/assets/bc9bb306-28e9-4738-89ae-c09fefe1335e">

**Comment by DonIsaac** [comment]
Fixed in #6070
