### ISSUE TITLE
minifier: incorrect constant folding for numeric operators

### ISSUE THREAD

**Issue by KermanX** [oxc-project/oxc#6161]
### Current Behavior

[Playground link](https://playground.oxc.rs/#eNqVlMtugzAQRX/FnQ2tRCJTpYqg6jbrLqqu2Dh0aJCMjWyTh6L8e8fhIbWBQFf4cefMMZZ8hgwSSJWwFo1bWlHip5A1PnLFHt5YEIQsF9JiyIKPHTKDtpaO6Zy1gRRSeGKFbVLB0+sAKgh8kqtRlIc0kSlUa7Xg014LPsOMQJNuHvQvuxlyc9xmqM02ixqzaNysSaQQzTCLrmbRPTPCNJkp2KJVW9xxazN0FXPsiOTTVHTvUltBSk0BU8VYzPk6iuPnl9V6xeM44q317XoQ+nzT14/+th4hpXC78eusqRqVG7LwzIFWE3LDFiOsGzkIQUNyBlMr/7En5cQREmdqDEEWynVjm+kK+8mp3GrZzZwRyubalJBc0ZcQKmHo0J5YkSqaPb4Lg8r2AF2bDDeFREW/hV4zh9YtnT0CFfu212Ia9+xuIdNf+I1eliZloYq8aBpluvS9+haHXUHQSmSE77QyrZzRciP1wZfs0Wy17fcvlx8siJ6k)

```js
// https://github.com/tc39/test262/blob/main/test/language/expressions/does-not-equals/bigint-and-number.js
assert.sameValue(0n != 0, false, 'The result of (0n != 0) is false');

// https://github.com/tc39/test262/blob/main/test/language/expressions/does-not-equals/bigint-and-string.js
assert.sameValue(0n != '', false, 'The result of (0n != "") is false');

// https://github.com/tc39/test262/blob/main/test/language/expressions/unsigned-right-shift/S9.6_A2.2.js
test((-2147483649 >>> 0) !== 2147483647)

// There are a few more tests failing because of possibly the same problem...
```

Is minified to:

```js
assert.sameValue(!0, !1, "The result of (0n != 0) is false"),
assert.sameValue(!0, !1, "The result of (0n != \"\") is false"),
test(!0);
```

---

I couldn't find anything related to this issue in my search. I'm sorry if this is a duplicate report.

**Comment by Boshen** [comment]
For `test((-2147483649 >>> 0) !== 2147483647)`

It's broken somewhere in

https://github.com/oxc-project/oxc/blob/f2ac584bb87f5d27d96016908e0bfb6d9966f631/crates/oxc_minifier/src/ast_passes/peephole_fold_constants.rs#L752-L763

**Comment by Boshen** [comment]
@7086cmd See above comment, I'm having a hard time fixing the code, you may give it a try.

**Comment by 7086cmd** [comment]
Yes, it is painful to handle scenarios with large numbers. Maybe I will handle this together with the bitwise not for large numbers.

**Comment by 7086cmd** [comment]
Found a method that probably helps: https://doc.rust-lang.org/std/primitive.i32.html#method.wrapping_mul.

**Comment by 7086cmd** [comment]
Found a method that probably helps: https://doc.rust-lang.org/std/primitive.i32.html#method.wrapping_sub. Successfully handled the scenario with the bitwise not!

**Comment by 7086cmd** [comment]
Seems solved.
