### ISSUE TITLE
feat(linter): eslint/no-this-before-super

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#618]
Implement ESLint's [`no-this-before-super`](https://eslint.org/docs/latest/rules/no-this-before-super#rule-details) rule.

To get started, run
```sh
just new-rule no-this-before-super
```

_note: this will likely need a control-flow-graph prior to implementing_

**Comment by Boshen** [comment]
Done https://github.com/oxc-project/oxc/blob/main/crates/oxc_linter/src/rules/eslint/no_this_before_super.rs
