### ISSUE TITLE
Transformer don't take `source_type` param

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6248]
Currently `Transformer::new` takes a `source_type` param:

https://github.com/oxc-project/oxc/blob/bc757c89b4974c051fbd660a843e867d864736f1/crates/oxc_transformer/src/lib.rs#L76-L86

Can we get rid of it? `source_type` is present in `Program` and parser updates it from "unambiguous" to either "script" or "module".

It seems to make more sense to use the value of `source_type` present in `Program`, than allow user to over-ride it.

I can't see any circumstance in which that's a useful thing to do, and it's a potential footgun. It's confusing that in transformer it's possible that `self.ctx.source_type.is_script() != !self.ctx.source_type.is_module()`, because it can also be "unambiguous". That's not theoretical - I hit this problem while trying to pass some TypeScript tests.

If for some obscure reason, the user *does* want to override it, they can always alter the value of `Program::source_type` before passing `Program` to transformer.

**Comment by Boshen** [comment]
Yes.

I also wanted a bigger API change for `Source` with path, text and related friends. But you may make this smaller breaking API change first.

**Comment by overlookmotel** [comment]
> I also wanted a bigger API change for `Source` with path, text and related friends.

Ah ha! Yes, that'd be nice. Maybe we could also combine it with https://github.com/oxc-project/backlog/issues/94

```js
let source = Source::from_file(path);
```

This would initialize a `Source` with the provided path, `SourceType` as deduced from the path's file extension, and also read the file from file system (using fast SIMD UTF-8 validation). A one-stop shop!

(we'd also provide more complex methods to create `Source` from a `String`, override `SourceType` etc)

> But you may make this smaller breaking API change first.

OK great. I'll do that now.
