### ISSUE TITLE
napi/transform: ts declaration file - incorrect `Es2015BindingOptions` interface name

### ISSUE THREAD

**Issue by marcalexiei** [oxc-project/oxc#6254]
`Es2015BindingOptions` interface is declared here:

https://github.com/oxc-project/oxc/blob/f98e12c13a62ac8b3231f2447de3d2d7e5916507/napi/transform/index.d.ts#L15

however when used inside `TransformOptions` it has the wrong name:  `ES2015BindingOptions`  (the S is uppercased)

https://github.com/oxc-project/oxc/blob/f98e12c13a62ac8b3231f2447de3d2d7e5916507/napi/transform/index.d.ts#L205

So when compiling with typescript using `skipLibCheck: false` this cause the following error:

```text
node_modules/.pnpm/oxc-transform@0.30.5/node_modules/oxc-transform/index.d.ts:195:12 - error TS2552: Cannot find name 'ES2015BindingOptions'. Did you mean 'Es2015BindingOptions'?

195   es2015?: ES2015BindingOptions
````

----

I noticed that this file is generated using `napi-rs`:

https://github.com/oxc-project/oxc/blob/f98e12c13a62ac8b3231f2447de3d2d7e5916507/napi/transform/index.d.ts#L1

So I assume I can't simply fix the typo and send a PR 😅.
After a quick search in the source code I'm unable to find any reference for the incorrect name (`Es2015BindingOptions`) expect the one in the declaration file, I found only `ES2015BindingOptions`.

I'm not familiar with rust project so I can't provide additional information 😢.

**Comment by shulaoda** [comment]
In `napi-rs`, Rust struct and field names are handled differently when exported to TypeScript interfaces:

1. **Struct names**: When a Rust struct name contains mixed case letters or numbers, `napi-rs` automatically converts it to camelCase. For example, `ES2015BindingOptions` becomes `Es2015BindingOptions` in TypeScript.

2. **Field type references**: When referencing a struct type in another struct (such as in `TransformOptions`), the original struct name is preserved. So, `es2015: Option<ES2015BindingOptions>` retains the original `ES2015BindingOptions` name in TypeScript.

Let me understand the relevant knowledge and see if there is a better solution.

**Comment by marcalexiei** [comment]
Hello shulaoda,
thanks for the detailed explanation and for opening the PR to fix the issue so quickly!
