### ISSUE TITLE
NAPI transform APIs

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6274]
Part of #6156. Here's a proposal for a revamped API for `oxc-transform` NPM package API.

This is draft only. It's a matter of taste, and I don't think there are any "right" answers as to what an API should look like. Other opinions very welcome!

### Principles

As Boshen has pointed out, first impressions matter. People expect to be able to start by throwing in some input and get a result. They shouldn't need to trawl through the docs for loads of obscure options which have to be provided before it works.

So principles are:

1. Keep it simple.
2. Provide sensible defaults - assume input is plain JS, and target is ES6.

I've tried to make API similar to Babel, but changing a few things which have always annoyed me about Babel's API.

### `filename` parameter

Personally, I don't like `filename` being a compulsory parameter to `transform()`. Sometimes there *is* no filename - input is just a code snippet - and having to provide `"fake.js"` as filename feels weird.

`path` is the first option and usually providing options of `{path: '/path/to/input.js'}` is all you need. Source type will be deduced from path (and therefore whether TS/JSX transform is required) - unless you override that with other options.

I think we can avoid any surprise by:

1. Clear error messages. e.g. "Input contains TypeScript syntax, but TS was not enabled. Enable TS by providing `path` option with a `.ts` or `.tsx` extension, or setting option `language: 'typescript'`".
2. Putting an example like this right at the top of the NPM package readme:

```js
import {transform} from 'oxc-transform';

// Simple usage
const {code} = transform('console.log("hello!")');

// Typescript
const {code} = transform(
    'function double(n: number): number { return n * 2; }',
    { language: 'typescript' }
);
// or
const {code} = transform(
    'function double(n: number): number { return n * 2; }',
    { path: '/path/to/input.ts' }
);

// JSX
const {code} = transform('<Hello />', { jsx: true });
// or
const {code} = transform('<Hello />', { path: '/path/to/input.jsx' });
```

### Salient points

* `transform` does not have a `path` param. `path` is provided as an option.
* No `errors` array in return values. Instead throw an error. Throwing errors is more idiomatic in JS.
* Standard way to specify downlevelling target is via `browserslist` query.
* Introduce `transformFile` and `isolatedDeclarationFile` methods which read + write to file system on Rust side. No NAPI overhead passing strings = faster. It's probably what people mostly want to do anyway.
* Don't group transforms by ES edition. Do you know what ES edition optional catch bindings were introduced in? I don't! Average user definitely won't.
* Minimize nested options objects. I find SWC's nested-objects-within-objects options quite difficult to navigate.

### Implementation

I think we should separate out the NAPI options from Rust options, if we need to in order to get a nice JS API. Sometimes what's idiomatic in JS and Rust is not the same.

Convert from NAPI options object to internal Rust options object as a separate "glue" layer on Rust side.

### Full API

```ts
export declare function transform(source: string, options?: TransformOptions): TransformResult;

export declare function transformFile(path: string, outputPath: string, options?: TransformOptions);

export declare function isolatedDeclaration(source: string, options?: IsolatedDeclarationOptions): IsolatedDeclarationResult

export declare function isolatedDeclarationFile(path: string, outputPath: string, options?: IsolatedDeclarationOptions);

// Same as now, except no `errors` property.
// `transform` and `transformFile` throw if any errors.
export interface TransformResult {
    code: string,
    map?: SourceMap,
    declaration?: string,
    declarationMap?: SourceMap,
}

// Same as now, except no `errors` property.
// `isolatedDeclaration` and `isolatedDeclarationFile` throw if any errors.
export interface IsolatedDeclarationResult {
    code: string,
    map?: SourceMap,
}

export interface TransformOptions {
    // --- Source ---

    // Path of input file.
    // Optional, but may throw error if any transforms that need it are enabled.
    // Note: Babel's option is called "filename", but I've always found that confusing.
    // "filename" should mean filename only, "path" means the full path.
    path?: string,

    // Path of root of application.
    // Note: This replaces "cwd". I think "rootPath" is clearer.
    rootPath?: string,

    // Module type of input.
    //
    // Default:
    // * If `path`, provided, based on file extension:
    //   * `.cjs` = 'script'
    //   * `.js`, `.mjs`, `.jsx`, `.ts`, `.tsx` = 'module'
    //   * Anything else = 'module'
    // * No `path` provided = `module'
    moduleType?: 'script' | 'module' | 'unambiguous',

    // Language of input.
    // 'js' is alias of 'javascript', 'ts' is alias of 'typescript'.
    //
    // Default:
    // * If `path`, provided, based on file extension:
    //   * `.js`, `.cjs`, `.mjs`, `.jsx` = 'javascript'
    //   * `.ts`, `.tsx` = 'typescript'
    //   * Anything else = 'javascript'
    // * No `path` provided = 'javascript'
    language?: 'javascript' | 'typescript' | 'js' | 'ts',

    // JSX input?
    // Default:
    // * If `path`, provided, based on file extension:
    //   * `.js`, `.cjs`, `.mjs`, `.ts` = `false`
    //   * `.jsx`, `.tsx` = `true`
    //   * Anything else = `false`
    // * No `path` provided = `false`
    jsx?: boolean,

    // --- Transforms ---

    // Output module type.
    // Not supported until we implement ESM-to-CommonJS transform.
    // 'commonjs' is an alias for 'script'.
    //
    // Default:
    // * If `outputPath` provided, based on file extension:
    //   * `.js`, `.mjs`, `.ts`, `.jsx`, `.tsx` = 'module'
    //   * `.cjs` = 'script'
    //   * Anything else = same as input
    // * No `outputPath` provided = same as input
    outputModuleType?: 'script' | 'module' | 'commonjs',

    // Downlevelling target.
    // `browserslist` query.
    // In future, we can also accept an object e.g. `{node: 20, chrome: 99}`,
    // but just support a string for now.
    // Default: Downlevel to ES6.
    targets?: string,

    // Alternative to `targets`, to specify which transforms exactly.
    // Error if both `targets` and `transforms` are provided.
    // In future we can support merging options here on top of options from browserslist query,
    // but for now, keep it simple.
    // Broken out into separate object to avoid too many options here.
    transforms?: Transforms,

    // Compiler assumptions
    // https://babeljs.io/docs/assumptions
    assumptions?: CompilerAssumptions,

    // --- Source maps ---

    // Generate source map?
    // 'external' is alias for `true`.
    // 'inline' and 'both' not supported yet.
    //
    // Default: `false`
    sourceMaps?: boolean | 'external' | 'inline' | 'both',

    // --- Output ---
    // Primarily for `transformFile`, but also for relative paths in source maps.
    // Specifies paths outputs are written to (`transformFile`),
    // or where they *would* be written to (`transform`).

    // Overwritten by `outputPath` param in `transformFile`.
    // Default: `undefined`.
    outputPath?: string,
    // Default: `outputPath + '.map'`
    outputSourceMapPath?: string,
    // Default: `withoutExt(outputPath) + '.d.ts'`
    outputDeclarationPath?: string,
    // Default: `outputDeclarationPath + '.map'`
    outputDeclarationSourceMapPath?: string,
}

// Transform options.
//
// All these options match the Rust-side transformer options types as closely as possible.
//
// If a transform has options, accept:
// * Options object = transform enabled with provided options
// * `true` = transform enabled with default options
// * `false` or `undefined` = transform disabled
//
// If transform has no options (e.g. `exponentiationOperator`):
// * `true` = transform enabled
// * `false` or `undefined` = transform disabled
export interface Transforms {
    // --- TS and JS ---

    // Automatically set to `false` (i.e. no TS transform) if either:
    // 1. `options.language != 'typescript'`
    // 2. `options.outputPath` has extension `.ts` or `.tsx`
    // Default: Default TS options (i.e. TS transform enabled if input is TS)
    typescript?: TypeScriptOptions | boolean,

    // Automatically set to `false` (i.e. no JSX transform) if either:
    // 1. `options.jsx != true`
    // 2. `options.outputPath` has extension `.jsx` or `.tsx`
    // Default: Default JSX options (i.e. JSX transform enabled if input is JSX)
    jsx?: JsxOptions | boolean,

    // --- Downlevel ---
    // Not grouped in `es2015`, `es2016` etc.
    // People will care about what transforms they want, not what ES edition they were in
    // (same as you choose specific plugins in Babel).

    arrowFunction?: ArrowFunctionOptions | boolean,
    exponentiationOperator?: boolean,
    objectRestSpread?: ObjectRestSpreadOptions | boolean,
    // ...etc...

    // --- Extra ---
    // No `true` as there are no default options for these.

    defineGlobals?: DefineGlobalsOptions | false,
    injectGlobals?: InjectGlobalsOptions | false,
}

export interface TypeScriptOptions {
    // Same as now
}

export interface JsxOptions {
    // Same as now
}

export interface IsolatedDeclarationOptions {
    // Same as now
}

export interface ArrowFunctionOptions {
    // Default: `false`
    spec?: boolean,
}

export interface ObjectRestSpreadOptions {
    // Default: `false`
    setSpreadProperties?: boolean,
}

export interface DefineGlobalsOptions {
    globals: Record<string, string>,
}

export interface InjectGlobalsOptions {
    globals: Record<string, string | [string, string]>,
}

export interface SourceMap {
    // Same as now
}
```

**Comment by daflyinbed** [comment]
what about babel's compiler assumption?

**Comment by overlookmotel** [comment]
> what about babel's compiler assumption?

Thanks for getting involved in the conversation. But sorry I don't understand what you mean. Could you possibly expand on that?

**Comment by Boshen** [comment]
I still disagree with `function transform(source: string, options?: TransformOptions)` being the default.

The chance of the user adding a TypeScript or jsx file is 100%, because they are using the transformer to transform ts or jsx files ... so getting an error message on the first try will be at 100%.

**Comment by Boshen** [comment]
For files like vue and svelte, they input is `<script setup lang="ts">`:

* https://svelte.dev/docs/typescript#script-lang-ts
* https://vuejs.org/guide/typescript/overview.html#usage-in-single-file-components

so for these use cases, we should just accept ... `lang` as an optional argument!

**Comment by overlookmotel** [comment]
> what about babel's compiler assumption?

Oh I'm sorry. Of course you mean this: https://babeljs.io/docs/assumptions

We do have a representation in transformer of these options: [`CompilerAssumptions`](https://github.com/oxc-project/oxc/blob/9736aa01126b414aaf43f9d6fcaf7b62406a6197/crates/oxc_transformer/src/compiler_assumptions.rs)

But none of the transforms currently implemented make any use of it. So we should add it, but we don't have to right now.

**Comment by overlookmotel** [comment]
> what about babel's compiler assumption?

Oh I'm sorry. Of course you mean this: https://babeljs.io/docs/assumptions

Good point. We do have a representation in transformer of these options: [`CompilerAssumptions`](https://github.com/oxc-project/oxc/blob/9736aa01126b414aaf43f9d6fcaf7b62406a6197/crates/oxc_transformer/src/compiler_assumptions.rs)

None of the transforms currently implemented make any use of it. But I've added it above.

**Comment by Boshen** [comment]
(I marked the above comments as off-topic).

> I believe the language option in TransformOptions above covers these cases.

Let me find where exactly are those external plugins altering the language source type ... and what options are they passing them in.

**Comment by overlookmotel** [comment]
Another question: Do you think it's OK to always throw if there are any errors? I *think* it is, but are there any errors which are actually more like warnings and shouldn't block transform from completing?

**Comment by Boshen** [comment]
> Another question: Do you think it's OK to always throw if there are any errors? I _think_ it is, but are there any errors which are actually more like warnings and shouldn't block transform from completing?

The current pipeline always bail on errors, given they are all syntax errors.

Oh btw, the diagnostics code frame has a filename in it, so it is really helpful to provide a filename!

**Comment by Boshen** [comment]
> Let me find where exactly are those external plugins altering the language source type ... and what options are they passing them in.

https://esbuild.github.io/content-types/#javascript

It's the esbuild loader API

https://github.com/vitejs/vite/blob/f721677d8c2b4559f7eb47e0aa4921a3c66f52f1/packages/vite/src/node/optimizer/index.ts#L1083-L1098

**Comment by Boshen** [comment]
We still lack the ability to turn off transforms.

**Comment by Boshen** [comment]
No more actionable items, but I'll come back to this issue when I add more APIs.
