### ISSUE TITLE
Override AST with new custom oxlint Rules 

### ISSUE THREAD

**Issue by IbrahimShamma99** [oxc-project/oxc#6278]
Hello OXC Team,

First off, thank you for the incredible work you're doing on this project. I've been using OXC and have found it to be a fantastic tool!

**Request:** 

Currently in my team we were able to migrate some of the EsLint rules we have to OXC, but  I'd like to request a feature that would allow us to write our custom linting rules, similar to how ESLint enables custom rule creation. Whether the custom rules are written in Rust or TypeScript doesn't matter, I am expecting some sort of override to AST and report warns/errors when specific case occurs. 

I understand that currently built custom rules in my team would not work out of the box since they're built upon `EsTree`.
But I think such a feature would let other OSS maintainers to write their rules as plugins independently.

Lemme know what do you think!

**Comment by DonIsaac** [comment]
Hi @IbrahimShamma99,custom plugins are on our radar. We are working towards this.

**Comment by DonIsaac** [comment]
Closing this as a duplicate.
