### ISSUE TITLE
await in <script type="module>

### ISSUE THREAD

**Issue by lborgman** [oxc-project/oxc#6369]
oxc thinks that "await" is not allowed here. I disagree.

```html
    <script type="module">
        // @ts-check
        const mod = await import(...);
```

**Comment by DonIsaac** [comment]
Looks like we need to update partial loaders to check for `type="module"`. I assume you found this when running `oxlint?`

**Comment by lborgman** [comment]
> Looks like we need to update partial loaders to check for `type="module"`. I assume you found this when running `oxlint?`

Yes, the oxc vscode extension.

**Comment by DonIsaac** [comment]
What kind of file is this? vue, HTML, etc?

**Comment by lborgman** [comment]
> What kind of file is this? vue, HTML, etc?

HTML

**Comment by Boshen** [comment]
@lborgman can you provide the full filename and file content? I cannot reproduce this without more context.

**Comment by lborgman** [comment]
@Boshen 
There is an example here: https://github.com/lborgman/oxc-await

**Comment by Boshen** [comment]
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/b720a97c-9db6-40d8-ac1e-273703f1d9c6">

Is this what you are seeing? This is not coming from oxc (I have oxc extension disabled).

**Comment by Boshen** [comment]
Close as can't repro.

**Comment by lborgman** [comment]
Thanks. I missed that it was not from oxc. Sorry.
