### ISSUE TITLE
VSCode Extension - "oxc client: couldn't create connection to server" after update to 0.9.10

### ISSUE THREAD

**Issue by Talaar** [oxc-project/oxc#6382]
After updating the vscode ext. i'll get connection erros and oxc linting stops.
In 0.9.9 still works.

```
[Error - 12:01:39 PM] oxc client: couldn't create connection to server.
Launching server using command ...\node_modules\.bin\oxc_language_server failed. Error: spawn ...\node_modules\.bin\oxc_language_server ENOENT
```

OS: Win11
Package manager: pnpm

**Comment by shulaoda** [comment]
Are you opening a single project?

**Comment by Talaar** [comment]
Both single and mono repo

**Comment by shulaoda** [comment]
I need to assemble my Windows machine to troubleshoot the issue, please hold on for a moment.

**Comment by shulaoda** [comment]
It seems to be a regression issue caused by issue https://github.com/oxc-project/oxc/issues/3426, which must be an `.exe` file on `Windows`. We need a better way to support `oxc_language_derver`.
