### ISSUE TITLE
Possibility to turn on oxlint --import-plugin in vscode extension

### ISSUE THREAD

**Issue by pumano** [oxc-project/oxc#6416]
Currently `oxc` vscode extension not show error messages for import plugin, but for example rules like `import/no-cycle` is very useful (while in eslint it's time intensive operation) but not working out of the box and not possible to turn on via config.

**Comment by DonIsaac** [comment]
Will be added in #6088

**Comment by pumano** [comment]
@DonIsaac can't wait!) Very important to me feature because I want to be early adopter as possible because my entire team will get benefits from 1 sec linting!

**Comment by DonIsaac** [comment]
Glad you're exited! This will be available in the v1 release.

**Comment by pumano** [comment]
@DonIsaac I build from source today vscode extension, fresh oxlint, oxlint suport plugins in config, when I add "import" It Works perfectly, but vscode extension not show "import" plugin warns / errors

**Comment by DonIsaac** [comment]
You need to change the Path to the  LSP binary

**Comment by pumano** [comment]
looks like problem reproduced in 0.10.0 - vscode extension not show any of warn or error for `import` plugin, while oxlint does. Looks like extension not looking info config "plugins" section while oxlint does.

**Comment by stavalfi** [comment]
hi, when will this be released formally in vscode? my team will be happy as well :)

**Comment by pumano** [comment]
@stavalfi you mean import plugin support, or overall supoort?

**Comment by stavalfi** [comment]
import plugin support for now, but overall support will be great as well ! Thank you!!

**Comment by pumano** [comment]
Looks like since 0.11.0 import rules working in vscode, but bug not in import plugin, but in some rules which not correctly working in vscode. So I close the issue, and open new with more details.
