### ISSUE TITLE
Get line number using oxc-parser

### ISSUE THREAD

**Issue by azat-io** [oxc-project/oxc#6458]
Hello!

Is there any way to get real line number of Node?
Can we add some option to `parseAsync` func to add information about it?

For example, I parse JS and read comments:

```ts
await oxc.parseAsync(source, { sourceFilename: 'test.js' })
return ast.comments
``` 

I get the following result:

```ts
[
  {
    value: ' Comment',
    type: 'Line',
    start: 2,
    end: 10,
  },
]
```

I need to get line number of this comment.

**Comment by leaysgur** [comment]
It's planned, but at the moment we can't get them, even on the Rust side.

Ongoing issue: https://github.com/oxc-project/oxc/issues/959

As referenced there, the only way seems to be to calculate the position from the original file for now.

**Comment by IWANABETHATGUY** [comment]
You can refer https://github.com/oxc-project/oxc/issues/5493

**Comment by overlookmotel** [comment]
Closing, not because it's an unreasonable request, but because I think the answer is covered by #959 and #5493. If I've missed something that's not covered by those two, please feel free to come back.

**Comment by bacarybruno** [comment]
Hello 👋
Now that https://github.com/oxc-project/oxc/pull/8687 is merged, can you please tell us what is the recommended way to get that information on `oxc-parser` ? 🙏

**Comment by bacarybruno** [comment]
Hello @overlookmotel 👋
Now that https://github.com/oxc-project/oxc/pull/8687 is merged, can you please tell us what is the recommended way to get that information on oxc-parser ? 🙏
