### ISSUE TITLE
oxlint v0.9.10 cannot start

### ISSUE THREAD

**Issue by mozhuanzuojing** [oxc-project/oxc#6462]
oxlint cannot start
![image](https://github.com/user-attachments/assets/54316940-d29b-4d59-a6d5-841327a2dfbf)

#### env：
Version: 1.95.0-insider (system setup)
Commit: 4b4bf8f594077c3dc53ef70518531f64ed566194
Date: 2024-10-11T18:44:53.770Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by shulaoda** [comment]
Already fixed in https://github.com/oxc-project/oxc/pull/6384
