### ISSUE TITLE
Consolidate multiple implementations of JavaScript evaluation

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6473]
I believe we have multiple implements of javaScript evalutation in the codebase:

1. constant folding in the minifier
2. evaluation of enum values in the transformer
3. a bit of evaluation in linter/tree_shaking

There may be more in downstream tools.

**Comment by DonIsaac** [comment]
Should I re-open my const eval PR?

**Comment by Boshen** [comment]
> Should I re-open my const eval PR?

That's a whole runtime evaluation, but goal is to detangle the constant evaluation mess 😢

**Comment by Boshen** [comment]
Started moving constant evaluation code in https://github.com/oxc-project/oxc/pull/6549

Will continue the move.
