### ISSUE TITLE
Property 'map' does not exist on type 'RegexpStringIterator<RegExpExecArray>'. ts(2339)

### ISSUE THREAD

**Issue by lborgman** [oxc-project/oxc#6476]
oxc vscode extension thinks that this line is incorrect but Google Chrome seems to think it is ok:

```JavaScript
fsmDeclaration.matchAll(/'([^']*?)'/g).map(m => m[1]);
```

**Comment by camc314** [comment]
can you share a screenshot of vscode?

this looks like a typescript error rather than an error from oxc

**Comment by DonIsaac** [comment]
We do not perform type checking. This is surely a typescript error.

**Comment by lborgman** [comment]
Ok. Thanks.
