### ISSUE TITLE
oxlint should support lint categories in config file

### ISSUE THREAD

**Issue by NateRadebaugh** [oxc-project/oxc#6515]
By default only "recommended" rules are enabled.

I understand I can configure which rules run via the CLI of correctness vs suspicious, etc. as documented here: https://oxc.rs/docs/guide/usage/linter/cli.html#allowing-denying-multiple-lints

I'd like to be able to configure that in the `.oxlintrc.json` file so that the vscode plugin will respect these settings, as well as enforce consistency across developers on projects without needing to put all the details in the `package.json` scripts

**Comment by pumano** [comment]
@NateRadebaugh according to https://github.com/oxc-project/oxc/pull/6088 will be released soon

**Comment by NateRadebaugh** [comment]
Thanks, closing
