### ISSUE TITLE
linter: Cannot register rules with identical names from different plugins

### ISSUE THREAD

**Issue by no-yan** [oxc-project/oxc#6520]
## Summary
Registering rules with identical names from different plugins causes build errors, due to naming conflicts.
As a result, identically named rules cannot be implemented across different plugins (e.g., jest/no-hooks and vitest/no-hooks).

## Example command:

Scaffolding a new Vitest rule that conflicts with an existing Jest rule:
```sh
just new-vitest-rule expect-expect
```

Changes made:

```diff
mod vitest {
+    pub mod expect_expect;
    pub mod no_conditional_tests;
    ...
}

oxc_macros::declare_all_lint_rules! {
    unicorn::throw_new_error,
    vitest::no_conditional_tests,
    ...
+    vitest::expect_expect,
}
```

### Build error:

```sh
> cargo build

error[E0428]: the name `ExpectExpect` is defined multiple times
   --> crates/oxc_linter/src/rules.rs:498:1
    |
498 | oxc_macros::declare_all_lint_rules! {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | `ExpectExpect` redefined here
    | previous definition of the type `ExpectExpect` here
    |
    = note: `ExpectExpect` must be defined only once in the type namespace of this enum
```

## Cause
The macro `oxc_macros::declare_all_lint_rules!` uses rule names as enum variants in RuleEnum.
When identical rule names are registered (e.g., jest/expect-expect and vitest/expect-expect), multiple definitions are created, resulting in a build failure.

In the example below, jest/expect-expect and vitest/expect-expect conflict:

```rs
pub enum RuleEnum {
    ConsistentTestIt(ConsistentTestIt),
    ExpectExpect(ExpectExpect),  // jest/expect-expect
    ...
    ExpectExpect(ExpectExpect),  // Conflict here
    PreferEach(PreferEach),
    PreferToBeFalsy(PreferToBeFalsy),
    PreferToBeObject(PreferToBeObject),
    PreferToBeTruthy(PreferToBeTruthy),
    RequireLocalTestContextForConcurrentSnapshots(RequireLocalTestContextForConcurrentSnapshots),
}
```

This result can be obtained by `cargo expand rules`.

## Impact
There are 43 rules in Vitest with identical names as Jest rules. This prevents their implementation.

<details><summary>List of rules</summary>

<p>

consistent-test-it
expect-expect
max-expects
max-nested-describe
no-alias-methods
no-commented-out-tests
no-conditional-expect
no-conditional-in-test
no-disabled-tests
no-done-callback
no-duplicate-hooks
no-focused-tests
no-hooks
no-identical-title
no-interpolation-in-snapshots
no-large-snapshots
no-mocks-import
no-restricted-matchers
no-standalone-expect
no-test-prefixes
no-test-return-statement
prefer-called-with
prefer-comparison-matcher
prefer-equality-matcher
prefer-expect-assertions
prefer-expect-resolves
prefer-hooks-in-order
prefer-hooks-on-top
prefer-lowercase-title
prefer-mock-promise-shorthand
prefer-snapshot-hint
prefer-spy-on
prefer-strict-equal
prefer-to-be
prefer-to-contain
prefer-to-have-length
prefer-todo
require-hook
require-to-throw-message
require-top-level-describe
valid-describe-callback
valid-expect
valid-title

</p>
</details>

**Comment by DonIsaac** [comment]
Many vitest rules, including `vitest/expect-expect`, have been [adapted for use in `eslint-plugin-vitest`](https://github.com/oxc-project/oxc/blob/97c8a3608fd78c69ce9b324f218b3209029180ff/crates/oxc_linter/src/utils/mod.rs#L21). This rule is already implemented, so you don't need to do it. If you want to try another rule, follow one of the existing rules in the list I linked as a reference.

**Comment by no-yan** [comment]
I was aware that expect_expect had already been implemented, but I didn't know about `VITEST_COMPATIBLE_JEST_RULES`. Thanks for the information!

This isn't urgent, but I think requiring all rule names across different plugins to be unique is impractical in the long term. 
Currently, this works for Vitest because it shares its implementation with Jest. However, as the ecosystem grows, different implementations may end up using the same rule name, making this requirement untenable.
Therefore, it's likely that we will need to revisit and adjust this requirement in the future.

**Comment by no-yan** [comment]
#7082 will address this issue as well.
