### ISSUE TITLE
Enhance .vscode Debug Settings for Easier Debugging in OXC Project

### ISSUE THREAD

**Issue by kth496** [oxc-project/oxc#6541]
It's easy to run the components of the OXC project with the `just` command in the codebase. However, I ended up having to modify the settings in `.vscode` to work with and debug the code.

It would be nice if `launch.json` and `tasks.json` in the `.vscode` directory had more debuggable settings.

**Comment by mysteryven** [comment]
Could you describe which part are you debugging and what's your `.vscode` is?

**Comment by mysteryven** [comment]
We don’t specify IDE/Editor in our development

**Comment by kth496** [comment]
@mysteryven 
I've suggested this because oxc contains '.vscode' directory.

Should '.vscode' be removed?
