### ISSUE TITLE
linter: Wrong path to language server on windows

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [oxc-project/oxc#6581]
### What version of Oxlint are you using?

0.9.10

### What happened?

`node_modules\.bin\oxc_language_server failed. `
this should be `node_modules\.bin\oxc_language_server.CMD` or  `node_modules\.bin\oxc_language_server.ps1`

**Comment by sschneider-ihre-pvs** [comment]
Or should reference the language server bundled with the extension in target/release

**Comment by pumano** [comment]
@sschneider-ihre-pvs could you confirm it's fixed in `oxlint` 0.11.0?

**Comment by sschneider-ihre-pvs** [comment]
Yes it seems to work now 👍
