### ISSUE TITLE
linter: unsafe fixer in `no-useless-spread`

### ISSUE THREAD

**Issue by shulaoda** [oxc-project/oxc#6618]
### What version of Oxlint are you using?

0.9.10

### What happened?

This change has side effects and is unsafe.

```js
> new Array(3).map((item) => { console.log(item) })
```

```js
> [...new Array(3)].map((item) => { console.log(item) })
undefined
undefined
undefined
```

**Comment by DonIsaac** [comment]
I need more details. Is the bottom one the original case? And did you mean the spread to cover the `map` as well?

**Comment by camc314** [comment]
empty items vs undefined

<img width="597" alt="Screenshot 2024-10-16 at 08 58 54" src="https://github.com/user-attachments/assets/58ac4d0d-019e-4176-ae55-71789db80bd7">

**Comment by magic-akari** [comment]
For all cases where n>0, `new Array(n)` always differs from `[...new Array(n)]`.
Hence, I recommend disabling the check for `[...new Array(n)]`.

**Comment by camc314** [comment]
yeah we should disable fixer or suggest a fix of `new Array(5).fill(undefined)`

**Comment by bensaufley** [comment]
I mentioned this on the Discord - I used to use this method to initialize a new array and so this was in my codebase. I've since switched to `Array.from({ length: 5 }, () => {/*…*/})`, for whatever that's worth. That's another option.

**Comment by magic-akari** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/2b469bee475a8f3f2767f4669864acdd89654017/test/no-useless-spread.mjs#L276

`[...new Array(3)]` appears as an invalid case in the test cases of eslint-plugin-unicorn, and I supposed this rule is based on different perspectives and assumptions.

> Sparse arrays are an anti-pattern, so we're not going to change the auto-fix, but we should document the issue with sparse arrays, so people can choose to turn off the rule if they want to use sparse arrays.

_Originally posted by @sindresorhus in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2480#issuecomment-2417777209_

**Comment by shulaoda** [comment]
> But OK, so, this appears to reveal an unrelated issue: I have not enabled any unicorn linters, or `no-useless-spread`.
> then I ran `oxlint -c .oxlintrc.json --fix` and I got this change

This may be because it is recommended and enabled by default in oxlint.
