### ISSUE TITLE
transformer: add style guide for import order

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#6637]
As #6582 does, we can write the import order style guide here. This way can help contributors how write transformer plugins that conform to our style.

https://github.com/oxc-project/oxc/blob/03e033fa05ae439ed035ec5efbc90ed1cfed99a3/crates/oxc_transformer/README.md#L21-L22

**Comment by overlookmotel** [comment]
Personally, I think it'd be ideal if we used this same import order convention in all crates, not just transformer.

So we'd need a universal "style guide". Where would that go? https://oxc.rs/docs/contribute/rules.html?

Or, even better, can we do it automatically with rustfmt/clippy/autofix action?

**Comment by Dunqing** [comment]
=> Or, even better, can we do it automatically with rustfmt/clippy/autofix action?

Yes, please! I can't remember this order.

**Comment by overlookmotel** [comment]
That was a question, not a statement! I don't know if any of these tools support doing that.

**Comment by overlookmotel** [comment]
Thanks @camc314. [group_imports](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#group_imports) with `StdExternalCrate` option gives us *some* of what we want, and would be an improvement. But:

1. It's unstable. Do we run `rustfmt` in nightly mode?
2. It wouldn't enforce `oxc_*` crates being grouped together after external crates.
