### ISSUE TITLE
Include ZWSP in irregular whitespace?

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6646]
#6639 turned up an odd anomaly.

The definition of "whitespace" [used by TypeScript](https://github.com/microsoft/TypeScript/blob/b8e4ed8aeb0b228f544c5736908c31f136a9f7e3/src/compiler/scanner.ts#L556) matches ours except for 1 character - `ZWSP` (`\u{200b}`).

Should this character be included in the group matched by `is_irregular_whitespace`?

**Comment by Boshen** [comment]
Context: https://eslint.org/docs/latest/rules/no-irregular-whitespace

It should be included.

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/blob/9d43a1124d51a3bb530eb815dc14e5a496082be0/crates/oxc_syntax/src/identifier.rs#L59
