### ISSUE TITLE
linter: eslint-plugin-react-hooks(rules-of-hooks) fires when it doesn't in ESLint for a wrapped component

### ISSUE THREAD

**Issue by bensaufley** [oxc-project/oxc#6651]
### What version of Oxlint are you using?

0.9.10

### What command did you run?
```sh
oxlint -c .oxlintrc.json -- path/to/example.tsx
```

### What does your `.oxlint.json` config file look like?
```jsonc
{
  "rules": {
    "react-hooks/rules-of-hooks": "error"
  }
}
```

### What happened?

A functioncomponent declared inside a component factory does not register as a component for the purpose of linting `rules-of-hooks`. Given a very limited reproduction like this (please ignore the particular utility of the example):

```tsx
import { type ComponentType, type ReactNode, useState } from 'react';

interface Options {
  property: string;
}

type MadeComponent<P> = ComponentType<P> & {
  property: string;
};

const makeComponent = <P,>(options: Options, Component: (props: P) => ReactNode) => {
  const Made = Component as MadeComponent<P>;
  Made.property = options.property;

  return Made;
};

const MyComponent = makeComponent({ property: 'foo' }, () => {
  const [value, setValue] = useState('');

  return <input type="text" value={value} onChange={({ currentTarget: { value: v } }) => setValue(v)} />;
});
```

The call to `useState` produces the following error in oxlint:

```
React Hook "useState" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function. [Error]
```

This does not occur in ESlint with the same configuration and the same code. Here's a minimal `.eslintrc.json`, with ESLint 8.56.0 (have not upgraded yet—was investigating oxlint as an alternative):

```json
{
  "plugins": ["@typescript-eslint", "react-hooks"],
  "parser": "@typescript-eslint/parser",
  "rules": {
    "react-hooks/rules-of-hooks": "error"
  },
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "react": {
      "pragma": "h",
      "version": "18.2.0"
    }
  },
  "parserOptions": {
    "tsconfigRootDir": ".",
    "project": "./tsconfig.eslint.json"
  }
}
```

**Comment by taearls** [comment]
if no one has started working on this issue, can I take a stab at it?

**Comment by taearls** [comment]
I did some digging into the source code of the react hooks eslint plugin. It appears that they do not currently support this use case, but they might in the future. 

https://github.com/facebook/react/blob/main/packages%2Feslint-plugin-react-hooks%2F__tests__%2FESLintRulesOfHooks-test.js#L934-L947

Currently, the react hooks eslint plugin only allows React hooks in function components and in other custom React hooks, which aligns with the current behavior of oxlint.

That being said, I'm not sure what the priorities are in terms of version compatibility. Does it make sense to implement a change for a use case that used to be supported, isn't supported now, but might be in the future?

@Boshen @camc314

**Comment by Boshen** [comment]
Thank you for the investigation. Let's align to eslint-plugin-react-hooks to remove ambiguity.

Close as won't fix.

**Comment by bensaufley** [comment]
@Boshen @taearls that isn't true, though. You can use this same code in ESLint and it will not throw a violation. I don't know what to tell you beyond that, but this is not feature parity. You can do this test yourself. `useState` is not a violation with ESLint, but it is with Oxlint

**Comment by bensaufley** [comment]
As an example, I just pulled the react repo and added this test case:

```js
    {
      code: normalizeIndent`
        // Valid because components can call functions.
        const MyComponent = makeComponent(function () {
          useHook();
        });
      `,
    },
```

And it passes.

**Comment by bensaufley** [comment]
It seems like _these_ existing tests are more or less doing the same thing, although the way they're commented makes it seem like they're special exception cases for memo/forwardRef: https://github.com/facebook/react/blob/9daabc0bf97805be23f6131be4d84d063a3ff446/packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js#L181-L230

**Comment by bensaufley** [comment]
OK! This fails: 

```js
    {
      code: normalizeIndent`
        // Valid because components can call functions.
        const MyComponent = makeComponent(function wrappedFunc() {
          useHook();
        });
      `,
    },
```

It looks like [`isInsideComponentOrHook`](https://github.com/facebook/react/blob/9daabc0bf97805be23f6131be4d84d063a3ff446/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L87-L101) searches up the tree for the first component name and checks if it's PascalCase (for components) or `useX` (for hooks). So the anonymous function passes, but if I name the function it fails.

**Comment by camc314** [comment]
so tldr is this right?


Should Pass >> 

```ts
const MyComponent = makeComponent(() => {
    useHook();
});
```

Should Pass >> 

```ts
const MyComponent2 = makeComponent(function () {
    useHook();
});
```

Should Fail >> 
```ts
const MyComponent3 = makeComponent(function foo () {
    useHook();
});
```

**Comment by bensaufley** [comment]
Yes that seems correct to me.

**Comment by bensaufley** [comment]
I _imagine_ this should also pass but I haven't done it myself:

```ts
const MyComponent4 = makeComponent(function InnerComponent() {
  useHook();
});
```

**Comment by camc314** [comment]
thanks @bensaufley i checked that - you're right. i updated the tldr

**Comment by bensaufley** [comment]
Probably should fail?

```ts
const foo = makeComponent(() => {
  useHook();
});
```

That might be covered by other tests etc, but just being thorough

**Comment by camc314** [comment]
@bensaufley this currently passes in eslint so i think we should leave making that one fail out of scope for now.

**Comment by bensaufley** [comment]
Wow, interesting! That surprises me. But yeah def out of scope for parity

**Comment by Boshen** [comment]
Close as out of scope.

**Comment by bensaufley** [comment]
@Boshen the whole thing? Was there a misunderstanding here, or was it decided parity wasn't desired? My "out of scope" comment was just about one specific test case – but much of this is in scope for parity with ESLint

**Comment by camc314** [comment]
i fixed this in some other PR, but i have added these tests as confirmed [here](https://github.com/oxc-project/oxc/issues/6651#issuecomment-2471702361)

**Comment by camc314** [comment]
@bensaufley apologies for the confusion here, mind taking look at the PR and confirming that's what you expected?

**Comment by bensaufley** [comment]
@camc314 thanks! Yes that looks right to me! 🎉

**Comment by taearls** [comment]
@camc314 would you mind linking the PR with the fixes for this when you get a chance? I'd be curious to see what was changed to address this.

**Comment by camc314** [comment]
it was either:
 - https://github.com/oxc-project/oxc/pull/7606 i think this one
 - https://github.com/oxc-project/oxc/pull/7570
