### ISSUE TITLE
Variable and Type declarations are merged into a single symbol in oxc_semantic

### ISSUE THREAD

**Issue by valeneiko** [oxc-project/oxc#6689]
## Summary

A common pattern to define enum in TS is:
```ts
export const Foo = [
  'bar',
  'baz'
] as const;

export type Foo = typeof Foo[number];
```

There are 2 distinct declarations here with the same name, but oxc_semantic symbol table merges them into one. 

## Actual result

`const Foo` is recorded in the symbol table. But `type Foo` is entirely missing.
Instead the `const Foo` declaration gains a `TypeAlias` flag.

[OXC Playground](https://playground.oxc.rs/#eNpFjksOgzAMRK8SecOGE1B1yyWARaCmQkrsyAktFOXuJWpCV37jz3gOmKAB3BxLUBOTD6plVnfV9aRUNWqp6kyfqqdBaf9bu/XUU74Lu8N8lpDnJDpa7Ygy3KAGhuYAWSkVv1PQGzRBVqzBLBQK+4kdXmK3I5uigmjyM4uFZtbGY6zBafEop+PJyaXwtVoaEz/wien3KexCy7z8RxSETWv4naK9UEb2OUKM8QtSumPE)

```json
[
  {
    "name": "Foo",
    "span": {
      "start": 13,
      "end": 16
    },
    "nodeId": 4,
    "scopeId": 0,
    "flags": "BlockScopedVariable | ConstVariable | Export | TypeAlias",
    "references": [
      {
        "nodeId": 24,
        "flags": "Type"
      }
    ]
  }
]
```

## Expected result

`const Foo` and `type Foo` should be treated as 2 distinct symbols: the same way they would be if they were named differently.

[OXC Playground](https://playground.oxc.rs/#eNpFjjEOgzAMRa8SeWHhBKCunKAbMARqKqRgR05ooSh3b6ISOvl929/+B4xQAW6WxauRyXnVMKubajtSqhi0FOVJn6KjXmn3W6s76uj0+d1ist2jLzFPSbW0LgNKX0MJDNUBslIqbievN6i8rFiCmclndiNbvMS+DGyy8qLJTSwLVJM2DkMJVotDiRcjpyuZr9XcGPmBT0y/o1hmmqf5PyIvbBrD7xTthTKwOyOEEL6xGWQY)

```json
[
  {
    "name": "Foo",
    "span": {
      "start": 13,
      "end": 16
    },
    "nodeId": 4,
    "scopeId": 0,
    "flags": "BlockScopedVariable | ConstVariable | Export",
    "references": [
      {
        "nodeId": 24,
        "flags": "Type"
      }
    ]
  },
  {
    "name": "Foo",
    "span": {
      "start": 63,
      "end": 66
    },
    "nodeId": 19,
    "scopeId": 0,
    "flags": "Export | TypeAlias",
    "references": []
  }
]
```

This would also match what TypeScript does ([TS AST Viewer](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7wGIQnAvHAbQCg44ByAIwEMoyAaE86gLzKIF04rVEV0BuIkVCRYcGAE8wwOFhz5J0iADNZ2AsgCuAWwrAo7fkA))
![ts-symbol-definition](https://github.com/user-attachments/assets/c54f631d-6ea0-42aa-a229-70d9bedde7e0)

**Comment by DonIsaac** [comment]
This is expected behavior. Typescript does the same thing, except it stores a list of declarations and we only store the last one.

**Comment by Dunqing** [comment]
> This is expected behavior. Typescript does the same thing, except it stores a list of declarations and we only store the last one.

As @DonIsaac said, This is expected behavior. Feel free to ask for help with `semantic`!

**Comment by valeneiko** [comment]
Just looked at semantic source in a bit more details. Indeed, I missed the fact symbol table also has all the redeclarations stored separately.

Anyway, the actual bug that prompted this issue is: `get_symbol_id_from_span` not returning the symbol, if I use one of the redeclaration spans. Here is the PR to fix it:
- #6701
