### ISSUE TITLE
minifier: cannot preserve unknown global reference in property key inside function body

### ISSUE THREAD

**Issue by KermanX** [oxc-project/oxc#6769]
[playground](https://playground.oxc.rs/#eNp1jrFOxDAQRH/FcpVIkU60QUd5lCBaQuH4NmDh7EZr+8IpSknHJ8DP8SXYhxzQ6VJlJt55M5PUspabjfj++hDb7Y3osChKEcU0lw3+uQaFKCbxGPAVacRbS62yT7W4EuluLq8bbDBxPt9PnMunDa4xzvNL81rg/7rVm0iVlSRZT5IDpo87oldvsvYcoJLWoM/aaRpgMce+JZudZ4WuI+5l3SnrYK7koNgBJ+LAENUB7hUDuhxR1tL4AD4w3gXvzB52AbU3FFdkRmo/MaJeKvIPTXt4hrQ5mt6g6cxvn6Y+VS5N44vx4Aal4/hM1oSeye7ihhQ5ALfklvd5/gFe0qyR)

```js
// ❌ ==> fn(() => {})
fn(() => {
  ({ [unknownGlobal]: 1 })
});

// ✅ ==> { [unknownGlobal]: 1 }
({ [unknownGlobal]: 1 });

// ✅ ==> fn(() => ({ [unknownGlobal]: 1 }))
fn(() => ({ [unknownGlobal]: 1 }));
```

**Comment by Boshen** [comment]
As a side note, it seems problematic to remove anything that has a side effect https://github.com/tc39/test262/blob/main/test/language/literals/numeric/S7.8.3_A4.1_T6.js

**Comment by camc314** [comment]
Yeah if a ref to the var isn't in scope, we can't remove it. minification is hard 😅 

```ts
fn(() => {
  ({ [unknownGlobal]: 1 })
});
```
should become
```ts
fn(() => {
    unknownGlobal
});
```

As a side note. i think some of closure compilers' test cases are incorrect
e.g.:
https://github.com/google/closure-compiler/blob/f888b14e237f6f18f9cb66eeef3e79f398c45a68/test/com/google/javascript/jscomp/PeepholeRemoveDeadCodeTest.java#L106
the ref to `x` should not be removed
https://github.com/google/closure-compiler/blob/f888b14e237f6f18f9cb66eeef3e79f398c45a68/test/com/google/javascript/jscomp/PeepholeRemoveDeadCodeTest.java#L107
the ref to `foo` should not be removed

**Comment by Boshen** [comment]
@camc314 try https://closure-compiler.appspot.com/home if the test case is ambiguous.

**Comment by camc314** [comment]
yep i see.
should we be trying to keep scopes in sync with the minified program?
