### ISSUE TITLE
Linter benchmarks run on PRs with no changes related to linter

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6824]
#6705 was intended to prevent linter benchmarks running on PRs which don't touch any code related to the linter.

It doesn't seem to be working. Linter benchmarks ran on #6814 which only changes 1 file in `oxc_traverse`.

@DonIsaac Any idea why this is?

**Comment by Boshen** [comment]
path negation doesn't work in `picomatch`.
