### ISSUE TITLE
oxc-parser解析出的AST目前有js工具可以成功生成代码吗？escodegen和recast测试都不行。rust我看有oxc_codegen，js是不是还没有

### ISSUE THREAD

**Issue by AnChunLi** [oxc-project/oxc#6850]

**Comment by Boshen** [comment]
no.

**Comment by AnChunLi** [comment]
Is there any js tool that can successfully generate code for the AST parsed by oxc-parser? Neither escodegen nor recast tests work. rust I see oxc_codegen, js is not yet

Is there no plan to support the js version of the generator？

**Comment by Boshen** [comment]
Everything on the js side is unstable at the moment.
