### ISSUE TITLE
Release new `@oxc-project/types` NPM package

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#6862]
#6755 and #6796 introduced a new NPM package `@oxc/types`. But we don't control the `@oxc` NPM scope. We need to decide a name for this package. `oxc-types`? `@oxc-project/types`?

Also, those PRs altered the publish workflows, and I'm not sure if this was all reviewed or not before merging.

We should not make a release until this is resolved. Releasing from current state of repo would break `oxc-parser` and `@oxc-parser/wasm` NPM packages.

**Comment by Boshen** [comment]
`@oxc-project/types`

**Comment by overlookmotel** [comment]
#6874 changed the package name to `@oxc-project/types`.

@Boshen is there anything else we need to do to make package release work, or are we all set to release these types onto the world?

**Comment by ottomated** [comment]
Looks like the release CI needs to be kickstarted by a manual release with how the version check works.
