### ISSUE TITLE
transformer: turn off typescript and jsx plugin by option and sourcetype 

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6865]
typescript and jsx plugins should be 

* turned off by default when the source type is not ts / jsx.
* can be turned off by an option

Change proposal:

```rust
struct TransformerImpl<'a, 'ctx> {
    x0_typescript: TypeScript<'a, 'ctx>,
    x1_react: React<'a, 'ctx>,
```

```rust
pub struct TransformOptions {
    pub typescript: TypeScriptOptions,
    pub react: JsxOptions,
}
```

Make these two optional.

In `oxc_transformer/src/lib.rs`,

change code to

```rust
        self.x0_typescript.map(|plugin| plugin.enter_program(program, ctx));
```

**Comment by overlookmotel** [comment]
We use 2 different patterns for representing whether a transform is enabled or not.

Mostly we use a boolean flag e.g.:

https://github.com/oxc-project/oxc/blob/b075982eaa6d11838a676d9129703f4d1070d7e8/crates/oxc_transformer/src/es2019/mod.rs#L24-L28

In other places it's an `Option` e.g.:

https://github.com/oxc-project/oxc/blob/b075982eaa6d11838a676d9129703f4d1070d7e8/crates/oxc_transformer/src/es2015/mod.rs#L29-L33

I'm not sure which is better. But it's probably worth investigating perf impact of each and standardizing one way or the other. These "is transform enabled?" checks are on an extremely hot path, so it may well have a measurable impact.

But for now, yes, the pattern you suggest looks good.

**Comment by Boshen** [comment]
We need to avoid the constructor call as well, which has a bit of logic overhead.

**Comment by Boshen** [comment]
#6889 fulfills my requirement, all the other change proposals is a bit more complicated.
