### ISSUE TITLE
pnpm lockfile is going to go into and out of sync

### ISSUE THREAD

**Issue by ottomated** [oxc-project/oxc#6914]
cc @Boshen
#6910 fixed a CI issue by disabling the lockfile check, but the underlying issue is this:
- ephemeral packages that are gitignored (i.e.`npm/parser-wasm`) need to be part of the pnpm workspace because they have a dependency
- Running `pnpm i` without those packages on your filesystem removes the references to them from the pnpm lock
- CI then generates those packages and tries to `pnpm i` but the lockfile is out of sync.

Not sure what the best move is. Maybe the `package.json`s need to be checked in?

**Comment by Boshen** [comment]
Check in `npm/parser-wasm`.
