### ISSUE TITLE
transformer: add es `target`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6982]
Babel does not have `target`, but we need it to make oxc-transform compatible with tsc / esbuild.

**Comment by overlookmotel** [comment]
Just to clarify, is `target` a browserslist query? Or something else?

**Comment by Boshen** [comment]
> Just to clarify, is `target` a browserslist query? Or something else?

Babel `targets` https://babel.dev/docs/options#targets

ESBuild `target` https://esbuild.github.io/api/#target

tsc `target` https://www.typescriptlang.org/tsconfig/target.html

**Comment by Dunqing** [comment]
Agree! When we have a target option, we can solve https://github.com/oxc-project/oxc/pull/6023.
