### ISSUE TITLE
transformer: needs to inject `babelHelpers` to run exec tests

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#7019]
Some plugins will transform code and wrap in helper functions, but now we haven't injected the `babelHelpers` global variable, which caused our exec tests to fail as long as we use the helper function. e.g: #6573

The implementation is like #6818 and would be better if we could reuse it

**Comment by Boshen** [comment]
* https://github.com/oxc-project/oxc/pull/7114
* https://github.com/oxc-project/oxc/pull/7121
