### ISSUE TITLE
linter: add support "ignores" to config

### ISSUE THREAD

**Issue by pumano** [oxc-project/oxc#7032]
### What version of Oxlint are you using?

0.10.3

### What does your `.oxlint.json` config file look like?

proposed example:

```json
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "ignores": [
      "packages/*",
      ".nx/",
      "dist/"
  ],
  "plugins": ["import", "unicorn"],
  "rules": {
    "oxc/no-barrel-file": "warn"
  }
  ```

### What happened?

When I use eslint flat config with eslint 9, eslint spam me warning about not use `.eslintignore` which is only way to ignore files and folders supported by `oxlint`. 

I suggest to support `"ignores"` in config from eslint flat config which way to set paths for ignoring. Link to `ignores` in eslint website: https://eslint.org/docs/latest/use/configure/ignore

After it implemented people from eslint 9 can use `oxlint` without annoying warnings.

**Comment by DonIsaac** [comment]
Is an .eslintignore not sufficient?

**Comment by pumano** [comment]
> Is an .eslintignore not sufficient?

It's deprecated in eslint 9, and it's warn every time I run eslint
