### ISSUE TITLE
When I use visit_function method to traverse a function node, how do I convert the function node from AST to code?

### ISSUE THREAD

**Issue by JasithC** [oxc-project/oxc#7046]
When I get a Function node, how do I get the source code corresponding to the node?

    fn visit_function(&mut self, it: &mut Function<'a>, flags: ScopeFlags) {
        walk_function(self, it, flags);
        // How to get the source code?
    }

**Comment by Boshen** [comment]
https://docs.rs/oxc_span/latest/oxc_span/struct.Span.html#method.source_text
