### ISSUE TITLE
linter: `declare_all_lint_rules!` macro naming collision between modules

### ISSUE THREAD

**Issue by pumano** [oxc-project/oxc#7082]
### What version of Oxlint are you using?

0.10.3

### What happened?

It's impossible to expose rules for example `import/no-namespace` rule due to naming collision with `typescript/no-namespace` in `declare_all_lint_rules!` macro

**Comment by Sysix** [comment]
is fixed with https://github.com/oxc-project/oxc/pull/7496

tested it in snapshot `eslint-plugin-eslint`: https://github.com/oxc-project/eslint-plugin-oxlint/pull/262/files#diff-ff389c66187cc169595103ea27c278a8cd64c4bd64570834fcee87b9aafd1fa4R289-R291
