### ISSUE TITLE
Linter should detect configuration file(s) if not provided

### ISSUE THREAD

**Issue by NateRadebaugh** [oxc-project/oxc#7101]
Can we standardize on `oxlint.json` or similar as the default config file that's supported?  There's been a few times in testing where I add a config file and forget to add it to the CLI and then get confused for a while trying to figure out why my configuration isn't being respected.

This would make onboarding easier.

Or at the end of running, perhaps spit out the name of the config file, or a warning if no config was provided/detected?

**Comment by Sysix** [comment]
The CLI now autodetect the `.oxlintrc.json` file in [v0.13.1](https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.13.1)
