### ISSUE TITLE
linter: `--import-plugin` checking inside `node_modules`

### ISSUE THREAD

**Issue by anthonyshew** [oxc-project/oxc#7123]
### What version of Oxlint are you using?

0.11.0

### What command did you run?

`oxlint -A all -D no-cycle --import-plugin`

### What does your `.oxlint.json` config file look like?

Don't have one!

### What happened?

We have a dependency that has `// @flow` in node_modules that throws out an error. I tried to patch-package it, but then it threw on a different error for `import { type foo } ...`.

When I remove `--import-plugin`, the error stops showing up. The exact dependency in question is `react-select@4.3.1`.

**Comment by DonIsaac** [comment]
Is this file actually using flow syntax? And is it being imported (either directly or as an import of an import)?

If so, this is intentional behavior.

**Comment by Boshen** [comment]
> The exact dependency in question is react-select@4.3.1

Which file exactly? I'm not seeing any published files with a `// @flow` comment.

**Comment by anthonyshew** [comment]
The files with the `//flow` comment are here: https://github.com/JedWatson/react-select/tree/d5c5ccd864ebba7c9d8a41146be666dff9b79b38/packages/react-select/src/components

Realizing now, I forgot to add that I tried to ignore errors from `node_modules` using `--ignore-path=node_modules` and that didn't help. I didn't really expect it to, but was worth a try. 😄

@DonIsaac, can you say why this would be the intended behavior? It's being imported into our code, but I was hoping I could lint our code, not node_modules. I'm sure there's a good reason why and I'm just not getting it.

**Comment by pumano** [comment]
@anthonyshew try to add `.eslintignore` in root folder of project and add `node_modules/*` to that. That should helps you.

**Comment by anthonyshew** [comment]
@pumano A `.eslintignore` file doesn't look like it's working for me either.
