### ISSUE TITLE
linter: VS Code logging settings

### ISSUE THREAD

**Issue by nrayburn-tech** [oxc-project/oxc#7136]
### What version of Oxlint are you using?

main

### What happened?

A few things I noticed when doing some testing in VS Code.

1. `oxc.trace.server` should be used to modify the logging.  Currently `oxc-vscode.trace.server` is what actually works.
    - I believe this is due to the `languageClientId` configured within the extension.  I don't know the implications of changing this to `oxc` or how to get this working using `oxc` without changing the `languageClientId`.
    - Having this available and working will add something else we can request from users for bug reports.
    - Resolved with https://github.com/oxc-project/oxc/pull/7181
1. Should there actually be two different output channels?  It could be replaced with a single `LogOutputChannel` instead of an `OutputChannel`. The `LogOutputChannel` allows the user to modify the log level on the fly in the UI.
    - When testing this, I noticed duplicate timestamps so it might need some additional changes.  Seems like VS Code adds a timestamp but our message also includes a timestamp.
    - https://github.com/oxc-project/oxc/pull/7196

**Comment by pumano** [comment]
also confirm that, only `oxc-vscode.trace.server` works, which is bug for end user, because currently it's not possible for end user turn on trace via `oxc.trace.server`

**Comment by Boshen** [comment]
I don't know how vscode works, feel free to make the changes that are reasonable.
