### ISSUE TITLE
wrong `comment.start` position

### ISSUE THREAD

**Issue by lukeed** [oxc-project/oxc#7150]
The OXC comment locations are off. It sets `start` as the index of the begin-comment syntax; eg; after `// ` or `/*` or `/** `.

For the example below, OXC reports:

1. range `[2, 14]` with `value=" hello world"`
2. range `[53, 63]` with `value="* another "`

And Babel reports:

1. `[0, 14]` with `value=" hello world"`
2. `[51, 65]` with `value="* another "`
    _Note that OXC `end` index is incorrect for Block comments too, despite matching value._

> [OXC](https://playground.oxc.rs/#eNpFTkuuwjAMvIrl1XtVpQrYBbHlFN2kwYVIiV05CR+h3p1UqGXlGdvzeaNDg10HNwpB4CEaLj3TcxLNMBZ22QtDKvHPtjD8G+ASB9Jjzz13TQOWJd9Ioek2lRNOVSsCJ9jtD0dsUdC8UQsvI7042yearIVaDJ7zipOTiTbyioOElWW1nEbRiGa0IdHc4mQ1kVbHiheXFW+v68LJha60ZFcSPfvR/06cVcI5yGOpdicdJNUK34x5/gCzc2O0)

> [Babel Playground](https://astexplorer.net/#/gist/7873554cbc634ef7893c1593aeae1afe/8b917fa204cd3630077038a5d8d6d5f9e117b9d8)

**Comment by leaysgur** [comment]
This isn't a comment to solve the issue, but I've investigated the current situation, so I'm leaving a note here.

https://github.com/oxc-project/oxc/blob/0b329516372a0353e9eb18e5bc0fbe63bce21fee/crates/oxc_parser/src/lexer/trivia_builder.rs#L43-L51

https://github.com/oxc-project/oxc/blob/0b329516372a0353e9eb18e5bc0fbe63bce21fee/crates/oxc_ast/src/ast/comment.rs#L45-L47

https://github.com/oxc-project/oxc/blob/0b329516372a0353e9eb18e5bc0fbe63bce21fee/crates/oxc_ast/src/ast/comment.rs#L104-L121

`Comment` AST seems to have `span` and `real_span()`. We need to use `real_span()` for the AST?

**Comment by Dunqing** [comment]
It looks like we should align with `Babel` or others, considering users may use NPM packages rather than Rust crate.

**Comment by lukeed** [comment]
Thank you 🏆
