### ISSUE TITLE
linter: `no-unused-vars` should support settings "ignoreRestSiblings"

### ISSUE THREAD

**Issue by pumano** [oxc-project/oxc#7157]
### What version of Oxlint are you using?

0.11.0

### What command did you run?

oxlint -c oxlintrc.json --quiet

### What does your `.oxlint.json` config file look like?

```json
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "rules": {
    "no-unused-vars": [
      "error",
      {
        "vars": "all",
        "args": "none",
        "caughtErrors": "none",
        "ignoreRestSiblings": true
      }
    ]
  }
}
```

### What happened?

it's not possible to configure "ignoreRestSiblings" in eslint `no-unused-vars`. Documentation: https://eslint.org/docs/latest/rules/no-unused-vars#ignorerestsiblings

example of code as example for testing:

#### **`kebab-case.pipe.ts`**

```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'kebabCase',
  standalone: true,
})
export class KebabCasePipe implements PipeTransform {
  transform(value: string, ...args: string[]): string {
    return value.toLowerCase().replace(/ /g, '-');
  }
}
```

```sh
 × eslint(no-unused-vars): Variable 'args' is declared but never used.
    ╭─[libs/some-lib/src/lib/pipes/kebab-case.pipe.ts:9:28]
  8 │ export class KebabCasePipe implements PipeTransform {
  9 │   transform(value: string, ...args: string[]): string {
    ·                            ────────┬────────
    ·                                    ╰── 'args' is declared here
 10 │     return value.toLowerCase().replace(/ /g, '-');
    ╰────
  help: Consider removing this declaration.
```

**Comment by camc314** [comment]
does the configuration option not work?
it looks like this is implemented

https://github.com/oxc-project/oxc/blob/main/crates/oxc_linter/src/rules/eslint/no_unused_vars/options.rs#L70-L85

**Comment by taearls** [comment]
Hi! I'd like to take a stab at fixing this issue.

**Comment by pumano** [comment]
@camc314 yes, it's not working as expected

**Comment by pumano** [comment]
@taearls 

test case for `eslint.rs`:

```rs
(
    r#"
    @Pipe({
        name: 'kebabCase'
    })
    export class KebabCasePipe implements PipeTransform {
        transform(value: string, ...args: string[]): string {
            return value.toLowerCase().replace(/ /g, '-');
        }
    }
    "#, Some(serde_json::json!([{ "ignoreRestSiblings": true }]))
),
```

**Comment by camc314** [comment]
@pumano 

apologies. i just reread this issue and sawh your minimal repo.

the rule is working correctly in this case.

ignoreRestSiblings is used when omitting properties from an object e.g.

const { id, ...rest } = user

since this is a rest parameter (arguments) its correct to report in this case

**Comment by taearls** [comment]
@camc314 good catch. I also noticed that if you comment out the `value` argument in the function body, the ignoreRestSiblings rule does get applied, so a lint error will not be thrown. the restful parameter itself, however, is not ignored (which, to your point, aligns with the eslint spec for `ignoreRestSiblings`). this means that `...args` must be referenced or it will throw an error (assuming `no-unused-vars` is enabled)
 
https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJpZ25vcmVSZXN0U2libGluZ3NcIjogdHJ1ZSB9XSovXG5cbi8vICdmb28nIGFuZCAnYmFyJyB3ZXJlIGlnbm9yZWQgYmVjYXVzZSB0aGV5IGhhdmUgYSByZXN0IHByb3BlcnR5IHNpYmxpbmcuXG52YXIgeyBmb28sIC4uLnJlc3QgfSA9IGRhdGE7XG5jb25zb2xlLmxvZyhyZXN0KTtcblxuLy8gT1JcblxudmFyIGJhcjtcbih7IGJhciwgLi4ucmVzdCB9ID0gZGF0YSk7XG5cbmV4cG9ydCBjbGFzcyBLZWJhYkNhc2VQaXBlIHtcbiAgdHJhbnNmb3JtKHZhbHVlLCAuLi5hcmdzKSB7XG4gICAgY29uc29sZS5sb2coYXJncyk7XG4gICAgLy8gcmV0dXJuIHZhbHVlLnRvTG93ZXJDYXNlKCkucmVwbGFjZSgvIC9nLCAnLScpO1xuICB9XG59Iiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==

there's a lot of existing test coverage for this rule, so I'm not sure that anything needs to be added from what I can tell. if there's nothing to do here, I'll leave this alone.

**Comment by camc314** [comment]
```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'kebabCase',
  standalone: true,
})
export class KebabCasePipe implements PipeTransform {
  transform(value: string, ...args: string[]): string {
    return value.toLowerCase().replace(/ /g, '-');
  }
}
```

with:
```
{ "ignoreRestSiblings": true }
```

report:
```
  ⚠ eslint(no-unused-vars): Variable 'args' is declared but never used.
   ╭─[no_unused_vars.tsx:8:28]
 7 │ export class KebabCasePipe implements PipeTransform {
 8 │   transform(value: string, ...args: string[]): string {
   ·                            ────────┬────────
   ·                                    ╰── 'args' is declared here
 9 │     return value.toLowerCase().replace(/ /g, '-');
   ╰────
  help: Consider removing this declaration.
```

---

```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'kebabCase',
  standalone: true,
})
export class KebabCasePipe implements PipeTransform {
  transform(value: string, ...args: string[]): string {
      return ''
  }
}
```

with:
```
{ "ignoreRestSiblings": true }
```

report:
```
  ⚠ eslint(no-unused-vars): Parameter 'value' is declared but never used.
   ╭─[no_unused_vars.tsx:8:13]
 7 │ export class KebabCasePipe implements PipeTransform {
 8 │   transform(value: string, ...args: string[]): string {
   ·             ──┬──
   ·               ╰── 'value' is declared here
 9 │     return ''
   ╰────
  help: Consider removing this parameter.

  ⚠ eslint(no-unused-vars): Variable 'args' is declared but never used.
   ╭─[no_unused_vars.tsx:8:28]
 7 │ export class KebabCasePipe implements PipeTransform {
 8 │   transform(value: string, ...args: string[]): string {
   ·                            ────────┬────────
   ·                                    ╰── 'args' is declared here
 9 │     return ''
   ╰────
  help: Consider removing this declaration.
```

---



```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'kebabCase',
  standalone: true,
})
export class KebabCasePipe implements PipeTransform {
  transform(...args: string[]): string {
    return ''
  }
}
```

with:
```
{ "ignoreRestSiblings": true }
```

report:
```
  ⚠ eslint(no-unused-vars): Variable 'args' is declared but never used.
   ╭─[no_unused_vars.tsx:8:13]
 7 │ export class KebabCasePipe implements PipeTransform {
 8 │   transform(...args: string[]): string {
   ·             ────────┬────────
   ·                     ╰── 'args' is declared here
 9 │     return ''
   ╰────
  help: Consider removing this declaration.
```

---


> I also noticed that if you comment out the value argument in the function body, the ignoreRestSiblings rule does get applied, so a lint error will not be thrown

is this in eslint or oxc? mind looking at the 2nd case above? i think it's reporting correctly?




@pumano i'm going to close this as i believe it's behaviour is correct - feel free to reply if you disagree.

**Comment by pumano** [comment]
@camc314 yes, you are right, I'm not correctly understand the settings for `ignoreRestSiblings` my bad.
