### ISSUE TITLE
Possible logic error in arrow functions transform

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#7174]
While reviewing #7113, I was confused by the logic in `get_arrow_function_scope`. Previously this function returned the `ScopeId` of enclosing arrow function (as the function's name suggests). But now it also returns the `ScopeId` of a class method or object method:

https://github.com/oxc-project/oxc/blob/b57d5a5277be14c02625fa3e223baeca86b5acb0/crates/oxc_transformer/src/common/arrow_function_converter.rs#L399-L409

Is this correct?

If it *is* correct, the name of the function should probably be changed to reflect what it's now doing, and a comment added explaining why.

**Comment by Dunqing** [comment]
It is correct, If async only, we need to treat the class async method and object async method as the `ArrowFunction` because the behavior is the same with `ArrowFunction`. I will change a suitable name to it.
