### ISSUE TITLE
Async function transforms mis-identifying object properties as methods

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#7175]
Stack up to #7148 contains a few places where it checks if a `Function` is an object method with `matches!(parent, Ancestor::ObjectPropertyValue(_))`. I think the code it's trying to match is:

```js
obj = {
    async function foo() {}
};
```

But it will also match where the function is a *property value*, not a method:

```js
obj = {
    foo: async function() {}
};
```

I think also need a check `if object_prop.method` to be able to tell the difference between the two.

https://github.com/oxc-project/oxc/blob/b57d5a5277be14c02625fa3e223baeca86b5acb0/crates/oxc_transformer/src/common/arrow_function_converter.rs#L401-L404

https://github.com/oxc-project/oxc/blob/c307e1b7e84a145f00a2c2e7b68b7f58baa817de/crates/oxc_transformer/src/es2017/async_to_generator.rs#L136-L140

https://github.com/oxc-project/oxc/blob/c307e1b7e84a145f00a2c2e7b68b7f58baa817de/crates/oxc_transformer/src/es2018/async_generator_functions/mod.rs#L148-L152

Personally, I think it'd be ideal if AST didn't use `ObjectProperty` for both properties and methods, to avoid this confusing ambiguity. https://github.com/oxc-project/backlog/issues/142

**Comment by Dunqing** [comment]
Yes, we should skip non-method ObjectPropertyValue
