### ISSUE TITLE
codegen: print esbuild trailing legal comments

### ISSUE THREAD

**Issue by hyf0** [oxc-project/oxc#7190]
```js
//! <script>foo</script>
export let x

console.log('in a') //! Copyright notice 1

console.log('in b') //! Copyright notice 1

console.log('in c') //! Copyright notice 2

export default () => {
	/**
	 * @preserve
	 */
}
```

output(pure codeggen, without bundling)

```js

//! <script>foo</script>
export let x;
console.log("in a");
console.log("in b");
console.log("in c");
export default () => {};

```

[esbuild](https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00%2F%2F%21+%3Cscript%3Efoo%3C%2Fscript%3E%0Aexport+let+x%0A%0A%0A%0Aconsole.log%28%27in+a%27%29+%2F%2F%21+Copyright+notice+1%0A%0Aconsole.log%28%27in+b%27%29+%2F%2F%21+Copyright+notice+1%0A%0Aconsole.log%28%27in+c%27%29+%2F%2F%21+Copyright+notice+2%0A%0Aexport+default+%28%29+%3D%3E+%7B%0A%09%2F**%0A%09+*+%40preserve%0A%09+*%2F%0A%7D&b=%00foo.js%00&o=--bundle+--splitting+--format%3Desm+--external%3Aext+--outdir%3Ddist+--legal-comments%3Dinline) 

```js
// entry.js
//! <script>foo<\/script>
var x;
console.log("in a");
//! Copyright notice 1
console.log("in b");
//! Copyright notice 1
console.log("in c");
//! Copyright notice 2
var entry_default = () => {
  /**
   * @preserve
   */
};
export {
  entry_default as default,
  x
};

```

**Comment by hyf0** [comment]
It would be nice if the codegen part of playground support comment-related options.

**Comment by Boshen** [comment]
I fixed the empty body case.

The `console.log('in a') //! Copyright notice 1` case contradicts to the documentation https://esbuild.github.io/api/#legal-comments

> Note that "statement-level" for JS and "rule-level" for CSS means the comment must appear in a context where multiple statements or rules are allowed such as in the top-level scope or in a statement or rule block. So comments inside expressions or at the declaration level are not considered legal comments.

esbuild's parser saved these trailing comments as statement level comments

https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/js_parser/js_parser.go#L8154-L8166

I'm undecided whether we should handle such cases. It takes a lot more work to handle such cases.

**Comment by hyf0** [comment]
Since printing legal comments only have a pratical standard from esbuild, I guess we could wait for users feedback and decide what's next.

**Comment by Boshen** [comment]
Agree. Close as not planned.
