### ISSUE TITLE
linter: eslint/no-cond-assign

### ISSUE THREAD

**Issue by markEHVN** [oxc-project/oxc#7238]
### What version of Oxlint are you using?

0.11.1

### What command did you run?

yarn oxlint -c .oxlint.json

### What does your `.oxlint.json` config file look like?

```
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "categories": {
    "correctness": "allow"
  },
  "env": {
    "node": true
  },
  "globals": {},
  "settings": {},
  "rules": {
    "no-undef": "error",
    "no-cond-assign": ["error", "always"]
  }
}

```

### What happened?

I saw inconsistency between eslint@8.57 and oxlint@0.11.1. 
When I defined a script:
```
for(let i = 0; i < nums.length; i+= 1){
  dosomething()
}
```

Oxlint can caught an error,  eslint passed it. 
You can saw all source code at [here](https://github.com/markEHVN/compare-eslint-oxlint-plugin/tree/eslint/no-cond-assign). 

- Attachments: 
<img width="1501" alt="Screenshot 2024-11-11 at 23 42 40" src="https://github.com/user-attachments/assets/8420635d-c024-4b8c-b435-0c986a3cde9d">

**Comment by camc314** [comment]
🫡 thanks for the detailed ticket and repro
