### ISSUE TITLE
linter: import/export with a typescript file only export type

### ISSUE THREAD

**Issue by markEHVN** [oxc-project/oxc#7239]
### What version of Oxlint are you using?

0.11.1

### What command did you run?

yarn oxlint -c .oxlint.json

### What does your `.oxlint.json` config file look like?

```
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "categories": {
    "correctness": "allow"
  },
  "plugins": ["import"],
  "env": {
    "node": true
  },
  "globals": {},
  "settings": {},
  "rules": {
    "import/export": "error"
  }
}

```

### What happened?

I caught an error when I try use import/export with an typescript only export type. ESLint plugin work well.

You can see source code [at here](https://github.com/markEHVN/compare-eslint-oxlint-plugin/tree/import/export)

<img width="1258" alt="Screenshot 2024-11-12 at 00 12 25" src="https://github.com/user-attachments/assets/8655d8cf-53a0-463c-806a-1eb136dcbd5e">

**Comment by pumano** [comment]
I try to check it

**Comment by Boshen** [comment]
> I try to check it.
> 
> UPD: reason is:
> 
> if files contains only `export type` or `export interface` that marked as no named export. Continue digging...
> 
> looks like problem in ( I may be wrong):
> 
> https://github.com/oxc-project/oxc/blob/1282221e36a7b5be53ba81278507218abc90ed79/crates/oxc_semantic/src/module_record/builder.rs#L273-L281

Thank you for the investigation, this is the problem. We need to add type information the `ModuleRecord` 😢

**Comment by Boshen** [comment]
I think the best practice here is to use `export type` for proper tooling support.

I added support for `export type * from 'mod'` in https://github.com/oxc-project/oxc/pull/7676

by excluding type export syntax: 

```
if star_export_entry.is_type {
  return;
}
```

Please forgive me for not checking for types, as tsc already does it, and it really complicates the import plugin.
