### ISSUE TITLE
some properties are mismatched in compat_data/data.json

### ISSUE THREAD

**Issue by ShuiRuTian** [oxc-project/oxc#7279]
For example, LogicalAssignmentOperators is ES2021, but in this json, it's marked as ES2020.

However, it seems the data is marked correctly in the source: https://github.com/compat-table/compat-table/blob/53e5fbf03803c1ff96b66ba9ce38f162e348d8b9/data-es2016plus.js#L5297

**Comment by Boshen** [comment]
Thank you for noticing.

**Comment by overlookmotel** [comment]
Fixed in #7284.
