### ISSUE TITLE
[Doc] the url of some file in some repo should have a specific commit or tag rather than branch

### ISSUE THREAD

**Issue by ShuiRuTian** [oxc-project/oxc#7291]
The doc/comment is great, but I noticed that some link is like 

> //! * Babel plugin implementation: <https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-nullish-coalescing-operator>

This is potentially buggy, because main branch is always changing and maybe someday the file is gone.

It would be better if the file is associated with a commit or tag, then it's expected to always be there.

**Comment by overlookmotel** [comment]
Agreed permalinks would be better. Would be very much appreciated if you'd be willing to fix them. Tags would probably be preferable, as the URLs are not as long.
