### ISSUE TITLE
feat: avoid referenced url in github to be master/main

### ISSUE THREAD

**Issue by ShuiRuTian** [oxc-project/oxc#7299]
Although #7298 rewrite the urls, it's still feasible to check in url that is realted to master/main branch. 

I suppose 2 options to avoid this in future:

1. git hooks, husky and some script. Check the committed files.
2. write a test(rust or js, whatever). Find the diff files between HEAD and main, and search the content.

For option 1, 

Pros: easy to understand 

Cons: 
- not forced, could be avoid manually, 
- make git operation slower

For option 2,

Pros: 
- must be runned, could not be skipped

Cons:
- Not common, RA is using this strategy
- The test case is not stable, related to branch and Head, this might be confusing.

**Comment by Boshen** [comment]
We can add it to CI https://github.com/oxc-project/oxc/blob/main/.github/workflows/link-check.yml

**Comment by Boshen** [comment]
This is too troublesome, close as not planned.
