### ISSUE TITLE
Docs show raw markdown

### ISSUE THREAD

**Issue by marvinhagemeister** [oxc-project/oxc#7336]
The documentation for the `jsx-curly-brace-presence` rule prints raw markdown https://oxc.rs/docs/guide/usage/linter/rules/react/jsx-curly-brace-presence.html

**Comment by leaysgur** [comment]
Now it's fixed. 🎉 

![image](https://github.com/user-attachments/assets/44e86361-21a8-4104-9e24-39f3cd25878e)
