### ISSUE TITLE
Sourcemaps generated by isolatedDeclaration don't work in VSCode

### ISSUE THREAD

**Issue by voronin-ivan** [oxc-project/oxc#7340]
`Go to definition` doesn't work with sourcemaps generated by [isolatedDeclaration](https://github.com/oxc-project/oxc/tree/167d2d560dfe1e33d0910a4ef54363f16f9f99ef/npm/oxc-transform#isolated-declarations-for-standalone-dts-emit) in VSCode (any version, any OS). Instead of leading to the source file, it leads to the declaration file, as if sourcemaps are not presented. Apparently, VSCode doesn't support `sourcesContent`. Sourcemaps by `tsc` work correctly since they contain a link to the declaration file instead of inlined code:
```diff
type SourceMap = {
  mappings: string
  names: Array<string>
  sources: Array<string>
  version: 3
- sourcesContent: Array<string>
+ file: string
}
```

Here is [the repo](https://github.com/voronin-ivan/oxc-declaration-sourcemaps-issue/tree/main) where you can reproduce this issue and see the difference between sourcemaps by oxc and tsc. Just open `playground.ts` and try to `Go to definition` of `multiply` in both directories to see the difference. With [github.dev](https://github.dev/voronin-ivan/oxc-declaration-sourcemaps-issue/tree/main), you can open and reproduce it right away in the web-based editor.

Note: it works fine in WebStorm, I'm not sure about other IDEs/editors tho.

As a quick fix for my project, I'm manually changing the generated sourcemaps [like this](https://github.com/voronin-ivan/oxc-declaration-sourcemaps-issue/commit/79826caef0c0a1c97d1024b1a9e980ebed3716fb).

What do you think about a possible solution for this? Should the format of sourcemaps be aligned with TSC, or does requesting support of inline sourcemaps for declarations in VSCode make sense?

**Comment by Boshen** [comment]
`oxc-transform` don't support writing the contents to a file right now, the caller is responsible for doing this task.

We'll revisit this in the future if there is a demand.

close as not planned right now.
