### ISSUE TITLE
`define` for optional chaining is different from esbuild

### ISSUE THREAD

**Issue by hi-ogawa** [oxc-project/oxc#7383]
I don't have a specific use case in mind, but I was testing a similar example from https://github.com/evanw/esbuild/issues/3551 which I reported on esbuild in the past and found a minor difference/inconsistency.

reproduction: https://github.com/hi-ogawa/reproductions/tree/main/rolldown-define-optional-chain

- input

```js
{
  define: {
    'globalThis.process.env': '{}'
  }
}
```

```js
console.log(globalThis.process.env)
console.log(globalThis.process?.env)
console.log(globalThis.process?.env.ok)
console.log((globalThis.process?.env).ok)
```

- output (oxc, rolldown)

```js
console.log({});
console.log(globalThis.process?.env);
console.log({}.ok);
console.log((globalThis.process?.env).ok);
```

- output (esbuild)

```js
var define_globalThis_process_env_default = {};
console.log(define_globalThis_process_env_default);
console.log(define_globalThis_process_env_default);
console.log(define_globalThis_process_env_default.ok);
console.log(define_globalThis_process_env_default.ok);
```

**Comment by IWANABETHATGUY** [comment]
Most of the part should be done with https://github.com/oxc-project/oxc/pull/7433 ?

**Comment by IWANABETHATGUY** [comment]
The only different should not relevant to optional chain?  Because for a normal `StaticMemberExpr` we still will not generate a shared object, we will replace each `DotDefineMemberExpr` with a `ObjectExpr`

**Comment by hi-ogawa** [comment]
Thanks for the fix!
I think we can close. I've never wondered why esbuild uses shared object, but I think that's for later when that alignment turns out to be important.
