### ISSUE TITLE
Ast: Distiguish class/object methods with ordinary function expressions in `FunctionType`

### ISSUE THREAD

**Issue by KermanX** [oxc-project/oxc#7385]
The `FunctionType` enum already distinguishes function declarations and expressions. However, class methods and object methods are also considered to be function expressions, although they are different in some ways. For example:

```js
const object = {
  fn: function(){},
  method(){}
}
object.fn.prototype     //=> {}
object.method.prototype //=> undefined
```

A possible solution is adding `MethodFunction` to the `FunctionType` enum.

**Comment by overlookmotel** [comment]
Similar to: https://github.com/oxc-project/backlog/issues/142

**Comment by Boshen** [comment]
This conforms to estree. The caller will need to figure out whether it's a function inside a class / object or not.

**Comment by overlookmotel** [comment]
Personally, I don't think we need to conform to ESTree. Serialization can take care of translating our AST to ESTree-compatible AST. But I think it's fine to close this issue, as https://github.com/oxc-project/backlog/issues/142 is sufficiently similar.
