### ISSUE TITLE
transformer: research inserting helper methods with `import` or `require`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#7396]
cjs vs esm 😡

**Comment by overlookmotel** [comment]
Helper methods should already inserted as `import` statements / `require` depending on `source_type`. What's missing?

**Comment by Boshen** [comment]
Babel uses numerous conditions to decide on what to insert: https://github.com/babel/babel/blob/54a8389fa31ce4fd18b0335b05832dc1ad3cc21f/packages/babel-helper-module-imports/src/import-injector.ts#L20-L78

**Comment by Boshen** [comment]
There is one failing test case in monitor-oxc due to this confusion:

```
file:///home/runner/work/monitor-oxc/monitor-oxc/node_modules/.pnpm/@azure+core-rest-pipeline@1.18.0_supports-color@9.4.0/node_modules/@azure/core-rest-pipeline/dist/esm/policies/proxyPolicy.js:2
import { HttpProxyAgent } from "http-proxy-agent";
         ^^^^^^^^^^^^^^
SyntaxError: The requested module 'http-proxy-agent' does not provide an export named 'HttpProxyAgent'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

We inserted the wrong import in one of the files in `http-proxy-agent`

**Comment by overlookmotel** [comment]
I'm confused. Our transforms only insert imports from `@babel/runtime` and `react`. We didn't insert that import.

It's present in the original source:

<img width="469" alt="proxy" src="https://github.com/user-attachments/assets/41d82921-7073-477f-b84c-826d4f70d588">

https://www.npmjs.com/package/@azure/core-rest-pipeline?activeTab=code

**Comment by Boshen** [comment]
It transformed files in `http-proxy-agent`, which breaks node.js because it cannot detect esm  anymore.

**Comment by Boshen** [comment]
Actual offending file: https://cdn.jsdelivr.net/npm/http-proxy-agent@7.0.2/dist/index.js

I need to figure out why it's set as a module https://github.com/oxc-project/oxc/blob/6e4805910a474dbaa172d3b268b86191940f4c03/crates/oxc_transformer/src/common/module_imports.rs#L157-L164

**Comment by overlookmotel** [comment]
I still don't get what's going on in that failing test with `http-proxy-agent`. So maybe I'm missing the point again, but...

In `monitor-oxc`, shouldn't we be determining whether a file is ESM or CommonJS by looking for a `type` field `package.json`? This code is running in NodeJS, so there should be no ambiguity, and no need to search the code for `import` / `export` statements to make a guess.

In the case of `http-proxy-agent` there is no `type` field present in `package.json`, so it should be treated as CommonJS.

**Comment by Boshen** [comment]
I figured it out ... 

In monitor-oxc, I set source type to `unambiguous` https://github.com/oxc-project/monitor-oxc/pull/75 and everything should work correctly.

Except ... it uncovers a parser logic that we need to handle: https://github.com/microsoft/TypeScript/blob/6f75783184328087627da983fe30a05fca4f6314/src/compiler/parser.ts#L1861

I temporarily hacked it by filter out these two error messages:

* `"The keyword 'await' is reserved"` for `const foo = await (async () => {})()`
* ``await` is only allowed within async functions and at the top levels of modules`

I'll add a task to the backlog for fixing the "top level await unambiguous source type problem"
