### ISSUE TITLE
linter: 0.13.0 is hanging with `--import-plugin` (or taking more than 5 minutes)

### ISSUE THREAD

**Issue by anthonyshew** [oxc-project/oxc#7406]
Was hoping to try out the fix for #7123 but adding `--import-plugin` is causing Oxlint to hang. I see output for many found errors but then it halts suddenly.

I'm trying to eventually run `oxlint -A all -D no-cycle --import-plugin` so trying to see what works and what doesn't:

Working:
- `oxlint`, exits as expected
- `oxlint -A all`, exits as expected
- `oxlint -D no-cycle`, exits as expected

Not working:
- `oxlint --import-plugin`, produces output for many errors, then halts
- `oxlint -A all --import-plugin`, no output, appears to hang (makes sense)
- `oxlint -D no-cycle --import-plugin`, produces output for many errors, then halts

This appears to be a regression specifically in 0.13.0. 0.12.0 is working as expected in all cases.

**Comment by anthonyshew** [comment]
Yes. 0.12.0 runs for me.

**Comment by camc314** [comment]
got it, thanks. do you have a repo i can repro this on?

**Comment by anthonyshew** [comment]
I unfortunately don't. I'm seeing this in our massive monorepo and I wouldn't know where to start with figuring out with deconstructing the matrix of possibilities that could be making this happen.

I was hoping there was something that made sense for this on the diff between 0.12 to 0.13, but I don't know enough about the codebase to know what would make sense. 😄

If there's nothing that sticks out to you, I can maybe try to bisect/cherry-pick between 0.12 and .013, build from source, and see if I can find something?

**Comment by Grohden** [comment]
Seeing the same.. just following the simplest example from the website in our codebase makes it hang for me:

`oxlint --config=./oxlintrc.json ./file-path`

with

`oxlintrc.json` (from the site) as

```json
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "plugins": ["import", "typescript", "unicorn"],
  "env": {
    "browser": true
  },
  "globals": {
    "foo": "readonly"
  },
  "settings": {},
  "rules": {
    "eqeqeq": "warn",
    "import/no-cycle": "error"
  },
  "overrides": [
    {
      "files": ["*.test.ts", "*.spec.ts"],
      "rules": {
        "@typescript-eslint/no-explicit-any": "off"
      }
    }
  ]
}
```

As soon as I remove the 'import' plugin it doesn't hang

**Comment by Grohden** [comment]
Checking here, we have a path in `tsconfig` configured like this:

```json
{
  "compilerOptions": {
     "paths": {
        "BAR/*": ["*"]
     },
  }
}
```

If I comment it, or I change it to

```json
{
  "compilerOptions": {
     "paths": {
        "BAR/src/*": ["./src/*"]
     },
  }
}
```

`oxlint` doesn't hang (`[".*"]` seems to be the root cause for me)

**Comment by camc314** [comment]
i can repro this with https://github.com/jsx-eslint/eslint-plugin-jsx-a11y
and `npx oxlint@latest -A all -D no-cycle --import-plugin .`

**Comment by anthonyshew** [comment]
I can confirm that's in our repository, so that could be my case.

**Comment by camc314** [comment]
sorry meant if i clone that repo and run it i can repro this hanging

**Comment by camc314** [comment]
it appears to hang here. https://github.com/oxc-project/oxc/blob/c00f6694355cc47954906744a5c5cdea129f8f49/crates/oxc_linter/src/service/module_cache.rs#L61-L65

**Comment by camc314** [comment]
bisecting now, but i'm guessing it's this commit https://github.com/oxc-project/oxc/commit/c00f6694355cc47954906744a5c5cdea129f8f49

**Comment by camc314** [comment]
ok, so it broke in 878189c407d4ec7e3d2a4beeb000095ba1666c85

**Comment by anthonyshew** [comment]
Running for me now! Thanks!
