### ISSUE TITLE
When I traverse to the IdentifierReference node, how should I get the location of the variable referenced by this node? How should I determine the scope problem?

### ISSUE THREAD

**Issue by JasithC** [oxc-project/oxc#7409]
function fa(h9, g, h, i, j, k, l, m) {
  g = {};
  h = g;
}
function ee(g) {
  g.h = 2
}
When I use visit_assignment_expression to traverse the nodes, I get two nodes with node type IdentifierReference and name g, but they are not the same node. How should I distinguish them?

**Comment by Boshen** [comment]
Use the reference id from identifier reference to access its symbol id: https://docs.rs/oxc_semantic/latest/oxc_semantic/struct.SymbolTable.html#method.get_reference

They are different if symbol ids mismatch.

Close as not an issue.

**Comment by JasithC** [comment]
match target {
        AssignmentTarget::ComputedMemberExpression(comp_member) => {
            if let Some(ident_ref) = comp_member.object.get_identifier_reference() {
                println!("refrence_id:{:#?}", ident_ref.reference_id());
                println!("refrence_id:{:#?}", ident_ref.reference_id);
                //Is this the correct way to get the reference_id of the IdentifierReference node? Why is the printed value always None?
