### ISSUE TITLE
Add baseline file based Symbol tester

### ISSUE THREAD

**Issue by ShuiRuTian** [oxc-project/oxc#7428]
There is already a symbol_tester.rs, however, I think there are some flaws:

1. it could not distinguish different symbol with same name.

``` ts
function foo(){
const foo = 123;
}
```
For this example, I think there is no way to assert that there are 2 symbols called "foo" and assert the status of inner "foo" symbol

2. it checkes implementation details. This might be good for some situations, but always arguable
3. Not pretty easy to use.

So, I suggest to add another tester, which refer typescript's design:
For one input file, typescirpt will generate 4 output file
- js
- type
- symbols
- errors.txt

I believe there is already a js files output tester. So it's kind of natural to have another one for symbol. 

In the symbol baseline file, for each appeared identifier, it's needed to record its the symbol, which could be done thorugh the span of declaration symbol.

this is an example from typescript repo:
```
function foo(foo: number, y: number, ...z: string[]) {
>foo : Symbol(foo, Decl(callWithSpread.ts, 2, 1))
>foo : Symbol(foo, Decl(callWithSpread.ts, 4, 13))
>y : Symbol(y, Decl(callWithSpread.ts, 4, 25))
>z : Symbol(z, Decl(callWithSpread.ts, 4, 36))

    foo
>foo : Symbol(foo, Decl(callWithSpread.ts, 4, 13))
}

```

**Comment by Boshen** [comment]
This creates too much noise in the codebase, close as not planned.
