### ISSUE TITLE
closure function Codegen error

### ISSUE THREAD

**Issue by underfin** [oxc-project/oxc#7501]
The closure function codegen is error, [reproduction](https://playground.oxc.rs/#eNpdTksOwiAQvQqZVZv2BLhw5ym6oQiGhM40A9XWhrsLGqpxNe/NzPvsoEFCYxfU0RE27b6mtmlFJwawRAOIsxgV543M89m0pwHrpRO/uu2t+/+GHgjkDrxgGWHDqFaQkRfTg3cYKw6aZnOQbRrJVxZZYbDEE0irfDCph1lxMJwdMy4uFR+vdaHpam6mZGcyOXTWfU8YmfzF06NUuxseKeQKn4yUXnFFXjI=)

### Input 

``` .ts
"foo" + (function(){y})() ? bar() : baz(); // the closure function wrapper is lost
```

### Output 
``` .ts
"foo" + function() {
	y;
}() ? bar() : baz();
```

### Expected 
``` .ts
"foo" + (function() {
	y;
}()) ? bar() : baz();
```

I found it at [here](https://github.com/rollup/rollup/blob/master/test/form/samples/pure-comment-scenarios-complex/main.js#L44). The [pervious line](https://github.com/rollup/rollup/blob/master/test/form/samples/pure-comment-scenarios-complex/main.js#L43) also is error at test, but i can't reproduction at playground.

**Comment by Boshen** [comment]
What error are you seeing? esbuild prints the same output https://esbuild.github.io/try/#dAAwLjIzLjEAACJmb28iICsgKGZ1bmN0aW9uKCl7eX0pKCkgPyBiYXIoKSA6IGJheigpOyA

**Comment by Boshen** [comment]
```
> "foo" + (function(){})() ? "bar" : "baz"; 
> 'bar'

> "foo" + function(){}() ? "bar" : "baz"; 
> 'bar'
```

both produce the same result.

Close as unclear issue.
