### ISSUE TITLE
unicode characters result in incorrect start/end values

### ISSUE THREAD

**Issue by danielroe** [oxc-project/oxc#7508]
There's an issue with `oxc-parser`, where it incorrectly generates start/end column values:

```ts
import Parser from 'oxc-parser'

const code = `
const a = 'œœ'
callOnce(a)
`

const ast = Parser.parseSync(code, { sourceType: 'module', sourceFilename: 'test/nuxt/composables.test.ts' })
const secondStatement = ast.program.body[1]
if (secondStatement && secondStatement.type === 'ExpressionStatement') {
  console.log(secondStatement.expression)
  console.log(code.slice(secondStatement.expression.start, secondStatement.expression.end))
  // llOnce(a)
}
```

maybe related: https://github.com/oxc-project/oxc/pull/7484

**Comment by Boshen** [comment]
The root cause is because Rust strings are utf8.

It seems like the usage of these spans are magic string manipulations. Let me investigate whether we can do this directly on the Rust side.

**Comment by pumano** [comment]
I got that problem when trying to implement `eslint/id-length` rule (currently in development).

@Boshen maybe my experience helps here:
when characters is unicode graphemes, they can be properly counted by unicode segmentation lib: https://docs.rs/unicode-segmentation/latest/unicode_segmentation/struct.Graphemes.html

I create specific function for that case:

```rs
fn count_graphemes(str: &str) -> usize {
    // if ascii count as usual
    if str.is_ascii() {
        return str.len();
    }
    return str.graphemes(true).collect::<FxHashSet<_>>().len();
}
```

that helps properly count characters which is unicode graphemes and help you set proper span

**Comment by Boshen** [comment]
The latest https://www.npmjs.com/package/oxc-parser release adds a few APIs and a magic string instance for accessing and manipulating UTF8 strings on the Rust.

See API section in https://www.npmjs.com/package/oxc-parser README or its test https://github.com/oxc-project/oxc/blob/main/napi/parser/test/magic_string.test.ts
