### ISSUE TITLE
linter: import plugin breaks with flow syntax in `.js` file in metro project

### ISSUE THREAD

**Issue by Grohden** [oxc-project/oxc#7549]
### What version of Oxlint are you using?

0.13.2

### What command did you run?

npx oxlint@latest --import-plugin ./src

### What does your `.oxlint.json` config file look like?

none

### What happened?

I'm trying to adopt oxlint in an RN project, but it seems that somehow the import plugin is forcing oxlint to parse some `node_modules` dependencies... and since they're for react native they're really weird (I'm just reporting, but I guess I expect you all to say "this is on maintainers to fix")

To simulate what I'm seeing try this
```sh
mkdir oxlint-issue && cd oxlint-issue

npm init // just yes on all
npm install --save react-native-appsflyer

mkdir ./src
echo "import appsFlyer from 'react-native-appsflyer';" > ./src/foo.tsx

npx oxlint@latest --import-plugin ./src
```

You'll get the expected unused export but you'll also get a unexpected token log:

```
➜  oxlint-issue npx oxlint@latest --import-plugin ./src 

  × Unexpected token
    ╭─[node_modules/react-native-appsflyer/index.js:18:33]
 17 │ 
 18 │ function initSdkPromise(options): Promise<string> {
    ·                                 ─
 19 │     if (typeof options.appId !== 'string' && typeof options.appId !== 'undefined') {
    ╰────
```

its really weird that this dependency is using ts syntax in js, but I guess that thats allowed and even worse: works on RN

I have another dependency which is [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util) which throws even more parsing errors, but I couldn't simulate it in a clean env (we never import it in our project, but still, somehow the import plugin tries to parse it)
![image](https://github.com/user-attachments/assets/30a04c93-6150-46e7-95bb-41cb9c852205)

**Comment by Boshen** [comment]
There is not a single indicator for us to know this is not a `.js` file ... https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/ed62341086e6eaab39d761fddf3dac0920f91c06/index.js

Who's burden should it be 😭

**Comment by pumano** [comment]
@Grohden just add "node_modules" to ignore.

**Comment by Grohden** [comment]
@pumano how? 
`.gitignore`, `.eslintignore`, `.oxlintignore` (this one prob doesn't even exist) don't work and were the first things I've tried.

`npx oxlint@latest --import-plugin ./src --ignore-pattern "node_modules/**"`
or
`npx oxlint@latest --import-plugin ./src --ignore-path ./.gitignore"`
`npx oxlint@latest --import-plugin ./src --ignore-pattern "node_modules"` don't work as well.

import plugin probably needs to parse dependencies regardless of ignore to be able to tell if something can or cannot be imported from a lib, I don't think ignore will work, but if it should, what am I doing wrong?

**Comment by Grohden** [comment]
@Boshen think [metro](https://metrobundler.dev/) will do its magic to solve it (I guess force ts on js?).. but yeah, really weird and no ts indications. But like I said, I'm just reporting "maybe there's a solution?"... but if there isn't one, I'm ok with it 🤷, I'll try to open some issues in the two mentioned packages

**Comment by Boshen** [comment]
> @pumano how? `.gitignore`, `.eslintignore`, `.oxlintignore` (this one prob doesn't even exist) don't work and were the first things I've tried.
> 
> `npx oxlint@latest --import-plugin ./src --ignore-pattern "node_modules/**"` or `npx oxlint@latest --import-plugin ./src --ignore-path ./.gitignore` `npx oxlint@latest --import-plugin ./src --ignore-pattern "node_modules"` don't work as well.
> 
> import plugin probably needs to parse dependencies regardless of ignore to be able to tell if something can or cannot be imported from a lib, I don't think ignore will work, but if it should, what am I doing wrong?

All ignores don't work on the files being imported, because we assume files coming from `node_modules` are semantically correct.

> @Boshen think [metro](https://metrobundler.dev/) will do its magic to solve it (I guess force ts on js?).. but yeah, really weird and no ts indications. But like I said, I'm just reporting "maybe there's a solution?"... but if there isn't one, I'm ok with it 🤷, I'll try to open some issues in the two mentioned packages

It's a dilemma isn't it? Let me ask around ...

**Comment by Boshen** [comment]
It's flow.

https://bsky.app/profile/mitsuhiko.at/post/3lcdf7dr3nc2s

It should have a `// @flow` at the top according to https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow

oxc handles `// @flow` so it is best to ask these repos to update their `.js` files with `// @flow`.
