### ISSUE TITLE
Semantic syntax checker mis-resolves private fields in class computed fields

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#7581]
Private fields in computed keys resolve to private properties of *enclosing* class. So `obj.#x` does not reference `C`'s `#x` binding here, and in both cases it should be a syntax error:

```js
class C {
  #x;
  [obj.#x]() {}
  [obj.#x] = 123;
}
```

[Oxc playground](https://playground.oxc.rs/#eNpNjk2uwjAMhK8Smc17UoX4EZsiVkhcAlikwUVBaYzsFIqq3h0HKGLljPPNjHtwUIILVsRsTX+Ixky6dR57qi7TSXf8+zf98LswGzNfLJXRLRRAUPbAbcxDHjHZDsrELRYQfExQ1jaICnF0xfFHHk1FYVSJbZSauPnAQwFXy4L8iqSWHe58wGgbDYCEkqYXAaVywYvS9zfkbUuWz6jtgLKYzVeZdnTCM+Y7VTQ++tqPZkcxMYVdoHs235ArEi17nzMMT3FQY6o=)

**Comment by Boshen** [comment]
```
VM804:3 Uncaught ReferenceError: obj is not defined
    at <anonymous>:3:8
```
