### ISSUE TITLE
`define` works differently from esbuild if it includes `import.meta.something` and `import.meta.something.anotherthing`

### ISSUE THREAD

**Issue by sapphi-red** [oxc-project/oxc#7594]
I made a test case as that was easier than explaining in text: https://github.com/oxc-project/oxc/pull/7593
[esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1kZWZpbmU6aW1wb3J0Lm1ldGEuZW52LkZPTz1pbXBvcnQubWV0YS5lbnYuRk9PIC0tZGVmaW5lOmltcG9ydC5tZXRhLmVudj1fX2Zvb19fAGNvbnNvbGUubG9nKGltcG9ydC5tZXRhLmVudiwgaW1wb3J0Lm1ldGEuZW52LkZPTyk)

**Comment by overlookmotel** [comment]
Fixed in #7621.
