### ISSUE TITLE
`define` replaces property access incorrectly

### ISSUE THREAD

**Issue by sapphi-red** [oxc-project/oxc#7598]
I made a test case as that was easier than explaining in text: https://github.com/oxc-project/oxc/pull/7597
[esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1kZWZpbmU6X19PQkpfXz0ie1wicHJvY2Vzc1wiOntcImVudlwiOntcIlNPTUVWQVJcIjpcImZvb1wifX19IiAtLWRlZmluZTpwcm9jZXNzLmVudi5TT01FVkFSPSJcImZvb1wiIgBjb25zb2xlLmxvZyhfX09CSl9fLnByb2Nlc3MuZW52LlNPTUVWQVIp)

**Comment by IWANABETHATGUY** [comment]
I don't think oxc define output is wrong, 
**esbuild output**
```js
```

**Comment by IWANABETHATGUY** [comment]
Ok, the output looks like a constant eval, but actually is a but, lol.

**Comment by sapphi-red** [comment]
Ah, sorry [the esbuild try link](https://esbuild.github.io/try/#dAAwLjI0LjAALS1kZWZpbmU6X19PQkpfXz0ie1wicHJvY2Vzc1wiOntcImVudlwiOntcIlNPTUVWQVJcIjpcImZvb1wifX19IiAtLWRlZmluZTpwcm9jZXNzLmVudi5TT01FVkFSPSJcIlNPTUVWQVJcIiIAY29uc29sZS5sb2coX19PQkpfXy5wcm9jZXNzLmVudi5TT01FVkFSKQ) should be this one (changed `--define:process.env.SOMEVAR="\"foo\""` to `--define:process.env.SOMEVAR="\"SOMEVAR\""`).

oxc replaces `__OBJ__.process.env.SOMEVAR` to `"SOMEVAR"` (should be `"foo"`).

**Comment by sapphi-red** [comment]
Slightly related: I noticed the reference behavior difference (https://github.com/oxc-project/oxc/issues/7641).
