### ISSUE TITLE
[transformer] bundle runtime helpers / remove runtime helper import code from output

### ISSUE THREAD

**Issue by sapphi-red** [oxc-project/oxc#7599]
I'm trying to use the transform api as a replacement of `esbuild.transform`. When esbuild needs to use a helper function for lowering, it injects them at the top of the output ([esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS10YXJnZXQ9ZXMyMDE3AGNvbnN0IGJhciA9IHsuLi4iYmIifQ)).
On the other hand, oxc injects a `import` or `require` for the helper function.

This makes it difficult to use it as an replacement for my case. I'm running esbuild in `renderChunk` hook of rollup and at that time the chunking has already done. I have to analyze the output and run a different build to get the helper functions and connect the chunks.

If oxc has a flag that injects the helper function into the output, it will be really easy to swap esbuild with oxc.

Or if oxc has a flag that makes the output to not include the `import`/`require`, I won't need to analyze the output.
An example API looks like this:
```js
const result = transformWithOxc(name, 'const bar = {..."bb"}', {
  target: 'es2017',
  sourceType: 'module',
  helpers: 'external' // proposed flag
})

console.log(result.helpers) // { '_objectSpread': '@babel/runtime/helpers/objectSpread2' }
```
Then, I can know which helpers are needed without analyzing the output.

**Comment by overlookmotel** [comment]
@sapphi-red Inserting helpers inline is quite a tricky task, so we're looking at the 2nd option you suggested.

Question: How would you use `result.helpers`?

Some helpers use other helpers. e.g. `_objectSpread` helper uses `_defineProperty` helper.

https://github.com/babel/babel/blob/38c7dce59c797bd8cf09544f1d97fb889f79fc3a/packages/babel-helpers/src/helpers/objectSpread2.ts

So would returning `{ _objectSpread: '@babel/runtime/helpers/objectSpread2' }` be sufficient? Are you able to figure out what "sub-helpers" are required on your side?

**Comment by sapphi-red** [comment]
> Question: How would you use `result.helpers`?

I was going to make a bundle from that information for each chunks. For example:
```js
let originalChunkCode = chunk.code
const bundle = await rolldown({
  input: '_virtual',
  plugins: [
    {
      name: 'v',
      load(id) {
        if (id === '_virtual') {
          return Object.entries(result.helpers).map(([k,v]) => `import ${key} from ${JSON.stringify(v)}`).join('\n')
        }
      }
    }
  ]
})
const output = bundle.generate({ format: 'iife', name: 'foo' })
const runtimeCode = output[0].code
const newChunkCode = runtimeCode + '\n' + Object.keys(result.helpers).map(k => `const ${k} = foo.${k}`).join('\n') + '\n' + originalChunkCode
```
So returning `{ _objectSpread: '@babel/runtime/helpers/objectSpread2' }` would be sufficient.

**Comment by overlookmotel** [comment]
Thanks for coming back. OK great. Was just double-checking before we implement something that turns out not to work for intended use case!
