### ISSUE TITLE
Parser: Incorrect AST location information when source code includes Chinese character

### ISSUE THREAD

**Issue by yuyinws** [oxc-project/oxc#7633]
[Oxc Parser Playground](https://playground.oxc.rs/#eNpFjz0OwjAMha9Sea44QCVWZgZGlhBcFJTYlZ0CVdW7sHCM3gbuQVJoOyXPP9977sFCBZZJYxH0UmyLI7zH5+c1HgFKYKh6kJbyox1F84CqNl6xBO8oLkItNwhVlDaLLpzYzyqKIa1Zwn94KKExoigTk1uxuHMeyYQEgIgaN1dN1o1gGrrh3giSrk7TxqHLdhD43HqEhMxpJmT6L45zwfIZL5iPSCI4crVbWxSF/c7zPee5oZxYE/oXdRi+EbpnhA==)

<img width="948" alt="image" src="https://github.com/user-attachments/assets/39521e53-d766-47a5-952e-97974e95d0dd">

[Babel Parser Playground](https://ast.sxzz.dev/#eNolyUEOQDAQheGrNG/tBBK3sDMWVY2QahujEhF3sXEMt+EeRuz+974NDjkGvWg2Ux9nZIhyNLqxTtpIm+B5ViN3qlCE+zqe8yIIBsGNvJKXQ5qMLddoCbnsMbTJSWc/R5e63vNnVU1+x/4CZM0oDA==)

<img width="1007" alt="image" src="https://github.com/user-attachments/assets/55c914a2-5e11-4a8a-8328-6524e263b84f">

---

Find a similar issue from [SWC](https://github.com/swc-project/swc/issues/1782), this may be helpful.

**Comment by Boshen** [comment]
The spans are in utf8 length. Everything on the js side is considered not stable.

We already have multiple issues for this, close as duplicate.
