### ISSUE TITLE
minifier: some minification improvements

### ISSUE THREAD

**Issue by sapphi-red** [oxc-project/oxc#7638]
Putting a list here that can trim down some bytes.

- printer
  - [x] [`import "./foo"` -> `import"./foo"`](https://playground.oxc.rs/#eNpFj0sOwyAMRK9SeR21+xyg6x4gG0qdlApsZJOkUZS7F/LrCg8wb8YzWKjBhciSLg1cby1zA400BBUw1DNIT+XQiZL5Qt0ar1iBd5ROoZYjQp2kL2IKT/aHSmJIW5awf14qiEYUpTCjYJ4GfBhB0j+Oe7F4dx7JhMyFhJquH4VsLrmrOc8n+7iw/MIOS90sgiPXui3IcihZOWJrNb5dZkZjz9bBUOd3tZIoCfu757H4B5Qna37edliWH8M7bl0=) (the space before `"`) https://github.com/oxc-project/oxc/pull/7650
  - [x] [`const foo = ''; export { foo }` -> `const foo="";export{foo}`](https://playground.oxc.rs/#eNpFj02OwjAMha8SecOmmgN0NFvWcwA2IbgQlNiR7fKjqncnaaGs4ufkfe9lggA9BCY1NzC7P7fb/Tp8FBZz07KaD3Ig6IChn0BGaoc+yfwD+sEnxQ5SJNuEBi4IvcnYxDMfOX2UiScdWPL78dxB8aIojVkE63TDfy9I+sXxKAH3MSH5XLlgqPZzVajmlruY67yxP4vAJzxjq1tFjhSHuAYFzi2rRqyt7pdYmcWHrXX2dE5vtZDIhNM+8b35byhH1nq9/mGeX3AxcvQ=) (the space before `{`) https://github.com/oxc-project/oxc/pull/7650
  - [ ] [`const str = 'a\nb'` -> ``const str=`a_b` ``](https://playground.oxc.rs/#eNpFj0sOwjAMRK9SecOm4gCV2LLmAGzc4EJQYle2y0eodyehUFbxJJk34xcE6CAImzfm2uyaDR6P3G+gBYHuBTpxPezJjg/oBkxGLaTIvgoLMhJ0rlMVz9xL+ilXZBtE8/fz3MKIaqSVOSqV6UYHVGL742TSQPuYiDEXLjiZb68GxVxzP+Yyr+zfRZATnanWLSJHjkNcgoLkmlUillb3SyzMEcPaOiOf01d9SOwqaZ/kXv030l6sPC87zPMbDXxtwQ==)(`_` is an actual line break, not a `\n`)
  - [x] [`throw "foo"` -> `throw"foo"`](https://playground.oxc.rs/#eNpFj0sOgzAMRK9SeY16AA7AugdgE1IDqRIb2QGKEHdvwq+reJLMm/EKFkqIvfD8qKFlrgEKYChXkJHyoQtF84WyNV6xAO8o3kItDwhllDGLJTTsLxXFkLYs4fy8FTAYUZTMHATTNOHLCJL+cTyKxcp5JBMSFyJqfH4Ukjnn7uY03+zrwvIbO8x1kwiOXOuOIMshZ6WIo9Xcu8QcjL1bB0OdP9VOoijsK89z9k8oDWt6PnbYth/wamwB) (the space before `"`) https://github.com/oxc-project/oxc/pull/7671
  - remove unneeded void ([oxc playground](https://playground.oxc.rs/#eNpFT7GOwjAM/ZXIC0WqELdWuhuZbmC4kSUEF3xK7MpJ20Oo/34J0NZSEj/7+fnlAQ4asPHOzrQ9u0TC5kbfNqFWW/M46YlNDjtaSoZxNEeVQBGrSjGKH3BrPr9WXomI6YcCSp9mTm0+9vv9diZNS+aEMwF3Xq7V5kabZ2Mq13wGoctqqFSgBoHmAdpzebL1ZP+gaa2PWIMnTguITjqEJmlfwD2cxc8oqeXYioY3eaqhsxpRi2aXfaMOeLSKHFc56dXhgTyyDVkXEsa0+42Qh8ve53DOF+254OSCVyx2MwjE1NJrkZNQduUVL1fjjbJmZ93iOli++jd6KnFS8QcvY5kfUM8Sc/v1h2n6B809oV8=), [esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1taW5pZnkAYXN5bmMgZnVuY3Rpb24gaGlMYXRlcigpIHsKICAgIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgICAgc2V0VGltZW91dChyZXNvbHZlLCAxMDAwKQogICAgfSkKICAgIGNvbnNvbGUubG9nKCdoaScpCn0KCgp2b2lkIGhpTGF0ZXIoKQo), [swc playground](https://play.swc.rs/?version=1.10.0&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczPU8jI9EksSS3S0FSo5uVSAILE8sTMEoW81HKFgKL83MziVA2NotTi%2FJyyVE0FWzuYKhAoTi0JycxNzS8tganQUTA0MDDQhCiphdLJ%2BXlAyVS9nPx0DfWMTHWgcC0vFy9XWX5mCsJ6Xi4AE8oLsZkAAAA%3D&config=H4sIAAAAAAAAA41VQY7bMAy87ysCn3vY5lAUfUBvfYOgWJSjVBYNkfImWOTvpRU7m93QRi9BzNGQIjmk3l92u%2BZEbfNr9y5%2F5WOwmSDfv8VCl8T2LJYG2t5Sm8PAzbcFPdEEeRsJqul6Qxq2uQOuLNq%2F7vczo4mIBAtjtvUhBX95jNliP2QgerCJVVyWHhLTZ%2F6MZXybAM7l0X5AjGDTBmIsmZAYOsia4xZjtAOBGW1WvEw3tTkQaiEmsDA4M2QcVDy5wAGTxHxGHVhnWnSgQCFDy2EEjSaxhJZI0lPyqbCDQ%2Bm62ucvbBhtLJaVmHCuLZHbKl6PGIiNL0kr4Q1cqcENnIv7lRm8ycAlp2feCUNa6clfAKlAtETJ9qD5rSe86GmN7TeZIXmRLF8UXPStZZmgk6KaELxS2akykDlo3czgSgtTZVvtOjO8Uj4KDgx4L1pRXNNb4PaoBeXLAOgVQPprvaaqG2DuU7iCTwOxAf%2BWLFkX2Hyit3xcR%2BnSHzBuBOiBj%2Bg2DkgrGNfhLFviPKzjJTkQaYBTjxSqwPMSkAFgNLHuyydtyHiIR9NFPHysifnA9b6He5u6Ou8P%2B5JxiDBCXJPxf4zIJip3GydVL5P9NL3wUxOllcEL318%2FPRuSysvyW5NqenTlIaGqydtz8qP5OLS8HEvVmkB%2FFmKt0%2FUfj5GfKOMGAAA%3D))

- mangler
  - [`const foo = ''; export const bar = () => foo` -> `const c='';export const bar=()=>c`](https://playground.oxc.rs/#eNpFT0luwzAM/IrAS1rA6ANcpMec+4BcZJVOFUikQMpZEPjvoeLEOYkz4iy8QYAeApNWNzK7rdtsvh1eCkt1Cz14Mfrj021/2spe9gQdMPQ3kInao1eq/gL96JNiBylSXYEGLgh9lamBax44vVAVTzqy5Ofy3EHxoijNswjadMJfL0j6tuNJAu5iQvLZfKGi1q+jgolb7kNs8+r9IgL/4QFbXQM5UhzjEhQ4tyyLWFqd/6N5Fh/W1tnTIT3Rw4mqcNolPjf9CWVgte/lhnm+A3hrdsE=) (top-level variables are not mangled even if it's a module file)
  - [`const loooooooooong = ''; export { loooooooooong }` -> `const a="";export{a as loooooooooong}` (same for `export const foooooooooooooooooooooo = ''`)](https://playground.oxc.rs/#eNpdj02OwyAMha+CvOkmmgNkNNuu5wDdUOqkVGAjm/RHUe5eSNK0qiWEH7a/Z0Zw0IJj0mwCb0G9+TO73a/Be2LJZvwqTgc5UD1rfQF0757PmFG1GRpgaEeQgeqlD8r2Dm1ng2IDwVPehDpOCG2WoYpHPHJ4qSyWtGOJa/PUQLKiKJWZBEt2xX8rSPrG8SAO9z4g2Vi4kFHzz0WhDFffebjkG/v14PiEPdZ1i4iefOcXI8exehWLZavb2Rdmsm7bOlrqw6pmEmXhsA98q/NXlCNrKS9/mKYnvm2Ojg==) (maybe related to the one above?)
  - [`const loooooooooong1 = {}; const obj = { loooooooooong1 }` -> `const a={},obj={loooooooooong1: a};`](https://playground.oxc.rs/#eNpdj0sOwjAMRK9SeV0hsS1iy5orpMEtQYld2SkfVbk7SX9IZBNPbL+ZTGChAcuksfK8H+qP1bma0qlaWtw+iv4fSVADQzOBjFQu/VA0b2g64xVr8I7iLtTygNBEGYv4hJb9pqIY0o4lrMOphsGIohTmIJirJ16NIOkPx6NYvDiPZELmQkSNh4dCXi6+83Kud/b2YPmGPZa4WQRHrnOLkeVQvLLFkup1d5k5GLunDoZ6v6qZRFHYXzy/yv4TpWXN7eUPKX0BmeR8Sw==) (maybe related to the one above?)

**Comment by Dunqing** [comment]
I also noticed we haven't trimmed whitespace between `ReturnStatement with `StringLitertal`. For example: `return "string"`.

**Comment by sapphi-red** [comment]
Another one:

- remove unneeded `void` ([oxc playground](https://playground.oxc.rs/#eNpFT7GOwjAM/ZXIC0WqELdWuhuZbmC4kSUEF3xK7MpJ20Oo/34J0NZSEj/7+fnlAQ4asPHOzrQ9u0TC5kbfNqFWW/M46YlNDjtaSoZxNEeVQBGrSjGKH3BrPr9WXomI6YcCSp9mTm0+9vv9diZNS+aEMwF3Xq7V5kabZ2Mq13wGoctqqFSgBoHmAdpzebL1ZP+gaa2PWIMnTguITjqEJmlfwD2cxc8oqeXYioY3eaqhsxpRi2aXfaMOeLSKHFc56dXhgTyyDVkXEsa0+42Qh8ve53DOF+254OSCVyx2MwjE1NJrkZNQduUVL1fjjbJmZ93iOli++jd6KnFS8QcvY5kfUM8Sc/v1h2n6B809oV8=), [esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1taW5pZnkAYXN5bmMgZnVuY3Rpb24gaGlMYXRlcigpIHsKICAgIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgICAgc2V0VGltZW91dChyZXNvbHZlLCAxMDAwKQogICAgfSkKICAgIGNvbnNvbGUubG9nKCdoaScpCn0KCgp2b2lkIGhpTGF0ZXIoKQo), [swc playground](https://play.swc.rs/?version=1.10.0&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczPU8jI9EksSS3S0FSo5uVSAILE8sTMEoW81HKFgKL83MziVA2NotTi%2FJyyVE0FWzuYKhAoTi0JycxNzS8tganQUTA0MDDQhCiphdLJ%2BXlAyVS9nPx0DfWMTHWgcC0vFy9XWX5mCsJ6Xi4AE8oLsZkAAAA%3D&config=H4sIAAAAAAAAA41VQY7bMAy87ysCn3vY5lAUfUBvfYOgWJSjVBYNkfImWOTvpRU7m93QRi9BzNGQIjmk3l92u%2BZEbfNr9y5%2F5WOwmSDfv8VCl8T2LJYG2t5Sm8PAzbcFPdEEeRsJqul6Qxq2uQOuLNq%2F7vczo4mIBAtjtvUhBX95jNliP2QgerCJVVyWHhLTZ%2F6MZXybAM7l0X5AjGDTBmIsmZAYOsia4xZjtAOBGW1WvEw3tTkQaiEmsDA4M2QcVDy5wAGTxHxGHVhnWnSgQCFDy2EEjSaxhJZI0lPyqbCDQ%2Bm62ucvbBhtLJaVmHCuLZHbKl6PGIiNL0kr4Q1cqcENnIv7lRm8ycAlp2feCUNa6clfAKlAtETJ9qD5rSe86GmN7TeZIXmRLF8UXPStZZmgk6KaELxS2akykDlo3czgSgtTZVvtOjO8Uj4KDgx4L1pRXNNb4PaoBeXLAOgVQPprvaaqG2DuU7iCTwOxAf%2BWLFkX2Hyit3xcR%2BnSHzBuBOiBj%2Bg2DkgrGNfhLFviPKzjJTkQaYBTjxSqwPMSkAFgNLHuyydtyHiIR9NFPHysifnA9b6He5u6Ou8P%2B5JxiDBCXJPxf4zIJip3GydVL5P9NL3wUxOllcEL318%2FPRuSysvyW5NqenTlIaGqydtz8qP5OLS8HEvVmkB%2FFmKt0%2FUfj5GfKOMGAAA%3D))

**Comment by Boshen** [comment]
I fixed some of the minor issues.

Going forward for 2025, I plan to do a big project on smaller bundle size, where we track and minimize bundle size methodically.

Close this issue as partially done.
