### ISSUE TITLE
transformer: `define` does not share reference for objects

### ISSUE THREAD

**Issue by sapphi-red** [oxc-project/oxc#7641]
[esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1kZWZpbmU6X19PQkpfXz0neyJ2YXJzIjp7IlNPTUVWQVIiOiJmb28ifX0nAGNvbnNvbGUubG9nKF9fT0JKX18udmFycykKX19PQkpfXy52YXJzLkFOT1RIRVIgPSAnYmFyJwpjb25zb2xlLmxvZyhfX09CSl9fLnZhcnMp)

```rust
#[test]
fn same_reference_for_object() {
    let config =
        ReplaceGlobalDefinesConfig::new(&[("__OBJ__", r#"{"vars":{"SOMEVAR":"foo"}}"#)])
            .unwrap();
    test(
        "
        console.log(__OBJ__.vars);
        __OBJ__.vars.ANOTHER = 'bar';
        console.log(__OBJ__.vars)",
        "
        const __OBJ__ = {vars:{SOMEVAR:\"foo\"}};
        console.log(__OBJ__.vars);
        __OBJ__.vars.ANOTHER = 'bar';
        console.log(__OBJ__.vars)",
        config.clone(),
    ); // fails
}
```

Oxc outputs:
```js
console.log({ 'vars': { 'SOMEVAR': 'foo' } }.vars);
({ 'vars': { 'SOMEVAR': 'foo' } }).vars.ANOTHER = 'bar';
console.log({ 'vars': { 'SOMEVAR': 'foo' } }.vars);
```

This has a different behavior.

**Comment by sapphi-red** [comment]
I'm not sure how many people relies on this behavior though

**Comment by IWANABETHATGUY** [comment]
after investigation, 
- webpack `DefinePlugin`: don't share object
- rollup: AFAIK they don't have the official `define` plugin(they have replace plugin based on string), don't support share object.
- oxc define: don't share object
- esbuild define: create a share object

So I am wondering if it is necessary to add this feature.

**Comment by sapphi-red** [comment]
It seems the reason was to reduce the bundle size rather than sharing the reference itself. https://github.com/evanw/esbuild/issues/581
I don't think it's a necessary thing, but I guess it'd be difficult to introduce this behavior later on as an optimization, as it changes the behavior.

**Comment by Boshen** [comment]
I want to reject this feature for now and evaluate the requirement when it is bought up again.

The motivation and discussion in https://github.com/evanw/esbuild/issues/581 is still unclear to me, and the I can't find any real examples of people using this feature.

And also, the behaviour of esbuild documented in https://github.com/evanw/esbuild/commit/a5288c6795e8639082b89625df8bfa954c967419#diff-f312cd3ffe8d88cf424d3f0bd04b41e5b0ad36e549874b5688028bf9091a61f5R967 is 

>  This release adds support for array and object literals with `--define` anyway, but they work differently than other `--define` expressions. In this case a separate virtual file is created and configured to be injected into all files similar to how the `--inject` feature works. This means there is only at most one copy of the value in a given output file. However, these values do not participate in constant folding and dead code elimination, since the object can now potentially be mutated at run-time.

Personally, this feature is really confusing in the scope of the `define` plugin, which makes it behave like an automated inject plugin.

**Comment by Boshen** [comment]
I'm going to close this as not planned for now, feel free to bring this up again when there is an actual requirement.
