### ISSUE TITLE
codegen: missing parens for `in` in for loop init

### ISSUE THREAD

**Issue by JasithC** [oxc-project/oxc#7690]
```
let a = [1, 2, 3]; for (b = 1, (V[0] in R) || a.length() == 3 || r == '1';;);
```

**Comment by Boshen** [comment]
Can you fill in more context?

**Comment by Boshen** [comment]
It's correct in the playground https://playground.oxc.rs/#eNo9TssKgzAQ/JVlTwo5qKUXpT9RSi9tDzFdJaBJ2ESoiP/eRNHTzgzz2AUV1jhQAAk3yEoBlYBL3kBnGbI2alHKnq/iA9rAPW+avHkbFGixXpAnk46fTZA/rANPJHDQJhzYK+voJPPY2uFggaXxcWXEupODp1Wgk+yJt0Y7saLHnMKxhLULGA2pejNEfOb3RJDcU9xF8lVRXpNb2S/1lD6MZNRGd3r3Kjs6Ju+P5XX9A72aVkE=

which version are you on?

**Comment by JasithC** [comment]
I have this problem with versions 0.31 and 0.38

**Comment by Boshen** [comment]
Close as cannot repro.

**Comment by Boshen** [comment]
Where are you getting these test cases? Fuzzing or real world code?

**Comment by JasithC** [comment]
It is real code

**Comment by overlookmotel** [comment]
Minimal repro:

```js
for (x = (y in z) || y || y;;);
```

[Playground](https://playground.oxc.rs/#eNo9jr0OgzAMhF8l8gQSQ1upS1DfomOXNDUoEvmRHSRS4N2bQGFJfPJ3d55Bg4TOk6gm8RBVEsaJby2WRaTtadu6fTlowIOcgUZXPk4uqglkpBEbGIyLIDs1cBasfcBjw8m+/XCoSMpxrrJ/eG0gKGKkLdKPpPGZijmHkAkRMlCyNyDPp393REU95mJAvl2u90Jr/8Eey4lZWONMZ3ZWexsImY/mdf0BEn9UzQ==)

Without the 2nd `|| y`, it works correctly.
