### ISSUE TITLE
oxc_ast: missing argument_expression in AstBuilder

### ISSUE THREAD

**Issue by alyalin** [oxc-project/oxc#7753]
Hey,

After 0.34 version I can't find `argument_expression` method in `AstBuilder`, nothing in changelog either.
Give me a hint, 0.35+ has only `argument_from_spread_element`

**Comment by overlookmotel** [comment]
I don't remember there being an `argument_expression` method. Maybe you mean `argument_from_expression`.

All the `*_from_*` methods were removed in #7073.

If what you're trying to do is to turn an `Expression` into an `Argument`, just do `Argument::from(expr)`.

I assume that's what you meant, so closing. Shout if not!

**Comment by alyalin** [comment]
```
    /// Convert a [`Expression`] into the corresponding variant of [`Argument`] without copying or re-allocating memory.
    #[inline]
    pub fn argument_expression(self, inner: Expression<'a>) -> Argument<'a> {
        Argument::from(inner)
    }
```

Haha, its that simple, much appreciate @overlookmotel
