### ISSUE TITLE
 module-lexer no longer in the oxc-parser npm package

### ISSUE THREAD

**Issue by walkerdb** [oxc-project/oxc#7788]
In `oxc-parser@0.38.0` I can reference `oxc.moduleLexerSync` and `oxc.moduleLexerAsync`.

As of `oxc-parser@0.39.0` that function is no longer exported.

Was that intentional? I can't find any mention of relevant breaking changes in changelogs. Was it extracted to its own package instead?

**Comment by Boshen** [comment]
It is removed, but returned directly from the parser instead. See https://github.com/oxc-project/oxc/blob/main/napi/parser/test/__snapshots__/esm.test.ts.snap for examples.

Two reasons it was removed:

* has an extra ast pass
* does not return all esm information 

Please let me know if there are values missing.

**Comment by ryanatkn** [comment]
Were dynamic imports with string literal specifiers omitted intentionally? I expected to see `dynamicImports` on `EcmaScriptModule`. A workaround is just crawling the AST yourself:

`import('dynamic_import')`

```json
{
  "type": "ImportExpression",
  "start": 0,
  "end": 24,
  "source": {
    "type": "Literal",
    "start": 7,
    "end": 23,
    "value": "dynamic_import",
    "raw": "'dynamic_import'"
  },
  "arguments": [],
  "phase": null
}
```
