### ISSUE TITLE
CI: `oxlint` binaries are not "immediately" available in npm 

### ISSUE THREAD

**Issue by Sysix** [oxc-project/oxc#7789]
The last eslint-plugin-oxlint release did not include all binary files for all platforms:
https://github.com/oxc-project/eslint-plugin-oxlint/commit/7300c69c55db26261b3b36b0ec8389154b2a5543#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL3704-L3713

After waiting a bit, `npm uninstall oxlint` and `npm install oxlint --save-dev` did add the missing binary files:
https://github.com/oxc-project/eslint-plugin-oxlint/pull/281/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3706-R3713

My suggestions:
Increase the "wait time" inside CI Job "Release"  after the release.

**Comment by Boshen** [comment]
Need to ping for all sub-packages prior :-/

**Comment by Boshen** [comment]
Changed to 3 minutes. Too lazy to write a ping :-)
