### ISSUE TITLE
linter: some parsing errors in 0.15.0

### ISSUE THREAD

**Issue by pumano** [oxc-project/oxc#7817]
### What version of Oxlint are you using?

0.15.0

### What command did you run?

oxlint -c oxlintrc.json --quiet

### What does your `.oxlint.json` config file look like?

I have `pixi.js` in project, oxlint 0.14.1 not throw error while proccessing `node_modules` but 0.15.0 throw false positive errors

I think it's somehow linked to introduced support `import source phases` 

### What happened?

  × Expected `from` but found `string`
    ╭─[node_modules/pixi.js/lib/filters/mask/MaskFilter.mjs:9:20]
  8 │ import vertex from './mask.vert.mjs';
  9 │ import source from './mask.wgsl.mjs';
    ·                    ────────┬────────
    ·                            ╰── `from` expected
 10 │ 
    ╰────

  × Expected `from` but found `string`
   ╭─[node_modules/pixi.js/lib/filters/defaults/blur/gpu/generateBlurProgram.mjs:3:20]
 2 │ import { GAUSSIAN_VALUES } from '../const.mjs';
 3 │ import source from './blur-template.wgsl.mjs';
   ·                    ─────────────┬────────────
   ·                                 ╰── `from` expected
 4 │ 
   ╰────

  × Expected `from` but found `string`
   ╭─[node_modules/pixi.js/lib/filters/defaults/color-matrix/ColorMatrixFilter.mjs:8:20]
 7 │ import fragment from './colorMatrixFilter.frag.mjs';
 8 │ import source from './colorMatrixFilter.wgsl.mjs';
   ·                    ───────────────┬──────────────
   ·                                   ╰── `from` expected
 9 │ 
   ╰────

  × Expected `from` but found `string`
   ╭─[node_modules/pixi.js/lib/filters/defaults/alpha/AlphaFilter.mjs:7:20]
 6 │ import fragment from './alpha.frag.mjs';
 7 │ import source from './alpha.wgsl.mjs';
   ·                    ─────────┬────────
   ·                             ╰── `from` expected
 8 │ 
   ╰────

  × Expected `from` but found `string`
   ╭─[node_modules/pixi.js/lib/filters/defaults/noise/NoiseFilter.mjs:7:20]
 6 │ import fragment from './noise.frag.mjs';
 7 │ import source from './noise.wgsl.mjs';
   ·                    ─────────┬────────
   ·                             ╰── `from` expected
 8 │ 
   ╰────

  × Expected `from` but found `string`
    ╭─[node_modules/pixi.js/lib/filters/defaults/displacement/DisplacementFilter.mjs:11:20]
 10 │ import vertex from './displacement.vert.mjs';
 11 │ import source from './displacement.wgsl.mjs';
    ·                    ────────────┬────────────
    ·                                ╰── `from` expected
 12 │ 
    ╰────

**Comment by Boshen** [comment]
Thank you for reporting, a very good regression for https://github.com/tc39/proposal-source-phase-imports
