### ISSUE TITLE
Release v0.15.1 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [oxc-project/oxc#7861]
https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.15.1

No asset was released.

<img width="277" alt="image" src="https://github.com/user-attachments/assets/dd60e578-b950-4aa4-bdc6-74f163893a61" />

The release workflow failed.

https://github.com/oxc-project/oxc/actions/runs/12316473012/job/34378223087

```
Run mkdir -p target
  mkdir -p target
  cargo release-oxc changelog --release oxlint
  {
    echo 'CHANGELOG<<EOF'
    cat ./target/OXC_CHANGELOG
    echo EOF
  } >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
Error: bump failed
Error: Process completed with exit code 1.
```

## Note

[aqua](https://aquaproj.github.io/) couldn't install oxc v0.15.1 due to this issue.

- https://github.com/aquaproj/aqua-registry/pull/29911

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.15.2
