### ISSUE TITLE
Semantic: `ScopeFlags` for a class in a class constructor has `ScopeFlags::Constructor`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#7900]
Input:

```js
class Outer {
  constructor() {
    class Inner {}
  }
}
```

Semantic sets `ScopeFlags` for `class Inner {}` as `StrictMode | Constructor`. I believe this is a mistake. It should just be `StrictMode`.

Weirdly I cannot replicate this in playground ([playground](https://playground.oxc.rs/#eNpFUEFOxDAM/ErlE0gVAiQufcBKnODAkUs2666CEruynYWq6t9xWnaRoiQzGc84XiDCADEH1e6tGkq3fFLXRSY1qdFY7u53yslN9UrUVGvjfPMFPTAMC0ilduhMFn5gGENW7CEnshvQyBPC4NYNzOXI+YpMAunIUv7Eaw9TEEXZPLlKxEPKSKG4ARiqPXypR+9PH3PzhcKnmtHZSdBLL/geBEn/LVs3m6Xfb4l7hgU5o7cKqM+PTy/gisgnPGP7lYOSKI3pWuwTMuF8yPzdii8oR1ZvYQ9a11+LTHim)). But on latest main, when I print `ScopeFlags` for all scopes I get this:

```
ScopeId(0): Program: ScopeFlags(StrictMode | Top)
ScopeId(1): Class(Outer): ScopeFlags(StrictMode)
ScopeId(2): Function(<anonymous>): ScopeFlags(StrictMode | Function | Constructor)
ScopeId(3): Class(Inner): ScopeFlags(StrictMode | Constructor)
```

Debug code:

```rs
let scopes = semantic.scopes();
let nodes = semantic.nodes();
#[allow(clippy::cast_possible_truncation)]
for i in 0..scopes.len() {
    let scope_id = ScopeId::new(i as u32);
    let flags = scopes.get_flags(scope_id);
    let node_id = scopes.get_node_id(scope_id);
    let kind = nodes.get_node(node_id).kind();
    let name = kind.debug_name();
    println!("{scope_id:?}: {name}: {flags:?}");
}
```

As this isn't visible on playground, is this the result of a very recent change? Or is there something else funny going on?

**Comment by overlookmotel** [comment]
@Dunqing Do you have any idea why this playground showed different `ScopeFlags` for this example than run locally?

I thought maybe it was because this problem was created by a recent change, and so Playground just wasn't up-to-date with latest main. But now I don't think that's true.

It's a problem for debugging if Playground behaves differently from what we get locally / in production.

**Comment by Dunqing** [comment]
> @Dunqing @Boshen Do you have any idea why playground showed different `ScopeFlags` for this example than when run locally?
> 
> I thought maybe it was because this problem was created by a recent change, and so Playground just wasn't up-to-date with latest main. But now I don't think that's true. Right now Playground still shows that `class Inner` does not have `Constructor` flag, and it must be up-to-date now.
> 
> It's a problem for debugging if Playground behaves differently from what we get locally / in production.

I found the root cause is #7950
