### ISSUE TITLE
bug(codegen): missing `,` when generating type parameters with jsx

### ISSUE THREAD

**Issue by camc314** [oxc-project/oxc#7917]
[Playground link](https://playground.oxc.rs/#eNo9T7sOwjAM/JXIE0gdAIklPAYGvoCxSwguipTalWMeVZV/J6VqJ5/t851vAA8WPFNS80RCCf5K5mSOt+q8apitua3N6WyGmmrVvkNzcVL2Qz7UlA9QAYMdQF40ltSTui9YlRdWEAPpjJPnDpemb+8c507FUWpYWrCNiwlzBZ2ThFIUCx5VZrxQ/wNQJ08sFoBpt9nuoTA8P7DkmOhtoNCE+biEVOF4jfwZj98od07lp8k05x+N1ltj)

input:

```tsx
const genericFn = <T,>(foo: T) => {
	type Bar = {};
};
```

output:
```tsx
const genericFn = <T>(foo: T) => {
	type Bar = {};
};
```

expected output:
```tsx
const genericFn = <T,>(foo: T) => {
	type Bar = {};
};
```

**Comment by overlookmotel** [comment]
Please excuse my lack of TypeScript knowledge, but does the trailing comma in `<T,>` have any semantic meaning?

**Comment by Boshen** [comment]
It breaks for `.tsx`.

**Comment by camc314** [comment]
iirc, the parser will interpret `<T>` as an opening jsx tag and not as a type parameter.

it's fine in non-jsx files because `<T>` **cant** be an opening jsx element.
