### ISSUE TITLE
[Feature Request] WASM build for non-js environment

### ISSUE THREAD

**Issue by VanillaMaster** [oxc-project/oxc#8064]
Yes it's possible to use current wasm build in non-js environment but it's at least inconvenient
Is it possible to provide wasm build with minimal c-style API to be used in arbitrary environment ?

**Comment by Boshen** [comment]
Do you have a proposal?

**Comment by VanillaMaster** [comment]
> Do you have a proposal?

no, only couple ot thoughts (nothing reasonable)
