### ISSUE TITLE
How should I delete a node?

### ISSUE THREAD

**Issue by JasithC** [oxc-project/oxc#8091]
In Traverse, how should I delete a node if I want to? Is there a relevant method that allows me to remove the corresponding code for a specified node?

**Comment by Dunqing** [comment]
Try to find a usage similar to what you want in [Transformer](https://github.com/oxc-project/oxc/tree/main/crates/oxc_transformer)

**Comment by Boshen** [comment]
Please provide more context of what you want to achieve.

**Comment by JasithC** [comment]
For example, in Traverse, I wrote the `enter_expression` method, where I directly use a method like `ctx.remove_expression()` to delete this node from the program, ensuring that the node I removed will not be present in the final generated code. I noticed the `move_expression` method, but that ultimately leaves behind a null value.

**Comment by camc314** [comment]
https://github.com/oxc-project/oxc/blob/c0dd3f8e32f233d069ca0be08108bc8d8c0262df/crates/oxc_ast/src/ast_builder_impl.rs#L115-L120

try using  `move_expression`? it repalces an expression with the `null` literal, effectivly removing the expression

**Comment by JasithC** [comment]
Yes, I am aware of this method. As the note mentions, this method will ultimately leave a null in its original position, but what I want is something that leaves absolutely nothing behind.

**Comment by JasithC** [comment]
Thank you very much for your reply.

**Comment by JasithC** [comment]
Thank you very much for your reply. However, I am a bit unclear about what you mean by being cleaned up by a minifier.

**Comment by camc314** [comment]
the minifier could remove `null` expressions (where possible)

e.g. an `ExpressionStatement` with a `null` expression, would simply be deleted however `return null` or `null` as an argument to a function would not be removed

**Comment by JasithC** [comment]
When I use CodeGenerator::new() to generate the code, I'm not sure why that null is still there. Is there some configuration option that needs to be passed?

**Comment by camc314** [comment]
see this for an example?

https://github.com/oxc-project/oxc/blob/main/crates/oxc_minifier/examples/minifier.rs#L55

**Comment by JasithC** [comment]
I see it, and I will look into how to use this thing. Thank you for the help you've provided; it's very useful to me.
